### ISSUE TITLE
Error using AutoDiagonalNormal with SVI + Predictive

### ISSUE THREAD

**Issue by tcbegley** [pyro-ppl/numpyro#1012]
I'm getting an error when using `AutoDiagonalNormal` to construct a guide for SVI, and then subsequently using that guide to construct the predictive distribution. 

```
UnboundLocalError: local variable 'event_ndim' referenced before assignment
```

The error comes from [this section](https://github.com/pyro-ppl/numpyro/blob/6823c495f62774172936fb437bb17210fd0179e0/numpyro/infer/autoguide.py#L485-L497) of the code. It looks to me like if the `if` statement is satisfied, then lines 495-497 will always fail? So it doesn't seem quite right, but I don't understand what's happening there well enough yet to be sure how to fix it.

Here's a minimal example. I see the error with NumPyro 0.6.0 and also when installing from `master`. Swapping `AutoDiagonalNormal` for `AutoNormal` resolves the issue, even though for this example where there is only a single latent I would expect them to be equivalent?

```python
import numpyro
import numpyro.distributions as dist
from jax import random
from numpyro.infer import SVI, Trace_ELBO
from numpyro.infer.autoguide import AutoDiagonalNormal, AutoNormal
from numpyro.infer.util import Predictive


def model(x=None):
    n = x.shape[0] if x is not None else 1
    mu = numpyro.sample("mu", dist.Cauchy())

    with numpyro.plate("plate", n):
        numpyro.sample("x", dist.Normal(mu, 1), obs=x)


if __name__ == "__main__":
    rng_key = random.PRNGKey(0)
    alpha = 2

    rng_key, subkey = random.split(rng_key)
    x = random.normal(subkey, (1000,)) + alpha

    # AutoDiagonalNormal results in an error when sampling from the predictive
    # AutoNormal doesn't have the same problem
    # guide = AutoNormal(model)
    guide = AutoDiagonalNormal(model)
    svi = SVI(model, guide, numpyro.optim.Adam(1e-3), Trace_ELBO())

    rng_key, subkey = random.split(rng_key)
    params, losses = svi.run(subkey, 1000, x)

    predictive = Predictive(
        model, guide=guide, params=params, num_samples=1000
    )

    rng_key, subkey = random.split(rng_key)
    # this line results in error is AutoDiagonalNormal was used
    posterior_predictive_samples = predictive(subkey)
```

**Comment by fehiepsi** [comment]
Thanks, @tcbegley! That's a bug introduced recently. Could you submit a PR with `event_ndim` moved outside of that `if/else` block?
```
event_ndim = site["fn"].event_dim
if ...
else ...
```

**Comment by tcbegley** [comment]
Sure, just submitted the requested change.
