### ISSUE TITLE
Makes a common interface for multivariate distributions

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#102]
Multivariate distributions does not have parameters `loc`, `scale` and it should stand on its own. So it would be nice if we make a common interface for it.

**Comment by neerajprad** [comment]
I think this is another strength of tfp or pytorch distributions which is distinguishing between event and batch shapes, due to which multivariate distributions do not require any special statement. I would therefore suggest prioritizing #82 than spending too much time making this work with scipy.

**Comment by fehiepsi** [comment]
Resolved in #111
