### ISSUE TITLE
Issue with `AutoContinuous` guides when using `numpyro.deterministic`

### ISSUE THREAD

**Issue by tcbegley** [pyro-ppl/numpyro#1020]
I've been having some issues fitting guides that inherit from `AutoContinuous` (first noticed with `AutoDiagonalNormal`) to a model that has both parameter and deterministic sites. This problem does not occur for `AutoNormal`. I've included a toy example below, but for context I originally encountered this when trying to train a neural network with Bayesian last layer and wanted to use `numpyro.deterministic` to capture the logits I was passing to a categorical sampling statement.

Here's the example

```python
import numpyro
import numpyro.distributions as dist
from jax import random
from numpyro.distributions import constraints
from numpyro.infer import SVI, Trace_ELBO
from numpyro.infer.autoguide import AutoDiagonalNormal


def model(y=None):
    n = y.size if y is not None else 100

    mu = numpyro.sample("mu", dist.Normal(0, 5))
    sigma = numpyro.param("sigma", 1, constraint=constraints.positive)
    numpyro.deterministic("sigma2", sigma ** 2)

    numpyro.sample("y", dist.Normal(mu, sigma).expand((n,)), obs=y)


if __name__ == "__main__":
    rng_key = random.PRNGKey(0)
    mu, sigma = 2, 3

    rng_key, subkey = random.split(rng_key)
    y = mu + sigma * random.normal(subkey, shape=(1000,))

    guide = AutoDiagonalNormal(model)
    optimiser = numpyro.optim.Adam(step_size=0.01)
    svi = SVI(model, guide, optimiser, Trace_ELBO())

    rng_key, fit_key, sample_key = random.split(rng_key, 3)
    params, losses = svi.run(fit_key, num_steps=400, y=y)

    guide.sample_posterior(sample_key, params, sample_shape=(1000,))
```

if you run this you get the error

```
AttributeError: 'function' object has no attribute 'support'
```

I believe I've tracked the problem down. The addition of the deterministic site means that `self._postprocess_fn` is built from `numpyro.infer.util.constrain_fn` rather than `numpyro.infer.util.transform_fn`, that happens [here](https://github.com/pyro-ppl/numpyro/blob/048d2c80d9f4087aa9614225568bb88e1f74d669/numpyro/infer/util.py#L401-L411). `numpyro.infer.util.constrain_fn` has [this](https://github.com/pyro-ppl/numpyro/blob/048d2c80d9f4087aa9614225568bb88e1f74d669/numpyro/infer/util.py#L107-L109) problematic substitution function which is where the error originates from, as it tries to access `site["fn"].support`, but this doesn't exist for parameter sites. The parameter sites are added [here](https://github.com/pyro-ppl/numpyro/blob/048d2c80d9f4087aa9614225568bb88e1f74d669/numpyro/infer/autoguide.py#L505-L513) because they are needed to replay the model.

Would a valid fix be to check if the site corresponds to a parameter [here](https://github.com/pyro-ppl/numpyro/blob/048d2c80d9f4087aa9614225568bb88e1f74d669/numpyro/infer/util.py#L108-L109) and simply return the value if so without trying to biject it? Something like

```python
def substitute_fn(site):
    if site["name"] in params:
        if site["type"] == "sample":
            return biject_to(site["fn"].support)(params[site["name"]])
        else:
            return params[site["name"]]
```

Would be happy to submit a PR if this looks right?

**Comment by fehiepsi** [comment]
Good catch - I believe all reasoning is correct. Please submit a PR (with this regression test in `test/infer/test_autoguide.py`). Thanks for the detailed explaination, @tcbegley!
