### ISSUE TITLE
feature request: please wrap optax optimizers

### ISSUE THREAD

**Issue by murphyk** [pyro-ppl/numpyro#1023]
The [optax library from Deepmind](https://github.com/deepmind/optax) is the future for jax ecosystem (e.g. it will be adopted by Flax team), and will likely replace [jax.experimental.optimizers](https://jax.readthedocs.io/en/latest/jax.experimental.optimizers.html). It would be good to update https://num.pyro.ai/en/stable/optimizers.html accordingly.

**Comment by fehiepsi** [comment]
Nice suggestion! I think we can add a new `numpyro.contrib.optax` module which "automatically" wraps `optax` optimizers and make them compatible with SVI. We can also add some helper methods in SVI or ELBO to make them compatible with `optax` directly.

**Comment by fehiepsi** [comment]
This is addressed in #1034. @murphyk @tcbegley thanks for requesting this feature and resolving it!
