### ISSUE TITLE
Shape mismatch with simplex constraint

### ISSUE THREAD

**Issue by gbdrt** [pyro-ppl/numpyro#1030]
We are using the Simplex constraint to implement custom distributions.
With this constraint, the `biject_to` function adds an element to the last dimension. 
Is it on purpose? The pyro implementation works as expected.

Here is a minimal example:
```python
import numpyro
import jax.numpy as jnp
from numpyro.distributions import Normal
from numpyro.distributions.constraints import simplex
from numpyro.distributions.transforms import biject_to
from jax.random import PRNGKey

class Simplex(Normal):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.support = simplex

    def sample(self, *args, **kwargs):
        s = super().sample(*args, **kwargs)
        return biject_to(self.support)(s)

Simplex(jnp.ones((2,2)),jnp.ones((2,2))).sample(PRNGKey(0))
```

Output:
```
DeviceArray([[0.8931128 , 0.05996092, 0.0469263 ],
             [0.65627587, 0.21112864, 0.1325955 ]], dtype=float32)
```

Using Pyro:
```python
import pyro
import torch
from pyro.distributions import Normal
from pyro.distributions.constraints import simplex
from pyro.distributions.transforms import transform_to

class Simplex(Normal):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.support = simplex

    def sample(self, *args, **kwargs):
        s = super().sample(*args, **kwargs)
        return transform_to(self.support)(s)

Simplex(torch.ones((2,2)),torch.ones((2,2))).sample()
```

Output:
```
tensor([[0.2603, 0.7397],
        [0.2416, 0.7584]])
```

**Comment by fehiepsi** [comment]
In Pyro `transform_to` is different from `biject_to`: the former is not bijective, while the latter is bijective. In NumPyro, there is no `transform_to` implemented. For comparison, you can use both `biject_to` in Pyro and NumPyro.

FYI, a bijective is a transform from R^m to codomain. A simplex in R^3 has 2 free dimensions, so its bijector's domain should be R^2. So if your input is in R^2, the output will be in R^3.

If you want to construct a transformed distribution, you can use
```
dist.TransformedDistribution(dist.Normal(...), biject_to(simplex))
```
which will give you a correct log probability.

**Comment by gbdrt** [comment]
Thanks a lot for your answer.
That makes a lot of sense.

**Comment by gbdrt** [comment]
But, then we have the following issue.
We want to get samples that follows the simplex constraints with a particular shape.
That is why we introduced the new distribution. 
So far we used the Simplex constraint and hacked the shape to get the expected results.

```python
x = MySimplex().sample(shape)
assert x.shape = shape
```

This is working fine with MCMC, and AutoDelta.
But, this is not working with most of the AutoGuides which, if I understand correctly, relies on transformation using `biject_to` and end up with a missing dimension.

Is there a way around this?

**Comment by fehiepsi** [comment]
I think for simplex support, you can use
```python
dist.TransformedDistribution(dist.Normal(...), biject_to(simplex))
```
or
```python
dist.Dirichlet(...)
```
or
```python
dist.ImproperUniform(simplex, event_shape=...)
```
Your sample method suggests that you wanted TransformedDistribution.

Assume that you want to have simplex in R^2xR^2, the `Simplex` definition in the topic comment has 4 issues:
+ batch_shape is wrong: it should be (2,), rather than Normal(...).batch_shape=(2, 2)
+ event_shape is wrong: it should be (2,), rather than Normal(...).event_shape=()
+ log_prob is wrong
+ input is wrong: `loc.shape` and `scale.shape` should have shape (2, 1), rather than (2, 2) (`biject_to(simplex)` converts shape (2, 1) to (2, 2) or (2, 2) to (2, 3))

**Comment by gbdrt** [comment]
Thank you for these precisions!

For the input shape we did what you suggested, but as you pointed out we realized that there was multiple issues with `batch_shape`, `event_shape`, and the transform.

```
dist.TransformedDistribution(dist.Normal(...), biject_to(simplex))
```

is working perfectly for us.
