### ISSUE TITLE
Feature request: option to save sampler diagnostics of the Warm-up samples

### ISSUE THREAD

**Issue by mdenhollander** [pyro-ppl/numpyro#1035]
When saving diagnostics of the HMC sampler (Divergences, Acceptance statistic and the tree-depth), Numpyro only saves the values for the samples that are not in the warm-up. However, it could be informative to evaluate the values of these diagnostics in the Warm-up samples as well.

Is there any way to save these diagnostics? If not, could this functionality be added in any way?

Many thanks in advance!

**Comment by fehiepsi** [comment]
I think the above snippet will provide the stats for the warmup phase. Please feel free to open this issue again if there are some other stats that cannot be obtained using the current api.
