### ISSUE TITLE
order of args to mcmc is inconsistent between pyro and numpyro

### ISSUE THREAD

**Issue by murphyk** [pyro-ppl/numpyro#1038]
I see that [pyro.mcmc](https://num.pyro.ai/en/stable/mcmc.html) uses (kernel, num_samples, warmup_steps)
but [numpyro.mcmc](https://num.pyro.ai/en/stable/mcmc.html) uses (kernel, warmup_steps, num_samples), which is a bit confusing.

**Comment by fritzo** [comment]
@fehiepsi if we do change one of the interfaces, we might want to enforce keyword-only args so that at least the breaking change is not silent:
```py
class MCMC:
    def __init__(
        sampler,
        *,
        num_warmup,
        num_samples,
        ...
    ): ...
```

**Comment by fehiepsi** [comment]
I can see the confusion. I think it is better to add that `*` to numpyro, although numpyro mcmc API is more mature than the one in pyro.

**Comment by fehiepsi** [comment]
Yeah, I guess many people will like the change. :D
