### ISSUE TITLE
Out of memory on a small NN with less parameters than the equivalent linear model

### ISSUE THREAD

**Issue by cfusting** [pyro-ppl/numpyro#1054]
I've been playing with the HMCECS example and find that when I convert the linear model to a one layer neural network I run out of memory. This occurs even if I reduce the feature size to 1 and the hidden dim to 2 (I'm using a small modification of the code from the BNN example). In this case there are actually less parameters than with the linear model, but JAX complains I am trying to allocate 938.07 GiB of memory; ouch!

Any ideas why this might be the case or shall I keep digging?

**Comment by martinjankowiak** [comment]
how exactly are you specifying the nn? code would be helpful.

**Comment by cfusting** [comment]
```
def model(X, Y, subsample_size=None):

      D_X, D_Y, D_H = X.shape[1], 1, 2

      w2 = numpyro.sample("w2", dist.Normal(jnp.zeros((D_X, D_H)), jnp.ones((D_X, D_H))))
      w3 = numpyro.sample("w3", dist.Normal(jnp.zeros((D_H, D_Y)), jnp.ones((D_H, D_Y))))

      with numpyro.plate("N", X.shape[0], subsample_size=subsample_size) as idx:
          z2 = nonlin(jnp.matmul(jnp.array(X)[idx], w2))
          z3 = jnp.matmul(z2, w3)

          return numpyro.sample("Y", dist.Normal(z3, 1), obs=jnp.array(Y)[idx])
````

**Comment by martinjankowiak** [comment]
i believe you need to use the `numpyro.subsample` primitive as in the example code

**Comment by fehiepsi** [comment]
I think you need to make sure that `z3` and `Y` are vectors. If they have shape `N x D_Y`, then you need to specify `dim=-2` in plate `N`:
```python
with numpyro.plate("N", X.shape[0], subsample_size=subsample_size, dim=-2)
```

**Comment by cfusting** [comment]
Thank you for helping me find this bug! Indeed it was an indexing issue. I found that by flattening `z3` and then either using `numpyro.subsample` or indexing via `X[idx, :]` it worked fine.
