### ISSUE TITLE
AttributeError: module 'numpyro' has no attribute 'render_model'

### ISSUE THREAD

**Issue by satosanffm** [pyro-ppl/numpyro#1060]
Hello, 

I was following : [http://num.pyro.ai/en/latest/tutorials/model_rendering.html](url)

```
!pip install -q numpyro@git+https://github.com/pyro-ppl/numpyro
```
```
from jax import nn
import jax.numpy as jnp

import numpyro
import numpyro.distributions as dist

assert numpyro.__version__.startswith('0.6.0')
```
```
def model(data):
    m = numpyro.sample('m', dist.Normal(0, 1))
    sd = numpyro.sample('sd', dist.LogNormal(m, 1))
    with numpyro.plate('N', len(data)):
        numpyro.sample('obs', dist.Normal(m, sd), obs=data)
```
```
data = jnp.ones(10)
numpyro.render_model(model, model_args=(data,))
```

However, I received an error message as follows:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-8c99a2eff0ba> in <module>()
      1 data = jnp.ones(10)
----> 2 numpyro.render_model(model, model_args=(data,))

AttributeError: module 'numpyro' has no attribute 'render_model'
```
The version of numpyro is correctly 0.6.0.. 
And the version of jax is 0.2.10 

Could you help me finding out why this error happens (is there any mismatch of related versions)? Thank you in advance!
(I read #949 but I was not sure if I should post this question there. If so, sorry..)

**Comment by fehiepsi** [comment]
I think you are using the master branch. I guess you can do
```
pip uninstall numpyro
pip uninstall numpyro
pip install -q numpyro@git+https://github.com/pyro-ppl/numpyro
```
in _your environment_.

**Comment by satosanffm** [comment]
Thank you so much for your quick response!

I run the following two codes as you suggested. However, I receive still the same error message,
_AttributeError: module 'numpyro' has no attribute 'render_model'_


```
pip uninstall numpyro
pip install -q numpyro@git+https://github.com/pyro-ppl/numpyro
```
```
Building wheel for numpyro (setup.py) ... done
```

**Comment by fehiepsi** [comment]
Are you installing numpyro to the same environment as your script? I guess you can try to update jax to see if your pip command can actually update a package: `pip install -U jax`. The latest jax version is 0.2.13.

**Comment by satosanffm** [comment]
The problem is solved! Thank you so much! 

Since I use Google Colab, I think the environment should not matter.
However, I probably forgot to restart the running time. 
(Today, I came back to work this morning and I ran the same code as yesterday. 
The code runs.)

Also, now the version of jax is 0.2.13.

Thank you again for your help.

**Comment by fehiepsi** [comment]
That makes sense. I'm not familiar with colab - I think you can do "Factor reset runtime" to reset everything you have installed in the colab environment. :) I also guess that
```
pip install -q -U numpyro@git+https://github.com/pyro-ppl/numpyro
```
might work. :)
