### ISSUE TITLE
Bayesian Models of Annotation example in the docs is broken

### ISSUE THREAD

**Issue by anbasile** [pyro-ppl/numpyro#1067]
The [Annotation example](https://num.pyro.ai/en/latest/examples/annotation.html) in the docs is currently broken. It requires installaton from master and not from pip of both numpyro and funsor because of `infer_discrete` and `funsor_interpretations`.  Then it works.

**Comment by fehiepsi** [comment]
Hi @anbasile, for the stable version, you can use [this link](http://num.pyro.ai/en/stable/examples/annotation.html). The link that you used is for the latest <-> master branch.

**Comment by anbasile** [comment]
Thanks!
