### ISSUE TITLE
failure when using conda install

### ISSUE THREAD

**Issue by wenouyang** [pyro-ppl/numpyro#1071]
Hello, I was trying to install numpyro using conda, and I got the following error message. Would you like to take a look at it? The system is Windows+Anaconda

(kaggle) C:\>conda install -c conda-forge numpyro
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.-
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by fehiepsi** [comment]
Hi @wenouyang, we will relax jax jaxlib versions in the next release, which will happens soon.

**Comment by fehiepsi** [comment]
We have just released jax/jaxlib versions. Hopefully, this is resolved now. For the Windows system, please also checkout [this note in README](https://github.com/pyro-ppl/numpyro#installation).
