### ISSUE TITLE
pip install numpyro failed on windows 

### ISSUE THREAD

**Issue by wenouyang** [pyro-ppl/numpyro#1072]
Hello, I was also trying to install numpyro using pip, which seems to fail as well. What are the best ways to install numpyro on Windows? Thanks.

Collecting jax==0.2.3
  Downloading jax-0.2.3.tar.gz (473 kB)
     |████████████████████████████████| 473 kB 3.3 MB/s
Collecting numpyro
  Using cached numpyro-0.4.0-py3-none-any.whl (175 kB)
  Using cached numpyro-0.3.0-py3-none-any.whl (157 kB)
  Using cached numpyro-0.2.4-py3-none-any.whl (159 kB)
  Using cached numpyro-0.2.3-py3-none-any.whl (145 kB)
  Using cached numpyro-0.2.2-py3-none-any.whl (145 kB)
  Using cached numpyro-0.2.1-py3-none-any.whl (141 kB)
  Using cached numpyro-0.2.0-py3-none-any.whl (95 kB)
  Using cached numpyro-0.1.0.tar.gz (73 kB)
Collecting jax==0.1.35
  Using cached jax-0.1.35.tar.gz (181 kB)
ERROR: Cannot install numpyro==0.1.0, numpyro==0.2.0, numpyro==0.2.1, numpyro==0.2.2, numpyro==0.2.3, numpyro==0.2.4, numpyro==0.3.0, numpyro==0.4.0, numpyro==0.4.1, numpyro==0.5.0 and numpyro==0.6.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    numpyro 0.6.0 depends on jaxlib==0.1.62
    numpyro 0.5.0 depends on jaxlib==0.1.59
    numpyro 0.4.1 depends on jaxlib==0.1.56
    numpyro 0.4.0 depends on jaxlib==0.1.55
    numpyro 0.3.0 depends on jaxlib==0.1.51
    numpyro 0.2.4 depends on jaxlib==0.1.37
    numpyro 0.2.3 depends on jaxlib==0.1.36
    numpyro 0.2.2 depends on jaxlib==0.1.36
    numpyro 0.2.1 depends on jaxlib==0.1.32
    numpyro 0.2.0 depends on jaxlib==0.1.27
    numpyro 0.1.0 depends on jaxlib>=0.1.14

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by fehiepsi** [comment]
We will relax jax jaxlib version the the next release. For now, you can use the installation method in cell 1: http://num.pyro.ai/en/latest/tutorials/bayesian_regression.html

**Comment by arunavsk** [comment]
> We will relax jax jaxlib version the the next release. For now, you can use the installation method in cell 1: http://num.pyro.ai/en/latest/tutorials/bayesian_regression.html

even this is not working

**Comment by fehiepsi** [comment]
Interesting, it is working on colab so I guess the issue is related to the recent pip resolver mechanism on a Windows system. Let's see if we still see the issue in the next release. For now, I think a solution can be:
+ update pip `pip install -U pip` (I'm seeing similar issue [here](https://github.com/pypa/pip/issues/8713))
+ uninstall jax/jaxlib/numpyro... (run `pip uninstall jax` 2 times)
+ install the latest jax/jaxlib versions
+ install the master branch of numpyro `pip install -q numpyro@git+https://github.com/pyro-ppl/numpyro`

**Comment by fehiepsi** [comment]
We have just released numpyro 0.7. Hopefully it is resolved now. Please reopen this issue if you face the error again.
