### ISSUE TITLE
DOC Sample from prior predictive

### ISSUE THREAD

**Issue by MarcoGorelli** [pyro-ppl/numpyro#1074]
From reading the [docs](http://num.pyro.ai/en/latest/tutorials/bayesian_regression.html), I can see that if I want to regress `y` onto `t`, I can do:
```python
def model(t, y=None):
    a = numpyro.sample('a', dist.Normal(0., 0.5))
    b = numpyro.sample('b', dist.Normal(0., 0.5))
    sigma = numpyro.sample('sigma', dist.Exponential(1.))
    mu = a + b*t
    numpyro.sample('obs', dist.Normal(mu, sigma), obs=y)

rng_key = random.PRNGKey(0)
rng_key, rng_key_ = random.split(rng_key)

# Run NUTS.
kernel = NUTS(model)
mcmc = MCMC(kernel, num_warmup=1000, num_samples=1000, num_chains=4)
mcmc.run(rng_key_, t=t, y=y)
mcmc.print_summary()
samples_1 = mcmc.get_samples()
```

I can then sample from the posterior predictive distribution with:
```python
rng_key, rng_key_ = random.split(rng_key)
predictive = Predictive(model, samples_1)
predictions = predictive(rng_key_, t=t)['obs']
```

However, how can I sample from the _prior_ predictive distribution?

(I'm happy to make a PR to clarify this in the docs once I've understood it)

**Comment by fehiepsi** [comment]
Hi @MarcoGorelli, to get samples from prior predictive, you can replace the posterior samples `samples_1` by `num_samples=1000`.

**Comment by MarcoGorelli** [comment]
So simple, thanks @fehiepsi !

Shall I mention this in the Bayesian Regression tutorial?

**Comment by fehiepsi** [comment]
Sure, pls go ahead! :)
