### ISSUE TITLE
[FR] Add version of `MixtureSameFamily` from Pyro

### ISSUE THREAD

**Issue by derekpowell** [pyro-ppl/numpyro#1081]
I'm finally following up on @fehiepsi 's suggestion that I make this feature request following our conversation in this [issue](https://github.com/arviz-devs/arviz/issues/1661) in the Arviz repo. __But looking over the docs again, it looks like this may have already been implemented with a Tensorflow distribution that may make this FR unnecessary.__ Please feel free to close if that's the case!

In case it's useful anyway, here's what I had written before noticing that in the Tensorflow distributions api:

It would be very useful to me and I imagine anyone else working with finite mixture models to have an implementation of a distribution like Pyro's [MixtureSameFamily](https://docs.pyro.ai/en/dev/distributions.html?highlight=MixtureSameFamily#pyro.distributions.MixtureSameFamily). Numpyro's ability to enumerate over and otherwise manage discrete variables is awesome, but for many finite mixture models it can also be useful to explicitly marginalize out discrete latent variables (e.g. see this example in the [Stan manual](https://mc-stan.org/docs/2_24/stan-users-guide/summing-out-the-responsibility-parameter.html). This is required for traditional implementations of HMC, but it seems like it would be useful even with Numpyro's additional capabilities both for speed and cases where the number of latent mixtures is large.

**Comment by peterroelants** [comment]
Do the NumPyro dev's think that having a dedicated implementation of `MixtureSameFamily` is still worth having?
Given that TensorFlow's [`MixtureSameFamily`](https://www.tensorflow.org/probability/api_docs/python/tfp/substrates/jax/distributions/MixtureSameFamily) can be used as [`distributions.MixtureSameFamily`](http://num.pyro.ai/en/stable/distributions.html#mixturesamefamily), and can now be used directly in the `sample` primitive (https://github.com/pyro-ppl/numpyro/issues/1106 & https://github.com/pyro-ppl/numpyro/pull/1109): 

Other relevant conversation: https://forum.pyro.ai/t/sample-from-the-mixture-same-family-distribution/3178/8

**Comment by fehiepsi** [comment]
I think it would be useful to have a NumPyro version, so users can do some sort of `dist.MixtureSameFamily(...).expand([...]).to_event(...)` or use it as a base dist of a numpyro transformed distribution.

**Comment by peterroelants** [comment]
@fehiepsi I tried to take a stab at implementing `MixtureSameFamily` in https://github.com/pyro-ppl/numpyro/pull/1123

I would love to get your feedback.

**Comment by peterroelants** [comment]
Implemented in https://github.com/pyro-ppl/numpyro/pull/1123

**Comment by fehiepsi** [comment]
Thank you, @peterroelants!
