### ISSUE TITLE
Production mode example

### ISSUE THREAD

**Issue by GMCobraz** [pyro-ppl/numpyro#1089]
Dear numpyro developers,

Good days.
I read the great post on the example in Gaussian process given by you guys.
I have some experience with Pymc3.

I have big interest in transfer the trained model to production.
In Pymc3, the trace from sample can be saved in .nc format by using to_netcdf.
While in production mode, I can simply load the .nc file by using from_netcdf.
From there, I can continue with my sample posterior distribution and making new predictions.

May I know, how is it done in numpyro?
Is there any ways or example to show how the trace from sample is saved and loaded again in new script?

Thank you very much.

Best Regards,
GMChin

**Comment by fehiepsi** [comment]
@GMCobraz Please checkout [arviz support for numpyro](https://arviz-devs.github.io/arviz/getting_started/CreatingInferenceData.html#from-numpyro). That library supports [NetCDF](https://arviz-devs.github.io/arviz/getting_started/XarrayforArviZ.html#netcdf).

**Comment by fehiepsi** [comment]
@GMCobraz If you get any trouble, please follow up in the [forum](https://forum.pyro.ai/). Your question will be more visible to other people in the community. :)
