### ISSUE TITLE
Investigate why adaptation does not work well with default HMC parameters

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#109]
For many models that seem to work well in Pyro with the default values for `trajectory_length` and `step_size` (see `test_mcmc.py`), the behavior in numpyro can be finicky in that either HMC / NUTS is too slow or we get wrong results, despite our tests running for many more steps than in Pyro.

**Comment by fehiepsi** [comment]
I wonder if turning on fast-math makes things better? Currently, np.sum in CPU without fastmath has high error which makes accept prob get wrong values. Even with fastmath, the error of np.sum is also large. I will take a look too.

**Comment by fehiepsi** [comment]
@neerajprad I just run the tests but didn't observe the flakiness. `np.sum` imprecision is one of the reason but it seems do not affect much these tests. Initial step_size should not be important if we turn on adapt_step_size. Could you point out a specific test with failed parameters so I can take a closer look?

**Comment by neerajprad** [comment]
I also don't see that HMC is at least passing without specifying `step_size`. However I still see NUTS not terminating without specifying `step_size` in `test_beta_bernoulli`. I'm not sure if that's due to fast-math mode, will check and confirm.

**Comment by fehiepsi** [comment]
According to #115, this issue seems have been resolved.
