### ISSUE TITLE
import numpyro error (version 0.7)

### ISSUE THREAD

**Issue by maxwellreynolds** [pyro-ppl/numpyro#1092]
Hello,

I installed the most recent version of numpyro (GPU) and am getting the following error when importing:

ImportError: cannot import name 'get_dtype' from 'numpyro.distributions.util'

**Comment by fehiepsi** [comment]
Hi @maxwellreynolds, that utility has been removed in 0.6 release. I think you can use `jnp.result_type` to achieve the same thing.

**Comment by maxwellreynolds** [comment]
Ok, sorry for not being clearer. I'm not calling get_dtype, I am getting this error just from the command:

`import numpyro`

Here is the trace:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c714a75f4912> in <module>
----> 1 import numpyro

../python3.7/site-packages/numpyro/__init__.py in <module>
      2 # SPDX-License-Identifier: Apache-2.0
      3 
----> 4 from numpyro import compat, diagnostics, distributions, handlers, infer, optim
      5 from numpyro.distributions.distribution import enable_validation, validation_enabled
      6 import numpyro.patch  # noqa: F401

../python3.7/site-packages/numpyro/distributions/__init__.py in <module>
      2 # SPDX-License-Identifier: Apache-2.0
      3 
----> 4 from numpyro.distributions.conjugate import BetaBinomial, GammaPoisson
      5 import numpyro.distributions.constraints  # noqa: F401
      6 from numpyro.distributions.continuous import (

../python3.7/site-packages/numpyro/distributions/conjugate.py in <module>
      8 from numpyro.distributions import constraints
      9 from numpyro.distributions.continuous import Beta, Dirichlet, Gamma
---> 10 from numpyro.distributions.discrete import (
     11     BinomialProbs,
     12     MultinomialProbs,

../python3.7/site-packages/numpyro/distributions/discrete.py in <module>
     37 from numpyro.distributions import constraints
     38 from numpyro.distributions.distribution import Distribution
---> 39 from numpyro.distributions.util import (
     40     binary_cross_entropy_with_logits,
     41     binomial,

ImportError: cannot import name 'get_dtype' from 'numpyro.distributions.util' (../python3.7/site-packages/numpyro/distributions/util.py)


Thanks!

**Comment by fehiepsi** [comment]
Could you uninstall numpyro first then install it again? Your source code seems to have content different from the last release.

**Comment by fehiepsi** [comment]
Sorry, @maxwellreynolds! I made a wrong release...

**Comment by maxwellreynolds** [comment]
I tried uninstalling and re-installing (using pip) and still getting the same error

**Comment by fehiepsi** [comment]
For some reason, the source file in https://pypi.org/project/numpyro/#files is correct but the binary file is wrong.
```
pip install numpyro --no-binary=:all:
```
gives me the correct installation. :(

**Comment by fehiepsi** [comment]
@maxwellreynolds The issue has been fixed in the last release. Thanks for the early note!
