### ISSUE TITLE
pip install numpyro failed on windows

### ISSUE THREAD

**Issue by GMCobraz** [pyro-ppl/numpyro#1094]
Hi numpyro developers,

Good day.
Same error happened to new release which can refer back to closed issue (pip install numpyro failed on windows #1072)

ERROR: Cannot install numpyro==0.1.0, numpyro==0.2.0, numpyro==0.2.1, numpyro==0.2.2, numpyro==0.2.3, numpyro==0.2.4, numpyro==0.3.0, numpyro==0.4.0, numpyro==0.4.1, numpyro==0.5.0, numpyro==0.6.0, numpyro==0.7.0 and numpyro==0.7.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    numpyro 0.7.1 depends on jaxlib>=0.1.65
    numpyro 0.7.0 depends on jaxlib>=0.1.65
    numpyro 0.6.0 depends on jaxlib==0.1.62
    numpyro 0.5.0 depends on jaxlib==0.1.59
    numpyro 0.4.1 depends on jaxlib==0.1.56
    numpyro 0.4.0 depends on jaxlib==0.1.55
    numpyro 0.3.0 depends on jaxlib==0.1.51
    numpyro 0.2.4 depends on jaxlib==0.1.37
    numpyro 0.2.3 depends on jaxlib==0.1.36
    numpyro 0.2.2 depends on jaxlib==0.1.36
    numpyro 0.2.1 depends on jaxlib==0.1.32
    numpyro 0.2.0 depends on jaxlib==0.1.27
    numpyro 0.1.0 depends on jaxlib>=0.1.14

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

Please help.

Thank you very much

**Comment by fehiepsi** [comment]
@GMCobraz @wenouyang Please see the note for [windows support](https://github.com/pyro-ppl/numpyro#installation). You'll need to install/build jax/jaxlib first. The simplest way to get `jaxlib` installed is to use `pip`/`conda` on Windows Subsystem for Linux. Please let us know if the notice in README needs to improve.
