### ISSUE TITLE
failure when using conda install (Windows)

### ISSUE THREAD

**Issue by GMCobraz** [pyro-ppl/numpyro#1095]
Dear numpyro developers,

Good day. Same error happened again in anaconda which can refer back to #1071.

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Not sure is OS problem or anaconda problem, since I am using Windows as OS.
I sincerely hope numpyro can develop and support also for Windows users.

Thank you very much.

**Comment by wenouyang** [comment]
@GMCobraz , I just noticed that I reported the same issue as you. Hope we can get this issue fixed soon.

**Comment by fehiepsi** [comment]
@GMCobraz Please see the note for [installing numpyro on windows](https://github.com/pyro-ppl/numpyro#installation).
