### ISSUE TITLE
Pareto distribution tfp vs numpyro implémentation

### ISSUE THREAD

**Issue by hyperfra** [pyro-ppl/numpyro#1098]
Hi
I have some issues in using the Pareto distribution. 
When the alpha is small the sample values from the Pareto are very different from the Pareto in TFP.
For alpha greater than 3-4 they are much more similar. 
 
![Pareto0 5](https://user-images.githubusercontent.com/39092766/125418298-81bc73dc-de11-4e24-81a3-240d39426d7a.png)
![Pareto1](https://user-images.githubusercontent.com/39092766/125418304-f9dd5185-1d6d-4553-a7bf-0f3b3d15436a.png)
![Pareto2](https://user-images.githubusercontent.com/39092766/125418310-43583b1e-6ba3-4d17-976a-1c8564e95fa4.png)
![Pareto5](https://user-images.githubusercontent.com/39092766/125418311-bc2533c9-8253-403f-8e38-65882a7dac59.png)
![Pareto15](https://user-images.githubusercontent.com/39092766/125418313-5fe93318-600f-43bb-a143-efa17c9bc42c.png)

**Comment by fehiepsi** [comment]
Hi @hyperfra, I'm not sure what's the root of the issue. Currently, we defined Pareto as a [transformed distribution](https://github.com/pyro-ppl/numpyro/blob/d121cff5dfdba51ace605a3c34448ccb41ec21af/numpyro/distributions/continuous.py#L1275). Currently, to generate a Pareto sample by:
+ generate u ~ Uniform(0, 1)
+ transform u -> -log(u) * alpha to get a Exponential sample
+ then perform exp(-log(u) * alpha) * scale

I think it is a bit expensive to take `log` then `exp`. You can add a `sample` method to generate a Pareto same directly
```
u ~ Uniform(0, 1)
transform u -> scale/(u ^ 1/alpha)
```

**Comment by fehiepsi** [comment]
After looking closer to the plot, it seems to me that they are pretty similar. Note that Pareto distribution has [infinite variance](https://en.wikipedia.org/wiki/Pareto_distribution) when `alpha <= 2`, so you will get very different histograms for different runs/seeds.
