### ISSUE TITLE
Checkpointing during MCMC

### ISSUE THREAD

**Issue by bmorris3** [pyro-ppl/numpyro#1100]
Hi devs, thanks for your contributions to this tool!

Is it possible to save the MCMC chains while the chains are running? I'm using numpyro on multiple GPUs in an HPC environment and would like to checkpoint my jobs in case of preemption.

**Comment by fehiepsi** [comment]
@bmorris3 Should [post_warmup_state](http://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.MCMC.post_warmup_state) solve the issue?

**Comment by bmorris3** [comment]
Yes I think so, sorry I missed it in the docs!
