### ISSUE TITLE
Use parse_known_args across all examples

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#1103]
Currently, when executing the example script in jupyter notebook, we will get an error due to `argparse` could not recognize additional jupyter argument:
```
error: unrecognized arguments: -f /home/fehiepsi/.local/share/jupyter/runtime/kernel-b4867b12-6bd4-4ec2-9adf-a328899062d1.json
```
s (through the call `parser.parse_args()`). A solution is to use `parse_known_args` as suggested by @GMCobraz in [forum](https://forum.pyro.ai/t/error-in-gaussian-process-example/3142/3)

**Comment by fritzo** [comment]
As commented in #1168, I think it's generally safer to error loudly. That's why we use assertions rather than hoping things work.

**Comment by fehiepsi** [comment]
Looking like users need to figure out how to use argparse properly in notebook. Let's close this issue. Thanks for your input, Fritz!
