### ISSUE TITLE
[Docs] Syntax highlighting broken for notebook examples / tutorials

### ISSUE THREAD

**Issue by tcbegley** [pyro-ppl/numpyro#1111]
Syntax highlighting doesn't seem to work on any notebook based examples tutorials in the deployed documentation. See e.g. http://num.pyro.ai/en/stable/tutorials/bayesian_regression.html

Interestingly I don't have the same problems if I build the documentation locally (following steps in a fresh virtual environment)

```
pip install .[doc]
pip install -r docs/requirements.txt
make docs
python -m http.server --directory docs/build/html
```

I can't see from the repo how the docs are built / deployed, so I suspect there's something in that process that disagrees with the above steps? In particular I think the `ipython` dependency is key, is that maybe not getting picked up in the build of the deployed docs?

**Comment by fehiepsi** [comment]
In the [latest build](https://readthedocs.org/projects/numpyro/builds/14369063/), readthedocs uses
```python
pip install --upgrade --no-cache-dir mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readt
```
Looking at [rtd documentation](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#pinning-dependencies) (the docs point to this [search](https://github.com/readthedocs/readthedocs-sphinx-search) package, which is pretty cool and convenient - we should use it), I think that we need to pin
```
nbsphinx==0.8.6
sphinx==4.1.2
sphinx_rtd_theme==0.5.2
# readthedocs-sphinx-search==0.1.0
```
in `docs/requirements.txt` file. But IIRC, the latest versions do not give the correct `Open in Colab`/`Open in Github` links... I can't remember exactly. We can try those latest versions again. Do you want to make a PR?
