### ISSUE TITLE
Memory allocation issue with parallel chains on multiple GPU

### ISSUE THREAD

**Issue by maxwellreynolds** [pyro-ppl/numpyro#1115]
Hello,

I am running NUTS for a larger model (~100,000 parameters) with 4 chains in parallel (4 GPUs available), num_warmup  = 1000, and num_samples = 10,000.

The progress bar is left at default (true)

I am getting the following error:

RuntimeError: Resource exhausted: Out of memory while trying to allocate 15273920000 bytes.

Versions
numpyro 0.7.2
jax 0.2.217
jaxlib 0.1.68
cuda 11.1

I did not have this error when I was using 5,000 samples.

I saw issue  #899 resolved the issue for 1  GPU but was wondering if there is any solution for multiple GPU.

 Thanks

**Comment by fehiepsi** [comment]
@maxwellreynolds I think you can use [post_warmup_sample](http://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.MCMC.post_warmup_state) for this (see the example there).

**Comment by maxwellreynolds** [comment]
This is helpful, thank you!
