### ISSUE TITLE
AssertionError because key is None when running arviz.from_numpyro on model with Categorical distribution

### ISSUE THREAD

**Issue by peterroelants** [pyro-ppl/numpyro#1121]
I'm running into an `AssertionError` because the [`.sample()` method](https://github.com/pyro-ppl/numpyro/blob/58a7beb383f7c233a7d9edfd8312b5011c0a6c90/numpyro/distributions/discrete.py#L310) of the `Categorical` distribution is being called with `key=None`:

```python-traceback
~/miniconda3/envs/numpyro/lib/python3.9/site-packages/numpyro/distributions/discrete.py in sample(self, key, sample_shape)
    308 
    309     def sample(self, key, sample_shape=()):
--> 310         assert is_prng_key(key)
    311         return categorical(key, self.probs, shape=sample_shape + self.batch_shape)
    312 

AssertionError:
```

This happens when calling `arviz.from_numpyro(mcmc)`. 
I ran into this issue when trying to implement a Gaussian mixture model in NumPyro. Please find the notebook with stacktrace and debug output in the following gist: https://gist.github.com/peterroelants/277d9d47a76a55c23a433d37bbbd6dd7/1cddeefd37243bcf61ac727738ac8de3d0b7bb69#file-gmm-issue-ipynb

I cannot immediately figure out if the `key=None` is originating from Arviz or from Numpyro.

Versions used:
```
arviz     : 0.11.2
numpy     : 1.21.1
jax       : 0.2.18
numpyro   : 0.7.2
```

**Comment by fehiepsi** [comment]
Hi @peterroelants, the reason is NUTS only gives posterior samples for continuous sites. You'll need to use `infer_discrete` to get samples for `i`. Please see [annotation](http://num.pyro.ai/en/stable/examples/annotation.html) for how to use `infer_discrete`.

For `arviz`, I think you either:
+ use `arviz.from_dict` API
+ add `i` values to `mcmc._states_flat` and `mcmc._states`.

**Comment by peterroelants** [comment]
Thanks, I got it to work with your suggestions: https://gist.github.com/peterroelants/277d9d47a76a55c23a433d37bbbd6dd7/1cddeefd37243bcf61ac727738ac8de3d0b7bb69#file-gmm-issue-ipynb
