### ISSUE TITLE
SVI with discrete latent variables

### ISSUE THREAD

**Issue by quattro** [pyro-ppl/numpyro#1124]
Hi all, thanks again for developing such a fantastic inference library. It's been a joy to use for simulations and inference procedures so far.

I noticed the recently implemented `TraceGraph_ELBO` and decided to try it out for inference of discrete latent variables and was met with `UserWarning: Currently, SVI does not support models with discrete latent variables`. Is this a regression bug, or am I mistaken in that `TraceGraph_ELBO` in numpyro cannot handle discrete latent variable?

If it's the former, I'm happy to add a small fork + pull request that adds a simple check on the `loss` member variable within an `SVI` instance.

I'm using `numpyro` version 0.7.1.

**Comment by fehiepsi** [comment]
Hi @quattro, you're right, we can remove that warning now. Please feel free to submit a PR. :)
