### ISSUE TITLE
Progress bars not changing for multiple chains in Jupyter

### ISSUE THREAD

**Issue by ojhall94** [pyro-ppl/numpyro#1154]
I'm currently having an issue where the progress bars show no change when running multiple chains in Jupyter Notebook. I've included screenshots of what this looks like below, and the versions of the (hopefully) relevant packages.

![image](https://user-images.githubusercontent.com/22291663/132845786-5ae235ff-b886-4382-b88b-b2b1841b32a3.png)

Numpyro - 0.7.2
Graphviz -0.16
ipywidgets - 7.6.4
tdqm - 4.62.2

**Comment by fehiepsi** [comment]
@ojhall94 Did you install the extension: https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-in-classic-jupyter-notebook?

**Comment by fehiepsi** [comment]
I guess we need to clarify in docs that we need to install extensions in addition to ipywidgets.

**Comment by fehiepsi** [comment]
I just add a note for installing the extensions in #1159. Thanks for raising this issue! Please feel free to reopen this issue if that doesn't explain the issue that you have.
