### ISSUE TITLE
Improved Error Message for Incorrect Sample Shape

### ISSUE THREAD

**Issue by RylanSchaeffer** [pyro-ppl/numpyro#1155]
I have a jax array of D parameters for D independent Bernoulli distributions. I wanted to draw N samples from each of the D Bernoulli distributions, but when I tried the following code, I received the error `unsupported operand type(s) for +: 'int' and 'tuple'`. 

```
            with numpyro.plate('data', num_obs):
                indicators = numpyro.sample(
                    'indicators',
                    numpyro.distributions.Bernoulli(probs=sticks),
                    sample_shape=num_obs)
```

A better error message would clarify what's wrong with the `num_obs` variable that I'm passing to the function.

**Comment by RylanSchaeffer** [comment]
I realized the error is that I'm misunderstanding how the plate and the sample shape interact. That said, I still think better error messages would be helpful :)

**Comment by fehiepsi** [comment]
Sorry for the late response, @RylanSchaeffer! I just make an assertation the sample_shape needs to be a tuple in #1158. Thanks!
