### ISSUE TITLE
AutoGuides do not permit sampling using only learned parameters

### ISSUE THREAD

**Issue by lumip** [pyro-ppl/numpyro#1160]
## The Goal
Our setting requires that we separate sampling from a learned variational posterior some time after and in a separate script/program than the inference and *without having access to the training data* any more.

## The Problem
We use NumPyro's SVI algorithm with the `AutoDiagonalNormal` guide to infer a variational approximation of our model posterior. We then store the learned parameters of the guide.

At a later time, to sample from the learned posterior, we load the stored parameters, set up our model and the `AutoDiagonalNormal` guide and then call `Predictive` to sample from the data. However, rather than giving us samples from our approximated posterior, this results in one of several possible errors (depending on the internals of the model).

Example code:
```Python
import numpy as np
import jax
import numpyro
import numpyro.distributions as dists
from numpyro.infer import SVI, Predictive
from numpyro.infer.autoguide import AutoDiagonalNormal
from numpyro.primitives import sample, plate

d = 2
np.random.seed(12345)

x = np.random.poisson(1.0, size=(100,))

def model(x, N):
    rate = sample('param', dists.Gamma(1., 1.))
    batch_size = len(x) if x is not None else None
    with plate('batch', N, batch_size):
        sample('x', dists.Poisson(rate), obs=x)

guide = AutoDiagonalNormal(model)

# run inference
optim = numpyro.optim.Adam(1e-2)
svi = SVI(model, guide, optim, numpyro.infer.Trace_ELBO())
state = svi.init(jax.random.PRNGKey(0), x, len(x))
state = jax.lax.fori_loop(0, 10000, lambda i, state: svi.update(state, x, len(x))[0], state)

# get params
params = svi.get_params(state)

## sampling directly after inference works fine
samples = Predictive(model, guide=guide, params=params, num_samples=1, return_sites=['param', 'x'])(
    jax.random.PRNGKey(1), None, 1
)
print(samples)

## sampling with fresh guide does not work
guide = AutoDiagonalNormal(model) # fresh setup of guide to emulate script without inference

samples = Predictive(model, guide=guide, params=params, num_samples=1, return_sites=['param', 'x'])(
    jax.random.PRNGKey(1), None, 1
)
print(samples)
```
The second call to `Predictive` raises a `RuntimeError: MCMC only supports continuous sites or discrete sites with enumerate support, but got ExpandedDistribution.` (but really it has issues with the `Poisson`). Using other distributions will results in different errors.

## A bit of digging into this
We did a bit of digging and have come to the conclusion that this is caused by how the autoguides work: When they are first used, they will trace through the model to determine how to convert samples from an unconstrained domain to whatever is required in the model. It does this for all sample sites that are not observations. This is problematic in our case since we only want to sample from the learned posterior and therefore do not at any point fix observations in the model. The autoguide therefore treats the final sample sites corresponding to observations as something it needs to optimise (even though it will never have to do that).

## Ways forward?
We believe this is quite an oversight: Since the learned parameters fully describe the variational posterior mathematically, saving and reloading those should suffice to sample from the posterior in the API as well, without having to pass data into the model again (which is also a promise in the docstring of `AutoDiagonalNormal`': "The guide does not depend on the model's ``*args, **kwargs``.")

A workaround for us currently is to simply pass in some dummy data to initialize the guide, then go forward to sample from it using the learned parameters. However, this is somewhat cumbersome and unintuitive.

We think that ideally `Predictive` or the autoguide should be made smart enough to detect this case (maybe with an additional input for autoguide on which sites should be considered observations even when no data is given) and handle it.

At least it should be possible to store and load the state of the autoguide alongside the parameters. We tried to see whether this is possible at the moment. It didn't seem to be the case, but maybe we missed something.

The error messages for this should also be improved, as they don't really point to the actual underlying problem and are not consistent (see below for more examples).

What do you think? Or is there already a way to achieve our purpose using NumPyro that we have not thought of?

### Categorical distribution:
```
x = np.random.multinomial(1, [.5, .25, .125, .125], size=(100,)) * np.array([1,2,3,4])
x = np.sum(x, axis=-1)

# Categorical
def model(x, N):
    ps = sample('param', dists.Dirichlet(np.ones(4,)))
    batch_size = len(x) if x is not None else None
    with plate('batch', N, batch_size):
        sample('x', dists.Categorical(ps), obs=x)
```
This raises a `ImportError: Looking like you want to do inference for models with discrete latent variables. This is an experimental feature. You need to install funsor to be able to use this feature. It can be installed with pip install funsor.`

### Normal distribution:
```
x = np.random.normal(10, 3, size=(100, 2))
x[:,-1] *= -1

# Normal
def model(x, N):
    loc = sample('param', dists.Normal(0, 100), sample_shape=(d,))
    scale = np.array([2., 2.])

    batch_size = len(x) if x is not None else None
    with plate('batch', N, batch_size):
        sample('x', dists.Normal(loc, scale).to_event(1), obs=x)
```
This raises a `TypeError: reshape total size must be unchanged, got new_sizes (1, 2) for shape (0,).`.

**Comment by fritzo** [comment]
In Pyro you can just call `guide()` to draw samples of latent variables: there is no need for `Predictive` except to perform deterministic computations in the model. Does that work for you?

**Comment by lumip** [comment]
Thanks @fritzo for pointing that out. However, the errors currently occur directly from the invocation of `guide` that happens internally in `Predictive`, so avoiding `Predictive` does unfortunately not solve the issue.

Could you specify what you mean by "you'll need to sore the guide"? Are you suggesting to pickle the entire class instance?

**Comment by fritzo** [comment]
@fehiepsi how do you serialize guides in NumPyro?  It would be nice if we could get pickle working, say via `__getstate__`/`__setstate__`.  In Pyro we simply:
```py
torch.save(guide, filename)
...
guide = torch.load(filename)
```

**Comment by fehiepsi** [comment]
I'll look into how to store state (though I'm not sure which state we need to store). @lumip's way to setup the guide with dummy data seems to be a good solution. It lets the guide know a bit information of the model (without that, model is just a function - we don't have a way to trace/interpret how the model works from model's source code, so even when we provide `params`, the guide won't know how to use that `params` variable.
I guess current solution is
```
guide = AutoDiagonalNormal(model)
with numpyro.handlers.seed(rng_seed=0):
    guide._setup_prototype(x, len(x))
    # or just guide(x, len(x))
```
And we want to support the following pattern
```
pickle.dump(guide, filename)
guide = pickle.load(filename)
```
so that @lumip can use the guide in another script without passing model's args, kwargs. It seems to be non-trivial at my first glance.

**Comment by lumip** [comment]
I came up with this rather hacky drop-in-replacment-wrapper-prototype around autoguides which samples dummy data from the model and and substitutes them as observations for the initialisation of the autoguide:

```
class SampleGuide:

    def __init__(self, model, observation_sites, base_guide_class, *base_guide_args, **base_guide_kwargs):
        """
        :param model: The model functions.
        :param observation_sites: Collection of parameter site names that are observations in the model.
        :param base_guide_class: The AutoGuide class to wrap around (NOT a class instance!).
        :param base_guide_args: Positional arguments to pass into base_guide_class's initializer.
        :param base_guide_kwargs: Keyword arguments to pass into bas_guide_class's initializer.
        """
        self._model = model
        self._base_guide_factory = lambda model: base_guide_class(model, *base_guide_args, **base_guide_kwargs)
        self._obs = observation_sites

    def __call__(self, *args, **kwargs):
        # We will probably be in the middle of a sampling stack
        # but I don't believe we really want that to affect or be affected by
        # initialisation of the guide.
        # Let's back it up and clear it for now.
        # NOTE: Not sure what the exact implications are. Especially with
        # potential parameter substitutions that might be ignored that way
        # we could really shoot ourselves in the foot here. This needs careful thought!
        stack_backup = numpyro.primitives._PYRO_STACK
        numpyro.primitives._PYRO_STACK = []

        # Here's the general strategy: NumPyro AutoGuide requires that all
        # parameters sites corresponding to observations need to be conditioned
        # on, but we don't have data. We sample some data from the
        # prior predictive distribution (using the model function) and condition
        # the model on those for the guide initialisation.

        # get plausible fake values for observed sites from prior
        with trace() as tr:
            seed(model, jax.random.PRNGKey(0))(*args, **kwargs)
            fake_obs = {site: val['value'] for site, val in tr.items() if site in self._obs}

        # feed model conditioned on fake observations to guide
        guide = self._base_guide_factory(condition(model, fake_obs))
        # trigger guide initialisation with fake observatons
        seed(guide, jax.random.PRNGKey(0))(*args, **kwargs)

        # reinstate the Pyro stack
        numpyro.primitives._PYRO_STACK = stack_backup

        return guide.__call__(*args, **kwargs)
```

That would avoid the need for pickling of the guide and the non-explicit dependency on a specific model a loaded pickled guide would have. I'm not sure how many assumptions of the stack I am violating here, though..

**Comment by fehiepsi** [comment]
I think you can also use `handlers.block` to isolate part of your program with the rest (so no need to play with `_PYRO_STACK`). Btw, could you help me review the pickling PR?

**Comment by lumip** [comment]
Thanks, I'll try that. And I'll have a look at the PR soon, didn't quite get around to it so far.
