### ISSUE TITLE
Add plated alternative to examples/horseshoe_regression.py

### ISSUE THREAD

**Issue by clgarciga** [pyro-ppl/numpyro#1164]
Reference: https://forum.pyro.ai/t/plating-and-the-numpyro-hs-example/3357

horseshoe_regression.py is perfect as is, but in writing other sparse regression models (non-Horseshoe), I've found that writing the model using plates where appropriate given the graphical model can, for more complex sparse reg models, really speed things up while yielding similar or better quality results. But plates were really confusing to me as a new user (somewhat less so now after spending lots of quality time on the docs and forum), and so I thought maybe others could benefit from seeing an alternative Horseshoe model that they could then apply to other, different models they're working on.

Just thought I'd pitch the idea. I can submit the PR if you think it's worth it. Note though that I only wrote the alternative for the normal likelihood, not the bernoulli one, but I could try doing that one too.

**Comment by clgarciga** [comment]
Edit: In case this wasn't clear, I meant show both, i.e. the current horseshoe_regression.py plus the plate version, to allow compare/contrast.

**Comment by martinjankowiak** [comment]
@clgarciga 

> I've found that writing the model using plates where appropriate given the graphical model can, for more complex sparse reg models, really speed things up while yielding similar or better quality results. 

can you explain what you mean? as i commented in the forum i don't believe there's any reason these differences should matter. the only difference should be ease of coding the model and/or readability of the model

**Comment by clgarciga** [comment]
@martinjankowiak Thanks for your reply. Let me try to explain.

Consider the following __Bayesian quantile regression__ model based on Alhamzawi, Yu, and Benoit, "Bayesian adaptive Lasso quantile regression" (2012):
![image](https://user-images.githubusercontent.com/13739205/134948004-70df4c3a-fad3-4d97-ad4b-05da5caabd15.png)
I say "based on" because there is one lambda vs. one lambda per beta.

This is the model, written to mirror your HS model:

```
def BQR(tau=0.5, a=5, b=.04, a_1=.01, b_rate_1=.1, X=None, y=None):
    T, K = X.shape
    
    # Deterministic
    theta            = (1-2*tau)/(tau*(1-tau))
    tau_star_squared = 2/(tau*(1-tau))
    
    # Non-Beta Priors
    sigma = numpyro.sample('sigma', dist.InverseGamma(a,b))
    z     = numpyro.sample('z', dist.Exponential(1/sigma*jnp.ones(T)))
    
    # Beta Priors
    lambda_        = numpyro.sample('lambda_', dist.Gamma(a_1,b_rate_1))
    v              = numpyro.sample('v', dist.Exponential(0.5*lambda_*jnp.ones(K)))
    unscaled_betas = numpyro.sample("unscaled_betas", dist.Normal(0.0, jnp.ones(K)))
    scaled_betas   = numpyro.deterministic("betas",  jnp.sqrt(v) * unscaled_betas)
    beta0          = numpyro.sample('beta0', dist.Normal(0, 5))

    # Likelihood
    mean_function = beta0+jnp.matmul(X,scaled_betas)+theta*z
    stddev_function = jnp.sqrt(tau_star_squared*sigma*z)
    numpyro.sample("y",dist.Normal(mean_function,stddev_function),obs=y)
```

Resulting time 3m45s:

![image](https://user-images.githubusercontent.com/13739205/134970012-a76245ec-0f33-4781-b11e-d571bc8bb87e.png)

This is the equivalent model written with plates:

```
def BQR_Lasso_Plated(tau=0.5, a=5, b=.04, a_1=.01, b_rate_1=.1, X=None, y=None):
    
    T, K = X.shape
    
    # Deterministic
    theta            = (1-2*tau)/(tau*(1-tau))
    tau_star_squared = 2/(tau*(1-tau))
    
    # Non-Beta Priors
    sigma = numpyro.sample('sigma', dist.InverseGamma(a,b))
    
    # Beta Priors
    lambda_ = numpyro.sample('lambda_', dist.Gamma(a_1,b_rate_1))
    beta0   = numpyro.sample('beta0', dist.Normal(0, 5))
    
    with numpyro.plate("plate_beta", K):
        v       = numpyro.sample('v', dist.Exponential(0.5*lambda_))
        unscaled_betas = numpyro.sample("unscaled_betas", dist.Normal(0.0, jnp.ones(1)))
        scaled_betas = numpyro.deterministic("betas", jnp.sqrt(v) * unscaled_betas)

    y_mean = beta0+jnp.matmul(X,scaled_betas)
    with numpyro.plate("plate_T",T):
        z  = numpyro.sample('z', dist.Exponential(1/sigma))
        sigma_obs = jnp.sqrt(tau_star_squared*sigma*z)
        y  = numpyro.sample("y", dist.Normal(y_mean+theta*z, sigma_obs),obs=y)
```

Resulting time 2m54s:

![image](https://user-images.githubusercontent.com/13739205/134970277-40d33338-4ba1-473e-96f3-eff6f89b42b5.png)

I'm pretty new to numpyro, so I don't discount the possibility I'm doing something wrong somewhere that's causing the different time results - if so, please let me know.

**Comment by clgarciga** [comment]
Thank you both. I understand. I might try some experiments like what @martinjankowiak suggests and report back, but for now I think the issue can be closed.
