### ISSUE TITLE
Possible incompatibility with latest jax?

### ISSUE THREAD

**Issue by jameschapman19** [pyro-ppl/numpyro#1165]
!pip install jax==0.2.21
!pip install numpyro

from numpyro.infer.hmc import HMC, NUTS

**Output**

/usr/local/lib/python3.7/dist-packages/numpyro/infer/__init__.py in <module>()
     10     TraceMeanField_ELBO,
     11 )
---> 12 from numpyro.infer.hmc import HMC, NUTS
     13 from numpyro.infer.hmc_gibbs import HMCECS, DiscreteHMCGibbs, HMCGibbs
     14 from numpyro.infer.initialization import (

/usr/local/lib/python3.7/dist-packages/numpyro/infer/hmc.py in <module>()
      6 import os
      7 
----> 8 from jax import device_put, lax, partial, random, vmap
      9 from jax.flatten_util import ravel_pytree
     10 import jax.numpy as jnp

ImportError: cannot import name 'partial' from 'jax' (/usr/local/lib/python3.7/dist-packages/jax/__init__.py)

**Comment by fehiepsi** [comment]
Hi @jameschapman19, we just fixed the issue and will make a release soon.

**Comment by RylanSchaeffer** [comment]
@fehiepsi thanks for the update :)
