### ISSUE TITLE
Bug? Discrete Latent Changing Shapes

### ISSUE THREAD

**Issue by EdwardRaff** [pyro-ppl/numpyro#1174]
Hi, I'm not sure if I'm doing something subtly wrong, but I've run into a weird bug where if I make a latent variable discrete, it's shape changes, causing everything to error out due to the shape changes. I've tried to remove all the unneeded code to isolate the behavior below. I've got two 10 x 10 matrices (any square shape will do) as input, and expect `u` and `v` in the below code to be of shape `(10,)`, which is true when both are continuous distributions. But when `v` becomes discrete, it's shape changes to `(2, 1)`, causing the `jnp.dot` call to fail. 

```python
Y = np.random.rand(10,10)
x = np.arange(Y.shape[0])
X = np.eye(x.max()+1)[x]

def model(X, Y):
  print("Start:", X.shape, Y.shape)

  N = Y.shape[0]

  with numpyro.plate('N', N):
    u = sample('u', dist.Normal(0, 2))
    # v = sample('v', dist.Beta(5, 5))#This runs fine
    v = sample('v', dist.BinomialProbs(0.5)) #This errors out and changes the shape? 
  print(u.shape, v.shape)
  jnp.dot(u, v)
  
  return

SEED = 1337
args = {'algo': 'NUTS', 'num_warmup': 30, 'num_samples':45, 'num_chains':1}
rng_key, rng_key_predict = random.split(random.PRNGKey(SEED))

kernel = NUTS(model)
mcmc = MCMC(
    kernel,
    num_warmup=args['num_warmup'],
    num_samples=args['num_samples'],
    num_chains=args['num_chains'],
    progress_bar=True,
)
mcmc.run(rng_key, X, Y)
```

~I've run into a similar weirdness trying to use `dist.BetaProportion(y_hat, 2.0), obs=Y` as the observed distribution at the end, but am hoping figuring this out will make that second problem go away :)~ Solved that one :)

**Comment by fritzo** [comment]
Hi @EdwardRaff, I'm guessing this is due to NumPyro's enumeration. You can read about some of our shape manipulation in the [tensor shapes tutorial](https://pyro.ai/examples/tensor_shapes.html) (for Pyro, but the concepts are the same).

To make your model compatible with NumPyro's discrete inference you'll need to support broadcasting. However I'm not sure your full model will support cheap inference by enumeration.  In particular, for enumeration to work you can't have sample sites downstream of `u` and `v` that are outside of the `N` plate; all downstream dependencies must be within the N plate.  What does your full model look like?

@fehiepsi might recommend alternatives to NUTS to deal with your discrete inference.

**Comment by clgarciga** [comment]
Posting this here since it seems related...
https://forum.pyro.ai/t/dot-general-error-when-uncentering-a-model/3397/3

Also wondering if maybe there is an error or warning that could be thrown when users attempt to use Discrete latents in an HMC/NUTS model?

**Comment by EdwardRaff** [comment]
@fritzo I just read through that tutorial, I'm not sure I understand how it is relevant here. How can I make my code more broadcasting friendly when the shape of the tensor generated for the discrete latent is changing? My understanding is broadcasting needs consistent shape sizes in the last dimension, and I don't understand how/why the shape is changing - so I do not know what to try and code to. 

>all downstream dependencies must be within the N plate

I think I can achieve that with this model. 

>What does your full model look like?

I'll have to get permission to share the whole code (work things), but it's basically adding another "Clusters" plate with the goal of having a stick-breaking prior and implementing a kind of biclustering approach to approximate the matrix Y. The `u` variable is to indicate which inputs can cause a cluster to be active, and the `v` variable to control which responses occur if the cluster is active (was going to make that part spike-and-slab esq, that all responses in a cluster are very similar values).

**Comment by clgarciga** [comment]
@fehiepsi Thank you, and, sure! Will submit PR.

**Comment by EdwardRaff** [comment]
> Is that what you expected?

Not at all! I'm very novice at the details of any HMC, so this is all very confusing default behavior to me. It sounds like `DiscreteHMCGibbs` is what I really need and was able to move forward with that. 

I've also run into some strangenesses on trying to use the InflatedZero models and trying to implement it myself, I don't know how you prefer I bring those up (new issue, here, somewhere else).
