### ISSUE TITLE
Add an info warning for HMC with enumeration

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#1180]
Quoted by @clgarciga in https://github.com/pyro-ppl/numpyro/issues/1174
> Also wondering if maybe there is an error or warning that could be thrown when users attempt to use Discrete latents in an HMC/NUTS model?

**Comment by fehiepsi** [comment]
Hi @clgarciga, you can use this link https://pyro.ai/examples/enumeration.html.

**Comment by clgarciga** [comment]
Okay, so, here's where I'm at with this: some MCMC kernels (e.g. HMC,NUTS) don't support discrete latents, and some do (e.g. DiscreteHMCGibbs, Mixed HMC). So I need to:
1. Check if the user is using MCMC
2. If yes, check if there are discrete latents in the model
3. If yes, check which kernel they are using
4. Check if that kernel supports discretes or not
5. If not, throw a warning (error?) that they need use a different kernel that supports discretes.
Does that make sense at all?

**Comment by fehiepsi** [comment]
I think you can add an info warning after [this line](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/util.py#L608). I'm not sure how to check properly for each kernel.
