### ISSUE TITLE
Using customized jit wrapper in Numpyro

### ISSUE THREAD

**Issue by srijaniiserprinceton** [pyro-ppl/numpyro#1210]
Hi,

I have written my model in jax which is functional by itself when run outside the Numpyro implementation. But it fails when I try to pass that as a `model` in numpyro the usual way. I use a wrapper on `jit` called `gnool_jit` that lets me hash arrays and hence pass them as static arguments. This is done as follows:
```
import jax.numpy as jnp
from jax import jit
from functools import partial

def some_hash_function(x):
    return int(jnp.sum(x))

class HashableArrayWrapper:
    def __init__(self, val):
        self.val = val
    def __hash__(self):
        return some_hash_function(self.val)
    def __eq__(self, other):
        return (isinstance(other, HashableArrayWrapper) and
                jnp.all(jnp.equal(self.val, other.val)))

def gnool_jit(fun, static_array_argnums=()):
    @partial(jit, static_argnums=static_array_argnums)
    def callee(*args):
        args = list(args)
        for i in static_array_argnums:
            if isinstance(args[i], tuple):
                args[i] = args[i].__class__(*[a.val for a in args[i]])
            else:
                args[i] = args[i].val
        return fun(*args)

    def caller(*args):
        args = list(args)
        for i in static_array_argnums:
            if isinstance(args[i], tuple):
                all_as = [HashableArrayWrapper(a) for a in args[i]]
                args[i] = args[i].__class__(*all_as)
            else:
                args[i] = HashableArrayWrapper(args[i])
        return callee(*args)

    return caller
```
 I have written a simpler code below which simply tries to find the optimal radius when fitting a circle to a set of points. In the script below I do not use the wrapper `gnool_jit` and is functional.
```
# miscellaneous imports                                                                       
import jax
from jax import random
from jax import grad, jit
import jax.numpy as jnp
import numpy as np  
from functools import partial
import matplotlib.pyplot as plt

import numpyro
import numpyro.distributions as dist
from numpyro.infer import MCMC, NUTS, HMC
import scipy.sparse
import sys
import numpy
import gnool_jit as gjit

nchains = 1

###################### MAKE DATA ############################
# initializing parameters                                                                     
# number of data points
N = 50
# the distribution of theta in data
theta_d = random.uniform(random.PRNGKey(seed = 123),
                         (N,), 
                         minval=0.0,
                         maxval=2*np.pi)

# sorting for better plotting
theta_d = np.sort(theta_d)

# the true radius
r_d = 1.0

# creating the true circle
x_d = r_d * np.cos(theta_d)
y_d = r_d * np.sin(theta_d)


# the intorducing artifical noise in data
error_xy = 0.1 * random.normal(random.PRNGKey(seed = 123),
                        (N,2))

# synthetic data with noise
x_d += error_xy[:, 0]
y_d += error_xy[:, 1]

# creating the radius of each data point
r_d = np.sqrt(x_d**2 + y_d**2)
sigma_d = np.sqrt(error_xy[:, 0]**2 + error_xy[:, 1]**2)

##################### BUILD MODEL #########################
@partial(gjit.gnool_jit, static_array_argnums=(0,1))
def calc_rad_from_coor(x_m, y_m):
    return jnp.sqrt(x_m**2 + y_m**2)

def model(theta, y=None):
    npts = len(theta)
    r_model = numpyro.sample('r_model',
                             dist.Uniform(0.0, 10.0*np.ones(npts)))
    '''
    x_model = r_model * jnp.cos(theta)
    y_model = r_model * jnp.sin(theta)

    # adding gjit function here
    r_model_gjit = calc_rad_from_coor(x_model, y_model)
    '''
    return numpyro.sample('r_post',
                          dist.Normal(r_model, sigma_d),
                          obs = r_d)


# setting up the sampler                                                                     
nuts_kernel = NUTS(model)
num_warmup, num_samples = 10, 500
mcmc = MCMC(nuts_kernel, num_warmup, num_samples, num_chains=nchains)

# sampling                                                                                   
mcmc.run(random.PRNGKey(123), theta_d, y = r_d)

r = mcmc.get_samples()['r_model'].mean()

print(r)
```

I modify the `model` to use the `gnool_jit` wrapper as follows
```
def model(theta, y=None):
    npts = len(theta)
    r_model = numpyro.sample('r_model',
                             dist.Uniform(0.0, 10.0*np.ones(npts)))
    
    x_model = r_model * jnp.cos(theta)
    y_model = r_model * jnp.sin(theta)

    # adding gjit function here
    r_model_gjit = calc_rad_from_coor(x_model, y_model)
    
    return numpyro.sample('r_post',
                          dist.Normal(r_model_gjit, sigma_d),
                          obs = r_d)
```
and it fails giving me the following error:
```
jax._src.traceback_util.FilteredStackTrace: ValueError: Non-hashable static arguments are not supported. An error occured while trying to hash an object of type <class 'gnool_jit.HashableArrayWrapper'>, <gnool_jit.HashableArrayWrapper object at 0x2b4331cfb610>. The error was:
ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(float32[])>with<JVPTrace(level=4/1)>
  with primal = Traced<ShapedArray(float32[])>with<DynamicJaxprTrace(level=2/1)>
       tangent = Traced<ShapedArray(float32[]):JaxprTrace(level=3/1)>
The problem arose with the `int` function. If trying to convert the data type of a value, try using `x.astype(int)` or `jnp.array(x, int)` instead.
```

How do use such functions with custom `gnool_jit` wrappers instead of the standard `jit`?

**Comment by fehiepsi** [comment]
I don't think the algorithms in NumPyro can support your usage. The requirement is your code needs to be able to compile. You should reach out to jax devs to find a way to compile your wrapper. It would be easier to test if things work without using numpyro, e.g. test if
```
def f(x, y):
    return calc_rad_from_coor(x, y)
```
can be jitted.

**Comment by samarth-kashyap** [comment]
Thanks @fehiepsi . The function compiles and executes when called outside of NumPyro. The function you suggested works fine. The problem seems to arise only when the function is called inside `model()`, so we suspect some conflict with NumPyro and custom wrapper. Is there a way to pass static arguments with NumPyro?

**Comment by fehiepsi** [comment]
By jitable, I meant if `jit(f)(x, y)` works. I just test and get the same
error, so at least it is not jitable in my system. You can specify any
python object to `mcmc.run(...)` (or to the arguments of your model) but
your code needs to be able to compile. Your wrapper can run but cannot be
compiled.

**Comment by samarth-kashyap** [comment]
ok my bad, I was just executing `f(x, y)`. `jit(f)(x, y)` does not work. I get your point now. jitting a gnool-jitted function seems to be the issue here.

**Comment by srijaniiserprinceton** [comment]
Is there any way to pass a `model` function to numpyro which bypasses the overall jilting of the `model`? To make it more clear, if we have the following block of code
```
def f1(arg1):
    <do something with arg1 and return>

def f2(arg2):
    <do something with arg2 and return>

_f1 = gnool_jit(f1)
_f2 = gnool_jit(f2)

def model(x, y):
    a = _f1(x)
    b = _f2(y)
    c = a+b
    return c
```
As you see, model just contains a bunch of already `gnool_jit`ted functions and hence does not need further jitting. Maybe you could point us to the place in the source code where the overall jitting of the model function is happening and we could replace that jitting step with the non-jitted model?

**Comment by fehiepsi** [comment]
You might want to try your luck with [this line](https://github.com/pyro-ppl/numpyro/blob/8236e3442dde1e13fb982f7706365c8d88c7c312/numpyro/util.py#L354). If potential function is evaluated inside a jax control flow, then you might need to disable control flow here and there, which is a bit complicated.

**Comment by srijaniiserprinceton** [comment]
Thanks for pointing to the line where the `jit`ting is happening. Turns out that we were overcomplicating things by trying to pass static arrays. As of now, the cleanest way to do this, I think, is to use tuples or nested tuples instead of the static arrays since tuples are hashable. If someone is interested, they can checkout [this question thread](https://github.com/google/jax/discussions/8439#discussioncomment-1585074) on the JAX discussion page.

After changing all the state arrays to tuples and nested tuples, the `model` function seems to be working for the first two iterations (maybe that's where it is getting compiled?) using numpyro. So, I think the JAX bit of our model works fine under regular `jit` ting. It starts failing at the step where the progress bar appears. Somehow, the nestedtuples become traced and hence unhashable. 

I think its fine to close this issue for now but I will create a new issue (to be marked as question) on the numpyro specific problem I am facing with more details. Thanks for your help on this one though!
