### ISSUE TITLE
Hashable tuples become traced from third iteration in Numpyro

### ISSUE THREAD

**Issue by srijaniiserprinceton** [pyro-ppl/numpyro#1212]
Hi,

I have a `model` function that runs as expected for the first two iterations and then fails. The reason why it fails is that tuples (which are hashable) and used as static arguments, become traced from the third iteration in numpyro. This is puzzling since the `model` function seems to be working and compiling fine when `jit`ted (as can be seen from the fact that it runs twice successfully) before unexpectedly changing the static (untraced) tuples to traced from the third iteration.

The `model` function is below and the [extremely simplified numpyro script can be found here on Collab.](https://colab.research.google.com/drive/17ImOoc_JrkPe1yxXaKLUFKBuXUTMsiwL?usp=sharing)

```
def model():
    for i in range(1):
        # calling the function with two static arguments
        print('Starting loop')
        a_static, b_static = func2_w_staticargs(GVARS.a, GVARS.b)

        print('Printing as arrays: \n', a_static, b_static)
        
        # converting to arrays to tuple to pass as static arguments
        # to the next function call 
        a_static_tuple = tuple(map(tuple, a_static))
        b_static_tuple = tuple(b_static)
        GVARS_new_ = namedtuple('GVARS_new',
                               ['a','b'])
        GVARS_new = GVARS_new_(a_static_tuple, b_static_tuple)
        
        print('Printing as tuples: \n', GVARS_new.a, GVARS_new.b)
        print('Hash values :,\n', GVARS_new.a.__hash__(), GVARS_new.b.__hash__())

        # second function called with tuples passed as static arguments
        a_static, b_static = func2_w_staticargs(GVARS_new.a, GVARS_new.b)

        fac = 1.0
        eig_sample = np.asarray(GVARS_new.b)

    # eig_sample = numpyro.deterministic('eig', eig_mcmc_func(w1=w1, w3=w3, w5=w5))
    return numpyro.sample('obs', dist.Normal(eig_sample, np.ones_like(b)), obs=np.asarray(b))
```
What I have explained above can be readily seen from the output:
```
Starting loop
Printing as arrays: 
 [[0 1]
 [2 3]] [0. 1. 2. 3.]
Printing as tuples: 
 ((0, 1), (2, 3)) (0.0, 1.0, 2.0, 3.0)
Hash values :,
 8408620485545502573 -8281178343658874797
Starting loop
Printing as arrays: 
 [[0 1]
 [2 3]] [0. 1. 2. 3.]
Printing as tuples: 
 ((0, 1), (2, 3)) (0.0, 1.0, 2.0, 3.0)
Hash values :,
 8408620485545502573 -8281178343658874797
  0%|                                                                  | 0/150 [00:00<?, ?it/s]Starting loop
Printing as arrays: 
 Traced<ShapedArray(int64[2,2])>with<DynamicJaxprTrace(level=2/1)> Traced<ShapedArray(float64[4])>with<DynamicJaxprTrace(level=2/1)>
Printing as tuples: 
 ((Traced<ShapedArray(int64[])>with<DynamicJaxprTrace(level=2/1)>, Traced<ShapedArray(int64[])>with<DynamicJaxprTrace(level=2/1)>), (Traced<ShapedArray(int64[])>with<DynamicJaxprTrace(level=2/1)>, Traced<ShapedArray(int64[])>with<DynamicJaxprTrace(level=2/1)>)) (Traced<ShapedArray(float64[])>with<DynamicJaxprTrace(level=2/1)>, Traced<ShapedArray(float64[])>with<DynamicJaxprTrace(level=2/1)>, Traced<ShapedArray(float64[])>with<DynamicJaxprTrace(level=2/1)>, Traced<ShapedArray(float64[])>with<DynamicJaxprTrace(level=2/1)>)
  0%|                                                                  | 0/150 [00:00<?, ?it/s]

```
It fails when trying to find the `__hash__()` value at the third iteration since the tuples somehow become dynamic traced objects which aren't hashable.
```
TypeError: unhashable type: 'DynamicJaxprTracer'
```

**Comment by fehiepsi** [comment]
FYI the first trace (outside of jit context) is to inspect the model, the second trace (outside of jit context) is to get valid initial parameters.

Just curious, what do you want to do with this hash stuff? The computation will eventually happen in the XLA compiler, not python. Are you trying to modify jax behaviors or just to collect some values?

**Comment by srijaniiserprinceton** [comment]
The line where I print the hash value of the namedtuple `GVARS_new` is just to see if it is hashable or not. As expected, it crashes as soon as the namedtuples are not hashable, i.e, when it gets converted to dynamic tracers. If I remove the printing of the hash value, it crashes with the following error:
```
ValueError: Non-hashable static arguments are not supported. An error occured while trying to hash an object of type <class 'tuple'>, ((Traced<ShapedArray(int64[])>with<DynamicJaxprTrace(level=2/1)>, Traced<ShapedArray(int64[])>with<DynamicJaxprTrace(level=2/1)>), (Traced<ShapedArray(int64[])>with<DynamicJaxprTrace(level=2/1)>, Traced<ShapedArray(int64[])>with<DynamicJaxprTrace(level=2/1)>)). The error was:
TypeError: unhashable type: 'DynamicJaxprTracer
```
As you see, it is trying to hash the named tuple above, the elements of which are now DynamicJaxprTrace.

**Comment by srijaniiserprinceton** [comment]
I think it might be better if I summarize the overall goal of our problem here:

So, the overall goal is to use the Bayesian sampling provided by `numpyro`. To do that we need to define a `model` function which `numpyro` essentially `jit`s since its going to run `model` many many times. 

Now, our `model` function involves two important steps:
```
def f1(<some args>):
    <calculates the indices to tile a big array in f2>
    <returns these indices>
    # as an example
    example_arr = [[10,20], [5, 19]]
    return example_arr

def f2(<args containing array of indices from f1>):
    <creates small matrices of shapes derived from the array calculated in f1>
    <tiles a big matrix using these small matrices by slicing the big matrix>
    <returns the big matrix>
    # as an example
    big_matrix[10:20, 5:19] = small_matrix  # of shape 10x14
    return big_matrix

def model(args_f1):
    a = f1(args_f1)     # a is the array of matrix indices that we will use to slice a big array inside f2
    b = f2(a)        # this is where the argument needs to be static so the 
                           # we can use it to create matrices and tile them in a big matrix inside f2
    return b
```
So, in short, we want to make our `model` function `jit`able and inside that we want to `jit` the functions f1 and f2 which will take in nested tuples of indices as static arguments.  This array of indices will be used to create smaller matrices and tile a larger matrix using the smaller matrices.

Currently, our code is failing because the argument `a` to be passed into `f2` is somehow getting traced in the third run as shown in the post above.

**Comment by fehiepsi** [comment]
I think you can just remove `jit` wrapper around `f1`. If `args_f1` is static, `f1(args_f1)` will be static if there is no jax op in `f1`. If you want to play with static values, then just use `numpy` on them. You don't need to use jax.numpy ops and jax.jit there.

**Comment by srijaniiserprinceton** [comment]
That works great! Exactly what I needed. Numpyro now works with my Jax'd code.
