### ISSUE TITLE
Estimating memory requirement

### ISSUE THREAD

**Issue by samarth-kashyap** [pyro-ppl/numpyro#1214]
Hello numpyro team,

I was wondering if there was a way to estimate the amount of memory required for the compilation and execution of a numpyro script. To illustrate my problem, I've presented a simplified version of the code I'm trying to run. 

```python
def model_func_mcmc(w1=None, w2=None, data_array_index=None):
    return <model computed for the given data_array_index>

def model():
    wmin, wmax = 0.2, 3.0
    num_data_arrays=10

    w1 = numpyro.sample('w1', dist.Uniform(wmin, wmax))
    w2 = numpyro.sample('w2', dist.Uniform(wmin, wmax))
    
    sigma = numpyro.sample('sigma', dist.Uniform(0.1, 10.0))
    m_collected = jnp.array([])
    for i in range(num_data_arrays):
        m_sample = numpyro.deterministic('m', model_func_mcmc(w1=w1, w2=w2, data_array_index=i))
        m_collected = jnp.append(m_collected, m_sample)
    return numpyro.sample('obs', dist.Normal(jnp.asarray(m_collected), sigma), obs=d_true)
```

I have `N=200` different data-arrays, each of which have a unique model, and depends on model parameters `w1` and `w2`. Ideally, I would want to use all the `200` data-arrays to constrain the model parameters. However, I noted that even when I work with a restricted dataset i.e. setting `num_data_arrays=10`, the memory taken up is quite high. The memory used only increases as I increase `num_data_arrays`.  So, is there a way to estimate how much memory would be used for a given numpyro run?  If the memory requirement is a lot, does it help to run the script on multiple nodes? Does numpyro accommodate the utlization of memory across nodes?

Thanks!

**Comment by fehiepsi** [comment]
I'm not sure how to do profiling in CPU but for GPU/TPU I guess you can use [this method](https://jax.readthedocs.io/en/latest/device_memory_profiling.html). I haven't done memory profiling in the past.
