### ISSUE TITLE
Should increasing `num_chains` increase compile time?

### ISSUE THREAD

**Issue by srijaniiserprinceton** [pyro-ppl/numpyro#1219]
This is a question about how changing the  `num_chains` changes compilation time in Numpyro. 

We have a particularly expensive `model` function and  note that when `num_chains=1`, the compilation time is around 5mins. However, when we change the `num_chains=3` with the same number of cores, the compilation time becomes 24 minutes. Is this behavior expected? According to my understanding, the different chains are just sampling different parts of the model prior in a certain iteration, but shouldn't require extra/separate compilation?

P.S.: Is there a way to label posts as `questions` by the author? I feel bad about posting `issues` which are not really suggestive bugs about Numpyro but really just me trying to understand Numpyro better. (Or maybe a discussion forum in Github?)

**Comment by maw501** [comment]
Hi @srijaniiserprinceton you can post questions like this in the [forum](https://forum.pyro.ai/c/numpyro/9) using the NumPyro tag.

**Comment by srijaniiserprinceton** [comment]
Thanks @maw501! I'll do that from now. Moving this question there.
