### ISSUE TITLE
Support multivariate normal distribution

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#122]
These distributions will be useful for a [multilevel model](https://github.com/rmcelreath/rethinking/tree/Experimental#multilevel-model-formulas) which I am intending to make an example as hierarchy model.

**Comment by neerajprad** [comment]
Reopening since multivariate normal still needs to be implemented.

**Comment by neerajprad** [comment]
cc. @martinjankowiak
