### ISSUE TITLE
Hierarchical time series?

### ISSUE THREAD

**Issue by CarolineTims88** [pyro-ppl/numpyro#1222]
I’m trying to write a hierarchical time series (ARMA) in numpyro.

There doesn’t seem to be too much documentation to help. Does anyone know of any resources that they may be able to point towards? 

Are Stan and pymc a bit more plug and play for now? Is there an intention to provide such documentation in the future?

Thanks in advance.

**Comment by fehiepsi** [comment]
I guess [AR example](http://num.pyro.ai/en/latest/examples/ar2.html) and [time series forecasting tutorial](http://num.pyro.ai/en/stable/tutorials/time_series_forecasting.html) would be helpful.
