### ISSUE TITLE
❓ Why is reparametrization required in this example?

### ISSUE THREAD

**Issue by pietrolesci** [pyro-ppl/numpyro#1228]
https://github.com/pyro-ppl/numpyro/blob/c7984a7dac72a5cc7fb391beabac129d900583a1/examples/annotation.py#L204

Hi there,

I am learning pyro/numpyro and I am trying to implement specific models and comparing them with the implementation published in the documentation. This parametrization is the main difference between my implementation and the official one. I guess there is something I am missing from my mental model. Is the reparametrization needed for better/faster inference? 

Any feedback is very much appreciated! :)

Best,
Pietro

**Comment by fritzo** [comment]
Hi @pietrolesci, not sure about this particular example, but I often find reparametrizing dramatically speeds up inference, or means the difference between svi diverging or converging.

**Comment by pietrolesci** [comment]
Hi @fritzo, 

Thanks a lot for your answer! This is in line with what I thought. I am not sure about why it is better in this case, though. Looping in @fehiepsi.

Thanks a lot for your consideration.

Best,
Pietro

**Comment by fehiepsi** [comment]
Hi @pietrolesci, I'm not sure what happens if we remove reparameterization in that example. In general, reparameterization helps NUTS a lot, for example in [Neal's funnel example](http://num.pyro.ai/en/latest/examples/funnel.html).

**Comment by pietrolesci** [comment]
Hi @fehiepsi,

Thanks a lot for your answer. This is super useful. Also, thanks for the pointer to Neal's funnel example.

 For context, I am trying to replicate [this example](https://github.com/pyro-ppl/numpyro/blob/master/examples/annotation.py#L204) in pyro. I would have some further questions as I am having some problems. Where is the best place to ask them? Can I ping you on this as well?

Thanks a lot in advance for your help.

Best,
Pietro

**Comment by pietrolesci** [comment]
In more detail, the reparametrization is creating problems when combined with the automatic enumeration of the discrete variables in pyro.

The code below is exactly the same as the numpyro example, apart from the obvious translations from jax to torch.

```python
def hierarchical_dawid_skene(positions: torch.Tensor, annotations: torch.Tensor) -> None:
    """
    This model corresponds to the plate diagram in Figure 4 of reference [1].
    """
    num_annotators = positions.unique().numel()
    num_classes = annotations.unique().numel()
    num_items, num_positions = annotations.shape

    # debugging
    print(f"{num_classes=}, {num_annotators=}, {num_items=}, {num_positions=}")

    with pyro.plate("class", num_classes):
        # NB: we define `beta` as the `logits` of `y` likelihood; but `logits` is
        # invariant up to a constant, so we'll follow [1]: fix the last term of `beta`
        # to 0 and only define hyperpriors for the first `num_classes - 1` terms.
        zeta = pyro.sample("zeta", dist.Normal(0, 1).expand([num_classes - 1]).to_event(1))
        omega = pyro.sample("Omega", dist.HalfNormal(1).expand([num_classes - 1]).to_event(1))

    with pyro.plate("annotator", num_annotators, dim=-2):
        with pyro.plate("class_abilities", num_classes):
            # non-centered parameterization
            with reparam(config={"beta": LocScaleReparam(centered=None)}):    # <- with this it does not work, beta is reshaped
                beta = pyro.sample("beta", dist.Normal(zeta, omega).to_event(1)).
            # pad 0 last dimension
            beta = F.pad(beta, [0, 1] + [0, 0] * (beta.dim() - 1))

    pi = pyro.sample("pi", dist.Dirichlet(torch.ones(num_classes)))

    with pyro.plate("item", num_items, dim=-2):
        c = pyro.sample("c", dist.Categorical(probs=pi))
        
        # debugging
        print(f"{c.shape=}, {beta.shape=}")

        with pyro.plate("position", num_positions):
            logits = Vindex(beta)[positions, c, :]
            pyro.sample("y", dist.Categorical(logits=logits), obs=annotations)
```

In the first MCMC iteration with NUTS (following the numpyro example), I get the following debug prints
```python
num_classes=4, num_annotators=5, num_items=10, num_positions=7
c.shape=torch.Size([10, 1]), beta.shape=torch.Size([5, 4, 4])
```

In the second iteration, when `c` is enumerated, I get the following debug prints
```python
num_classes=4, num_annotators=5, num_items=10, num_positions=7
c.shape=torch.Size([4, 1, 1]), beta.shape=torch.Size([4, 4])
```

What puzzles me is the fact that `beta` size is changed from `(5, 4, 4)` to `(4, 4)`. This does not happen when I remove the reparametrization.

Any suggestion on where to look to understand what happens?

Thanks a lot in advance for your time.

Best,
Pietro

**Comment by fehiepsi** [comment]
It is best to use [forum](https://forum.pyro.ai/) for questions and discussions. We mainly use github to track issues and feature requests. If removing reparameterizer leads to an error, then there might be a bug. You can create an issue for it. Note that using `center=None` is not expected, it should be `center=0` to be equivalent to numpyro model.

**Comment by pietrolesci** [comment]
Hi @fehiepsi, 

You are right - I amended the code. Also, I will post this on the forum to check whether this is indeed a bug or not. Thanks a lot for your help so far - I really appreciated it.

Best,
Pietro

**Comment by pietrolesci** [comment]
Asked on forum [here](https://forum.pyro.ai/t/issue-when-combining-reparametrization-and-automatic-anumeration/3561).
