### ISSUE TITLE
TFP distributions

### ISSUE THREAD

**Issue by dirmeier** [pyro-ppl/numpyro#1231]
Hello all,

sorry if this question is stupid, but I cannot manage to get TFP distributions working. Even the simplest case, like below, throws an error:

```python
x = TFPDistribution[tfd.Normal](0.0, 1.0)

AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_41495/2841383036.py in <module>
----> 1 TFPDistribution[tfd.Normal](0.0, 1.0)

    120     @lru_cache(maxsize=None)
    121     def __getitem__(cls, tfd_class):
--> 122         assert issubclass(tfd_class, tfd.Distribution)
    123 
    124         tfd_class_name = tfd_class.__name__

AssertionError: 
```
Am I doing this correctly? But also this fails for me with the same error

```python
def model():
    x = numpyro.sample("x", TFPDistribution[tfd.Normal](0.0, 1.0))
    numpyro.sample(
        "y", 
        dist.Normal(x, 1.0),
        obs=np.array([1.0, 2.0, 1.2])
    )
```

Thanks for the help!

**Comment by fehiepsi** [comment]
I think TFP distributions are no longer a subclass of `tfd.Distribution`. We might want to change that assertion to something else.

**Comment by dirmeier** [comment]
Ah I see, you mean as they inherit from `AutoCompositeTensorDistribution` ? I'll try to fix this.
Thanks!
