### ISSUE TITLE
Cannot install numpyro for GPU

### ISSUE THREAD

**Issue by PetrarcaBruto** [pyro-ppl/numpyro#1238]
Hi,
Not sure if this is a numpyro issue or an operators error:

I installed numpyro with the following statement, in a clean miniconda environment:
1) pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html
....
Successfully built jax
Installing collected packages: six, numpy, typing-extensions, scipy, opt-einsum, flatbuffers, absl-py, jaxlib, jax
Successfully installed absl-py-1.0.0 flatbuffers-2.0 jax-0.2.25 jaxlib-0.1.73+cuda11.cudnn82 numpy-1.21.4 opt-einsum-3.3.0 scipy-1.7.3 six-1.16.0 typing-extensions-4.0.0

2) I tried to install numpyro for cuda 
pip install numpyro[cuda]
Collecting numpyro[cuda]
  Downloading numpyro-0.8.0-py3-none-any.whl (264 kB)
     |████████████████████████████████| 264 kB 1.5 MB/s
**WARNING: numpyro 0.8.0 does not provide the extra 'cuda'**
Requirement already satisfied: jax>=0.2.13 in ./miniconda3/envs/jax/lib/python3.9/site-packages (from numpyro[cuda]) (0.2.25)
Requirement already satisfied: jaxlib>=0.1.65 in ./miniconda3/envs/jax/lib/python3.9/site-packages (from numpyro[cuda]) (0.1.73+cuda11.cudnn82)
Collecting tqdm
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Requirement already satisfied: numpy>=1.18 in ./miniconda3/envs/jax/lib/python3.9/site-packages (from jax>=0.2.13->numpyro[cuda]) (1.21.4)
Requirement already satisfied: opt-einsum in ./miniconda3/envs/jax/lib/python3.9/site-packages (from jax>=0.2.13->numpyro[cuda]) (3.3.0)
Requirement already satisfied: typing-extensions in ./miniconda3/envs/jax/lib/python3.9/site-packages (from jax>=0.2.13->numpyro[cuda]) (4.0.0)
Requirement already satisfied: absl-py in ./miniconda3/envs/jax/lib/python3.9/site-packages (from jax>=0.2.13->numpyro[cuda]) (1.0.0)
Requirement already satisfied: scipy>=1.2.1 in ./miniconda3/envs/jax/lib/python3.9/site-packages (from jax>=0.2.13->numpyro[cuda]) (1.7.3)
Requirement already satisfied: flatbuffers<3.0,>=1.12 in ./miniconda3/envs/jax/lib/python3.9/site-packages (from jaxlib>=0.1.65->numpyro[cuda]) (2.0)
Requirement already satisfied: six in ./miniconda3/envs/jax/lib/python3.9/site-packages (from absl-py->jax>=0.2.13->numpyro[cuda]) (1.16.0)
Installing collected packages: tqdm, numpyro
Successfully installed numpyro-0.8.0 tqdm-4.62.3

3) I uninstalled it, so I could install numpyro cuda in a different way (see step 4)

$ pip uninstall numpyro
Found existing installation: numpyro 0.8.0
Uninstalling numpyro-0.8.0:
  Would remove:
    /home/roger/miniconda3/envs/jax/lib/python3.9/site-packages/numpyro-0.8.0.dist-info/*
    /home/roger/miniconda3/envs/jax/lib/python3.9/site-packages/numpyro/*
Proceed (Y/n)? y
  Successfully uninstalled numpyro-0.8.0

4) pip install numpyro[cuda] -f https://storage.googleapis.com/jax-releases/jax_releases.html

  Looking in links: https://storage.googleapis.com/jax-releases/jax_releases.html
  Collecting numpyro[cuda]
    Using cached numpyro-0.8.0-py3-none-any.whl (264 kB)
  ****WARNING: numpyro 0.8.0 does not provide the extra 'cuda'****
Requirement already satisfied: jax>=0.2.13 in ./miniconda3/envs/jax/lib/python3.9/site-packages (from numpyro[cuda]) (0.2.25)
Requirement already satisfied: jaxlib>=0.1.65 in ./miniconda3/envs/jax/lib/python3.9/site-packages (from numpyro[cuda]) (0.1.73+cuda11.cudnn82)
Collecting tqdm
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Requirement already satisfied: numpy>=1.18 in ./miniconda3/envs/jax/lib/python3.9/site-packages (from jax>=0.2.13->numpyro[cuda]) (1.21.4)
Requirement already satisfied: opt-einsum in ./miniconda3/envs/jax/lib/python3.9/site-packages (from jax>=0.2.13->numpyro[cuda]) (3.3.0)
Requirement already satisfied: typing-extensions in ./miniconda3/envs/jax/lib/python3.9/site-packages (from jax>=0.2.13->numpyro[cuda]) (4.0.0)
Requirement already satisfied: absl-py in ./miniconda3/envs/jax/lib/python3.9/site-packages (from jax>=0.2.13->numpyro[cuda]) (1.0.0)
Requirement already satisfied: scipy>=1.2.1 in ./miniconda3/envs/jax/lib/python3.9/site-packages (from jax>=0.2.13->numpyro[cuda]) (1.7.3)
Requirement already satisfied: flatbuffers<3.0,>=1.12 in ./miniconda3/envs/jax/lib/python3.9/site-packages (from jaxlib>=0.1.65->numpyro[cuda]) (2.0)
Requirement already satisfied: six in ./miniconda3/envs/jax/lib/python3.9/site-packages (from absl-py->jax>=0.2.13->numpyro[cuda]) (1.16.0)
Installing collected packages: tqdm, numpyro
Successfully installed numpyro-0.8.0 tqdm-4.62.3

My queston is numpyro installed to work with cuda? If not is how do I install a numpyro version that uses cuda.
Thanks,
Petrarca

**Comment by fehiepsi** [comment]
Hi @PetrarcaBruto, currently, we just have `numpyro[cuda]` in the master branch. It will be available in the next release. For now, you can use
```
pip install --upgrade "jax[cuda]"
pip install numpyro
```

**Comment by PetrarcaBruto** [comment]
Thank you for your quick reply.
