### ISSUE TITLE
Support exporting to arviz InferenceData

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#125]
There are a bunch of features available in [arviz](https://arviz-devs.github.io/arviz/api.html). We can utilize that great library without adding dependency by making a utility function which converting our `fori_append` results to a dictionary `arviz_dict`. Then in arviz, we just need to use [arviz.from_dict](https://arviz-devs.github.io/arviz/generated/arviz.from_dict.html#arviz.from_dict) to get density, trace_plot, and a bunch of new stats such as `loo`, `waic`,...

**Comment by fehiepsi** [comment]
Actually, our `fori_append` output + `transform` functionalities are quite convenient for this job. The following code plots well the result.
```
hmc_states = fori_append(sample_kernel, hmc_state, num_samples,
                         transform=lambda x: {"z": x.z})

import arviz as az
data = arviz.from_dict(hmc_states)
az.plot_trace(data);
```
cc @neerajprad

**Comment by neerajprad** [comment]
Good idea. I think since we are using very straightforward data structures, it is best to delegate all the diagnostics / plotting to arviz.
