### ISSUE TITLE
Raise an exception (or warning) when calling the inverse of a non-invertible transform.

### ISSUE THREAD

**Issue by omarfsosa** [pyro-ppl/numpyro#1253]
The `Transform` class in `numpyro.distributions.transforms` provides an `inv` property which is meant to return the inverse transform. However, this is available even for functions that are not invertible. In those cases, we silently return the identity function which seems weird.

### Example:
```python
import numpyro.distributions as dist

f1 = dist.transforms.AbsTransform()
print(f1.inv(-1))       # Not defined, but returns -1
print(f1.inv(f1(-1))) # Returns +1
```

The issue is also present in transformations that are obtained via `ComposeTransform`.
When the transformation is invertible, it is very easy to obtain the CDF of the transformed distribution (which is something I often need). So I think providing an 'automatic' inverse function is a good idea, but maybe it'd be good to raise an error (or at least a warning) when trying to access the inverse of a non-invertible transform.

**Comment by fehiepsi** [comment]
Yeah, I think it is better to raise a warning. (I'm not sure if we want to take inverse of abs transform some where)

**Comment by fehiepsi** [comment]
@omarfsosa Do you want to add that warning?
