### ISSUE TITLE
Change the link at the right side of the GitHub repository to HTTPS

### ISSUE THREAD

**Issue by ayaka14732** [pyro-ppl/numpyro#1261]
Currently the link at the right side of the GitHub repository is still using HTTP. The modification should be very straightforward.

![](https://user-images.githubusercontent.com/68557794/147192803-a24f2985-bf50-44ed-a35a-e7fe2db2a9a7.png)

**Comment by fehiepsi** [comment]
Thanks for the catch! Currently, we don't use `https` for numpyro docs. We'll update it soon.

**Comment by fehiepsi** [comment]
`https` should be the default setting now. Thanks!
