### ISSUE TITLE
Tutorial on truncated distributions in NumPyro

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#1268]
It would be nice to have a tutorial on truncated distributions in NumPyro. The tutorial might include:
+ some explanations/usages for `TruncatedNormal`, `TruncatedCauchy`, `TruncatedDistribution`, `FoldedDistribution`, `HalftNormal`, `HalfCauchy`.
+ how to construct a truncated distribution using `host_callback`. This will enable users to define their own truncated distributions, for both continuous/discrete distributions https://forum.pyro.ai/t/truncated-binomial-how-to-implement/2808 . This might be [a nice example](https://nbviewer.org/github/cameronraysmith/applied-probabilistic-inference/blob/master/nbs/python/pbw-numpyro-colab.ipynb#Account-for-upper-limit-of-detection).

cc @omarfsosa

**Comment by omarfsosa** [comment]
Thanks @fehiepsi , I'm already working on this. Will open a PR soon :)

**Comment by omarfsosa** [comment]
Preliminary work is here: #1272. Comments and suggestions are more than welcome.

**Comment by fehiepsi** [comment]
Fixed on #1272. Thanks @omarfsosa!
