### ISSUE TITLE
Haiku networks with more than one param

### ISSUE THREAD

**Issue by OlaRonning** [pyro-ppl/numpyro#1282]
The [`haiku_module`](https://github.com/pyro-ppl/numpyro/blob/de22e7143c9792fe14e6c6d6647a9cb66d71f956/numpyro/contrib/module.py#L181) expects the callable only to have one parameter. It would be nice if the module worked an arbitrary number of parameters. Below is a distilled version of a model which currently produces a `TypeError` due to the missing positional argument `prev`. 
 
``` python
import haiku as hk
import jax.numpy as jnp
from jax.nn import relu, softplus
from numpyro import handlers
from numpyro.contrib.module import haiku_module


class NN:
    def __init__(self, hid_dim, out_dim):
        self.hid_dim = hid_dim
        self.out_dim = out_dim

    def __call__(self, x, prev):
        h_latent = relu(hk.Linear(self.hid_dim)(prev))
        h_x = relu(hk.Linear(self.hid_dim)(x))
        h_joint = jnp.concatenate((h_latent, h_x), axis=-1)
        scale = softplus(hk.Linear(self.out_dim)(relu(h_joint)))
        return scale


def model(subsample_size=2, z_dim=3):
    nn = haiku_module(
        "model_emitter",
        hk.transform_with_state(
            NN(
                hid_dim=10,
                out_dim=5
            ),
        ),
        input_shape=(subsample_size, z_dim),  # input_shapes = ((subsample_size, zdim), (subsample_size, zdim))
    )


with handlers.seed(rng_seed=0), handlers.trace() as tr:
    model()
```

The issue is only instantiation, so a simple solution is to allow nested tuples in `input_shape` (and maybe rename it to `input_shapes`). Let me know what you think.

**Comment by fehiepsi** [comment]
I think you can use `kwargs` for additional arguments.

**Comment by OlaRonning** [comment]
I see. `def __call__(self, x, prev=jnp.ones((2,3))):` works as expected. It does make the networks slightly rigid, but it's workable. Thanks for the help @fehiepsi.

**Comment by fehiepsi** [comment]
I guess you can use the original `__call__(self, x, prev)` with `haiku_module(..., prev=...)`? Otherwise, we can support additional `*args` signature in `flax/haiku_module`.

**Comment by OlaRonning** [comment]
Somehow I missed that `kwargs` are passed to `nn_module.init`. That is precisely the behavior I was looking for, so I'll close the issue.
