### ISSUE TITLE
How to make variable name incremental inside scan?

### ISSUE THREAD

**Issue by Hockey86** [pyro-ppl/numpyro#1286]
Hi there,

I'm trying to implement a time series model with latent variable H using numpyro (great project!!)
But I'm stuck with a seemingly easy problem: I want to name the inferred latent variables "H_1", "H_2", ... (number is time index) so that later I can get the posterior by their names

```python
def transition_fn(h_last, t):
    h_mean = ... 
    h_current = numpyro.sample(f'H_{t}', dist.Normal(loc=h_mean, scale=10))  # f'H_{t}' is problematic
    return h_current, h_current

h_init = numpyro.sample('hidden_init', dist.Normal(loc=0, scale=10))
hlast, vals = scan(transition_fn, h_init, np.arange(100))
...
# later after model training
post_h = mcmc.get_samples()
# hope post_h = {'H_1': [...], 'H_2': [...], ...}
```

As you see, `f'H_{t}'` is problematic since `t` is not an integer anymore.

So my question is, how to pass an integer time index into `transition_fn`, or any other solutions?
Thanks!

**Comment by MarcoGorelli** [comment]
maybe something like
```python
def transition_fn(h_last, t):
    h_mean, idx = ... 
    h_current = numpyro.sample(f'H_{idx}', dist.Normal(loc=h_mean, scale=10))  # f'H_{t}' is problematic
    return (h_current, idx+1), h_current

h_init = numpyro.sample('hidden_init', dist.Normal(loc=0, scale=10))
idx = 1
hlast, vals = scan(transition_fn, (h_init, idx), np.arange(100))
...
# later after model training
post_h = mcmc.get_samples()
# hope post_h = {'H_1': [...], 'H_2': [...], ...}
```
?

**Comment by fehiepsi** [comment]
I think you can loop over vals and use numpyro.deterministic to record their values.

**Comment by Hockey86** [comment]
Hey, thanks a lot! Your solution worked!
Actually, without assigning time index inside the variable name, instead of `f'H_{t}'`, just name it `'h_t'`, and `'h_t'` itself will become an array that contains all time steps. Nice!

**Comment by Hockey86** [comment]
Hey, thanks a lot! Returning (h_current, idx+1) did not work because idx
will still be a Jax object, not an int.
Actually, without assigning time index inside the variable name, instead of
`f'H_{t}'`, just name it `'h_t'`, and `'h_t'` itself will become an array
that contains all time steps. Nice!

**Comment by fehiepsi** [comment]
> just name it `'h_t'`, and `'h_t'` itself will become an array
that contains all time steps

That's right. Glad that the problem is resolved. :)
