### ISSUE TITLE
Question about JIT compiler

### ISSUE THREAD

**Issue by dcmvdbekerom** [pyro-ppl/numpyro#1287]
As the title says, I have a question about the JIT copiler.
Please let me know if this is not the right place to post this.

Let us use the 8 school MCMC model as an example.
For calculating the log-likelihood, the log-probabilty for the 8 elements are summed to calculate the potential energy here: https://github.com/pyro-ppl/numpyro/blob/6a0856b7cda82fc255e23adc797bb79f5b7fc904/numpyro/infer/util.py#L83

When evaluating the NUTS-kernel, the gradient of the potential energy function is evaluated here:
 https://github.com/pyro-ppl/numpyro/blob/6a0856b7cda82fc255e23adc797bb79f5b7fc904/numpyro/infer/util.py#L360

This sum and gradient could be replaced by a single VJP. 
My question is: Does the JIT compiler understand this and does it make this replacement?

Thank you!

**Comment by fehiepsi** [comment]
I'm not sure what's happening under the hood of JIT compiler. It is better to raise the question in JAX. :)
