### ISSUE TITLE
Subsampling local variables

### ISSUE THREAD

**Issue by tomasgeffner** [pyro-ppl/numpyro#1294]
Hi,

First of all, thanks for creating and maintaining Numpyro, I've been using it a lot! I have a question about subsampling in models with local variables. Let `g` represent the global variables, and `z = [z_1, z_2, ..., z_M]` the local variables (not observed, where we have M local variables). Consider the model

```
def model(M):
    u = numpyro.sample("u", Normal(0., 1.))
    z = numpyro.sample("z", Normal(u, np.ones(M)))
```

which is basically p(u, z) = N(u|0, 1) \prod_i N(z_i | u, 1). Is there a simple way of defining this model so that it allows subsampling the local variables? That is, I would like to pass the model a variable `u` and values for each of the local variables `z_i`, but getting an unbiased estimate of the potential function obtained by evaluating the model at some subset of the `z` (either chosen randomly, or by me passing a subset of indices).

Thanks!

**Comment by fehiepsi** [comment]
Hi @tomsons22, we mainly use github to track issues. For questions and discussions, please use the forum. For  subsampling, we use [plate](https://num.pyro.ai/en/stable/primitives.html#numpyro.primitives.plate) (see [this tutorial](https://pyro.ai/examples/svi_part_ii.html#Subsampling)).

**Comment by tomsons22** [comment]
Sorry about that, wasn't aware of the forum! And thanks for linking the tutorial, I'll have a look and reach out if needed. Thanks!

**Comment by fehiepsi** [comment]
For your model, you can do
```python
def model(M):
    u = numpyro.sample("u", Normal(0., 1.))
    with numpyro.plate("M", M, subsample_size=3):
        z = numpyro.sample("z", Normal(u, 1))
```
Let's close this issue and follow up in the forum if needed. :)
