### ISSUE TITLE
Automatic partial centering of hierarchical models

### ISSUE THREAD

**Issue by albcab** [pyro-ppl/numpyro#1311]
Hi! I am working on contributing an example/tutorial on automatic partial centering of hierarchical models (as in Algorithm 2 of https://arxiv.org/abs/1906.03028). For example, with Neal's funnel
```python
def model(dim=8):
    x1 = numpyro.sample('x1', dist.HalfNormal(5.))
    with numpyro.plate('j', dim-1):
        with numpyro.handlers.reparam(config={'xrest': LocScaleReparam(None)}):
            xrest = numpyro.sample('xrest', dist.Normal(0, x1))
```
I use SVI to train a base diagonal normal and the LocScale parameter
```python
guide = AutoDiagonalNormal(model)
svi = SVI(model, guide, numpyro.optim.Adam(.01), Trace_ELBO(100))
params = svi.run(jrnd.PRNGKey(123), 1000).params
```
to then fix the LocScale parameter and reparametrize the model
```python
model = numpyro.handlers.substitute(model, {'xrest_centered': params['xrest_centered']})
reparam_model = NeuTraReparam(guide, params).reparam(model)
```
which should help sampling algorithms. In the case of Neal's funnel all LocScale parameters are optimal at 0 but in real work scenarios it would be preferable for each `xrest` to have its own LocScale parameter. I'm wondering what is the best way to achieve this? My solution now is to do
```python
def model(dim=8):
    x1 = numpyro.sample('x1', dist.HalfNormal(5.))
    for i in range(dim-1):
        with numpyro.handlers.reparam(config={f'xrest{i}': LocScaleReparam(None)}):
            xrest = numpyro.sample(f'xrest{i}', dist.Normal(0, x1))
```
possibly with a `jax.lax.scan`/`fori_loop`. Pyro docs show `plate` as iterable but it's not iterable in numpyro, are there plans to make it iterable in numpyro too? Could I help in making this happen? Thanks for the help!

**Comment by fehiepsi** [comment]
Hi @albcab, I think you can move `plate` statement into the `reparam` handler.

You can use [our forum](https://forum.pyro.ai/) for questions and discussions. :)

**Comment by fritzo** [comment]
I believe the default behavior in Pyro is to create one learnable parameter per element of the latent variable. So in Pyro the default behavior should match what @albcab is requesting?

@albcab have you checked the shape of the `params['xrest_centered']` parameter?

@fehiepsi do you know if NumPyro behaves differently from Pyro here?

**Comment by fehiepsi** [comment]
Oh, it turns out that the parameters have the same shape as the distribution event shape, so only
```
dist.Normal(0, x1).expand([dim-1]).to_event()
```
works in both Pyro and NumPyro.

**Comment by albcab** [comment]
```python
def model(dim=8):
    x1 = numpyro.sample('x1', dist.HalfNormal(5.))
    with numpyro.handlers.reparam(fn=numpyro.plate('j', dim-1), config={f'xrest': LocScaleReparam(None)}):
        xrest = numpyro.sample(f'xrest', dist.Normal(0, x1).expand([dim-1]).to_event())
```
has the behaviour I was looking for ,thanks. The forum is great :)

**Comment by fehiepsi** [comment]
Glad that it works. I think you can also remove fn= part in the reparam handler.
