### ISSUE TITLE
`numpyro.render_model` behaviour changed in 0.9.0

### ISSUE THREAD

**Issue by tcbegley** [pyro-ppl/numpyro#1318]
I noticed that the behaviour of `numpyro.render_model` appears to have changed since the latest release, specifically arrows signifying conditional dependence are not being rendered properly.

I haven't had time to dig into why this is yet, but here is a simple recreation

```python
import numpyro
import numpyro.distributions as dist


def model():
    theta = numpyro.sample("theta", dist.Uniform())
    
    with numpyro.plate("N", size=10):
        numpyro.sample("y", dist.Bernoulli(theta))
        
        
if __name__ == "__main__":
    g = numpyro.render_model(model)
    g.render(f"model-{numpyro.__version__}", format="png")
```

Running this with 0.8.0 and 0.9.0 I get (respectively)

![model-0 8 0](https://user-images.githubusercontent.com/15220906/152194532-07f70d39-8197-41c5-9e14-beefc33b807e.png)

![model-0 9 0](https://user-images.githubusercontent.com/15220906/152194539-98a41b9f-a673-4937-b864-1fb9e6c3d420.png)

**Comment by tcbegley** [comment]
Seems like it may be related to #1248?

**Comment by tcbegley** [comment]
Something has changed in `get_model_relations` in `numpyro.contrib.render`. I get different outputs there with 0.8.0 and 0.9.0

```diff
{
- 'sample_sample': {'theta': [], 'y': ['theta']}, 
+ 'sample_sample': {'theta': [], 'y': []}, 
  'sample_dist': {'theta': 'Uniform', 'y': 'BernoulliProbs'}, 
  'plate_sample': {'N': ['y']}, 
  'observed': [],
}
```

**Comment by fehiepsi** [comment]
Could you try to use `jax 0.2.27`? I [suspected](https://github.com/pyro-ppl/numpyro/pull/1314#issuecomment-1028110807) it caused the problem.
