### ISSUE TITLE
Working example for Bayesian Quantile Regression and AsymmetricLaplace Distribution

### ISSUE THREAD

**Issue by d-diaz** [pyro-ppl/numpyro#1319]
I've prepared a simple working example of Bayesian Quantile Regression using an implementation of an AsymmetricLaplace distribution in a Colab Notebook [here](https://colab.research.google.com/drive/1h4yoaIYcDRHy6XYDtMgrUUCB0fJ1uf0v?usp=sharing). I'd like to offer this up as an example for numpyro documentation, but am not sure whether this needs to be converted to script or if it can be utilized as a notebook.

**Comment by fehiepsi** [comment]
Hi @d-diaz I think it is best to have asymmetric laplace distribution in the library and a tutorial (which might be best to explain how quantile regression works and how to use numpyro to such problem) or an example script with current content. Using asymmetric parameter will match wikipedia article but you can make a wrapper like a function `make_lilelihood(..., quantile)` for your convenience in example/tutorial. Thanks for contributing!

**Comment by fehiepsi** [comment]
It seems to me that the scale parameter lambda in the main wikipedia article should be the rate. Scipy also uses asymetry parameterization. If you find quantile argument useful, you can define a new distribution named AssymetryLaplaceQuantile or something like that. :)

**Comment by d-diaz** [comment]
I think it seems most sensible to implement an AssymetricLaplace class following the Scipy and Pyro and Wikipedia pattern and a distinct AsymmetricLaplaceQuantile class following the Bayesian quantile regression pattern. I don’t know the use cases for the AsymmetricLaplace with asymmetry parameterization, but did run into a the need for this quantile regression version in my own work. I’ll expand the minimal working example in Colab into a notebook tutorial around quantile regression and add these two classes into the library. Will report back here when that’s done.

**Comment by fehiepsi** [comment]
That's an awesome plan, thanks @d-diaz!
