### ISSUE TITLE
compat module: compat.infer.MCMC broken

### ISSUE THREAD

**Issue by alexander-maier** [pyro-ppl/numpyro#1321]
Calling
```python
compat.infer.MCMC(kernel, num_warmup=100, num_samples=1000)
```
throws an error since no kwargs are handed to `mcmc.MCMC`. Also, shouldnt the correct `compat` call be
```python
compat.infer.MCMC(kernel, warmup_steps=100, num_samples=1000)
```
Thanks :)

**Comment by fehiepsi** [comment]
Thanks, @alexander-maier! I think we'll need to use [keyword arguments here](https://github.com/pyro-ppl/numpyro/blob/9719466a584af80683a7aa04401d4e065cc569ae/numpyro/compat/infer.py#L99-L100). It is surprised to me that we don't have a test for this.
