### ISSUE TITLE
Vectorized sampling: error when var size is 0

### ISSUE THREAD

**Issue by hessammehr** [pyro-ppl/numpyro#1328]
JAX refuses to reshape an array using the `(-1, ...)` shape notation if its `size` (i.e. product of `shape`) is 0. This causes issues with vectorized sampling when samples from different chains are concatenated.

# Steps to reproduce
```python
import numpy as np
import numpyro

import numpyro.distributions as dist

from jax import random
from numpyro.infer import MCMC, NUTS

J = 8
n = 0
y = np.random.rand(n, J)
sigma = np.array([15.0, 10.0, 16.0, 11.0, 9.0, 11.0, 10.0, 18.0])


# Slightly modified Eight Schools example

def eight_schools(J, sigma, y=None):
    mu = numpyro.sample('mu', dist.Normal(0, 5))
    tau = numpyro.sample('tau', dist.HalfCauchy(5))
    with numpyro.plate('J', J):
        theta = numpyro.sample('theta', dist.Normal(mu, tau))
        numpyro.sample('obs', dist.Normal(theta, sigma), sample_shape=(n,))

nuts_kernel = NUTS(eight_schools)

mcmc = MCMC(nuts_kernel, num_warmup=50, num_samples=100, num_chains=2, chain_method='vectorized')

rng_key = random.PRNGKey(0)

mcmc.run(rng_key, J, sigma, y=y, extra_fields=('potential_energy',))
```

Sampling of individual chains works fine but a `[TypeError: reshape new_sizes must all be positive, got (-1, 0, 8).]()` is raised during final concatenation of samples.

# Possible fix
In `mcmc.py:612`

```python
states_flat = tree_map(
    lambda x: jnp.reshape(x, (-1,) + x.shape[2:]), states
)
```

simply calculating the dimension of the first axis is sufficient

```python
states_flat = tree_map(
    lambda x: jnp.reshape(x, (x.shape[0] * x.shape[1],) + x.shape[2:]), states
)
```

It seems unlikely that the issue can be "fixed" upstream in jax, since numpy has the same policy towards reshaping. Happy to open a PR with the above fix if it seems reasonable.

**Comment by fehiepsi** [comment]
Oh, what's the subtle issue. Please feel free to make the change.
