### ISSUE TITLE
Trivial model leaks tracer according to `jax.checking_leaks`

### ISSUE THREAD

**Issue by colehaus** [pyro-ppl/numpyro#1329]
See the gist here to reproduce: https://gist.github.com/colehaus/e68699dd0a5267545146025d4be6a027

If you run the model without checking for leaks, it seems to work fine and no tracer errors are thrown.

Interestingly, when I run the same code locally, no tracer leaks are flagged when running with `num_chains=1` but they are flagged when running with `num_chains=2`.

**Comment by fehiepsi** [comment]
This seems to be some (possibly false positive) leaks from an old version of jax. Could you try to update jax version?

**Comment by colehaus** [comment]
I just updated the gist and bumped to JAX 0.2.28 (sorry, didn't realize the standard NumPyro invocation for notebooks didn't install the latest version of JAX by default). Now the error only happens for `num_chains=2` which is the same behavior as locally (where I'm running 0.2.27).

**Comment by fehiepsi** [comment]
I'm seeing this warning
```
/usr/local/lib/python3.7/dist-packages/jax/core.py:757: UserWarning: JAX check_tracer_leaks behavior can trigger false positives when used with a debugger.
To avoid false positives and silence this warning, you can disable thread tracing using
the following:

  import threading
  threading.current_thread().pydev_do_not_trace = True
```
in your notebook. It seems that the issue is fixed in the master branch. You can try with
```
%pip install -qU --force-reinstall --no-deps jaxlib jax git+https://github.com/pyro-ppl/numpyro.git
```

**Comment by colehaus** [comment]
Ah, setting `pydev_do_not_trace = True` didn't make a difference but upgrading to master did. Thanks!
