### ISSUE TITLE
Notebook example for a nested hierarchical model

### ISSUE THREAD

**Issue by cstoafer** [pyro-ppl/numpyro#1336]
I'm interested in contributing a notebook example showing how to setup a nested hierarchical model.  I'm opening a ticket based on the suggestion from issue #189 to see if this is a valuable contribution.  

The notebook would outline a model similar to https://forum.pyro.ai/t/add-additional-level-in-hierarchical-model/3022/5 and https://forum.pyro.ai/t/hierarchical-model-with-two-levels/3775/6.  I plan to copy or extend the [Bayesian Hierarchical Linear Regression notebook](https://github.com/pyro-ppl/numpyro/blob/332dfd2dd0aa4a264da6d4ea190e0fed6a2ddf3b/notebooks/source/bayesian_hierarchical_linear_regression.ipynb) and include "SmokingStatus" as a partially pooled variable.

**Comment by fehiepsi** [comment]
Thanks, @cstoafer! We love to have more tutorials/examples. Please feel free to extend the Bayesian Hierarchical Linear Regression notebook. :)
