### ISSUE TITLE
Memory leak when calling MCMC multiple time with non-static observations

### ISSUE THREAD

**Issue by wiseodd** [pyro-ppl/numpyro#1347]
I'm aware of https://github.com/pyro-ppl/numpyro/issues/448 and its fix https://github.com/pyro-ppl/numpyro/issues/448#issuecomment-561984834. However, when the data in `mcmc.run` is dynamic (notice `np.random.randn()` in the last line of the following code), the memory leak becomes present again (4GB of memory usage and growing after 3 minutes). Any idea how to prevent this?

```python
import numpy as np
from numpyro import sample
import numpyro.distributions as dist
from jax import random
from numpyro.infer import MCMC, NUTS


def model(y_obs):
    mu = sample('mu', dist.Normal(0., 1.))
    sigma = sample('sigma', dist.HalfCauchy(3.))
    y = sample('y', dist.Normal(mu, sigma), obs=y_obs)

kernel = NUTS(model)
mcmc = MCMC(kernel, num_warmup=1, num_samples=2, progress_bar=False)
mcmc._compile(random.PRNGKey(0), np.zeros((1,)))

while True:
    mcmc.run(random.PRNGKey(0), np.random.randn())
```

**Comment by fehiepsi** [comment]
Could you try `mcmc = MCMC(..., jit_model_args=True)`? Otherwise, we can't prevent memory of jit caches.

**Comment by wiseodd** [comment]
Thanks a lot, it works! One additional question: Can we also use this workaround for SVI? I encountered a similar memory leak behavior and I can't find `jit_model_args` arg or its equivalent in SVI's docs.

**Comment by fehiepsi** [comment]
For SVI, you can do
```
@jit
def get_result(...):
   svi = ...
   return svi results
```
We think it is much simpler than we incorporate jit_model_args there. But you can create a FR for it.

**Comment by wiseodd** [comment]
Thanks!
