### ISSUE TITLE
Efficient Metropolis Adjusted Langevin Algorithm (MALA) Sampler?

### ISSUE THREAD

**Issue by HanGuo97** [pyro-ppl/numpyro#1353]
Hi, I noticed that we have a `MetropolisAdjustedLangevinAlgorithm` via `TFPKernel`. However, it seems like the latter is not very optimized (the runtime is very slow). I'm curious if there are plans to implement MALA natively using `numpyro`?

It also seems like MALA can be implemented as HMC [with just one leapfrog step](https://github.com/tensorflow/probability/blob/main/spinoffs/oryx/oryx/experimental/mcmc/kernels.py#L191-L194). Would that be the case in `numpyro` as well? Notably, I don't think the current HMC implementation has an explicit knob to set the number of leapfrog steps.

Thanks in advance for the help!

**Comment by fehiepsi** [comment]
> I don't think the current HMC implementation has an explicit knob to set the number of leapfrog steps

That's right. We can expose `num_leapfrog_steps` to HMC if it is useful. Currently, we used fixed trajectory, rather than fixed num_leapfrog_steps.

For MAHA, we welcome the contribution (using [this MH pattern](https://gist.github.com/aflaxman/8d52ded24d0279b1dbbe74dd91c283b6)). Currently, we don't have plan to implement it.

**Comment by HanGuo97** [comment]
Thanks! I noticed that in [this line](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/hmc.py#L358), `num_leapfrog_steps` is implicitly set to `trajectory_length / step_size`. In that sense, as long as I set `trajectory_length == step_size`, this should give me the expected behavior of MALA?

**Comment by fehiepsi** [comment]
I think so, as long as you set `adapt_step_size=False`. :)

**Comment by HanGuo97** [comment]
Got it, thanks again!
