### ISSUE TITLE
How to properly define a Mixture

### ISSUE THREAD

**Issue by mfouesneau** [pyro-ppl/numpyro#1357]
I am trying to define a mixture model 
Something like

<img src="https://render.githubusercontent.com/render/math?math=\color{gray}y_i ~\mid~ \hat{y}_{in}, \hat{y}_{out}, \sigma_y, \sigma_{out} \rightsquigarrow (1 - g_i) \, \mathcal{N}(\hat{y}_{in}, \sigma_y) + g_i \, \mathcal{N}(\hat{y}_{out}, \sigma_{out})">

I see there is a `MixtureSameFamily` which would work in my current example below but is not flexible to defining different distributions

I cannot make the model below work. I get `ValueError: All input arrays must have the same shape.`, which I cannot figure from where

```python
def jax_model_outliers(x=None, y=None, sigma_y=None):

    ## Define weakly informative Normal priors 
    beta = numpyro.sample("beta", dist.Normal(0.0, 100))
    alpha = numpyro.sample("alpha", dist.Normal(0.0, 100))

    ## Define Bernoulli inlier / outlier flags according to 
    ## a hyperprior fraction of outliers, itself constrained
    ## to [0,.5] for symmetry
    frac_outliers = numpyro.sample('frac_outliers', dist.Uniform(low=0., high=.5))

    ## variance of outliers
    sigma_y_out = numpyro.sample("sigma_y_out", dist.HalfNormal(100))

    with numpyro.plate("data", len(y)):
        ## define the linear model
        ypred_in = numpyro.sample("ypred_in", 
                                  dist.Normal(beta + alpha * x, sigma_y))

        ypred_out = numpyro.sample("ypred_out", dist.Normal(0, sigma_y_out))
    
        is_outlier = numpyro.sample('is_outlier', 
                                    dist.Bernoulli(frac_outliers), 
                                    infer={'enumerate': 'parallel'})
        # Explicit for debugging
        mix_ = dist.Categorical(probs=jnp.array([is_outlier, 1 - is_outlier]))
        comp_ = dist.Normal(jnp.array([beta + alpha * x, sigma_y, 0]),
                            jnp.array([sigma_y, sigma_y_out]))
        mixture = dist.MixtureSameFamily(mix_, comp_)

        # likelihood
        numpyro.sample("obs", mixture, obs=y)
```

Thanks for help

**Comment by fehiepsi** [comment]
Hi @mfouesneau, could you use https://forum.pyro.ai/ for questions? I think you can try to isolate the issue by printing out shapes of all variables in your model. And see where the error happens (e.g., would using `jnp.array([beta + alpha * x, sigma_y, 0])` works).

**Comment by mfouesneau** [comment]
@fehiepsi, I did not manage to connect to the forum. With both email and Github `Sorry, there was an error authorizing your account. Please try again.`

**Comment by mfouesneau** [comment]
Moved to forum: https://forum.pyro.ai/t/how-to-properly-define-a-mixture/3980
