### ISSUE TITLE
General Advice for Handling GPU Out-of-memory Errors for MCMC

### ISSUE THREAD

**Issue by HanGuo97** [pyro-ppl/numpyro#1359]
Hi, I noticed that I repeatedly ran into out-of-memory errors on GPUs when running MCMC (notably, `NUTS`/`HMC`). I searched around the issues and came across a couple of fixes such as `progress_bar`, but that unfortunately didn't work for me.

I'm curious if there is some general advice for handling such errors, e.g., places to change? I wasn't able to create a minimum example, as OOM happens usually after hours of running. Thanks in advance for the help!

(Not sure if this is useful, by my use case involves running different MCMC on different objectives in sequence, thousands of them. Each runs <1 min, and I frequently observed an OOM error after a few hundred of these.)

**Comment by fehiepsi** [comment]
Hi @HanGuo97 could you ask your question in our forum? It is easier to search around and discuss there.

**Comment by HanGuo97** [comment]
Unfortunately, I'm having trouble posting this in the forum. Couldn't sign up for some reason... I will close this question here for now then.

**Comment by fehiepsi** [comment]
Maybe you need to sign-up using email. For some reason, github registration does not work...
