### ISSUE TITLE
A question about generalizing into domain specific models (e.g. time series) 

### ISSUE THREAD

**Issue by hesenp** [pyro-ppl/numpyro#1361]
I noticed that we already have [a few time series forecasting models](https://num.pyro.ai/en/stable/tutorials/time_series_forecasting.html) as part of the examples. For these models we mostly write the models from ground up.

On the other side of the spectrum, there's all these open source packages like Prophet, Orbit which just rely on a few models internally, but have more of a peripheral functions to make them easy to use for folks who are not modeling experts. Coincidentally, Orbit has [this LGT model](https://uber.github.io/orbit/tutorials/lgt.html) which is highly similar to the SGT model that Numpyro has used as an example, linked above. 

I wonder if there's any thoughts to building some domain specific models/packages based on numpyro? like `numpyro-ts` that uses numpyro as compute engine in the backend, but has utility functions in the front, so that people could do modeling easily? 

an example code would like: 

```
model = SGT() 
model.fit(data_frame)
model.predict(another_data_frame)
```

this could make the code / package very easy to get picked up by general practitioners.

**Comment by fehiepsi** [comment]
There are efforts in the past https://github.com/pyro-ppl/numpyro/pull/544 https://github.com/pyro-ppl/numpyro/pull/551 see e.g. [the lynx example](https://github.com/pyro-ppl/numpyro/blob/36457e8e15cd898ded44a2a8d5fd038d429606a1/numpyro/contrib/forecast/lynx.ipynb). If anyone is interested, please feel free to reuse/modify the code there but I think it is better to start with some popular algorithms e.g. those in [Rob Hyndman's forecasting book](https://otexts.com/fpp3/ses.html).

**Comment by hesenp** [comment]
oh interesting. what's your thought on these code in the [forecast folder](https://github.com/fehiepsi/numpyro/tree/pylgt/numpyro/contrib/forecast) @fehiepsi ? do you have plans to check them in some time?

**Comment by fehiepsi** [comment]
Hi @hesenp, I don't have a plan for it. Currently, for time series problems, I just construct the model from scratch. But I believe having a module for basic forecasting models would be useful for many people.

**Comment by fehiepsi** [comment]
That API sounds reasonable to me. We can have default methods to get init values/ to-be-scanned values for traditional models while still provides extensions for some derived models. Like to include global terms as in [Orbit](https://uber.github.io/orbit/tutorials/dlt.html)

**Comment by hesenp** [comment]
Yeah Orbit is where I started to get the idea. The pattern is even more apparent in their [StanEstimator](https://github.com/uber/orbit/blob/dev/orbit/estimators/stan_estimator.py). Basically the core model is specified through a bunch of stan files. The rest is all wrappers to massage data and run the estimation. Prophet is similar too. Prophet is basically all resolving around just [one single stan file](https://github.com/facebook/prophet/blob/main/python/stan/unix/prophet.stan). The rest is all house keeping code.

**Comment by fehiepsi** [comment]
If you want, we can write a [design doc](https://github.com/pyro-ppl/pyro/wiki/Design-Docs) to exercise models that we want to put into (personally, I prefer textbook models to complicated ones so it might be easier to find common patterns for my usage case). I'm happy to collaborate. :)

**Comment by hesenp** [comment]
Interesting ... seems Fritz and Martin gave some thought into this way back as well, as documented in [this doc](https://docs.google.com/document/d/1jqQ_7mCnggqqmICzux2Fr9yvHO5AoVpBdmjNC0i6JAY/edit#heading=h.9kdf8uwe49yj). I guess I'll just carve out some time in the weekend to doodle a prototype out.

**Comment by fehiepsi** [comment]
@tomwallis designed an api for object-oriented wrappers around numpyro in https://github.com/ag-perception-wallis-lab/numpyro-oop I think that is the way to go for domain-specific models.
