### ISSUE TITLE
[Examples]: Using Cholesky decomposition for GP decomposition kernel matrix inversion

### ISSUE THREAD

**Issue by nipunbatra** [pyro-ppl/numpyro#1364]
The [GP example](https://num.pyro.ai/en/latest/examples/gp.html) directly inverts the covariance matrix.

```python
K_xx_inv = jnp.linalg.inv(k_XX)
K = k_pp - jnp.matmul(k_pX, jnp.matmul(K_xx_inv, jnp.transpose(k_pX)))
```

It may be better to use the Cholesky decomposition instead. See the following for an implementation: https://gregorygundersen.com/blog/2019/09/12/practical-gp-regression/

Should be a simple fix. I can have a student submit a PR if this is of interest.

**Comment by fehiepsi** [comment]
Hi @nipunbatra I think it is intended to use non-optimized code there. cc @martinjankowiak

**Comment by jecampagne** [comment]
@nipunbatra  Ho that would be great for me if you have some more effective code.
