### ISSUE TITLE
Gaussian Process example: a typo or a bug?

### ISSUE THREAD

**Issue by jecampagne** [pyro-ppl/numpyro#1373]
Hello, here are few lines picked up from the Gaussian Process example:
```python
# do GP prediction for a given set of hyperparameters. this makes use of the well-known
# formula for gaussian process predictions
def predict(rng_key, X, Y, X_test, var, length, noise):
    # compute kernels between train and test data, etc.
    k_pp = kernel(X_test, X_test, var, length, noise, include_noise=True)      
    k_pX = kernel(X_test, X, var, length, noise, include_noise=False)
    k_XX = kernel(X, X, var, length, noise, include_noise=True)
````
Looking for instance at the book 
```
C. K. I. Williams, Gaussian Processes for Machine Learning, the MIT Press, 2006,
```
page 16

![image](https://user-images.githubusercontent.com/20539759/159229508-b1c2f815-f25f-4492-b212-57be07c7ebba.png)

I would expect that `k_pp` is defined **without noise** 
```python
 k_pp = kernel(X_test, X_test, var, length, noise, include_noise=False)  
```
Don't you think ?
Thanks.

**Comment by fehiepsi** [comment]
I think Kpp with noise corresponds to y while without noise corresponds to f.

**Comment by jecampagne** [comment]
But if I am write `Kpp` is what is defined as `K(X_ast,X_ast)`   which is used for `bar(f)_*` and `cov(f_ast)`.

**Comment by jecampagne** [comment]
By the way the  [Gpy](https://github.com/SheffieldML/GPy/blob/devel/GPy/core/gp.py) library introduces `predict_noiseless` function:
```python

    def predict_noiseless(self,  Xnew, full_cov=False, Y_metadata=None, kern=None):
        """
        Convenience function to predict the underlying function of the GP (often
        referred to as f) without adding the likelihood variance on the
        prediction function.
        This is most likely what you want to use for your predictions.
```

**Comment by fehiepsi** [comment]
Yes, if you want noiseless prediction then you can set `include_noise=False`.

**Comment by fehiepsi** [comment]
I guess this is already clarified. Please feel free to reopen this one if needed.
