### ISSUE TITLE
[Feature Request] Show params in `render_model()`

### ISSUE THREAD

**Issue by karm-patel** [pyro-ppl/numpyro#1379]
Hi @fehiepsi and team,

Prof. @nipunbatra explained the [issue](https://github.com/pyro-ppl/pyro/issues/3023) (in `pyro`) of rendering params in `pyro.render_model()` and then I added this feature in `pyro` ([PR](https://github.com/pyro-ppl/pyro/pull/3039)). I would like to add the same feature in `numpyro`. 

I have tried to add this feature for `numpyro`  and tested it on some examples. Consider the following model,

```python
def model(data):
    m = numpyro.param("m", jnp.array(0))
    sd = numpyro.param("sd", jnp.array([1]),constraint=constraints.positive)
    lambd = numpyro.sample("lambda",dist.Normal(m,sd))
    with numpyro.plate("N", len(data)):
        numpyro.sample("obs", dist.Exponential(lambd), obs=data)
```
I have added `sample_params` and `params_constraint` keys in dictionary returned by `contrib.render.get_model_relations()`.  I added Provenance Tracking for params in `get_model_relations` to add values in `sample_param`.
```python
numpyro.contrib.render.get_model_relations(model,model_args=(data,))
```
![image](https://user-images.githubusercontent.com/59387624/160380376-608f5744-5bae-4179-a122-50046afb9352.png)

```python
data = jnp.ones(10)
numpyro.render_model(model, model_args=(data,), render_distributions=True))
```
![image](https://user-images.githubusercontent.com/59387624/160379101-c6ab2b2a-d194-4c50-a1a9-5e727973ae19.png)

I have added optional argument `render_params` in `render_model()` to show params in the plot. Also, `render_distributions=True` shows the constraints of params with distributions of the sample.

```python
numpyro.render_model(model, model_args=(data,), render_params=True, render_distributions=True)
```
![image](https://user-images.githubusercontent.com/59387624/160378988-916f2dc4-f281-4430-ad96-a54dfb71a4a7.png)

**@fehiepsi, Can you please review this? if it meets your expectaion, then I would like to create a PR for the same.**

**Comment by fehiepsi** [comment]
Thanks @karm-patel! The enhancement looks great to me.
