### ISSUE TITLE
How to deal with parameter as sum of a constant + a numpyro.sample distribution?

### ISSUE THREAD

**Issue by jecampagne** [pyro-ppl/numpyro#1382]
Hello,

I have a question (stupid certainly), if I have a model using a parameter `k` that I know is above 4, if I code  
```python
k  = 4. + numpyro.sample('k', dist.LogNormal(0.1))
```
and running NUTS I get
```
                 mean       std    median      5.0%     95.0%     n_eff     r_hat
          k      1.77      1.78      1.20      0.04      3.98   1254.35      1.00
```
does this means that the "k" parameter in the `spls=mcmc.get_sample()` will be the "k" of the numpyro.sample or the "k" python variable that I have defined?

It seems that I should add the constant "4" to the `spls["k"]`, right?

Thanks.

**Comment by fehiepsi** [comment]
Hi @jecampagne, please use [our forum](https://forum.pyro.ai/) for questions and discussions.

You can use
```
k  = numpyro.deterministic("k", 4. + numpyro.sample('k_base', dist.LogNormal(0.1))
```
or
```
k  = numpyro.sample('k', dist.TransformedDistribution(dist.LogNormal(0.1), dist.transforms.AffineTransform(4., 1.))
```
You can also add `4` to `spls["k"]`.
