### ISSUE TITLE
CAR sampler

### ISSUE THREAD

**Issue by theorashid** [pyro-ppl/numpyro#1390]
This is a proposed **enhancement**.

Conditional autoregressive (CAR) models are very useful in spatial settings. Previously, our group has specified a model with a CAR as

```
tau = numpyro.sample('tau', dist.Gamma(14, 4))
alpha = numpyro.sample('alpha', dist.Uniform(low=0.0, high=1.0))

D = jnp.diag(d)
Q = tau*(D - alpha * A)
phi = numpyro.sample('phi', dist.MultivariateNormal(loc=jnp.zeros(N), precision_matrix=Q))
```

`d` is a vector of the number of neighbours of each spatial unit. `A`, is our adjacency matrix: specifying which spatial units share a boundary.

There are implementations in [pymc](https://github.com/pymc-devs/pymc/blob/fa015e3c1f7e087ea5577ba777ca8a631ed7eccd/pymc/distributions/multivariate.py#L2105) and [stan](https://mc-stan.org/users/documentation/case-studies/mbjoseph-CARStan.html), which make use of the sparseness of A, where possible, to improve efficiency in calculating logp. There are also variations like [ICAR](https://mc-stan.org/users/documentation/case-studies/icar_stan.html), which are popular in the spatial statistics field.

Is this something worth implementing or are the efficiency gains going to be very small relative to our current implementation? Is it easy to implement (just port from pymc)? Happy to have a go but I'd need a fair amount of direction and help

**Comment by fehiepsi** [comment]
Hi @theorashid, there is a [jax.experimental.sparse](https://jax.readthedocs.io/en/latest/jax.experimental.sparse.html) module but I'm not sure if it helps here. I will need to dive into it a bit...

**Comment by theorashid** [comment]
There's also [jax.scipy.sparse](https://jax.readthedocs.io/en/latest/jax.scipy.html#module-jax.scipy.sparse.linalg). Looking at the pymc code, we'd need equivalents of `aesara.sparse.dot` and `at.slinalg.eigvalsh` and some way of detecting whether A is sparse. Quite impressive that the aesara team built up sparse functions. I'm surprised jax don't have this functionality

**Comment by fehiepsi** [comment]
Looking at the Stan post, I think you don't need to use JAX here. Just simply computing those quantities using numpy and when compiled, they will become constants, hence become pretty fast to compute.

**Comment by theorashid** [comment]
Okay looking at the pymc implementation, which is equivalent to the stan one, comments inline:

```python
# this block involes manipulating adjacency matrix W and calculating eigenvalues
# this block is only computed once, so we can use the numpy equivalents
if sparse:
    D = sp_sum(W, axis=0)
    Dinv_sqrt = at.diag(1 / at.sqrt(D))
    DWD = at.dot(aesara.sparse.dot(Dinv_sqrt, W), Dinv_sqrt)
else:
    D = W.sum(axis=0)
    Dinv_sqrt = at.diag(1 / at.sqrt(D))
    DWD = at.dot(at.dot(Dinv_sqrt, W), Dinv_sqrt)
lam = at.slinalg.eigvalsh(DWD, at.eye(DWD.shape[0]))

d, _ = W.shape

if value.ndim == 1:
    value = value[None, :]

logtau = d * at.log(tau).sum()
logdet = at.log(1 - alpha.T * lam[:, None]).sum()
delta = value - mu

# this block involes quantities calculated at each iteration
if sparse:
    Wdelta = aesara.sparse.dot(delta, W)
else:
    Wdelta = at.dot(delta, W)

tau_dot_delta = D[None, :] * delta - alpha * Wdelta
logquad = (tau * delta * tau_dot_delta).sum(axis=-1)
```

So I think only `Wdelta = jnp.dot(delta, W)` would need a sparse equivalent, as that's the only sparse part computed at each iteration. How much difference would a sparse represenation of `Wdelta` make here? `dot` should be quite fast

**Comment by fehiepsi** [comment]
I think the speed depends on the size of `W`. jax sparse library supports dot product of a sparse matrix and a vector, something like
```python
from jax.experimental.sparse import BCOO

W = BCOO.from_scipy_sparse(W_sparse)
Wdelta = W @ delta
```

**Comment by theorashid** [comment]
Okay so it would be something like:

```python
class CAR(Distribution):
    arg_constraints = {
        "mu": constraints.real_vector,
        "W": constraints.positive_definite,
        "alpha": constraints.unit_interval,
        "tau": constraints.positive,
    }
    support = constraints.real_vector
    reparametrized_params = [
        "mu",
        "alpha",
        "tau",
    ]

    def __init__(
        ...
    ):
        ...

    @validate_sample
    def log_prob(self, value):
        D = W.sum(axis=0)
        Dinv_sqrt = jnp.diag(1 / jnp.sqrt(D))
        DWD = jnp.dot(jnp.dot(Dinv_sqrt, W), Dinv_sqrt)

        lam = jnp.linalg.eigvalsh(DWD, at.eye(DWD.shape[0]))

        d, _ = W.shape

        logtau = d * jnp.log(tau).sum()
        logdet = jnp.log(1 - alpha * lam[:, None]).sum()
        delta = value - mu

        if isinstance(W, scipy.sparse.spmatrix):
            W = BCOO.from_scipy_sparse(W)

        Wdelta = W @ delta # is this always sparse?

        tau_dot_delta = D[None, :] * delta - alpha * Wdelta
        logquad = (tau * delta * tau_dot_delta).sum(axis=-1)

        return -0.5 * (logtau + logdet - logquad)

    ...
```

Roughly. Unless you think the first few logp terms need to be sparse as well. Apparently alpha can be an array but I've only ever seen it used as a float. I'd need a fair amount of help with all the other functions that make the distribution work in numpyro.

**Comment by fehiepsi** [comment]
> the D, Dinv_sqrt, DWD terms need to be sparse

I think so. The computations that involve `W_sparse` can be moved to the sparse block:
```
# Compute lambda
D = W.sum(axis=-1)
D_rsqrt = D ** (-0.5)
W_scaled = W * (D_rsqrt * D_rsqrt[:, None])  # not sure if it's better to use some sparse op here?
if scipy.sparse.issparse(W):
    lambda = np.linalg.eigvalsh(W_scaled, np.eye(D.shape[-1]))
    W = BCOO.from_scipy_sparse(W)
else:
    lambda = jnp.linalg.eigvalsh(W_scaled, np.eye(D.shape[-1]))
W_delta = W @ delta  # this is fast if W is sparse
```

(I would suggest to use the notation and the algorithm demonstrated in the Stan article as reference, rather than using code from PyMC - otherwise we will need to add copyright notice for this distribution.)

> make the distribution work in numpyro

For broadcasting, I think you can follow the logic in MVN. You can skip broadcasting W if W is sparse. For the `sample` method, I guess we can use sparse computation (I don't how to derive the math for it) but if it is not required in your usage case, we can just simply draw samples from MVN distribution.

Some other pointers:
+ You can add test case [here](https://github.com/pyro-ppl/numpyro/blob/master/test/test_distributions.py#L368)
+ The distribution is exposed [here](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/distributions/__init__.py)
+ The sphinx entry can be added [here](https://github.com/pyro-ppl/numpyro/blob/master/docs/source/distributions.rst)
