### ISSUE TITLE
Ran out of free dims during allocation for assignment25

### ISSUE THREAD

**Issue by Tiantian-H** [pyro-ppl/numpyro#1393]
Hi, I encountered the following error: 

ValueError   Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/numpyro/contrib/funsor/enum_messenger.py](https://localhost:8080/#) in _gendim(self, name_request, dim_request)
    132             or (dim_type == DimType.VISIBLE and fresh_dim <= self._first_available_dim)
    133         ):
--> 134             raise ValueError(f"Ran out of free dims during allocation for {fresh_name}")
    135 
    136         return fresh_name, fresh_dim

ValueError: Ran out of free dims during allocation for assignment25

when implenmenting 

` for i in range(100):
        assignment_i = numpyro.sample("assignment"+str(i), dist.Categorical(weights))`

I know in pyro, `pyro.markov` can be used to handle over 25 variables in enumeration, However, it seems that there's no `numpyro.markov` function in numpyro. Could you please give me any advice?

Besides, I know it's possible to use 
`with numpyro.plate('n',100):
        assignments = numpyro.sample("assignments", dist.Categorical(weights)) `  
to generate a vector of 100 elements, however, in my case I do need seperate index. But I find it's not possible to use
`assignment_i = assignments[i]` to extract each separate element due to the change of dimension during enumeration.

Thank you so much!

**Comment by fehiepsi** [comment]
I think you can use [contrib.funsor.markov](https://num.pyro.ai/en/stable/funsor.html#numpyro.contrib.funsor.enum_messenger.markov) but native loops in JAX would be slow. I would recommend to use `scan` as in the [hmm](https://num.pyro.ai/en/stable/examples/hmm_enum.html) example.

**Comment by fehiepsi** [comment]
Hope that your issue has been resolved. Please feel free to reopen this if needed.
