### ISSUE TITLE
Support for polars

### ISSUE THREAD

**Issue by GH-maggio** [pyro-ppl/numpyro#1396]
I'm just inquiring if there are any plans to support polars, an alternative to pandas. I'm currently going through [https://github.com/fehiepsi/rethinking-numpyro](https://github.com/fehiepsi/rethinking-numpyro) and while I can cast polars Series into numpy arrays, what would need to be done to support polar dataframes?

polars: [https://pola-rs.github.io/polars-book/user-guide/index.html](https://pola-rs.github.io/polars-book/user-guide/index.html)

This does work though:

```
# Load the data:
# car braking distances in feet paired with speeds in km/h
# see cars.info() for details
cars = pd.read_csv("../data/cars.csv", index_col=0)

import polars as pl

cars = pl.read_csv("../data/cars.csv")


# fit a linear regression of distance on speed
def model(speed, dist_):
    mu = numpyro.param("a", 0.0) + numpyro.param("b", 1.0) * speed
    numpyro.sample("dist", dist.Normal(mu, 1), obs=dist_)


svi = SVI(
    model,
    lambda speed, dist_: None,
    optim=optim.Adam(1),
    loss=Trace_ELBO(),
    #speed=cars.speed.values,
    #dist_=cars.dist.values,
    speed=cars.speed.to_numpy(),
    dist_=cars.dist.to_numpy(),
)
```

**Comment by fehiepsi** [comment]
Hi @GH-maggio, we only support numpy/jax arrays. If you want to use your data format, I would recommend to write some wrappers on the top of numpyro that do the conversion.

**Comment by GH-maggio** [comment]
Thank you @fehiepsi, I think the `.to_numpy()` will work for me.
