### ISSUE TITLE
Resume the mcmc.run() training  

### ISSUE THREAD

**Issue by YihaoZhou27** [pyro-ppl/numpyro#1397]
I am trying to run a time-consuming MCMC sampler. I am wondering if it is possible to resume the training after I save and reload the MCMC object. 

To be specific, in my case, I need to run many MCMC iterations and each step generally takes a long time. I use GPU node so the maximum walltime of each job is limited. I have to run `mcmc.run()` for some steps and save the results, which hasn't been converged. Then I want to reload the mcmc object and continue the warmup step. Is it possible? Now each time I run `mcmc.run()`, it seems it starts from scratch.

**Comment by fehiepsi** [comment]
Hi @YihaoZhou27, would [post warmup state](https://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.MCMC.post_warmup_state) be suffice?

**Comment by YihaoZhou27** [comment]
Oh, sorry. I should open this issue in pyro. I use pyro actually. So is there a similar implementation in pyro?

**Comment by fehiepsi** [comment]
For Pyro, it is trickier. Please feel free to open an issue for it. Thanks!
