### ISSUE TITLE
non-expected behaviour for numerically large parameters?

### ISSUE THREAD

**Issue by eyhl** [pyro-ppl/numpyro#1411]
Hi I am running some test to use numpyro in a context of geophysics, where parameter values can be of size 1e10. 

It seems to me that numpyro behaves oddly when I try to sample a Normal(1e10, 1e9) for an example. See comparison between numpyro and pyro below.

**Numpyro**
```
import numpyro
import numpyro.distributions as np_dist
from numpyro.infer import MCMC, NUTS

def model():

    # sample1 = numpyro.sample("rigidity1", bounded_rig1)
    sample1= numpyro.sample("rigidity1", np_dist.Normal(1e10, 1e9))
    
rng_key = random.PRNGKey(0)
rng_key, rng_key_ = random.split(rng_key)

# Run NUTS.
kernel = NUTS(model)
num_samples = 1000
mcmc = MCMC(kernel, num_warmup=1, num_samples=num_samples)
mcmc.run(rng_key_)

print(mcmc.get_samples()["rigidity1"].min() , mcmc.get_samples()["rigidity1"].mean(), mcmc.get_samples()["rigidity1"].max())
```
**Output**
`-158660.42 -44193.098 75339.68`

**Pyro**
```
import pyro
import pyro.distributions as dist
from pyro.infer import MCMC, NUTS

def model(height, obs=None, df_em=None):
    sample1 = pyro.sample("rigidity1", dist.Normal(1e10, 1e9))

# Run inference in Pyro
nuts_kernel = NUTS(model)
mcmc = MCMC(nuts_kernel, num_samples=1000, warmup_steps=1, num_chains=1)
mcmc.run(X_train, y_train, df_em)

print(mcmc.get_samples()["rigidity1"].min() , mcmc.get_samples()["rigidity1"].mean(), mcmc.get_samples()["rigidity1"].max())
```
**Output**
`tensor(-0.5968) tensor(1.0164e+10) tensor(1.9318e+10)`

Any ideas what causes this?

**Comment by martinjankowiak** [comment]
@eyhl i don't know why the results in pyro are different but it's generally a terrible idea to have very large/small numbers in models. wherever possible the model should be redefined so that parameters are O(1). for example one might write:

```
def model(height, obs=None, df_em=None):
    sample1 = 1e10 * pyro.sample("rigidity1", dist.Normal(1.0, 0.1))
```

in any case i think this sort of question is probably more suitable for our [forum](https://forum.pyro.ai/)
