### ISSUE TITLE
A strange bug

### ISSUE THREAD

**Issue by nana-zhang** [pyro-ppl/numpyro#1417]
Hello, I am a beginner of numpyro. After Jax is installed, numpyro is installed with conda, but when I simply call numpyro.sample() The following error occurred. I am confused. Can you help me?
![1ac09c679124614f84bd5ffb846faad](https://user-images.githubusercontent.com/70929994/171617942-136eda96-5baa-4dca-b88f-e12ec7f400d5.png)

**Comment by martinjankowiak** [comment]
please refer to the [FAQ](https://github.com/pyro-ppl/numpyro#frequently-asked-questions)
