### ISSUE TITLE
change the number of parallel chains within the program

### ISSUE THREAD

**Issue by HerculesJack** [pyro-ppl/numpyro#1421]
Hi, to my understanding, to run multiple MCMC chains in parallel, we'd need to call `numpyro.set_host_device_count(n)` at the beginning of the program, before any jax calls, like this:

```
import numpyro
numpyro.set_host_device_count(4)
import jax.numpy as jnp
from jax.random import PRNGKey
from numpyro.infer import MCMC, NUTS

def f(x):
    return ((x - 2)**2 / 2).sum()

kernel = NUTS(potential_fn=f)
mcmc = MCMC(kernel, num_warmup=1000, num_samples=1000000, num_chains=4)
mcmc.run(PRNGKey(0), init_params=jnp.ones((4, 32)))
posterior_samples = mcmc.get_samples()
assert jnp.all(jnp.abs(jnp.std(posterior_samples, axis=0) - 1) < 0.1)
# mcmc.print_summary()
```

While if we change the first few lines to this, it won't run 4 chains in parallel.

```
import numpyro
import jax.numpy as jnp
jnp.ones(3)
numpyro.set_host_device_count(4)
```

Is it possible to lift this restriction? If I understand correctly, this is because once any jax evaluation is done, the xla environment variables are read and stored and will not be read again. Can we kind of "force reimport" jax within `numpyro.set_host_device_count(n)`, so that it will observe the new value of xla variables? This will give us better control of the parallelization. Thanks.

Related previous threads: #364, pyro-ppl/brmp#17, @fehiepsi, @neerajprad

**Comment by fehiepsi** [comment]
I don't think that this is possible for now. Please reach out to jax devs for suggestions on modifying host devices during executions.
