### ISSUE TITLE
DLT Model - Logistic Trend

### ISSUE THREAD

**Issue by scroobiustrip** [pyro-ppl/numpyro#1431]
Hey there, 

I initially posted this on the Pyro forum, however they believed this was an issue rather than a problem specific to the model (although I'm sure it can be improved) so thought I add it as an issue.

Recently I've been trying to implement the [DLT model](https://orbit-ml.readthedocs.io/en/stable/tutorials/dlt.html) from Uber's Orbit package in Numpyro, using a logistic global trend.

However, I'm encountering an issue where it only returns a flat trend regardless of what changes I make, (unlike when using linear trend which seems to work fine!).

Trying to copy the [stan code](https://github.com/uber/orbit/blob/dev/orbit/stan/dlt.stan#L245-L246), the logistic function is written as:

```python
@jax.jit
def logistic(floor, cap, level, coef, time_delta, t):
    return floor + (cap - floor) / (1. + jnp.exp(-1. * (level + coef * (t - 1) * time_delta)))
```

With the model specified as:

```python
def dlt(
    y, 
    global_trend='logistic', 
    floor=11.75, 
    cap=9999, 
    damped_factor=0.8,
    n_seasons=52, 
    future=0) -> None:

    time_delta = 1
    cauchy_sd = jnp.max(y) / 150
    response_sd = jnp.std(y) 
    # smoothing params
    lev_sm = numpyro.sample('lev_sm', dist.Uniform(0, 1))
    slp_sm = numpyro.sample('slp_sm', dist.Uniform(0, 1))
    # dof
    nu = numpyro.sample('nu', dist.Uniform(2, 20))
    # residuals
    obs_sigma = numpyro.sample('obs_sigma', dist.HalfCauchy(cauchy_sd))
    # local trend proportion
    lt_coef = numpyro.sample('lt_coef', dist.Uniform(0, 1))

    if global_trend in ['logistic']:
        gl = numpyro.sample('gl', dist.Normal(0, 10))
        gb = numpyro.sample('gb', dist.Laplace(0, 1))
    else:
        gl = numpyro.sample('gl', dist.Normal(0, response_sd))
        gb = numpyro.sample('gb', dist.Normal(0, response_sd))

    # seasonal params
    sea_sm = numpyro.sample('sea_sm', dist.Uniform(0, 1))

    # initial seasonality
    with numpyro.plate('n_seasons', n_seasons):
        init_s = numpyro.sample("init_s", dist.Cauchy(0, 0.3))

    def transition_fn(carry, t):

        level, trend, s = carry

        if global_trend == 'logistic':
            gt_sum = numpyro.deterministic('gt_sum', logistic(floor, cap, gl, gb, time_delta, t))
        else:
            gt_sum = numpyro.deterministic('gt_sum', linear(gl, gb, time_delta, t))

        ## Forecast process
        lt_sum = level + damped_factor * trend
        y_hat = jnp.clip(gt_sum + lt_sum + s[0], a_min=0.)
        y_t = jnp.where(t >= T, y_hat, y[t])

        level_prev = level
        trend_prev = trend

        ## Update process
        level = lev_sm * (y_t - gt_sum - s[0]) + (1 - lev_sm) * lt_sum 
        trend = slp_sm * (level - level_prev) + (1 - slp_sm) * damped_factor * trend_prev
        new_s = sea_sm * (y_t - gt_sum - level) + (1 - sea_sm) * s[0]

        new_s = jnp.where(t >= T, s[0], new_s)        
        season = jnp.concatenate([s[1:], new_s[None]], axis=0)

        y_ = numpyro.sample('y', dist.StudentT(nu, y_hat, obs_sigma))

        return (level, trend, season), y_ 

    T = y.shape[0]

    level_init, trend_init = y[0], y[0]

    s_init = jnp.concatenate([init_s[1:], init_s[:1]], axis=0)

    carry = (level_init, trend_init, s_init)

    with numpyro.handlers.condition(data={'y': y[1:]}):
        _, ys = scan(
            transition_fn,
            carry,
            jnp.arange(1, T + future)
        )

    if future > 0:
        numpyro.deterministic("y_forecast", ys[-future:])
```

However, unfortunately when forecasting all I can get the model to return is a flat trend rather than one that saturates as it approaches the floor value.

There’s a line in the [stan file](https://github.com/uber/orbit/blob/dev/orbit/stan/dlt.stan#L255-L264) about initially setting the level to 0 to try and solve a degeneracy problem, but it didn't make too much difference when trying to replicate this by adding:

```python
lt_sum = jnp.where(
    t >= 1, 
    level + damped_factor * trend, 0.
) 
```

I’ve been using the sample dataset from the Orbit [DLT example](https://github.com/uber/orbit/blob/dev/examples/dlt.ipynb) itself to try and test this.

Any help would be hugely appreciated!

**Comment by scroobiustrip** [comment]
Hey @fehiepsi have posted it [here](https://forum.pyro.ai/t/dlt-model-logistic-trend/4349) if anyone gets a chance to look - if it looks beyond all hope, pls say I'll take another stab at it another time 😅

**Comment by fehiepsi** [comment]
Hi @scroobiustrip, I took a look at the model - it's pretty complicated so I'm not sure which causes your observation... Probably you can check the posterior samples. If there are extreme values, you can try to set priors away from such values

**Comment by fehiepsi** [comment]
Close in favor of the forum post.
