### ISSUE TITLE
numpyro.set_host_device_count seems to be ignored?

### ISSUE THREAD

**Issue by bmorris3** [pyro-ppl/numpyro#1432]
Hi, 

Thanks for your work on this excellent package! I'm trying to run jax+numpyro on a CPU with 128 cores. I want it to only use a few of the cores. I'm trying to achieve this behavior like so:

```python
import numpyro

cpu_cores = 8
numpyro.set_host_device_count(cpu_cores)

import jax
from jax import lax

def f(x):
    """This function is designed to kill time on each CPU"""
    carry, y = lax.scan(lambda carry, x: (carry,x), 0, jnp.arange(1_000_000_000))
    return y
jax.pmap(f)(jnp.arange(8))
```

When I run the above function (**be careful** not to run this on a machine with <100 GB memory), I expect the pmap call to distribute the call to `f` over the 8 CPU cores that we allocated. Instead, if I `htop` on the machine, I see that all CPUs are running (see attached screenshot). 

<img width="1431" alt="Screenshot 2022-06-17 at 12 03 47" src="https://user-images.githubusercontent.com/3497584/174277844-ec67ac0d-cca2-4be6-8223-33e525895b7e.png">

Additionally, we see that when you do not call `numpyro.set_host_device_count`, we get one CPU device from `jax.devices()`, but that `pmap` calls to `f` are distributed over all cores.

Is there a way to limit the number of cores that jax/numpyro sees on a machine with many CPUs? Thanks again!

cc @hoeijmakers

**Comment by Hoeijmakers** [comment]
Thanks for that pointer, which led us to what seems to be a working solution, but without the usage of mpiexec:
For running our script on 8 cores with `numpyro.set_host_device_count(8)`, we get the expected behaviour when running the script as: 
`taskset -c 0-7 python3 /path/to/pythonfile.py`

**Comment by fehiepsi** [comment]
I guess this is resolved. Please feel free to reopen this otherwise. :)
