### ISSUE TITLE
issues when numpyro.enable_validation(is_validate=True)

### ISSUE THREAD

**Issue by hyperfra** [pyro-ppl/numpyro#1438]
Hi
I identified a strange behavior: 
I estimate a VectorAutoRegression model and when  I use numpyro.enable_validation(is_validate=True), (which I had in the code
for some versions of the model with a MultivariateTruncated) , the resuts of any simple version of the model (with MultivariateNormal residuals say) were off. 
Taking out numpyro.enable_validation(is_validate=True) the results look fine.
Should I be worried?

best

**Comment by fehiepsi** [comment]
I think there might be some problems. When enabling the validation, we mask out-of-support samples by zero density. Not sure if it is related. Could you make reproducible code?

**Comment by hyperfra** [comment]
sorry, you are quite right.

[https://gist.github.com/hyperfra/9e8df68414b0172c852a16db82659bc6](url)

**Comment by fehiepsi** [comment]
Thanks @hyperfra! It seems that there is something wrong with the validation logic of LKJCholesky distribution.

**Comment by hyperfra** [comment]
ok :-)
