### ISSUE TITLE
Stein BNN predictions for a single input case

### ISSUE THREAD

**Issue by caxelrud** [pyro-ppl/numpyro#1440]
The documentation example predicts for the full training input cases.
I am trying to get the predictions for a single input case (row) including Confidence Interval.

The existing code is:
`preds = pred(pred_key, xte, subsample_size=xte.shape[0])["y"].reshape(-1, xte.shape[0])
`
I tried to use the first input element from the training data using the following expression:
`pred(pred_key, xte[0].reshape((1,-1)))["y"]
`
I got the following error:
`ValueError: Cannot take a larger sample than population when 'replace=False'
`
What is the correct way to do it?
Thxs

**Comment by OlaRonning** [comment]
Hi @caxelrud,

You need to pass in the `subsample_size=1` parameter to `pred` and then you'll have to fix the downstream computations to also only use the first datapoint. It will become:
``` python
    ...
    preds = pred(
        pred_key, xte[0].reshape(1, -1), subsample_size=1, hidden_dim=args.hidden_dim
    )["y"]

    y_pred = jnp.mean(preds, 1) * ytr_std + ytr_mean
    rmse = jnp.sqrt(jnp.mean((y_pred.mean(0) - data.yte[0]) ** 2))

    print(rf"Time taken: {datetime.timedelta(seconds=int(time_taken))}")
    print(rf"RMSE: {rmse:.2f}")

    # compute mean prediction and confidence interval around median
    mean_prediction = jnp.mean(y_pred, 0)

    ran = np.arange(mean_prediction.shape[0])
    percentiles = np.percentile(
        preds.reshape(-1, 1) * ytr_std[0] + ytr_mean[0], [5.0, 95.0], axis=0
    )

    # make plots
    fig, ax = plt.subplots(figsize=(8, 6), constrained_layout=True)
    ax.add_collection(
        LineCollection(
            zip(zip(ran, percentiles[0]), zip(ran, percentiles[1])), colors="lightblue"
        )
    )
    ax.plot(data.yte[0], "kx", label="y true")
    ...
```

**Comment by caxelrud** [comment]
I looks good to me. Thanks!
