### ISSUE TITLE
expose get_dependencies() and get_model_relations() in API

### ISSUE THREAD

**Issue by mattja** [pyro-ppl/numpyro#1447]
`get_dependencies()` and `get_model_relations()` are covered in the documentation, but seems they are not accessible in the public API? In this respect differing from pyro.

`AttributeError: module 'numpyro.infer' has no attribute 'inspect'`

**Comment by fehiepsi** [comment]
You can import `get_dependencies` from
```
from numpyro.infer.inspect import get_dependencies
```
Please feel free to make a PR for moving `get_model_relations` from `numpyro.contrib.render` to `numpyro.infer.inspect`. :)

**Comment by mattja** [comment]
Thanks for pointing this out. PR incoming.
