### ISSUE TITLE
A tutorial for integrating ODEs multiple times

### ISSUE THREAD

**Issue by A2P2** [pyro-ppl/numpyro#1450]
Hi, 
I'm wondering if there is a need to contribute with a tutorial for integrating ODEs multiple times based on different initial conditions. It's also possible to extend the current Lotka-Volterra example instead.

I oriented myself about the usage of jax.vmap for this purpose with the help of forums:
https://forum.pyro.ai/t/parallelization-plate-and-odes/2763
https://forum.pyro.ai/t/making-a-for-loop-more-efficient/3437/22

Is it of interest? Let me know what you think.

**Comment by fehiepsi** [comment]
The contribution would be awesome! Currently, we only have an example for Lotka-Volterra. A tutorial with motivations for your usage case would be super helpful for users.

**Comment by zz100chan** [comment]
@A2P2 hi! I think this is a good contribution and I am also somewhat have similar issues now.
I wonder if you have a tutorial already? :)

**Comment by A2P2** [comment]
@zz100chan 
My apologies for the late reply and for generally ignoring the thread.

I do have a draft written, see it attached. I tried to follow the style of the current Lotka-Volterra tutorial. Let me know if it works for you and if something is not clear. Once again, it's in a draft state at the moment. Attached as a zip file.
![multiple_lotka_volterra](https://github.com/pyro-ppl/numpyro/assets/34135768/a27c246b-fbde-44af-b35d-0bfa0fa91990)
[lotka_volterra_multiple.zip](https://github.com/pyro-ppl/numpyro/files/12783084/lotka_volterra_multiple.zip)

I've tried to implement a few things: 1) integrate with different initial conditions, 2) allowed to have missing values in the data. I use regularly spaced time arrays, but it's not a must.

The MCMC is somewhat slow. I've turned on `numpyro.enable_x64()`, otherwise problems with convergence were observed.  For my job, I actually used solvers from the [https://github.com/patrick-kidger/diffrax](diffrax) package instead of ones from jax, due to some convergence problems as well.
![ode_convergence](https://github.com/pyro-ppl/numpyro/assets/34135768/07d16bae-adaf-4bbe-9615-73629d3d1847)

@fehiepsi I'm glad to finish the tutorial properly if you provide some feedback. Once again, my apologies for disappearing.

**Comment by fehiepsi** [comment]
Could you make a version of it on https://gist.github.com/?

**Comment by fehiepsi** [comment]
Thank you! I'll take a look later of the week.

**Comment by fehiepsi** [comment]
Hi @A2P2, the example looks great. In the tutorial, it would be nice to include some introduction to the model, how the dataset looks like, and motivation for integrating ODEs multiple times.

**Comment by A2P2** [comment]
@fehiepsi thanks for checking it quickly. I've added a short motivation to the gist, I'll add the dataset description later.
Shall I make a pull request with it?

**Comment by fehiepsi** [comment]
Could you turn it into a (probably short?) tutorial, rather than an example? We have several [tutorials here](https://num.pyro.ai/en/stable/) (those without `Example:` prefix).

**Comment by A2P2** [comment]
Will do!

**Comment by A2P2** [comment]
@fehiepsi  here is the tutorial version on colab, let me know what you think.
https://gist.github.com/A2P2/ae09ed99f84372ff346b0d352ca7b4ed

**Comment by fehiepsi** [comment]
super cool, @A2P2 !
