### ISSUE TITLE
Examples using Stein BNN for Binary and Multi-Class Classification

### ISSUE THREAD

**Issue by caxelrud** [pyro-ppl/numpyro#1451]
I am looking for examples using Stein BNN for Binary and Multi-Class Classification.

**Comment by caxelrud** [comment]
These following link has an example of BNN for binary classification in JAX (Two Moons case).
It is a reference for a binary classification using Stein BNN,
https://github.com/probml/pyprobml/blob/master/notebooks/book2/17/bnn_hierarchical.ipynb

**Comment by OlaRonning** [comment]
Isn't it sufficient to change the [likelihood](https://github.com/pyro-ppl/numpyro/blob/master/examples/stein_bnn.py#L110) to a Bernoulli or Categorical in the existing example? 

(you probably also want to remove the [normalizing](https://github.com/pyro-ppl/numpyro/blob/master/examples/stein_bnn.py#L44) from your datapipeline)

**Comment by caxelrud** [comment]
I changed the last statement from sample from Normal to sample from Bernoulli but now I get `ValueError: Incompatible shapes for broadcasting: ((100,), (2,))`.

Here is the code.

```
def model(x, y=None, hidden_dim=50, subsample_size=100):
    prec_nn = numpyro.sample("prec_nn", Gamma(1.0, 0.1))  # hyper prior for precision of nn weights and biases
    n, m = x.shape
    with numpyro.plate("l1_hidden", hidden_dim, dim=-1):
        b1 = numpyro.sample("nn_b1",Normal(0.0,1.0 / jnp.sqrt(prec_nn),),)      # prior l1 bias term
        assert b1.shape == (hidden_dim,)
        with numpyro.plate("l1_feat", m, dim=-2):
            w1 = numpyro.sample("nn_w1", Normal(0.0, 1.0 / jnp.sqrt(prec_nn)))  # prior on l1 weights
            assert w1.shape == (m, hidden_dim)
    with numpyro.plate("l2_hidden", hidden_dim, dim=-1):
        w2 = numpyro.sample("nn_w2", Normal(0.0, 1.0 / jnp.sqrt(prec_nn))) # prior on output weights
    b2 = numpyro.sample("nn_b2", Normal(0.0, 1.0 / jnp.sqrt(prec_nn)))     # prior on output bias term
    prec_obs = numpyro.sample("prec_obs", Gamma(1.0, 0.1))                 # precision prior on observations

    with numpyro.plate("data",x.shape[0],subsample_size=subsample_size,dim=-1,):
        batch_x = numpyro.subsample(x, event_dim=1)
        if y is not None:
            batch_y = numpyro.subsample(y, event_dim=0)
        else:
            batch_y = y
        #numpyro.sample("y",Normal(jnp.maximum(batch_x @ w1 + b1, 0) @ w2 + b2, 1.0 / jnp.sqrt(prec_obs)),obs=batch_y,)  # 1 hidden layer with ReLU activation
        numpyro.sample("y", dist.Bernoulli(logits=(jnp.maximum(batch_x @ w1 + b1, 0) @ w2 + b2, 1.0 / jnp.sqrt(prec_obs))), obs=batch_y,)

```

**Comment by caxelrud** [comment]
I took several operations to debug the last statement of the model as:
`numpyro.sample("y", dist.Bernoulli(probs=(batch_x @ w1 + b1, 0) @ w2 + b2), obs=batch_y,)
`
Now, trying stein.run gives me the following error:
`TypeError: unsupported operand type(s) for @: 'tuple' and 'DeviceArray'`

**Comment by martinjankowiak** [comment]
@caxelrud github issues are not a great place to discuss beginner questions. please use the [forum](https://forum.pyro.ai/). github issues are meant for bug reports, feature requests, etc.

the error is very clear. `batch_x @ w1 + b1` is an array. but for some reason (probably because you kept around old code without examining it carefully) you combine it into a tuple with `, 0)`.  you probably want something like `logits=(batch_x @ w1 + b1) @ w2 + b2`. `probs` can't work because `probs` need to be between 0 and 1.
