### ISSUE TITLE
Unable to fit MA(1) time series model when `theta` is greater than 1.

### ISSUE THREAD

**Issue by paulsbrookes** [pyro-ppl/numpyro#1453]
I have been experimenting with an MA(1) time series model and I have noticed a possible bug when fitting the to following synthetic data:

```
from jax import random
rng_key = random.PRNGKey(12)
seeds = random.split(rng_key, 10)
n_series = 1
theta = 2

noise = random.normal(shape=(2000, n_series), key=seeds[0])
noise = noise.at[0].set(0.0)
train = noise[1:] + theta*noise[:-1]
```

To fit this data I run the following code:
```
import numpyro
from numpyro.infer import MCMC, NUTS, init_to_sample, init_to_feasible, init_to_value
import numpyro.distributions as dist
from numpyro.contrib.control_flow import scan
import jax.numpy as jnp


def model(y):
    n_series = y.shape[1]
    with numpyro.plate("plate", n_series):
        theta = numpyro.sample("theta", dist.Normal(0.0, 1.0))

    def transition_fn(carry, t_idx):
        epsilon_prev = carry
        mean = theta * epsilon_prev
        y_pred = numpyro.sample("y_pred", dist.Normal(mean, 1.0))
        carry_new = y_pred - mean
        return carry_new, y_pred

    time_indices = jnp.arange(0, y.shape[0])
    init_carry = jnp.empty(shape=(n_series), dtype=float)
    with numpyro.handlers.condition(data={"y_pred": y}):
        _, y_predictions = scan(
            transition_fn,
            init_carry,
            time_indices,
        )


nuts_kernel = NUTS(model, init_strategy=init_to_value(values={"theta": 0.0}))

mcmc = MCMC(nuts_kernel, num_samples=40000, num_warmup=20000, num_chains=4)
mcmc.run(seeds[1], y=train)
mcmc.print_summary()
```

I receive the following output:
```
                mean       std    median      5.0%     95.0%     n_eff     r_hat
     theta      0.48      0.01      0.48      0.46      0.49  62149.40      1.00

Number of divergences: 0
```

The value for `theta` is wrong. It should be 2, as in the generated data above. However there is no indication that the MCMC sampling has been unsuccessful. There are no divergences, `r_hat` is equal to 1, `n_eff` is high, and the standard deviation is small but realistic.

When I experiment with `theta` I see that the parameter is correctly inferred if |theta|<1. Otherwise the inferred values are not correct.

The model appears to be unstable for values if |theta|>1, since `mean = theta * epsilon_prev` can diverge towards infinity at later values of `t_idx` as the `scan` is carried out. See here for more details: https://forum.pyro.ai/t/exploding-loc-parameter-in-ma-1-time-series-model/4442.

Values of `theta` greater than 1 are a bit unrealistic, but in this synthetic dataset the correct value is 2 and the model converges to an incorrect answer without giving any indication that there is a problem, so this may indicate some kind of bug.

**Comment by fehiepsi** [comment]
This seems to be expected due to numerical errors growth exponentially w.r.t. time steps when theta > 1. Please see the explanation in the above jax thread. Thanks for reporting, @paulsbrookes !
