### ISSUE TITLE
Example Docker Image fails to build

### ISSUE THREAD

**Issue by timpiperseek** [pyro-ppl/numpyro#1455]
The example docker image found [here ](https://github.com/pyro-ppl/numpyro/tree/master/docker/release).
Is failing to build (atleast for me) with the following error message.

```
#6 3.235 ERROR: Could not find a version that satisfies the requirement jaxlib>=0.1.65 (from numpyro[cuda111]) (from versions: none)
#6 3.244 ERROR: No matching distribution found for jaxlib>=0.1.65 (from numpyro[cuda111])
```

Anyone know the solution?

**Comment by fehiepsi** [comment]
@AndrewCSQ I guess we need `numpyro[cuda]` here?

@timpiperseek could you change the last line of that file to
```
numpyro[cuda] -f https://storage.googleapis.com/jax-releases/ ...
```
and reinstall?

**Comment by timpiperseek** [comment]
yes that install but it is giving the warning.
`WARNING: numpyro 0.10.0 does not provide the extra 'jaxlib_cuda'`
also it looks like it is no longer using GPU and is reverting to CPU. Although I am not confident if that is because of your suggested change

**Comment by fehiepsi** [comment]
Maybe that's because they change the binary url: from the last `jax_releases` to `jax_cuda_releases`

**Comment by timpiperseek** [comment]
yes that works

**Comment by fehiepsi** [comment]
Yeah, could you help me make a PR?

**Comment by timpiperseek** [comment]
yes of course.
I think just changing line 24 to 
`numpyro[cuda] -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

should do the trick
