### ISSUE TITLE
Understanding strange shape behavior due to enumerating discrete latent variables

### ISSUE THREAD

**Issue by thisiscam** [pyro-ppl/numpyro#1456]
Hi,

I tried the following code 

```python
import jax
import jax.numpy as jnp
import jax.random as jrandom

import numpyro
from numpyro import distributions as dist


def model(X, N=100):
  with numpyro.plate("N", N):
    X1 = numpyro.sample("X1", dist.Normal(0., 1.), obs=X)
    X2 = numpyro.sample("X2", dist.Bernoulli(jnp.ones(N) * 0.5))
    X3 = numpyro.sample("X3", dist.Bernoulli(jnp.ones(N) * 0.5))
    X = jnp.vstack([X1, X2, X3])
    return X


key = jrandom.PRNGKey(0)
guide = numpyro.infer.autoguide.AutoNormal(model)
svi = numpyro.infer.SVI(model,
                        guide,
                        numpyro.optim.Adam(1e-3),
                        loss=numpyro.infer.TraceGraph_ELBO())
svi_results = svi.run(key, 100, jnp.ones(100))
```

Since X2 and X3 are discrete latent variables, SVI will enable enumeration support from funsor. However, I get the following cryptic error:
```
File "test_enum.py", line 14, in model
    X = jnp.vstack([X1, X2, X3])
  File "python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 1694, in vstack
    return concatenate(arrs, axis=0)
  File "python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 1683, in concatenate
    arrays = [lax.concatenate(arrays[i:i+k], axis)
  File "python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 1683, in <listcomp>
    arrays = [lax.concatenate(arrays[i:i+k], axis)
TypeError: Cannot concatenate arrays with different numbers of dimensions: got (1, 100), (2, 1), (2, 1, 1).
```

I think I understand that the dimensions for X2 and X3 has a leading "2" because it is trying to enumerate the booleans. I don't understand:
- how broadcasting would work in this case
- why the batch dimension (N=100) is dropped from X2 and X3? 
- why X2 and X3 have different shapes?

#741 and #1174  seem related

**Comment by fehiepsi** [comment]
I would recommend to look at enumerate tutorial, but here are quick answers to your questions
+ you can broadcast 3 arrays such that they have the same shape, then stack
+ That is the design choice. Under the hood, for each item in the batch plate N, those discrete variables have the same support/value, which is [0, 1]. So we only need to return a single item.
+ you will want to enumerate x2 over axis -2, and enumerate x3 over axis -3, so their to-be-enumerated dimension will be different. It might be easier to think of enumeration as loops: for v2 in x2.support, for v3 in x3.support, for n in range(N): do something.

Btw, AutoNormal only works for continuous latent models (see README for guidance on choosing suitable inference algorithm to your model). In addition, TraceGraphElbo does not perform enumeration. We also haven't supported enumeration for svi yet.

**Comment by thisiscam** [comment]
Hi, thanks for the quick response.

Is my following understanding of the desired broadcasting scheme correct?
```
X1:  1, 1, 4, 100
X2:  1, 2, 1, 1
X3:  2, 1, 1, 1
```

> AutoNormal only works for continuous latent models

I thought the point of enumeration is to sum out the discrete variables so that there are only continuous latent variables?

> We also haven't supported enumeration for svi yet.

Thanks! Currently the above code does run (up to the shape mismatch problem). Is there anything technically blocking from getting enumeration + SVI to work?

**Comment by fehiepsi** [comment]
I'm not sure where 4 comes from but the rest seems correct to me. We haven't supported enumeration for AutoNormal and SVI. Please see https://github.com/pyro-ppl/numpyro/issues/741 for more context.

**Comment by thisiscam** [comment]
Corrected to:
```
X1:  1, 1, 1, 100
X2:  1, 2, 1, 1
X3:  2, 1, 1, 1
```

#741 mentioned that enumeration is "not tested" -- so not officially supported but the presumably some code exists? 
In fact, I was able to get through the dimension error following your suggestion and come to another error:
```
  File "python3.8/site-packages/numpyro/infer/util.py", line 246, in potential_energy
    log_joint, model_trace = log_density_(
  File "python3.8/site-packages/numpyro/contrib/funsor/infer_util.py", line 274, in log_density
    result, model_trace, _ = _enum_log_density(
  File "python3.8/site-packages/numpyro/contrib/funsor/infer_util.py", line 244, in _enum_log_density
    raise ValueError(
ValueError: Expected the joint log density is a scalar, but got (2,). There seems to be something wrong at the following sites: {'_pyro_dim_4'}.
```

I am not sure why the enumerate dimension is left there but not summed out. Maybe I should look else where (Pyro seems to support what I need) for SVI support. Or maybe if you think the enumeration mechanism is mostly there, I can also look into this and figure out what is going wrong?

**Comment by fehiepsi** [comment]
I think it should be
```
X1:  1, 1, 100
X2:  1, 2, 1
X3:  2, 1, 1
```

> Pyro seems to support what I need
Yeah, I would recommend using Pyro for SVI with enumeration.

> the enumeration mechanism is mostly there
I guess it is a little bit complicated - I'm not sure.

**Comment by thisiscam** [comment]
> I think it should be
> 
> ```
> X1:  1, 1, 100
> X2:  1, 2, 1
> X3:  2, 1, 1
> ```

I need the dimension to perform the concatenation?

> Yeah, I would recommend using Pyro for SVI with enumeration.

Fair enough. I hope discrete enumeration in numpyro will catch up with Pyro at some point!
