### ISSUE TITLE
module 'jaxlib.pocketfft' has no attribute 'pocketfft'

### ISSUE THREAD

**Issue by beekill95** [pyro-ppl/numpyro#1468]
Right now, I cannot use numpyro with gpu support. When I install numpyro with gpu support using `pip install numpyro[cuda] -f https://storage.googleapis.com/jax-releases/jax_releases.html`, the installation runs just fine. However, when I import numpyro, the following error was thrown:

```
[/usr/local/lib/python3.7/dist-packages/jax/_src/lax/fft.py](https://localhost:8080/#) in <module>()
    143 batching.primitive_batchers[fft_p] = fft_batching_rule
    144 if pocketfft:
--> 145   xla.backend_specific_translations['cpu'][fft_p] = pocketfft.pocketfft

AttributeError: module 'jaxlib.pocketfft' has no attribute 'pocketfft'
```

Here is the colab notebook for reproduction: https://colab.research.google.com/drive/1tHmdv4P1I9AdviF5XFot5fhBQbDZWNEo?usp=sharing

**Comment by fehiepsi** [comment]
Hi @beekill95, the link is updated to `https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`. Could you help me fix the path in README file?

**Comment by beekill95** [comment]
Installing the package from the updated link does fix the error for me. Thank you!
