### ISSUE TITLE
Possibility of using models as distributions

### ISSUE THREAD

**Issue by hessammehr** [pyro-ppl/numpyro#1472]
In certain situations it would be convenient to be able to treat models like distributions. As an example, one approach to calculating the Bayes factor for two models is to create a mixture distribution like so (`mixing_weights` acting as prior probabilities p(M1) / p(M2)):

```python
def compare_models(model1, model2, mixing_weights, data):
    mixing_distribution = sample('m', Categorical(mixing_weights))
    mixture = Mixture([model1, model2], mixing_distribution)
    sample(mixture, obs=data)
# inspect 'm' in posterior to compare model1 vs model2 | data
```

I wondered how feasible/realistic it would be to enable such a use case (and whether there is a better way).

EDIT: One possibility would be to return the observed distributions from each model. I wondered if there was a way to achieve the same effect without having to modify the models.

**Comment by fehiepsi** [comment]
Using a model like a distribution seems to be similar to TFP's [JointDistribution](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/JointDistribution). I feel that it's not quite complicated (for basic usage). We will need to define some notions for: joint support (a dictionary of site: support), joint sample (which traces the model and returns latent samples), joint log_prob (using the current `log_density` utility). We will need to update some logic in `Mixture` to treat `value` as a dictionary (using `jax.tree_map`).

> return the observed distributions from each model

Shouldn't it be `partial(model, data)` assuming we have a statement like `sample("obs", dist, obs=data)` in the model?

**Comment by hessammehr** [comment]
@fehiepsi thank you for your comment and apologies for the delayed response. To clarify the phrase that you had asked about, I have been using the following solution since opening this issue.

```python
def model1():
    a = sample(...)
    b = sample(...)
    return {
        'observable1': sample('o1', Normal(a)),
        'observable2': sample('o2', Poisson(b)),
    }

def model2():
    c = sample(...)
    d = sample(...)
    return {
        'observable1': sample('o1', Normal(c + d)),
        'observable2': sample('o2', Poisson(c * d)),
    }

def model(data):
    m1 = model1()
    m2 = model2()

    assert list(m1) == list(m2)

    for var in m1:
        mix = Mixture(Categorical(...), [m1[var], m2[var]])
        sample(f'obs_{var}', mix, obs=data[var])
```

Which is a bit verbose but clear enough. I hope this clarifies the workaround I was referring to. Your suggestion sounds more general without requiring as much boilerplate, though I have to admit I'm not quite sure how to go about implementing it.

**Comment by fehiepsi** [comment]
> but clear enough

agreed! let's reopen this issue or create a new one for using models as distributions in the future if needed.
