### ISSUE TITLE
Example: Hilbert space approximation for Gaussian processes 

### ISSUE THREAD

**Issue by kaijennissen** [pyro-ppl/numpyro#1476]
It's not really an issue but the [Hilbert space approximation for Gaussian process](https://num.pyro.ai/en/latest/examples/hsgp.html) example does not converge.
Any suggestions on how to fix this?

<details>
<summary> `--chain=1 --num-samples=10000 --num-warmup=2000`</summary>

![plots](https://user-images.githubusercontent.com/50238578/189150121-181c4c00-9819-4592-bed1-9a3acc21dee9.png)
<img width="776" alt="Screenshot1" src="https://user-images.githubusercontent.com/50238578/189150036-e39f1424-d888-4401-bd93-b708f97ac1c3.png">
<img width="821" alt="Screenshot2" src="https://user-images.githubusercontent.com/50238578/189150045-b954bb57-fbdb-45f1-9b64-fdc2795c1fe7.png">
<img width="820" alt="Screenshot3" src="https://user-images.githubusercontent.com/50238578/189150057-c56e1beb-0d71-48d0-8f3e-d23002cea801.png">
</details>

<details>
<summary> `--chain=2 --num-samples=10000 --num-warmup=2000`</summary>

![plots2](https://user-images.githubusercontent.com/50238578/189164356-527eb7f0-3865-425e-a803-c56d267bffc9.png)
<img width="1559" alt="Screenshot5" src="https://user-images.githubusercontent.com/50238578/189164405-d419cfab-2918-4bca-9707-68ff07ce50f8.png">
<img width="821" alt="Screenshot4" src="https://user-images.githubusercontent.com/50238578/189164428-f8a768ca-f704-4e4e-9aa6-ead8b2264942.png">

</details>

**Comment by martinjankowiak** [comment]
@kaijennissen did you try double precision (`--x64`) and/or more warmup samples?

**Comment by omarfsosa** [comment]
@kaijennissen , following @martinjankowiak 's recommendation. I manage to get good mixing with
```bash
python hsgp.py --num-chains=2 --x64 --num-warmup=4000 --num-samples=4000 --save="./hsgp.png"
```

Give it a go and if it does not work I can look into it (it took about 28mins to run in my machine).

**Comment by kaijennissen** [comment]
@martinjankowiak @omarfsosa '--x64' made the difference. Thank you.
