### ISSUE TITLE
Using jax.numpy versus numpy in diagnostics

### ISSUE THREAD

**Issue by ayhteo** [pyro-ppl/numpyro#1482]
Heya, more of a question versus an issue:

Currently if I want to assess jax arrays with `diagnostics`, I have been resorting to converting them back to numpy arrays then running through the diagnostics, for example in `effective_sample_size`, the item assignment flags that jax arrays are immutable.

https://github.com/pyro-ppl/numpyro/blob/22c45db47ce56266ce2fdfa87efafc7235abd946/numpyro/diagnostics.py#L175

Is there a design choice to prefer numpy over jax for this purpose?

**Comment by fehiepsi** [comment]
We wanted to use numpy to improve speed and have better print format. I think it is better to add `x = jax.device_get(x)` at the top of those utilities to convert jax device arrays to numpy arrays. Do you want to make such change?

**Comment by ayhteo** [comment]
sure, I realized its the sole function that does item assignment in the file so there only needs to be this update for `effective_sample_size`. I have raised a PR https://github.com/pyro-ppl/numpyro/pull/1483 for this one line change 😄
