### ISSUE TITLE
Make MCMC diagnostics available in Numpyro

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#149]
Right now we don't have any diagnostics to measure the quality of mixing. It will be nice to either implement diagnostics like we have done in Pyro, or perhaps just use the `arviz` library for this (preferable to offload this to arviz if possible).

**Comment by fehiepsi** [comment]
I think we can have some diagnostics such as r_hat or n_eff to be able to use in examples and defer other diagnostics/information criterion to arviz.

**Comment by fehiepsi** [comment]
Maybe I can take care of this issue because I have made a preliminary version `n_eff` last week.
