### ISSUE TITLE
Mixture: Intermediates cannot be coerced to bool

### ISSUE THREAD

**Issue by hessammehr** [pyro-ppl/numpyro#1490]
```python
from jax import numpy as jnp
from jax.random import PRNGKey
from numpyro import distributions as dist
from numpyro import sample
from numpyro import handlers as hdl
from numpyro.infer.util import log_density

key = PRNGKey(0)

def model(toggle):
    d1 = dist.HalfNormal()
    d2 = dist.LogNormal()
    mixing = dist.Categorical(jnp.full((2,), 0.5))
    mixture = dist.Mixture(mixing, [d1, d2])
    if toggle:
        sample('s', mixture)
    else:
        sample('s', mixture, sample_shape=(2,))

with hdl.seed(rng_seed=key):
    l1 = log_density(model, [], {'toggle': True}, {})
    l2 = log_density(model, [], {'toggle': False}, {})
```

In the above `l1` evaluates fine, as the intermediates returned in the model trace is a `DeviceArray` containing a single number, but when sample/batch shape is anything but `(1,)`, `intermediates` is an array with size > 1 the following boolean coercion causes and error: 

![image](https://user-images.githubusercontent.com/392251/197748939-3dfa2096-4d2a-4451-9371-d8187bfcefee.png)

Comparing `_MixtureBase` to other distributions with `sample_with_intermediates`, it seems all other cases return a list of intermediates, whereas `_MixtureBase` simple returns a jax array directly. It appears the most logical fix would simply be `_MixtureBase.sample_with_intermediates` returning the intermediates array wrapped a list in order to comply with the current API. If this sounds like a reasonable fix, I would be happy to send a PR.

**Comment by fehiepsi** [comment]
You are right, we need to return a list there. Thanks for the catch! Please submit the fix :)

**Comment by hessammehr** [comment]
Thanks for the quick feedback and the tip to fix the CI glitch, @fehiepsi
