### ISSUE TITLE
Example: Text-Based Ideal Points in Numpyro

### ISSUE THREAD

**Issue by elchorro** [pyro-ppl/numpyro#1497]
I wrote a Colab notebook with a Numpyro implementation of [Text-Based Ideal Points](https://arxiv.org/abs/2005.04232) (Vafa, Naidu & Blei, 2020).

It uses SVI with mean field ELBO, manual minibatching and Optax. It is [here](https://colab.research.google.com/drive/1JQEbAf8aTuEw9X9Yfqsgi6cEScuQ-i6c?usp=sharing) It is also linked from the original TBIP repo (https://github.com/keyonvafa/tbip).

Do you think it may be useful example to include? If so, what's the way to do that? If not, feel free to close and ignore.

PS Dave Blei was really impressed by Numpyro when I showed him this. Congratulations to the team.

**Comment by fehiepsi** [comment]
It's an excellent tutorial, @elchorro! We are happy to have it in the tutorials. You can add the notebook in [this folder](https://github.com/pyro-ppl/numpyro/tree/master/notebooks/source) and add link to it in [this index file](https://github.com/pyro-ppl/numpyro/blob/master/docs/source/index.rst). It would be nice to include a thumbnail for the tutorial - you can put a `[filename].png` file in [this folder](https://github.com/pyro-ppl/numpyro/tree/master/docs/source/_static/img/tutorials) where `[filename]` is the name of your notebook file.

**Comment by elchorro** [comment]
Thank you @fehiepsi

I made a PR #1498 and it passes tests but any suggestions are always welcome.

**Comment by elchorro** [comment]
Closed by #1498

Thank you guys!
