### ISSUE TITLE
Not quite clear to me how the model used by NUTS should be defined

### ISSUE THREAD

**Issue by Kaktus1990** [pyro-ppl/numpyro#1501]
In [the documentation](https://num.pyro.ai/en/latest/mcmc.html#id7) it is written that the model contains the NUTS primitives but there is no more info on how the model should be built.
The model function does not return anything. I tried to figure it our from the examples. In [this example](https://num.pyro.ai/en/latest/tutorials/bayesian_regression.html#Model-1:-Predictor---Marriage-Rate)  and also in [this one](https://num.pyro.ai/en/latest/examples/ode.html) also it does not seem to be explained how MCMC/NUTS can figure out which variable is the dynamic model, which is the parameters or initial conditions.
Can someone help me with that?

**Comment by fehiepsi** [comment]
Hi @Kaktus1990, please checkout the getting start page: https://num.pyro.ai/en/latest/getting_started.html Those variables from `sample` primitive without `obs=...` will be the latent variables, those with `obs=...` will be the observed variables. You can choose an initialization strategy through the [init_strategy parameter](https://num.pyro.ai/en/latest/mcmc.html#numpyro.infer.hmc.NUTS). Please follow up questions in forum instead. We use github mainly to track issues or feature requests.
