### ISSUE TITLE
NUTS with pmap+vectorized: time scaling?

### ISSUE THREAD

**Issue by jecampagne** [pyro-ppl/numpyro#1502]
Hello,
I have followed the snippet written in a note on MCMC
```
It is possible to mix parallel and vectorized sampling, i.e., run vectorized chains on multiple devices using explicit pmap. 
```
and I have modified accordingly an existing script using NUTS. I run on  1, 2 and 4 V100 GPUs (all on the same node) 
to  produce 16 chains of 1000 samples/chain (200 warm) 

- 18h30 on 1 GPU (6 chains) 
- 13h30 on 2 GPUs (8 chains/GPU)
- 11h00 on 4 GPUs (4 chains/GPU)

I wander if this scaling is expected : ie I was expected to devide by 4 the time spend to production 16 chains with 4 GPUs compared to 1 GPU, while I get poorly 40% reduction.

May I have done something wrong?

**Comment by fehiepsi** [comment]
Hi @jecampagne, I don't have resources to test but I feel that the non-linear behavior is expected.

**Comment by jecampagne** [comment]
It is expected for instance in multhread CPU where the CPU should manage the multithrzding
but if the pmap copy the code/model in each GPU I have not the intuition/hint why there should be a mechanism that brake the linear scaling  ? Do you have a ref? thanks

**Comment by fehiepsi** [comment]
There are several factors here. Probably, the time to run 4-chain MCMC on 1 GPU is 11h, and the time to run 16-chain MCMC on 1 GPU is 18h30. With 4 devices, you can run 4 x 4-chain MCMC on 4 GPUs in 11h. Other factors include time to move arrays to devices and copy arrays from devices to hosts...
