### ISSUE TITLE
SineBivariateVonMises generates NaN log probability for negative correlation parameter

### ISSUE THREAD

**Issue by 19MM97** [pyro-ppl/numpyro#1511]
When using [SineBivariateVonMises](https://num.pyro.ai/en/stable/distributions.html#sinebivariatevonmises) in an MCMC setting with the NUTS sampler and hard assigning the correlation parameter of the SinveBivariateVonMises to a negative value, the model can not be initialised. Sampling from a SineBivariateVonMises with a negative correlation parameter does work though.
 @fehiepsi traced, that the log probability becomes NaN.

How to recreate:

`data = SineBivariateVonMises(0, 0, 1, 1, -1).sample(PRNGKey(42), (1000, ))`

and train this model:

```
@numpyro.handlers.reparam(
    config={"phi_loc": CircularReparam(), 
            "psi_loc": CircularReparam(),
           }
)
def min_example(data_2d):
    phi_loc = sample('phi_loc', VonMises(0, 10))
    psi_loc = sample('psi_loc', VonMises(0, 10))
    
    phi_conc = sample('phi_conc', Beta(1, 1))
    psi_conc = sample('psi_conc', Beta(1, 1))
    
    conc = -sample('conc', HalfNormal(1))
    
    depInd = SineBivariateVonMises(phi_loc, psi_loc, 70 * phi_conc, 70 * psi_conc, conc)
    
    obs = sample('obs', depInd, obs=data_2d)
```

Further information can be found in this [forum post](https://forum.pyro.ai/t/negative-correlation-sinebivariatevonmises/4786/3)

**Comment by fehiepsi** [comment]
Could you add a full code to replicate the issue? We have the valid parameters
```
{'phi_loc': DeviceArray(0.29627275, dtype=float32),
 'psi_loc': DeviceArray(-0.03310037, dtype=float32),
 'phi_concentration': DeviceArray(19.143257, dtype=float32),
 'psi_concentration': DeviceArray(44.272667, dtype=float32),
 'correlation': DeviceArray(-0.6486334, dtype=float32)}
```
but gets invalid log_prob with distribution
```
SineBivariateVonMises(phi_loc, psi_loc, 70 * phi_conc, 70 * psi_conc, conc)
```
and observed `data_2d`. I guess we don't need to whole training process to see the issue.

**Comment by fehiepsi** [comment]
cc @OlaRonning

**Comment by OlaRonning** [comment]
The problem is the [`log(corr)`](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/distributions/directional.py#L403) in the normalization. If we move the `2*m` factor into the `log` (so it becomes `log(corr**(2*m))`) we will always have positive values which will eliminate that source of NaNs. I'll open a PR once I've run the tests.

**Comment by OlaRonning** [comment]
#1515 was resolves the NaNs from negative correlation. @19MM97 feel free to reopen if the problem persists.
