### ISSUE TITLE
Any way to record the number of gradient call in HMC/NUTS?

### ISSUE THREAD

**Issue by xidulu** [pyro-ppl/numpyro#1521]
Hi

I am wondering if there is any API that allows one to know the number of oracle calls to grad(potential_func) during the NUTS sampling process?

**Comment by fehiepsi** [comment]
Could you ask the questions on the forum instead? You can record the number of leap frogs steps through the field `extra_fields=("num_steps",)` in MCMC run (see the [docs](https://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.MCMC.warmup))

**Comment by xidulu** [comment]
@fehiepsi Thanks!
