### ISSUE TITLE
Example: Predator-Prey Model gives weird results when using num_chains > 2

### ISSUE THREAD

**Issue by Sangwon91** [pyro-ppl/numpyro#1522]
Hello, I just tried the example, [Example: Predator-Prey Model](https://num.pyro.ai/en/latest/examples/ode.html), with `adapt_step_size=False` and `num_chains=2`.

Also, I added the lines to enable multiple draws on the CPU.
```
numpyro.set_host_device_count(8)
print(jax.local_device_count())
```

When I plot the trace of sigma, weird patterns are shown as follows

```
sigma = mcmc.get_samples()["sigma"]

plt.plot(sigma[:, 0])
plt.plot(sigma[:, 1])
plt.show()
```

![image](https://user-images.githubusercontent.com/20216145/210956661-c65c09cb-978e-4889-a7b1-c9b2afbf2746.png)

It seems the second draw wasn't performed. Any suggestions would be helpful. 

Thank you.

**Comment by fehiepsi** [comment]
Hi @Sangwon91, the ode solve is not always stable. You need to adjust settings like `rtol`, `atol`, `maxsteps` to make it work. You might also want to customize the initial values. Anyway, it's good to adapt step size for MCMC, do you have any reason to disable it?

Could we follow up the discussion in [our forum](https://forum.pyro.ai/) instead?

**Comment by Sangwon91** [comment]
Sure. Close the issue as I posted the discussion in the [forum](https://forum.pyro.ai/t/example-predator-prey-model-gives-weird-results-when-using-num-chains-2/4873). Thank you.
