### ISSUE TITLE
Compatibility with windows?

### ISSUE THREAD

**Issue by Sarenrenegade** [pyro-ppl/numpyro#1524]
Hello,
I'm currently developping a code that aims to inverse 36 chlorine data. One important aspect is that I wish this code to be easily accessible (that includes that my code should work on different OS). For some reason I was not able to install numpyro on a windows computer, I tried via anaconda and pip, and also tried a "manual" install. Have you any ideas why the installation of numpyro is not working on windows ? 
Thanks in advance,

**Comment by fehiepsi** [comment]
Hi @Sarenrenegade, have you tried the suggestion in the [installation](https://num.pyro.ai/en/stable/getting_started.html#installation) section? This builder might also be helpful: https://github.com/cloudhan/jax-windows-builder

**Comment by Sarenrenegade** [comment]
Hi, yes I have. JAX is installed correctly but numpyro installation fails...

**Comment by fehiepsi** [comment]
Interesting! could you pass the failing message?

**Comment by Sarenrenegade** [comment]
Hi, sorry for the delay!
Here is what I get:

ERROR: Cannot install numpyro==0.1.0, numpyro==0.10.0, numpyro==0.10.1, numpyro==0.11.0, numpyro==0.2.0, numpyro==0.2.1, numpyro==0.2.2, numpyro==0.2.3, numpyro==0.2.4, numpyro==0.3.0, numpyro==0.4.0, numpyro==0.4.1, numpyro==0.5.0, numpyro==0.6.0, numpyro==0.7.0, numpyro==0.7.1, numpyro==0.7.2, numpyro==0.8.0, numpyro==0.9.0, numpyro==0.9.1 and numpyro==0.9.2 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by Sarenrenegade** [comment]
I should mention that I tried it on a windows 10 machine, in a clean virtual env. I also tried the conda install solution, again in a fresh conda virtual environment and via the pycharm community interface in a fresh venv.

**Comment by Sarenrenegade** [comment]
Hi, thanks for your answer. Numpyro gets installed but when I try to import numpyro I get this message : ModuleNotFoundError: jax requires jaxlib to be installed. See https://github.com/google/jax#installation for installation instructions.... 
I tried to remove and reinstall jax but it still does not work...

**Comment by fehiepsi** [comment]
The issue is not related to numpyro. jax requires jaxlib so you need to install it first. Please see https://github.com/google/jax#installation as in the error message. You can also try https://github.com/cloudhan/jax-windows-builder as in the above comment.
