### ISSUE TITLE
Wishart distributions?

### ISSUE THREAD

**Issue by saraelshawa** [pyro-ppl/numpyro#1538]
Hi, 

Is it possible to sample from a Wishart distribution using numpyro? 

Thank in advance!

**Comment by fehiepsi** [comment]
I think so. You can use TFP distributions with numpyro: e.g. [WishartTriL](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/WishartTriL).

**Comment by saraelshawa** [comment]
Thank you. I was having issues with `WishartTril` using TFP so I thought numpyro might have it's own implementation :)

**Comment by fehiepsi** [comment]
I guess you can use [LKJCholesky](https://num.pyro.ai/en/stable/distributions.html#lkjcholesky) instead of `WishartTril`. We don't have Wishart distribution implemented.
