### ISSUE TITLE
Memory leak JAXNS sampling

### ISSUE THREAD

**Issue by MauricioGS99** [pyro-ppl/numpyro#1540]
Hello, 
Mi Swap memory goes up to 30 GBs when running the following code:
I'll resume it because of length.

I have N number of models (causal bayesian networks) with K variables each. Each model is of the form:

(I have code which generates arbitrary number of models, this one is created by hand for sake of the example)

`def patient_1():
    disease = numpyro.sample("disease",dist.Bernoulli(0.3))
    treatment = numpyro.sample("treatment",dist.Bernoulli(0.6))
    list_variables=[disease,treatment]
    list_variables_no_treatment=[disease]
    
    bloodpressure = numpyro.sample("bloodpressure",dist.Normal(non_linear_fn(jnp.array(random.sample(list_variables_no_treatment,np.random.randint(0,1))),np.random.randint(0,1)*treatment),1))
    list_variables.append(bloodpressure)
    list_variables_no_treatment.append(bloodpressure)
                                   
    weight = numpyro.sample("weight", dist.Normal(non_linear_fn(jnp.array(random.sample(list_variables_no_treatment,np.random.randint(0,2))),np.random.randint(0,1)*treatment), 1))
    list_variables.append(weight)
    list_variables_no_treatment.append(weight)
    
    heartattack=numpyro.sample("heartattack",dist.Normal(non_linear_fn(jnp.array(random.sample(list_variables_no_treatment,np.random.randint(1,3))),np.random.randint(0,1)*treatment),1))
    list_variables.append(heartattack)
    list_variables_no_treatment.append(heartattack)
    
    variables=[]
    list_variables=[disease,treatment,bloodpressure,weight,heartattack]
    
    for i in range(5,k):
        vi=numpyro.sample('variable'+str(i),dist.Normal(non_linear_fn(jnp.array(random.sample(list_variables,np.random.randint(0,i))),np.random.randint(0,1)*treatment), 1))
        variables.append(vi)
        list_variables.append(vi)
    vi=numpyro.sample('variable'+str(k),dist.Normal(non_linear_fn(jnp.array(random.sample(list_variables,np.random.randint(0,k))),treatment), 1))
    variables.append(vi)
    list_variables.append(vi)
    return list_variables`

And I sample from it using:
`kernel_1=NestedSampler(patient_1)
kernel_1.run(jrn.PRNGKey(1149343))`

And everything works well, but it consumes my 64gbs of installed RAM + 30 gbs of swap memory. 

Any ideas why? 

Thanks.

**Comment by fehiepsi** [comment]
Hi @MauricioGS99, originally we made the wrapper to easily use jaxns for numpyro models. Since then, there are several new releases. We will deprecate this wrapper because jaxns uses its own PPL now. I would recommend to use jaxns directly for your model. The memory issue might be resolved in the new version.
