### ISSUE TITLE
[FR] SVI: avoid initializing model params when already specified in guide

### ISSUE THREAD

**Issue by msegado** [pyro-ppl/numpyro#1552]
(Context: https://forum.pyro.ai/t/sharing-params-between-model-guide-i-e-tied-weights/5033/)

Sharing parameter values between a model and its guide is helpful in some applications, e.g. symmetric autoencoders. This can *almost* be accomplished by defining a param as usual in the guide and calling `numypro.param("shared_site_name")` in the model, but [since `SVI` only replays sample values](https://github.com/pyro-ppl/numpyro/blob/737d7d9ec0dc5d6649f85bbedddf28ca07908e20/numpyro/infer/svi.py#L186-L187) and not parameter values before tracing the model, the return value of this `param()` call defaults to `None` which breaks any downstream code that uses it.

The [desired behavior in SVI is to avoid initializing any model parameters already specified in the guide](https://forum.pyro.ai/t/sharing-params-between-model-guide-i-e-tied-weights/5033/6). I can see a couple of ways of accomplishing this:

1. Explicitly substitute initialized parameter values from the guide before tracing the model. Here's a strawman implementation which uses `substitute()` to avoid changing the semantics of `replay()`: https://github.com/pyro-ppl/numpyro/compare/master...msegado:numpyro:feat-shared-param-init.
2. Change the `replay()` handler to support replaying param values. This should probably be opt-in via an `include_params` kwarg or similar to avoid breaking existing user code, and would also require a change to the docs.

The first seems like the more natural approach to me, but I figured it would be good to ask before opening a PR 🙂 Thoughts?

**Comment by fehiepsi** [comment]
Oh, the first solution sounds great to me! Thanks!
