### ISSUE TITLE
Inverse bjiector transformation (from constrained to unconstrained space)

### ISSUE THREAD

**Issue by aymgal** [pyro-ppl/numpyro#1554]
Hi,
Is it possible, with the current interface, to design a function that takes as input the pytree of _constrained_ parameter values and return _unconstrained_ values, given a model with Pyro primitives? For instance, I am looking for a function that does the inverse transform of `constrain_fn()` from `numpyro.infer.util`.

Sorry to ask here but I could not find the answer in the code. So maybe there is no easy implementation of it yet.

**Comment by aymgal** [comment]
I just found a way to achieve this, using this piece of code embedded in [`infer.util`](https://github.com/pyro-ppl/numpyro/blob/9a43b19faf547c7b7259d0e5550d1d9125e9a881/numpyro/infer/util.py#L343).

If you find it useful, I can write a PR for adding a function `unconstrained_fn()` to the module, following the same interface as the existing `constrained_fn()`.

**Comment by fehiepsi** [comment]
yes, please make a PR if it is helpful for your usage case. Thanks!

**Comment by aymgal** [comment]
Ok @fehiepsi ! I will propose a PR once I am sure that I fully understand everything regarding my own test case, and I can write functions that are general enough to be useful to anyone.

**Comment by fehiepsi** [comment]
Take your time, @aymgal. Please let me know if you need some clarification in the code. This feature is also useful for https://forum.pyro.ai/t/initialize-mcmc-chains-from-multiple-predetermined-starting-points/5062/10

**Comment by aymgal** [comment]
@fehiepsi I am in the process of opening a PR. Beforehand I just wanted to check with you about the available functions in `infer.util`.
In my use cases I have a model with both `param` and `sample` sites, so I need an `constrain_fn` (and a new `unconstrain_fn`) that both supports `param`. If I am correct, the current implementation of `constrain_fn` only considers `sample` sites, leaving untouched the `param` although they can be subject to specific constrains.

I thought the simple option was to implement the following function 
```python
def get_transforms(model, model_args, model_kwargs, params):
    """
    (EXPERIMENTAL INTERFACE) Retrieve transforms functions given a NumPyro model.
    This function supports 'param' sites.

    :param model: a callable containing NumPyro primitives.
    :param tuple model_args: args provided to the model.
    :param dict model_kwargs: kwargs provided to the model.
    :param dict params: dictionary of unconstrained values keyed by site
        names.
    :return: `dict` of transformation keyed by site names.
    """
    substituted_model = handlers.substitute(model, params)
    model_trace = handlers.trace(substituted_model).get_trace(*model_args, **model_kwargs)
    transforms = {}
    for k, v in model_trace.items():
        if v["type"] == "param":
            constraint = v["kwargs"].pop("constraint", constraints.real)
            with helpful_support_errors(v):
                transforms[k] = transforms.biject_to(constraint)
        elif (
            v["type"] == "sample"
            and not v["is_observed"]
            and not v["fn"].support.is_discrete
        ):
            with helpful_support_errors(v):
                transforms[k] = transforms.biject_to(v["fn"].support)
    return transforms
```

and then use the already existing `transform_fn` to apply either the forward (`invert=False`, from unconstrained to constrained space) or backward (`invert=True`, from constrained to unconstrained space) transform to a dict of site values. What do you think?
However, this implementation would lead to an alternate version of `constrain_fn`, so I am not sure what is the best here.

I am happy to give further details if something is unclear.

**Comment by fehiepsi** [comment]
> which may not necessarily always lead to the same results

Your proposal looks great to me. Why this approach might lead to a different result?

**Comment by fehiepsi** [comment]
> which may not necessarily always lead to the same results

Your proposal looks great to me. Why this approach might lead to a different result?

**Comment by fehiepsi** [comment]
> which may not necessarily always lead to the same results

Your proposal looks great to me. Why this approach might lead to a different result?

**Comment by fehiepsi** [comment]
I think `constrain_fn` only transforms sites in the inputs. If the inputs only contain sample sites then it should only return the corresponding output for those sample sites.

**Comment by aymgal** [comment]
Ok I opened #1564 , let me know what you think!
