### ISSUE TITLE
numpyro.render_model

### ISSUE THREAD

**Issue by srsani** [pyro-ppl/numpyro#1555]
When I try to run the sample render code 

```
def model(data):
    m = numpyro.sample("m", dist.Normal(0, 1))
    sd = numpyro.sample("sd", dist.LogNormal(m, 1))
    with numpyro.plate("N", len(data)):
        numpyro.sample("obs", dist.Normal(m, sd), obs=data)
        

data = jnp.ones(10)
numpyro.render_model(model, model_args=(data,))
```

I get the following error:

> 2460 raise NameError(
   2461     f'unbound axis name: {axis_name}. The following axis names (e.g. defined '
   2462     f'by pmap) are available to collective operations: {named_axes}')

NameError: unbound axis name: _provenance. The following axis names (e.g. defined by pmap) are available to collective operations: []

numpyro == 0.11.0
jax==0.4.6

**Comment by fehiepsi** [comment]
Hi @srsani, the issue is fixed upstream. We will make a release sometime next week.
