### ISSUE TITLE
An error appears if I include the `mask`.

### ISSUE THREAD

**Issue by donga0223** [pyro-ppl/numpyro#1578]
Without `mask` function, I can fit the model. But when I include `mask = True ... with numpyro.handlers.mask(mask=mask):  `
I got this error message. 
ValueError: Incompatible shapes for broadcasting: shapes=[(100, 10, 5), (100, 10)]

The dimension of `intercept + zHmean` is (100,10,5) and the dimension of `log_sigma_eps` is (100,10,5,5). 

```
mask = True 
        if y is not None:
            # Mask nan values, then substitute a default value to
            # avoid nans in gradients
            mask = ~jnp.isnan(y)

        with numpyro.handlers.mask(mask=mask):            
            if self.sigma_factors_model == 'constant':
                numpyro.sample(
                    'y',
                    dist.Normal(loc=intercept + zHmean, scale=log_sigma_eps),  
                    obs=y)

            elif self.sigma_factors_model == 'AR':
                numpyro.sample(
                    'y',
                    dist.MultivariateNormal(loc=intercept + zHmean, scale_tril=Omega_tl),
                    obs=y)
                    
```

**Comment by fehiepsi** [comment]
Hi @donga0223, it's not clear to me where the issue comes from by looking at the above code. Could you make a small reproducible code instead? You can just make some fake `intercept`, `zHmean` etc.

**Comment by fehiepsi** [comment]
I'm going to close this issue. Please feel free to reopen this.
