### ISSUE TITLE
Documentation: Typo in Tutorial?

### ISSUE THREAD

**Issue by daikonradish** [pyro-ppl/numpyro#1586]
I'm following along a tutorial: https://num.pyro.ai/en/stable/tutorials/bayesian_hierarchical_linear_regression.html

![Screen Shot 2023-05-14 at 10 03 10 AM](https://github.com/pyro-ppl/numpyro/assets/3773819/b0b8dca4-cef3-44c3-9d98-b6913f99bc2f)

I think that there might be typo  in the second last line of the above, as I think sigma is supposed to be half-normal and not normal?

It's probably very low-pri. Sorry for not being able to fix this myself, I can't get the documentation to build on my machine :/

**Comment by OlaRonning** [comment]
Hi @daikonradish 

That is indeed the case. Feel free to open a pull request and fix it. Let me know if you need help.

Best, Ola

**Comment by fehiepsi** [comment]
Hi @daikonradish, this is fixed in the latest version. https://num.pyro.ai/en/latest/tutorials/bayesian_hierarchical_linear_regression.html
