### ISSUE TITLE
Way to change num_samples of MCMC in post predictive check

### ISSUE THREAD

**Issue by t-tetsuya222** [pyro-ppl/numpyro#1592]
I would like to sample more than the sample_size which is designated in MCMC.
For example, 
```
nuts = numpyro.infer.NUTS(model) 
mcmc = numpyro.infer.MCMC(nuts, num_warmup=3000, num_samples=2500, num_chains=4)
```

In this case, Sample's batch dimension size is equal to 2500 x 4 = 10,000
But, I would like to sample more than 10,000 , e.g., 100,000 in PPC
When I try to designate num_samples=100000 in Predictive as follows:
```
ppc = numpyro.infer.Predictive(model, trace, num_samples=100000)
```

, I get the following UserWarning.
**Sample's batch dimension size 10000 is different from the provided 100000 num_samples argument.**

Is there any way to change num_samples in post predictive check.

**Comment by fehiepsi** [comment]
You can do
```
resample_idx = jax.random.choice(jax.random.PRNGKey(0), 10000, 100000)
new_samples = jax.tree_util.tree_map(lambda x: x[resample_idx], samples)
```

**Comment by t-tetsuya222** [comment]
Hello, @fehiepsi 

Thanks!
The code works by modifying a little bit.
'''
resample_idx = jax.random.choice(jax.random.PRNGKey(0), 10000, (100000, ))
new_samples = jax.tree_util.tree_map(lambda x: x[resample_idx], samples)
'''
