### ISSUE TITLE
 distributed log_prob/grad computation with distributed sampling

### ISSUE THREAD

**Issue by dkn16** [pyro-ppl/numpyro#1594]
I'm working with the exciting new distributed feature of the numpyro, however, when I try to distribute the parameter, I meet an error . Here is my code, modified from the example in #1514 

```
import jax
from jax.experimental import mesh_utils
from jax.sharding import PositionalSharding
import numpy as np
import numpyro
import numpyro.distributions as dist
from numpyro.infer import MCMC, NUTS
X = np.random.randn(125)
y = np.random.randn(125)
def model(X, y):
    beta = numpyro.sample("beta", dist.Normal(X, 1))
    numpyro.sample("obs", dist.Normal(beta, 1), obs=y)
mcmc = MCMC(NUTS(model), num_warmup=10, num_samples=10)
# See https://jax.readthedocs.io/en/latest/notebooks/Distributed_arrays_and_automatic_parallelization.html
sharding = PositionalSharding(mesh_utils.create_device_mesh((5,)))
X_shard = jax.device_put(X, sharding.reshape(5, ))
y_shard = jax.device_put(y, sharding.reshape(5))
mcmc.run(jax.random.PRNGKey(0), X_shard, y_shard)
```

I want to sample a distributed `beta` to compute the likelihood. however, I got an error like
```

ValueError: Sharding GSPMDSharding({devices=[1,5]0,1,2,3,4}) implies that array axis 1 is partitioned 5 times, but the dimension size is 126 (full shape: (10, 126), per-dimension tiling factors: [1, 5] should evenly divide the shape)

```

I'm wondering if that is because I wrote the wrong code or if this feature is currently not supported by `numpyro`?

**Comment by fehiepsi** [comment]
I don't think this is supported (though you might try `init_to_sample` strategy instead). It seems tricky to distribute the kinetic energy computation etc. with the current code base. For your purpose, it's better to e.g. `pmap` a sampling function on a chunk of data - MCMC will like that because it can use independent info like step_size on each item.
