### ISSUE TITLE
Sample and evaluate independent parameter sets at once

### ISSUE THREAD

**Issue by JR-1991** [pyro-ppl/numpyro#1603]
First of all, lots of thanks for the great library! Its fun to use and as a beginner I've had a great intro to the topic 🙌

I am currently using Numpyro to solve an inverse problem to estimate parameters of a coupled system of ODEs using `diffrax` for the integration part.  Since the latter is capable to `vmap` across multiple sets of parameters I was wondering if it is possible to subsample parameters to evaluate those in parallel. 

So far I am able to obtain a matrix of parameters and ingest it into my simulation function:

```python
with numpyro.plate("parameters", 10):
    theta = sample_from_distributions()

_, states = sim_func(y0s, theta, times)

# Shapes -> theta: (10, n_params) / states: (10, time, species)
```

My question is, if I am now specifying a `numpyro.plate` to model my observations across all parameter sets, will Numpyro treat these as independent across all of them? Thought about something like this:

```python
with numpyro.plate("parameter_sets", 10):
    numpyro.sample("y", dist.TruncatedNormal(states, sigma, low=0.0), obs=data)
```

Curious if this is possible. Would help me a lot!

**Comment by martinjankowiak** [comment]
@JR-1991 can you please ask your modeling question on the [forum](https://forum.pyro.ai/)? github issues are meant for bug reports, feature requests, etc
