### ISSUE TITLE
Sampling from `TruncatedNormal` returns infinities when location parameter is outside bounds

### ISSUE THREAD

**Issue by rafaelkaufmann** [pyro-ppl/numpyro#1606]
As far as I can tell there is nothing in the mathematical definition of this distribution that requires loc to be within bounds, and it would be useful for one of my use cases.

**Comment by fehiepsi** [comment]
Could you provide reproducible code?

**Comment by rafaelkaufmann** [comment]
```
from numpyro.distributions import TruncatedNormal
from jax.random import PRNGKey

key = PRNGKey(42)
sample = TruncatedNormal(loc=1.1, scale=0.005, low=-1., high=1.).sample(key, (1000,))
sample
```
I did not realize when I first posted, but this only returns -inf when the scale is small relative to the distance between loc and the bound, otherwise it's correct. Probably the CDF values at this point are so close to small that we bump into floating point issues.

**Comment by martinjankowiak** [comment]
@rafaelkaufmann the tails will always be an issue if you push out enough but for this particular case this does the fix

```
from numpyro.util import enable_x64
enable_x64()
```

**Comment by fehiepsi** [comment]
In the latest numpyro release, your code returns a concrete number instead of inf. But that number is out of support (due to precision issues). Probably we can clip the values afterward but it's better to use x64.

**Comment by rafaelkaufmann** [comment]
Hello, sorry for the late reply. I can confirm that using x64 solves this. I will also update NumPyro. In any case, it would certainly be best to clip the values coming out of the distribution to the support as I would imagine incredibly puzzling bugs coming out of this issue ("WDYM TruncatedNormal doesn't truncate?")
