### ISSUE TITLE
AutoGuide for param sites

### ISSUE THREAD

**Issue by aymgal** [pyro-ppl/numpyro#1613]
Hi,
If I understand correctly what is going on in auto guides such as `AutoNormal`, only the `sample` sites of the numpyro model get corresponding mean and width parameters associated to them. I am currently working with a model that contain both `sample` and `param` sites, and I would like to model the posterior distribution also of these latter sites.

Hence, before trying to adapt the code for what I am looking for, I wanted to make sure: is there some mathematical reason why auto guides do not create posterior parameters for `param` sites?

**Comment by martinjankowiak** [comment]
@aymgal can you please ask your question on our [forum](https://forum.pyro.ai/). github issues are intended for bug reports, feature requests, etc

**Comment by aymgal** [comment]
Ok will do! (it's not clear to me if what I brought up above is an actual issue in AutoGuide, or if this is intended)
