### ISSUE TITLE
Bug: num_steps for warmup returns a zero matrix

### ISSUE THREAD

**Issue by Madhav-Kanda** [pyro-ppl/numpyro#1620]
I am using the following code to get the number of gradient evaluations during warmup:

```
nuts_kernel = NUTS(funnel_model)
mcmc = MCMC(nuts_kernel, num_warmup=1000, num_samples=1000)
mcmc.warmup(rng_key, extra_fields=('num_steps',))
warmup_steps = mcmc.get_extra_fields()['num_steps']
```

But, the return value that I get is a zero matrix. Thus, I believe that this is a potential bug.

**Comment by fehiepsi** [comment]
To collect warmup samples, you need to specify `collect_warmup=True` in the `warmup` method.
