### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by pyatsysh** [pyro-ppl/numpyro#1634]
In the LKJ distribution, there is a code snippet with example [here](https://num.pyro.ai/en/stable/distributions.html#numpyro.distributions.continuous.LKJ)

In this example, the following line:
`# we can also use a faster formula `cov_mat = jnp.outer(theta, theta) * corr_mat``

Should be changed to
`# we can also use a faster formula `cov_mat = jnp.outer(sigma, sigma) * corr_mat``

**Comment by fehiepsi** [comment]
Thanks, could you submit the fix?
