### ISSUE TITLE
A tutorial for Automatic Partial centering of model using LocScaleReparam

### ISSUE THREAD

**Issue by Madhav-Kanda** [pyro-ppl/numpyro#1635]
Hi,
I wonder if I could contribute an example/tutorial for doing automatic partial centering of the model using LocScaleReparam based on [Automatic Reparameterisation of Probabilistic Programs](https://arxiv.org/abs/1906.03028). I could not find any example/tutorial that guides how to use LocScalReparam along with SVI to get centeredness between 0 & 1 and consequently reparameterizing the model accordingly. Let me know what you think.

**Comment by fehiepsi** [comment]
Yes, please feel free to contribute. Thanks, @Madhav-Kanda!
