### ISSUE TITLE
Why does the mcmc take so much GPU memory? 

### ISSUE THREAD

**Issue by DQSSSSS** [pyro-ppl/numpyro#1636]
Here is a simple MCMC code:

```python
from collections import namedtuple
import jax
from jax import random
import jax.numpy as jnp
import numpyro
import numpyro.distributions as dist
from numpyro.infer import MCMC

# close jit
# jax.config.update("jax_disable_jit", True)

MHState = namedtuple("MHState", ["u", "rng_key"])

class MetropolisHastings(numpyro.infer.mcmc.MCMCKernel):
    sample_field = "u"

    def __init__(self, potential_fn, step_size=0.1):
        self.potential_fn = potential_fn
        self.step_size = step_size

    def init(self, rng_key, num_warmup, init_params, model_args, model_kwargs):
        return MHState(init_params, rng_key)

    def sample(self, state, model_args, model_kwargs):
        u, rng_key = state
        rng_key, key_proposal, key_accept = random.split(rng_key, 3)
        u_proposal = dist.Normal(u, self.step_size).sample(key_proposal)
        accept_prob = jnp.exp(self.potential_fn(u) - self.potential_fn(u_proposal))
        u_new = jnp.where(dist.Uniform().sample(key_accept) < accept_prob, u_proposal, u)
        return MHState(u_new, rng_key)

def f(x):
    return ((x - 2) ** 2).sum()

kernel = MetropolisHastings(f)
mcmc = MCMC(kernel, num_warmup=0, num_samples=1000000)
mcmc.run(random.PRNGKey(0), init_params=jnp.array([1., 2.]))
posterior_samples = mcmc.get_samples()
mcmc.print_summary()  
```

I ran this code on a single A100 GPU, I found that when the code runs in the line `mcmc.run`, the GPU memory costs more than 60G GPU memory. 
I use `pprof` (following this [link](https://jax.readthedocs.io/en/latest/device_memory_profiling.html)) to do the profiling in the main loop in the code file `numpyro/util.py` 356-361 lines, I got the node graph:
![profile002](https://github.com/pyro-ppl/numpyro/assets/19804552/d6a45e16-66d9-42a7-a23c-9c5c057e95d3)
 `numpyro/util.py` 356-361 lines:
```python
            with tqdm.trange(upper) as t:
                for i in t:
                    vals = jit(_body_fn)(i, vals)
                    t.set_description(progbar_desc(i), refresh=False)
                    if diagnostics_fn:
                        t.set_postfix_str(diagnostics_fn(vals[0]), refresh=False)
```

And I found that if I close the jit option this problem still exists. I think this algorithm should not take so much GPU memory, but I don't know where the GPT memory going. It is used for speed? Or other something?

**Comment by martinjankowiak** [comment]
for simplicity the MCMC implementation pre-allocates memory for samples to be generated. you're generating a very large number of samples (10^6) so this is presumably the reason. do you really need that many samples? if the reason you need lots of samples is because you have a low effective sample size it's probably sufficient to generate a large number of samples but only keep a certain fraction. e.g. with `thinning=10` you would keep 10% of samples and use 10% as much memory.

**Comment by fehiepsi** [comment]
Alternatively, you can perform mcmc run [sequentially](https://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.MCMC.post_warmup_state). After each time you run, copy your samples into a CPU host using `jax.device_get`.

**Comment by fehiepsi** [comment]
I'm going to close the issue because the behavior seems to be expected.
