### ISSUE TITLE
 dist.NegativeBinomialProbs(r, p) yields different results compared to scipy's calculation

### ISSUE THREAD

**Issue by qipengchen** [pyro-ppl/numpyro#1637]
Hey,

I'm not sure if it's a bug, but I noticed that the mean and variance calculated using dist.NegativeBinomialProbs(r, p) are different from those calculated using scipy. Here is the test sample:

```
import numpy as np
import numpyro.distributions as dist
from scipy.stats import nbinom

r = 5#np.random.randint(1,100,10000)
p = 0.3#np.random.uniform(0,1,10000)

print((dist.NegativeBinomialProbs(r, p).mean - nbinom.mean(r, p)).mean())
# -9.52

print((dist.NegativeBinomialProbs(r, p).variance - nbinom.var(r, p)).mean())
# -35.83

r = np.random.randint(1,100,10000)
p = np.random.uniform(0,1,10000)

print((dist.NegativeBinomialProbs(r, p).mean - nbinom.mean(r, p)).mean())
# 183.92

print((dist.NegativeBinomialProbs(r, p).variance - nbinom.var(r, p)).mean())
# 1936220.9

```

Also, I found that NegativeBinomial2 seem work fine. so, I'm not sure if there is an error in the calculation of concentration or rate. 
https://github.com/pyro-ppl/numpyro/blob/ca96eca8e8e1531e71ba559ef7a8ad3b4b68cbc2/numpyro/distributions/conjugate.py#L245C1-L246C33

**Comment by fehiepsi** [comment]
I think the interpretations of `r` in scipy and numpyro (which is a fork of pytorch) are different. In scipy, `r` is the number of successes and , while in numpyro it is the number of failures. So you need to change `p` to `1 - p` in numpyro to be consistent. Do you want to update the documentation for this clarification?

**Comment by qipengchen** [comment]
Yes, as you said, the parameters of the two packages have different meanings. After rewriting the code, I found that the means and variances of the two are similar.

```
import numpy as np
import numpyro.distributions as dist
from scipy.stats import nbinom

r = 5#np.random.randint(1,100,10000)
p = 0.3#np.random.uniform(0,1,10000)

print((dist.NegativeBinomialProbs(r, 1-p).mean - nbinom.mean(r, p)).mean())
# -1.7763568394002505e-15

print((dist.NegativeBinomialProbs(r, 1-p).variance - nbinom.var(r, p)).mean())
# 0.0

r = np.random.randint(1,100,10000)
p = np.random.uniform(0,1,10000)

print((dist.NegativeBinomialProbs(r, 1-p).mean - nbinom.mean(r, p)).mean())
# 2.431489370963245e-10

print((dist.NegativeBinomialProbs(r, 1-p).variance - nbinom.var(r, p)).mean())
# -0.08209099
```
I am glad to provide clarification for the parameter meaning in the document, but I am sorry that I do not know how to modify the source code to achieve this.
