### ISSUE TITLE
Pareto distribution log_prob not -inf below scale

### ISSUE THREAD

**Issue by mdmould** [pyro-ppl/numpyro#1639]
Probability density evaluations for the Pareto distribution should be zero below `scale`, the minimum value of the distribution, but instead the support extends below `scale`. This does not affect sampling from the distribution, but it does affect `log_prob` evaluations, where somehow to support constraint `(scale, inf)` is not respected.

E.g.:
```
import jax.numpy as jnp
from jax.random import PRNGKey
from numpyro.distributions import Pareto
import matplotlib.pyplot as plt

scale = 10
alpha = 5
dist = Pareto(scale, alpha)

samples = dist.sample(PRNGKey(0), (1_000,))
plt.hist(samples, bins=20, density=True)
# Minimum sample is at scale = 10

x = jnp.linspace(0, 100, 1_000)
prob = jnp.exp(dist.log_prob(x))
plt.plot(x, prob)
# prob is not zero below scale

plt.semilogy()
plt.show()

print(jnp.trapz(prob[x > scale], x[x > scale]))
# Pareto is properly normalized within the correct support (scale, inf),
# but log_prob is not -inf below scale
```

This causes incorrect likelihood evaluations if, e.g., a Pareto distribution is part of a model via a sample site and observed data lies below `scale`.

The workaround is to replace sampling from the Pareto distribution with manual `log_prob` evaluations:
```
# replace, e.g.,
numpyro.sample('obs', Pareto(scale, alpha), obs=obs)

# with, e.g.,
numpyro.factor('log_prob', jnp.where(obs > scale, Pareto(scale, alpha).log_prob(obs), -jnp.inf))        
```

**Comment by fehiepsi** [comment]
I think you can get desired behavior by using `numpyro.enable_validation()`.

**Comment by mdmould** [comment]
That works, thanks!
