### ISSUE TITLE
Add support for InverseTransform

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#164]
This will allow us to create new transform classes out of existing ones. e.g. `LogitTransform` as `SigmoidTransform().inv`. 

It will also be nice if the client code can just take in a list of transforms and call `.inv` on it without having any knowledge of whether the original or the inverted transform was passed in.

e.g. 
**Numpyro**

```sh
>>> t = SigmoidTransform()

>>> t.inv
 <bound method SigmoidTransform.inv of <numpyro.distributions.constraints.SigmoidTransform object at 0x7f92680ce710>>

>>> t.inv.inv
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-15abeba100ea> in <module>
----> 1 t.inv.inv

AttributeError: 'function' object has no attribute 'inv'
```

**Pytorch**
```sh
>>> t = SigmoidTransform()

>>> t.inv
 _InverseTransform()

>>> t.inv.inv
 SigmoidTransform()
```

**Comment by fehiepsi** [comment]
I have thought about this and found that it just makes things more confusing. Could you be more explicit about `the client code can just take in a list of transforms and call .inv on it without having any knowledge of whether the original or the inverted transform was passed in`? I guess there are some usage cases where both `SigmoidTransform()` and `SigmoidTransform().inv` are used in client code?

**Comment by neerajprad** [comment]
> Could you be more explicit about the client code can just take in a list of transforms and call .inv on it without having any knowledge of whether the original or the inverted transform was passed in? 

The reason would just be to have a wider class of transforms available by not having to write a separate implementation for the inverse transform if a transform is bijective. e.g. Instead of a `LogitTransform`, we should just be able to use `SigmoidTransform().inv` as a regular transform. Right now transforms from a constraint to real are not first class transforms (but simply functions) because, amongst other things, we cannot invert them. Just as we can compose transforms, we should also be able to invert them when they are invertible. Also, you could imagine a use case where we need to compose with the inverse transform.

**Comment by neerajprad** [comment]
Changed the title/description to better reflect the motivation. This is a nice to have, but isn't blocking anything that we are working on right now.

**Comment by fehiepsi** [comment]
Hmm, this might be nice to have. But I am curious because I don't know an explicit distribution which requires this feature.

**Comment by neerajprad** [comment]
@fehiepsi - One such example to the last point that I mentioned is the [Gumbel](https://github.com/pytorch/pytorch/blob/master/torch/distributions/gumbel.py#L38) distribution.

**Comment by fehiepsi** [comment]
Thanks for pointing it out! Though applying ExpTransform.inv to a Uniform distribution does not make sense to me (in terms of domain, codomain and their corresponding logdet) in that particular distribution, there might be other distributions with similar pattern. It is good to know btw.
