### ISSUE TITLE
chain_method=vectorized not working for multiple chains

### ISSUE THREAD

**Issue by james-bowden** [pyro-ppl/numpyro#1640]
Hi, I understand that this is still an experimental feature so no urgency here, but:

I have code that runs on {parallelized, >1 chains}, {vectorized, 1 chain only}, and breaks for {vectorized, >1 chains} which is exactly the point of this option as I understand it. Desired behavior would be that code working for the above (more standard) cases also works for this setting.

I've attached the error message below; wondering if this is my fault (perhaps my model doesn't have the correct input/output dims for vectorizing and need to add another None dim?) or just a bug. I haven't tried to test this in other settings (e.g., simple demo), nor do I have a minimum reproducible code.

![image](https://github.com/pyro-ppl/numpyro/assets/61923965/57e9d478-4b3a-4d73-9640-a56dc746c8f1)

**Comment by fehiepsi** [comment]
I think it's just a bug somewhere. vmap is tested here https://github.com/pyro-ppl/numpyro/blob/ca96eca8e8e1531e71ba559ef7a8ad3b4b68cbc2/test/infer/test_mcmc.py#L481

**Comment by james-bowden** [comment]
One thing I just realized: my first MCMC run works just fine (so it does actually vectorize, I guess), and subsequent runs do not. I'm using the `jit_model_args=True` param so wonder if it has to do with that instead.

**Comment by fehiepsi** [comment]
We have a test here. Could you check if it passes now?

https://github.com/pyro-ppl/numpyro/blob/ca96eca8e8e1531e71ba559ef7a8ad3b4b68cbc2/test/infer/test_mcmc.py#L593

**Comment by fehiepsi** [comment]
I assume that the issue has been resolved now. Please follow up on our forum if you have further questions.
