### ISSUE TITLE
How to properly sample within `SVI`?

### ISSUE THREAD

**Issue by snehjp2** [pyro-ppl/numpyro#1653]
Hi, I think I'm severely misunderstanding or misusing `sample` within SVI. Here is (a skeleton of) some of the code.

```python

def model():
        sample_shape = (100, )

        gamma_prior = dist.Normal(-20, 5).expand(sample_shape)
        gammas = numpyro.sample('gammas', gamma_prior)

        ### below, run simulation with parameters and compute loss with output
        . 
        .
        .

        numpyro.factor("loss", -total_loss)

    guide = AutoBNAFNormal(model, num_flows=1)
    optimizer = Adam(step_size=1e-2)
    svi = SVI(model, guide, optimizer, loss=Trace_ELBO())
    .
    .
    ### below is training loop
```

What's expected is that `gammas` are drawn from a prior (Gaussian) distribution with the above parameters. However, whatever I do, these samples seem to only come from the standard Gaussian when printing, e.g. it is ignoring the mean and variance I have defined.

If I draw parameters from the prior this way:

```python
gamma_prior = dist.Normal(-20, 5).expand(sample_shape)
gammas_samples = gamma_prior.sample(jax.random.PRNGKey(1))
```

The behavior is as expected. What am I doing wrong??

**Comment by martinjankowiak** [comment]
@snehjp2 can you please ask your question on our [forum](https://forum.pyro.ai/).

github issues are intended for bug reports, feature requests, etc
