### ISSUE TITLE
Specify python version for pip

### ISSUE THREAD

**Issue by deto** [pyro-ppl/numpyro#1656]
Can the python version be specified for pip in the setup.py?  Specifically using the method here:
- https://stackoverflow.com/questions/45778790/specifying-the-minimum-python-version-required-for-a-module-in-pip

i.e. `python_requires` so that it's picked up by pip

Currently, the update of this to drop 3.9 support broke a build of mine on a python 3.8 image.  I can get around this by pegging it to 0.12.1, but if python_requires is added, I believe pip will do this dependency resolution automatically.

**Comment by fehiepsi** [comment]
Thanks for the ping! Do you want to make a PR for it?
