### ISSUE TITLE
Why do we need to seed model in ELBO

### ISSUE THREAD

**Issue by howsiyu** [pyro-ppl/numpyro#1670]
Example:
https://github.com/pyro-ppl/numpyro/blob/d9b52d7054cc84af687022810003a13efc7f5703/numpyro/infer/elbo.py#L196

If we delete the line and change the next line to use `model` directly I still can run my code without any change to the result.

**Comment by fehiepsi** [comment]
This is to cover the case where there are random latent variables in model but not in guide. Please ask questions on https://forum.pyro.ai/ instead. We only use github to track issues and feature requests.
