### ISSUE TITLE
Enforcement of arg_constraints / parameter constraints

### ISSUE THREAD

**Issue by e-pet** [pyro-ppl/numpyro#1677]
The Poisson rate parameter is supposed to be positive, i.e., > 0. However, numpyro will happily let me do the following:

```python
p = numpyro.distributions.Poisson(rate=0)
p.log_prob(0)  # yields nan
p.log_prob(1)  # yields -inf
```

When I look in the code / docs, I find https://github.com/pyro-ppl/numpyro/blob/f5bd186adda3a3436c21192a7b649cc4dd42e8e9/numpyro/distributions/discrete.py#L682 and https://github.com/pyro-ppl/numpyro/blob/f5bd186adda3a3436c21192a7b649cc4dd42e8e9/numpyro/distributions/constraints.py#L292

At first I thought that just the "strict" part of the positivity check was broken, but it seems that numpyro will equally happily let me use rates < 0... is this intended behavior or a bug? Are arg_constraints not enforced in any way?

**Comment by fehiepsi** [comment]
I think it's enabled with `numpyro.distributions.Poisson(rate=0, validate_args=True)`.

**Comment by e-pet** [comment]
You are completely right of course, sorry for the non-issue! I was not aware of the flag / that those checks have to be enabled and are disabled by default. (That would have saved me a _lot_ of debugging time, I think. :D)

**Comment by fehiepsi** [comment]
You can change the global setting with [enable_validation](https://num.pyro.ai/en/stable/utilities.html?highlight=enable_validation#numpyro.distributions.distribution.enable_validation).
