### ISSUE TITLE
Zero HMC acceptance rate for standard normal

### ISSUE THREAD

**Issue by JakobRobnik** [pyro-ppl/numpyro#1678]
Step size tuning in HMC fails on a standard Gaussian. Acceptance rate is 0, regardless of the step size. The problem goes away with NUTS. 
The problem is shown in this notebook: 
https://colab.research.google.com/drive/1QBrROnhUEAOcP3Q9-pT8AfwFjZdu9y1y?usp=sharing

**Comment by fehiepsi** [comment]
I think the confusion here is that HMC respects `trajectory_length`. So `step_size=trajectory_length / num_steps`. In your case, trajectory_length is large, so step_size will be large. This is confusing. We can't adapt step size if we have a fixed num_steps. But I guess we need to improve the tqdm bar to report the actual step_size - currently, it reports the input value (which will be changed if num_steps is specified).

**Comment by fehiepsi** [comment]
We can also raise a warning if `num_steps` is specified.

**Comment by JakobRobnik** [comment]
Thank you for the quick response.
Is it possible to fix the number of LF steps per sample and tune the
stepsize to the desired acceptance rate?

**Comment by fehiepsi** [comment]
It can be supported by allowing setting `trajectory_length=None` or something. Currently, with a fixed trajectory length and fixed number of steps, the step size will also be fixed.
