### ISSUE TITLE
Scan doesn't work with replay

### ISSUE THREAD

**Issue by deoxyribose** [pyro-ppl/numpyro#1685]
Given a model adapted from the scan doctest:

```python
def gaussian_hmm(y=None, T=T, N=N):
    def transition(x_prev, y_curr):
        with numpyro.plate('data', N):
            x_curr = numpyro.sample('x', dist.Normal(x_prev, 1.5))
            y_curr = numpyro.sample('y', dist.Normal(x_curr, 0.3), obs=y_curr)
        return x_curr, (x_curr, y_curr)
    with numpyro.plate('data', N):
        x0 = numpyro.sample('x_0', dist.Normal(jnp.zeros(N), 5.))
    _, (x, y) = scan(transition, x0, y, length=T)
    return (x, y)
    
with numpyro.handlers.seed(rng_seed=0):
    x, y = gaussian_hmm()

svi = SVI(gaussian_hmm, custom_guide, Adam(0.1), Trace_ELBO(num_particles=1), y=y, T=T, N=N)

n_steps = 5000
results = svi.run(random.PRNGKey(0), n_steps)
```

HMC gives the expected results. SVI runs without errors, but gives bad results, because the ELBO is not computed correctly. The scan operator blocks all handlers except substitute and condition, including the replay effect handler used in ELBO.

A preliminary implementation can be seen here https://github.com/pyro-ppl/numpyro/compare/master...aleatory-science:numpyro:master, which uses a similar logic to the way substitute is implemented for scan, and reuses the `substitute_stack` to store the replay trace.

**Comment by deoxyribose** [comment]
I could make a PR as it is, but note that `scan_enum` hasn't been correspondingly edited (if it needs to be), and I'm not sure if and how the implementation otherwise needs to changed, or tested. @fehiepsi do you want to review what's there now, or is there something else I can add first?

**Comment by fehiepsi** [comment]
Thanks @deoxyribose !
