### ISSUE TITLE
tqdm hangs when `set_postfix_str` with `refresh=True`

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#169]
This issue is observed while running the LGT example. It is resolved if we replace `refresh=True` at
```
t.set_postfix_str(get_diagnostics_str(hmc_state), refresh=True)
```
to `refresh=False`.

**Comment by neerajprad** [comment]
Is this using `tqdm.notebook`? I think `refresh=True` by default at least on the command line.

**Comment by fehiepsi** [comment]
I think we are using `trange`. For notebook widget, it should be `tnrange`. The issue happens when we set refresh=True and the iterator changes the speed drastically at some iterations. This happens in notebook with `trange`, not tqdm.notebook.

**Comment by neerajprad** [comment]
I am unfortunately not able to replicate the issue on Mac. I have tried with the latest dependencies for jax, jaxlib and tqdm and the kernel simply crashes on the cell that runs `mcmc` with `Process finished with exit code 132 (interrupted by signal 4: SIGILL)`. What version of jax/jaxlib are you on?

**Comment by fehiepsi** [comment]
Oppss... it is strange. I did not get that crashing issue, only hanging issue. I am using master version, both for jax and jaxlib. Let me test with official releases later today.

**Comment by fehiepsi** [comment]
It seems that `refresh=False` works as expected. Let's open the issue again when something is wrong with prog_bar.
