### ISSUE TITLE
[FR] add affine-invariant ensemble sampling (including DE-MCMC) and ensemble slice sampling

### ISSUE THREAD

**Issue by amifalk** [pyro-ppl/numpyro#1691]
as implemented in [emcee](https://emcee.readthedocs.io/en/stable/) and [zeus](https://zeus-mcmc.readthedocs.io/en/latest/index.html) - both methods are gradient free. For likelihood free models, differential evolution monte carlo (DE-MCMC) tends to be [robust](https://www.sciencedirect.com/science/article/abs/pii/S0022249616301663).

I have minimal working drafts of the two classes [here](https://github.com/amifalk/numpyro/blob/demc/numpyro/infer/ensemble.py) with utility functions [here](https://github.com/amifalk/numpyro/blob/demc/numpyro/infer/ensemble_util.py). I tried to make the api align with emcee and zeus where possible. 

Also, ```batch_ravel_pytree()``` in ensemble_util.py should make it easier to implement future mcmc methods that share information between chains.

Let me know what you think!

**Comment by fehiepsi** [comment]
Thanks, @amifalk! It's great to have a likelihood-free inference algorithm in NumPyro. Welcome to contribute!
