### ISSUE TITLE
[FR] constrain values for AutoDelta.median()

### ISSUE THREAD

**Issue by amifalk** [pyro-ppl/numpyro#1712]
In a similar vein to #951. All Normal guides and guides that inherit from AutoContinuous automatically constrain the parameters before returning them when median() is called. AutoDelta is the only exception.

Internally, this is handled by calling `self._postprocess_fn` on the guide params, which removes the auto_loc boilerplate attached to every variable and returns deterministic sites as a nice side effect. This would be a convenient feature to have in AutoDelta (and I'm happy to add it).

**Comment by amifalk** [comment]
And actually, this might be a more elegant solution to #951 that wouldn't require calling predictive in the `sample_posterior` method of AutoDelta to get the deterministic sites.

**Comment by fehiepsi** [comment]
Agreed! Your proposal sounds great to me.

**Comment by fehiepsi** [comment]
Hi @amifalk, currently, AutoDelta.median() will return the constrained values. Could you clarify the motivation for the change again?

**Comment by amifalk** [comment]
Sorry about that! Yes, that was a mistake in the original post. This change would return deterministic sites when the `.median()` method is called in AutoDelta, but I'm not sure the PR is worth it given that this is already possible by calling `.sample_posterior()`.

**Comment by fehiepsi** [comment]
@amifalk Do you want to make median return deterministic sites? If so, I guess it makes sense to call sample_posterior with empty sample shape.

**Comment by amifalk** [comment]
@fehiepsi Yes, thanks! I think that's the simplest solution.
