### ISSUE TITLE
Normalizing Flow MCMC

### ISSUE THREAD

**Issue by Qazalbash** [pyro-ppl/numpyro#1734]
# Description
It would be great to have Normalizing Flow MCMC method.

## Paper reference
- [Adaptive Monte Carlo augmented with normalizing flows](https://arxiv.org/abs/2105.12603)
- [Efficient Bayesian Sampling Using Normalizing Flows to Assist Markov Chain Monte Carlo Methods](https://openreview.net/pdf?id=mvtooHbjOwx)

**Comment by fehiepsi** [comment]
Hi @Qazalbash, please check out https://github.com/kazewong/flowMC . We do not have plan to support those algirthms.

**Comment by h2o64** [comment]
> I think you can achieve pretty similar results using the flow reparametrizations that are already implemented : https://num.pyro.ai/en/latest/examples/neutra.html

Hi @renecotyfanboy 
I released [a paper](https://arxiv.org/abs/2302.04763) last year answering this very question. FlowMC is significantly superior to NeuTra on multimodal distributions. I believe its addition would be nice.

**Comment by renecotyfanboy** [comment]
That's super interesting, I had no idea there would be significant differences between flow reparametrization and proposal. This could be a great addition in the [contributed codebase](https://num.pyro.ai/en/latest/contrib.html) if there is no plan to maintain it in the core package

**Comment by fehiepsi** [comment]
I think it is better to use [inference utilities](https://num.pyro.ai/en/stable/utilities.html#module-numpyro.infer.util) on numpyro models to get the joint density and use flowMC on the top of that. It would be great to have a tutorial for it.

**Comment by fehiepsi** [comment]
Please checkout https://num.pyro.ai/en/latest/tutorials/other_samplers.html for integration with other apis.
