### ISSUE TITLE
Adding HMCECS proxy functions

### ISSUE THREAD

**Issue by OlaRonning** [pyro-ppl/numpyro#1744]
Hi,

I'm working on a neural proxy function for HMCECS and have a Taylor expansion proxy with an approximate Hessian. However, the file is becoming somewhat unruly as the proxies are currently in `hmc_gibbs.py`. If I move (only) the proxy functions to a separate file under `contrib` and keep using the static method interface for HMCECS (i.e., `HMCECS.taylor_proxy`), there is no change to the user interface, and I think it would be easier to work with. 

Let me know what you think.

edit: change would look like [this](https://github.com/aleatory-science/numpyro/pull/3) (moved PR to aleatory)

**Comment by fehiepsi** [comment]
yeah, putting it in contrib sounds good to me.

**Comment by OlaRonning** [comment]
Thanks for merging, Du.
