### ISSUE TITLE
ImportError: cannot import name 'CAR' from "numpyro.distrubutions.continuous'

### ISSUE THREAD

**Issue by ttakayaflexpower** [pyro-ppl/numpyro#1781]
When I tried to import numpyro, I got the following error:
`ImportError: cannot import name 'CAR' from 'numpyro.distributions.continuous'`

I checked the .distributions.continuous module that lives in Lib/site-packages but there is 'CAR' function defined in line 1536. Why does installing the package not work?

I installed numpyro after uninstalling jax and running a command `pip install numpyro`. The version is 0.14.0 as in the output of `pip freeze` below.
![image](https://github.com/pyro-ppl/numpyro/assets/145468547/f5b76510-7e7b-47fb-b2cc-6f3b2ab9c377)

I would appreciate any help!

**Comment by fehiepsi** [comment]
I think that your workspace might not be setup correctly. Could you try to remove numpyro then install it again?

**Comment by fehiepsi** [comment]
Closed because I think this is a problem of the workspace.
