### ISSUE TITLE
HSGP utility functions in the `contrib` module?

### ISSUE THREAD

**Issue by juanitorduz** [pyro-ppl/numpyro#1788]
I have been using the Hilbert Space approximation for Gaussian Processes a lot. The main ingredients are the spectral densities of the kernels and the eigenvalues and eigenvectors of the Laplacian in a box, see https://num.pyro.ai/en/stable/examples/hsgp.html

Would you like me to add these functions (and spectral densities from other common kernels) to the `contrib` module so other users can import them?

**Comment by fehiepsi** [comment]
That would be awesome, @juanitorduz!

**Comment by juanitorduz** [comment]
ok! I will start working on it in the upcoming weeks 😄 !
