### ISSUE TITLE
autocorrelation function

### ISSUE THREAD

**Issue by jecampagne** [pyro-ppl/numpyro#1828]
Hello,
May be I have not using the "autocorrelation" correctly but in case I post the snippet on Colab [HERE](https://colab.research.google.com/drive/1nKAZSp3RM-X356z2bpsYK_u6gCbYEZ8_?usp=sharing).
The result is that the Arviz auto-corr seems ok
![image](https://github.com/pyro-ppl/numpyro/assets/20539759/7e49e683-a795-468d-95b9-7245beaa7162)

while the numpyro function exhibits a strange behavior
![image](https://github.com/pyro-ppl/numpyro/assets/20539759/b3b3d000-fa12-4549-b9fc-682ca9003d4a)

Any idea?

**Comment by jecampagne** [comment]
Well looking at the code
In numpyro there is a line  
```python
 autocorr = autocorr / np.arange(N, 0.0, -1)
```
while the  arviz/autocorr  output agree if I replace the above line by 
```python
autocorr = autocorr / autocorr[0]
```
![image](https://github.com/pyro-ppl/numpyro/assets/20539759/b92da571-7d4d-4d32-bd03-33c1c3326e20)

**Comment by fehiepsi** [comment]
Could you use the change in #1785? It seems that we also divide `autocorr[0]` at [this line](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/diagnostics.py#L132)

**Comment by jecampagne** [comment]
Ok thanks @fehiepsi, so I understand the pb and probably a solution would be to have a flag to switch from one to the other normalisation schema.

**Comment by fehiepsi** [comment]
I think we can change the behavior. No need for a new flag. Do you want to submit a PR?

**Comment by fehiepsi** [comment]
Closed because this is duplicated of https://github.com/pyro-ppl/numpyro/issues/1785
