### ISSUE TITLE
Crash when using `TruncatedNormal` in `parallel` MCMC, but not in `sequential` MCMC

### ISSUE THREAD

**Issue by damonbayer** [pyro-ppl/numpyro#1836]
I have encountered a very strange issue while using `TruncatedNormal`. With `numpyro.set_host_device_count(2)` commented out, this script runs fine. Uncommenting it causes this script to crash.

Everything works fine with `my_distribution = dist.Normal()`, so it appears to be related to the `TruncatedNormal`.

```python
import jax.random as random
import numpyro
import numpyro.distributions as dist

from numpyro.infer import MCMC, NUTS

numpyro.set_host_device_count(2)

my_distribution = dist.TruncatedNormal(low=1, high=2)
n_data_samples = 1
n_mcmc_samples = 1
n_mcmc_warmup = 0
n_mcmc_chains = 2
rng_key = random.PRNGKey(0)


data_samples = my_distribution.sample(rng_key, (n_data_samples,))


def my_model():
    numpyro.sample("obs", my_distribution, obs=data_samples)


nuts_kernel = NUTS(my_model)
mcmc = MCMC(
    nuts_kernel,
    num_warmup=n_mcmc_warmup,
    num_samples=n_mcmc_samples,
    num_chains=n_mcmc_chains,
)
mcmc.run(rng_key)
```

**Comment by fehiepsi** [comment]
It is better to move the definition to the model. Some distributions cache info during running, which might cause tracer leakage.
```
def my_model():
    my_distribution = dist.TruncatedNormal(low=1, high=2)
    numpyro.sample("obs", my_distribution, obs=data_samples)
```

**Comment by damonbayer** [comment]
Moving the definition to the model does work around the issue.

Is this considered a bug? It seems to only affect `TruncatedNormal` when both `low` and `high` are specified. If only one of them is specified, the model runs fine. This observation, combined with the fact that it only affects parallel sampling, makes me think that this could be fixed.

**Comment by fehiepsi** [comment]
We use `lazy_property` here and there https://github.com/pyro-ppl/numpyro/blob/master/numpyro/distributions/truncated.py#L215

Maybe a general fix is to not turn those properties into attributes at https://github.com/pyro-ppl/numpyro/blob/master/numpyro/distributions/util.py#L695 if it is a tracer:`numpyro.util.not_jax_tracer(value)`. Do you want to submit that enhancement?

**Comment by damonbayer** [comment]
@fehiepsi I could look into implementing this, but I understand very little about this level of the numpyro codebase, so I would probably require some help.

In @CDCgov's  [multisignal-epi-inference](https://github.com/CDCgov/multisignal-epi-inference) project, we set up models that allow users to supply their own distributions as arguments, so the workaround you suggested is not applicable in our work. This issue prevents us from running some models in parallel, which is unfortunate.

**Comment by fehiepsi** [comment]
I think a fix is to move the `setattr` statement to the if block, so that we dont save any tracer as attribute of global instances (like your distributions). You can add a simple test that you have in the topic comment.
