### ISSUE TITLE
Predictive: better docs for setting obs to `None`

### ISSUE THREAD

**Issue by tomwallis** [pyro-ppl/numpyro#1845]
Hello,

It wasn't clear to me until I dug into some strange behaviour that the `Predictive` method requires setting `obs` to `None`. I see now that the examples do it, but it's not made explicit that this is required for the class to work as intended. Could this be made more explicit in the [docs](https://num.pyro.ai/en/latest/utilities.html#predictive)? Thanks in advance!

**Comment by fehiepsi** [comment]
You are right. It is not trivial to realize that api. Do you want to enhance the docs?

**Comment by tomwallis** [comment]
I can try. To do this, should I build the docs locally, or are the changes to the source files sufficient?

**Comment by tillahoffmann** [comment]
Expanding the documentation in the source file linked below should do the trick. You don't need to build the documentation locally, but it can be helpful for checking that the output looks like what you intended.

https://github.com/pyro-ppl/numpyro/blob/d61f15c0d05a7a86ca464248e5c6f8814b56e457/numpyro/infer/util.py#L851-L918

**Comment by tomwallis** [comment]
Thanks @tillahoffmann. I have created a PR that hopefully does the trick. I was not able to build the docs locally without more time investment, so I have not checked the intended output.
