### ISSUE TITLE
Add CodeCov

### ISSUE THREAD

**Issue by juanitorduz** [pyro-ppl/numpyro#1851]
Hi! I have seen Pyro has a CodeCov (https://about.codecov.io/) badge, and I think this is a handy tool, not only to see how is the test coverage but also on each PR to have more visibility about parts of the code that are untested *maybe overseen by the reviewers). I have used this on other public and private projects, which has always been helpful. Just a suggestion here ;)

**Comment by fehiepsi** [comment]
Thanks, it would be great to support it.
