### ISSUE TITLE
Best practices to use one distribution to define another distribution

### ISSUE THREAD

**Issue by Qazalbash** [pyro-ppl/numpyro#1864]
I have defined some distributions as child classes of `Distribution`. They are very closely linked, and one is used in another definition. I made a mistake not testing them. Upon testing, I ran into issues which are below,

1. For example, I have used `DoublyTruncatedPowerLaw` to define `PowerLawPrimaryMassRatio` like [this](https://github.com/gwkokab/gwkokab/blob/4cb54303293f7b22831cd47f15bb1f13d278f8d2/src/gwkokab/models/_models.py#L780-L810). The following test code passes out of the bound values to the distribution. It expects `UserWarning` but the problem is those out-of-the-bound values are used to construct another distribution. When that distribution gets invalid input values it throws a `ValueError`.

https://github.com/pyro-ppl/numpyro/blob/3cde93d0f25490b9b90c1c423816c6cfd9ea23ed/test/test_distributions.py#L2170-L2175

> [!NOTE]
> This list might get new entries.

**Comment by fehiepsi** [comment]
IIUC the issue has been resolved downstream. Please reopen otherwise.

**Comment by Qazalbash** [comment]
No, this issue hasn't been resolved. I was expecting any input later, so I moved on to use the definition of the methods as a function, but I would still like to see the workaround.

**Comment by fehiepsi** [comment]
Could you ask the question on forum instead? I dont understand the question here. I think we already have a couple of examples in docs on how to define a distribution.
