### ISSUE TITLE
Refactor argument validation?

### ISSUE THREAD

**Issue by tillahoffmann** [pyro-ppl/numpyro#1865]
What are your thoughts on refactoring the argument validation code below into a separate method `validate_args()` (or another name) so it can be invoked on an existing instance? The motivation is that I often have jitted functions that return distribution instances which I would like to validate.

https://github.com/pyro-ppl/numpyro/blob/94f4b99710d855bea456210cf91e6e55eeac3926/numpyro/distributions/distribution.py#L231-L246

**Comment by fehiepsi** [comment]
Yup, exposing that method would be convenient.
