### ISSUE TITLE
Estimate the parameters of a mixture of product distributions 

### ISSUE THREAD

**Issue by Claudmj** [pyro-ppl/numpyro#1869]
Is it possible to estimate the parameters of a product of say normal distributions? If so is it possible to do the following or is it better to define a new distribution and provide a likelihood function for the product distribution.
```python
    # Sample from the two normal distributions
    with pyro.plate("data", len(data)):
        x1 = pyro.sample("x1", dist.Normal(mu1, sigma1))
        x2 = pyro.sample("x2", dist.Normal(mu2, sigma2))

        # Observe the product of the two variables
        pyro.sample("obs", x1 * x2, obs=data[:, 0] * data[:, 1]) 
```

**Comment by fehiepsi** [comment]
Hi @Claudmj, I think you can simply do:
```
x1 = pyro.sample(...)
pyro.sample("obs", dist.Normal(mu2 * x1, sigma2 * x1), obs=...)

**Comment by Claudmj** [comment]
> Hi @Claudmj, I think you can simply do:
> 
> ```
> x1 = pyro.sample(...)
> pyro.sample("obs", dist.Normal(mu2 * x1, sigma2 * x1), obs=...)
> ```

Thank you
