### ISSUE TITLE
Evaluating models in Numpyro.

### ISSUE THREAD

**Issue by Claudmj** [pyro-ppl/numpyro#1875]
Is there anyway to evaluate mixture models such as the following [Sine-skewed sine (bivariate von Mises) mixture](https://num.pyro.ai/en/stable/examples/ssbvm_mixture.html) ? I tried using the following:

`    numpyro.infer.util.log_likelihood(model=ss_model, posterior_samples=posterior_samples, data=data[aa],
                                      num_data=len(data[aa]), K=K)`

But I get an error in the assertion in the sample method for the key. I have tried to get the "observed" model and pass that through but I get the same error about the key.

**Comment by Claudmj** [comment]
May you please do so I'd really like to evaluate the best number of components for this approach.

**Comment by fehiepsi** [comment]
Sorry. It's not clear what's going on. I can follow up on the forum. Please also include small, reproducible code there.
