### ISSUE TITLE
num_parallel_workers is deprecated

### ISSUE THREAD

**Issue by nstarman** [pyro-ppl/numpyro#1878]
https://github.com/pyro-ppl/numpyro/blob/e4622925d4ceb2f1cf7436f57ecb8dcf2a6ddd96/numpyro/contrib/nested_sampling.py#L261

This should be replaced by the "devices" argument. I think (but may be wrong) that this defaults to 1 and can be removed entirely, otherwise I think ``devices=jax.devices()[:1]`` is the correct substitution.

**Comment by nstarman** [comment]
I see this will be resolved by #1871

**Comment by fehiepsi** [comment]
Right. Let me close the issue.
