### ISSUE TITLE
Masking a Mixture Model makes `component_` methods unavailable

### ISSUE THREAD

**Issue by nstarman** [pyro-ppl/numpyro#1885]
The `MaskedDistribution` object wraps models, but does not necessarily expose their public API.
I'm raising this Issue to perhaps add support for the `components_` methods.

Possible Options:
1. Some clever method of auto-wrapping methods accessed by `__getattr__`.
2. Have a `MaskedMixtureDistribution` class that is returned by `MixtureDistribution.mask()`.
3. instead of `.mask()` masking the Distribution, it returns the same mixture, but calling `.mask()` on all the component distributions.

**Comment by fehiepsi** [comment]
If you want to access properties of the base dist, the third option makes sense to me. But I think it is better access the components via `d.base_dist.[attribute]`

**Comment by nstarman** [comment]
I can push a PR for option 3!

> But I think it is better access the components via d.base_dist.[attribute]

That's what I do currently, but that loses the mask, so all the `component_` methods aren't masked.

**Comment by fehiepsi** [comment]
You can mask those components just like the way you mask the mixture. I
would recommend to keep the components as-is and only mask them when needed.

**Comment by nstarman** [comment]
Are you saying option 2 is best then?

**Comment by fehiepsi** [comment]
All of them modify the "default" behavior and introduce new "potentially more convenient in some usage case" behavior. I just meant that you can do `d.base_dist.component...mask(...)` to get a masked component without modifying the default behavior.

**Comment by fehiepsi** [comment]
I guess we can close because the behavior is expected.
