### ISSUE TITLE
I cannot use the forum `https://forum.pyro.ai/`

### ISSUE THREAD

**Issue by aleksejs-fomins** [pyro-ppl/numpyro#1889]
Problems with the forum
1. I do not see a way to register, only to Log in
2. When I attempt to log in with Github, I get redirected to the OAuth page of Github which says the following:

> Be careful!
> The redirect_uri is not associated with this application.
> The application might be misconfigured or could be trying to redirect you to a website you weren't expecting.

What is the intended way of using the forum for new users?

**Comment by fehiepsi** [comment]
Thanks for the report, @aleksejs-fomins! Let us take a look at the settings.

**Comment by fehiepsi** [comment]
I think this is fixed. Please reopen if the issue happens again.

**Comment by sheinkmana** [comment]
@fehiepsi I have a slightly different issue with the forum: I have been trying to ask the question for a while now: the earlier issue with GitHub authentication was fixed but I haven't posted before and when I try to sign up it says "New account registrations are not allowed at this time." 
Thanks!

**Comment by fehiepsi** [comment]
Could you double check? I hope it works again now.

**Comment by sheinkmana** [comment]
It works now, huge thanks!
