### ISSUE TITLE
Regarding sampling on discrete variable.

### ISSUE THREAD

**Issue by real-junjiezhang** [pyro-ppl/numpyro#1896]
Hi,

Thanks for your amazing work in advance!

Assume I have 1000 sentences, each 10 sentence will be combined to a group. And this group be converted to some embedding by our local embedding function.The distance/diversity will be measured by cosine similarity. What I want is to sample as much diverse sequence group as possible. 

My problem is whether my case if fit for MCMC, In other words, can I use DiscreteHMCGibbs to realize this.Let's say I want sample 10000 different sentence group.

Can someone show me the pseudo code.I am little bit struggling in how to write the code!

Thanks so much!!

**Comment by fehiepsi** [comment]
Could you use our forum https://forum.pyro.ai/ for questions? We prefer using github to track issues and features.

**Comment by real-junjiezhang** [comment]
> Could you use our forum https://forum.pyro.ai/ for questions? We prefer using github to track issues and features.

It shows New account registrations are not allowed at this time.

**Comment by fehiepsi** [comment]
Sorry, could you double check? I hope it works now.

**Comment by real-junjiezhang** [comment]
It works, thank you.
