### ISSUE TITLE
'z' values for HMC and NUTS seem to be in the constrained space which is inconsistent with the current docs

### ISSUE THREAD

**Issue by soichiro-hattori** [pyro-ppl/numpyro#1903]
Hi,

Thank you for this amazing package! 

The docs for [HMCState](https://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.hmc.HMCState) currently mention:
z - Python collection representing values **(unconstrained samples from the posterior)** at latent sites.

However, I think it's actually returning the parameter values in the constrained space.
Here's a toy model which I think shows this issue.

```python
import jax
import jax.numpy as jnp
import numpy as np
import numpyro
import numpyro.distributions as dist, numpyro.infer as infer
import matplotlib.pyplot as plt
from functools import partial

jax.config.update('jax_enable_x64', True)

rng = np.random.default_rng(seed=12)

x = np.linspace(0, 10, 100)
m_true, b_true = 1.0, 5.0
y_true = m_true*x + b_true
sigma = 1.5
yerr = sigma * rng.standard_normal(x.size)

y = y_true + yerr
fig, ax = plt.subplots(dpi=200)
ax.plot(x, y_true, color='k')
ax.errorbar(x, y, yerr=1, ls='none', marker='.')
ax.set_xlabel('x')
ax.set_ylabel('y')
```
![image](https://github.com/user-attachments/assets/7a593448-f939-4362-9b98-729b0193ab18)

```python
# define numpyro model
def model(x, yerr, y=None):
    m = numpyro.sample('m', dist.TruncatedNormal(low=0.0))
    b = numpyro.sample('b', dist.Normal())

    y_model = m * x + b

    numpyro.sample('obs', numpyro.distributions.Normal(y_model, yerr), obs=y)


kernel = numpyro.infer.NUTS(model)

sampler = numpyro.infer.MCMC(
    kernel,
    num_warmup=500,
    num_samples=1000,
    progress_bar=True,
)
sampler.run(jax.random.PRNGKey(12), x, yerr=sigma, y=y)
sampler.print_summary()
samples = sampler.get_samples()  # constrained_space
z = sampler._states['z']  # docs mention this is in unconstrained space
print(jnp.allclose(z['m'], samples['m']), jnp.allclose(z['b'], samples['b']))  # (True, True)

_unconstrain_fn = partial(infer.util.unconstrain_fn,
                          model,
                          (x, sigma),
                          {'y': y},
                          )

unconstrained_parameters = jax.vmap(_unconstrain_fn, in_axes=({'m': 0, 'b': 0},))(samples)

fig, axs = plt.subplots(nrows=2, dpi=200)
for i, param in enumerate(['m', 'b']):
    axs[i].plot(jnp.squeeze(z[param]), label='z')
    axs[i].plot(unconstrained_parameters[param], ls='--', label='unconstrained')
axs[0].axhline(m_true, lw=1, color='k', label='true value')
axs[1].axhline(b_true, lw=1, color='k', label='true value')

axs[0].set_ylabel('m')
axs[1].set_ylabel('b')

for ax in axs:
    ax.legend(fontsize=8)
```
![image](https://github.com/user-attachments/assets/83d233b7-66e4-444b-a461-2d1ffacbb1e8)

For the **m** parameter, the values returned from calling `sampler._states['z']` are exactly the same as the samples returned from `sampler.get_samples()`, which are in the constrained space. I've plotted the unconstrained values for **m** which seem to be correct given that they take on negative values (which would be outside the support for the `TruncatedNormal` I defined). And `b` is the same since it's unconstrained anyways.

My guess is that this behavior is coming from lines 494-501 from the `infer.mcmc.py` file,
https://github.com/pyro-ppl/numpyro/blob/c8a09908552ec90192e89b3d495b376e2038284b/numpyro/infer/mcmc.py#L494C9-L501C34
```python
        if len(site_values) > 0 and jnp.shape(site_values[0])[0] > 0:
            if self._jit_model_args:
                states[self._sample_field] = postprocess_fn(
                    states[self._sample_field], args, kwargs
                )
            else:
                states[self._sample_field] = postprocess_fn(states[self._sample_field])
        return states, last_state
```
since it's calling `postprocess_fn` on `states` (`last state` is in the unconstrained space though), and the `postprocess_fn` is no longer the identity function at this point.

If this is the intended behavior (and I'm not totally misunderstanding something), would it be possible to update the docs to highlight that `z` is actually in the **constrained space**?

Thanks again for all the work you put into this package!

**Comment by fehiepsi** [comment]
Sorry for tthe confusion. HMCState.z is in unconstrained space, but the values we collect in MCMC.run is transformed. Please update the docs if you see something unclear.

**Comment by soichiro-hattori** [comment]
@fehiepsi : Thanks for the quick response!
I see. So is there a way to access `HMCState.z` (in the unconstrained space) after `MCMC.run`? Or is the recommended approach to just use the `unconstrain_fn` to transform them?
