### ISSUE TITLE
MCMC returns no samples when model contains deterministic variables only

### ISSUE THREAD

**Issue by hessammehr** [pyro-ppl/numpyro#1911]
# Steps to reproduce

```python
from jax import numpy as jnp
from numpyro import sample, deterministic, distributions as dist

def test_model():
    x = deterministic('x', jnp.array([1.0, 2.0]))

mcmc = MCMC(NUTS(test_model), num_warmup=1000, num_samples=1000)
    mcmc.run(random.PRNGKey(0))
    samples = mcmc.get_samples()

samples # {}
mcmc.print_summary() # ERROR
```

# Expected behaviour
`samples` should contain `x`, an array of shape `(1000, 2)`.

# Observed behaviour
`samples` is `{}`. Unrelated to this, `mcmc.print_summary()` is not able to deal with `samples` being empty.

```
in print_summary(samples, prob, group_by_chain)
    296 summary_dict = summary(samples, prob, group_by_chain=True)
    298 row_names = {
    299     k: k + "[" + ",".join(map(lambda x: str(x - 1), v.shape[2:])) + "]"
    300     for k, v in samples.items()
    301 }
--> 302 max_len = max(max(map(lambda x: len(x), row_names.values())), 10)
    303 name_format = "{:>" + str(max_len) + "}"
    304 header_format = name_format + " {:>9}" * 7

ValueError: max() iterable argument is empty
```

**Comment by fehiepsi** [comment]
Re `print_summary`: we can just simply not print anything if there are no samples to summarize from.

Re model with only deterministic: currently, we skip postprocessing if there are no latent variables in the model. The main reason is: for vectorized postprocess_fn, we need some values to vmap over. To fix the issue, we can replace [vmap(postprocess_fn)](https://github.com/pyro-ppl/numpyro/blob/c110053eb95f5398f11b93ce3efa21de4559012c/numpyro/infer/mcmc.py#L406) by a call `ensure_vmap(postprocess_fn)`, where `ensure_vmap` can take empty argument. Something like
```
def ensure_vmap(fn, batch_size=None):
    def wrapper(x):
        x_arrays = jax.tree.flatten(x)[0]
        if len(x_arrays) > 0:
            return vmap(fn)(x)
        else:
            assert batch_size is not None
            return jax.tree.map(lambda x: jnp.broadcast_to(x, (batch_size,) + jnp.shape(x)), fn(x))

    return wrapper
```

**Comment by hessammehr** [comment]
@fehiepsi Thanks for the thorough and very helpful explanation (as always). I wasn't able to change the behaviour by making the modification suggested to `mcmc.py` (see diff below) even when passing `chain_method='vectorized'` and `num_chains=2`.

<img width="1293" alt="image" src="https://github.com/user-attachments/assets/12b7a57f-5f05-48cd-bc76-11aa6d908a44">

**Comment by fehiepsi** [comment]
Yoy can enable postprocessing for that case by removing this check https://github.com/pyro-ppl/numpyro/blob/5c2eafa4d7573d085895c6bb04ee4cff799df346/numpyro/infer/mcmc.py#L495

**Comment by hessammehr** [comment]
Now `postprocess_fn` seems to get called but this line seems to get called instead (`states` is `{}`):

https://github.com/pyro-ppl/numpyro/blob/5c2eafa4d7573d085895c6bb04ee4cff799df346/numpyro/infer/mcmc.py#L408

**Comment by fehiepsi** [comment]
Could you sync to master and apply the same logic?
