### ISSUE TITLE
Test batching rule for distributions

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#192]
To support parallel chains, we need to make sure that each piece of the code works well under `vmap`. Currently, there is no batching rule for `lax.cond`. Given that we rarely use `lax.cond` and it can be replaced by a `while_loop` or `np.where`, this work is possible now. But making the whole thing works at the same time might be error prone and hard to debug / review. So this PR splits the task into many steps, each should be on its own PR.

- [ ] Add batching test for dist construction, log_prob, and support transforms. We can test for the `potential_fn` generated by a model with a single sample statement.

**Comment by neerajprad** [comment]
The initial tasks are valuable in their own right, but before investing too much time on this, we should evaluate the following alternatives:

 - using `pmap` instead which may not require batching all of the primitives.
 - using sequential chains instead of parallel chaining. While this will be slower, for certain models / data sizes (specially if we are already saturating the GPU) it might be acceptable since we will also avoid recompilation costs.

**Comment by fehiepsi** [comment]
Yeah, that's a good idea. Personally, I would prefer using `pmap` because it resolves the problem of different trajectory length for each chain (which `vmap` won't). Not sure what is the current status of `pmap`. Let me dive into it a bit to see if it works now. I remember that there are some flags to enable `pmap` for CPU but last time I tried, things did not work.

> using sequential chains instead of parallel chaining. While this will be slower, for certain models / data sizes (specially if we are already saturating the GPU) it might be acceptable since we will also avoid recompilation costs.

Yes, either `vmap` or `pmap` works, we should support this feature. Users usually do not have multi-GPUs to use it (or they want to take the benefit of intra-op parallelism)

 > The XLA CPU backend supports intra-op parallelism (i.e. it can shard a single operation across multiple cores) but it does not support inter-op parallelism (i.e. it cannot execute independent operations concurrently across multiple cores). The XLA GPU backend is competitive with the standard TensorFlow implementation, sometimes faster, sometimes slower.

**Comment by fehiepsi** [comment]
Close because it might not need to test batching rule for distributions. Let's address related issues in separate PRs instead.
