### ISSUE TITLE
BNN example unusually slow on the GPU

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#204]
@martinjankowiak reported that the BNN example is very slow (~60x) slower on the GPU, with the latest jax/jaxlib. While some slowness is expected on small datasets, such a large difference probably points to a perf issue in JAX.

As a point for comparison, the GP example while slower on the GPU is in a similar ballpark (20s on CPU vs 30s on GPU), and is much faster than the CPU for larger N.

**Comment by fehiepsi** [comment]
Indeed, from our last discussion, many examples are slow in GPU. I guess we can isolate the source of slowness by first looking at the performance of `jit(potential_fn)(init_params)`.

**Comment by fehiepsi** [comment]
@neerajprad @martinjankowiak I just make a [benchmark](https://gist.github.com/fehiepsi/43e78b321d9f96ffd036244f1b727799) to compare performance of bnn in cpu and gpu. It seems that cpu is just way faster (70x faster) than gpu for those `matmul` operators on bnn dataset. So it is a problem of GPU (or XLA GPU), not our library. To me, this performance is expected. If you think that it is unexpected, then I'll ask some JAX dev about it. Otherwise, I think we can close this issue.

**Comment by martinjankowiak** [comment]
hmm i'm surprised the difference is so large. when i do timing comparisons using pytorch for similarly sized matmuls i find that cpu32 and cpu64 are about the same and that cuda32 is about 3x slower (so a difference but not a huge one).

**Comment by fehiepsi** [comment]
Yup, it is a good idea to test against GPU performance in other framework. I'll do that to see how difference they are.

**Comment by fehiepsi** [comment]
So with a similar setting, in my GPU, PyTorch took 105ms. Using torch.jit.trace, the time is reduced to 77ms. Because JAX took 35ms, JAX is 2x faster than PyTorch in this benchmark. In CPU, JAX is just way faster because the code is compiled to LLVM.

**Comment by neerajprad** [comment]
@fehiepsi - The timings that you see might be a bit misleading due to [asynchronous dispatch](https://jax.readthedocs.io/en/latest/async_dispatch.html). If you change your last line to `loop(w).block_until_ready()` and ensure that you aren't hitting the cache, the timings for the gpu and cpu are nearly the same. So this is probably not what would explain the 70x difference. I think it is more likely to be some inefficiency in a cuda kernel.

**Comment by fehiepsi** [comment]
@neerajprad The notebook actually prints out the result of `loop` function. I add `block_until_ready` and still get the same result (as long as the input `w` has constant shape).

**Comment by neerajprad** [comment]
> I add block_until_ready and still get the same result (as long as the input w has constant shape).

That's quite strange. I am consistently seeing 160-170ms for both CPU and GPU ([notebook](https://nbviewer.jupyter.org/gist/neerajprad/8408bb8e9ac1d689f4abad0048d415b7). What CUDA version and jaxlib version are you using?

**Comment by fehiepsi** [comment]
That looks like they are compiling speed. Changing `config.update('jax_platform_name', 'cpu')` also requires you reset the kernel. Maybe `%reset -sf` does not reset the kernel? I am using `jaxlib 0.1.21` install from [this section](https://github.com/google/jax#pip-installation), cuda 100.

**Comment by neerajprad** [comment]
> Changing config.update('jax_platform_name', 'cpu') also requires you reset the kernel. 

Thanks, @fehiepsi. I'm able to replicate your results now. The compile time is 3-3.5 X slower for CUDA, and the actual computation seems to be 100-120 X slower on my machine.

**Comment by neerajprad** [comment]
Maybe I'm doing something wrong though because CPU also seems to be much faster even with `N, D_X, D_H = 5000, 3000, 5000`.

**Comment by fehiepsi** [comment]
I saw that in my system too. Can't guess why. :D

**Comment by fehiepsi** [comment]
Regarding the performance of BNN in GPU, I have sent this benchmark to JAX team. Hopefully, inference time in GPU will be improved in the next versions of jax/jaxlib.

**Comment by fehiepsi** [comment]
> CPU also seems to be much faster even with N, D_X, D_H = 5000, 3000, 5000

It seems that CPU XLA cached constant values, so we get good performance in CPU. When I make things not constant, the benchmark results are as expected (CPU is much slower than GPU).
```python
import jax
from jax import jit, lax, numpy as np
jax.config.update('jax_platform_name', 'cpu')

def fn(w):
    return np.sum(X * w)

@jit
def loop(w):
    def body_fn(i, val):
        w = val[0]
        # return w, fn(w) will make it fast in CPU
        return w - 0.001, fn(w)

    w, f = lax.fori_loop(0, 1000, body_fn, (w, 0.))
    return f

X = np.ones((1000, 1000))
w = np.ones((1000, 1000))
loop(w).block_until_ready()
import time
tic = time.time()
loop(w).block_until_ready()
print("time: ", time.time() - tic)
```

I would like to close this issue because the behavior here seems expected. When I change `num_data` to `10000`, I can see that GPU is a few times faster than CPU for bnn example. To me, this is just evidence for the observation that JAX CPU is so fast with small arrays.
