### ISSUE TITLE
Implement IAF autoguide

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#214]
Given that we will have IAF implemented soon, it is time to make some auto guide using it. So far, I guess that we just need to mimic the current [implementation](https://github.com/pyro-ppl/pyro/blob/dev/pyro/contrib/autoguide/__init__.py#L618) in Pyro.

- [x] Implement AutoDiagonalNormal (mainly to sketch out necessary ingredients for IAF one)
- [x] Implement AutoIAFNormal

**Comment by neerajprad** [comment]
@fehiepsi - are you working on this?

**Comment by fehiepsi** [comment]
I am making Delta distribution. Do you intend to work on auto normal?

**Comment by neerajprad** [comment]
Sure, I can try to sketch out auto normal in the meantime.
