### ISSUE TITLE
Support for Scipy.Sparse

### ISSUE THREAD

**Issue by timothyb0912** [pyro-ppl/numpyro#221]
Support for sparse matrices and sparse matrix operations would allow "easy" (i.e. in essentially native numpy/scipy) automatic differentiation in situations where users rely on sparse matrices to avoid dataset size limitations.

Note that this was a greatly requested feature in Autograd, and such support would be greatly appreciated!
https://github.com/HIPS/autograd/issues/80

**Comment by neerajprad** [comment]
We rely on JAX for automatic differentiation, and it will be best to take this up with the JAX devs. I see that there is already an issue tracking this (https://github.com/google/jax/issues/765) that you could add to.
