### ISSUE TITLE
example notebooks do not format correctly on website

### ISSUE THREAD

**Issue by jamestwebber** [pyro-ppl/numpyro#231]
Probably not obvious to the author, so I thought I'd mention this. It looks like the notebook markdown does not get properly formatted when being compiled by sphinx (specifically it doesn't recognize lists).

I'm not familiar enough with sphinx to diagnose the issue, but it might just be a matter of adding [nbsphinx](https://nbsphinx.readthedocs.io) to the build process so it can handle ipynb files better?

**Comment by fehiepsi** [comment]
Thanks @jamestwebber ! It seems that the issue has been resolved at https://github.com/pyro-ppl/numpyro/pull/215 but the website is not updated yet. We'll make sure that it is updated before the next release.

**Comment by neerajprad** [comment]
Closing since this should be fixed now. Please reopen if you see any other formatting issues with the tutorials.
