### ISSUE TITLE
How to use residual based boostrap with numpyro?

### ISSUE THREAD

**Issue by Nathan-Furnal** [pyro-ppl/numpyro#245]
Hi, 

Basically I'm trying to sample from residuals of univariate time series in order to create prediction intervals for the series.

Is there an easy way to do that in Numpyro?

Thanks!

**Comment by fehiepsi** [comment]
Hi @Nathan-Furnal , could you elaborate or provide some literature regarding what you want to achieve?

**Comment by Nathan-Furnal** [comment]
@fehiepsi Sure ! I'd like to have a fast and reliable way to create nonparametric prediction intervals. 

Something similar to what is described in Hyndman's book on [prediction intervals](https://otexts.com/fpp2/prediction-intervals.html). If the uncorrelated assumption is broken, we can fall back on [block bootstrap](https://otexts.com/fpp2/bootstrap.html) 

In an [Uber paper](https://arxiv.org/pdf/1709.01907.pdf) there was also talk about providing confidence intervals but since it's in a Bayesian Network framework and in a different setup, I'm wondering how much could be used in a more simple time series forecast problem.

Thanks!

**Comment by fehiepsi** [comment]
Hi @Nathan-Furnal, looking like you want to do something like [this section](http://pyro.ai/numpyro/time_series_forecasting.html#Forecasting). There for each set of sampled parameters, we predict future outcomes for the next 34 time steps. I see that it is similar to bootstrap method. After collecting future predictions for all sets of parameters (in NumPyro, this step is pretty fast using `jax.vmap`), we compute the prediction interval using [HPDI](https://en.wikipedia.org/wiki/Credible_interval). Does that align with what you want?

**Comment by fehiepsi** [comment]
You can use [quantile](https://docs.scipy.org/doc/numpy/reference/generated/numpy.quantile.html) to get quantiles (instead of HPDI) of prediction. Given a value, I think you can compute the probability by assuming that predictions (at a given time step) follow a Normal distribution and use `np.exp(Normal(mean, std).log_prob(value))`. If you want something like "inverse" quantile, I guess you can use
```
inv_quantile = sum(value > preds) / len(preds)
```

**Comment by Nathan-Furnal** [comment]
@fehiepsi Thank you very much for your explanations ! My problem is that I expected the parameters of the residuals not to follow a Normal distribution or at least I'm not willing to take that step yet. Were I to sample over many series, do you think I could use numpyro to define an empirical distribution for the priors ? Thanks again for your time

**Comment by fehiepsi** [comment]
We usually assign equal probability for each prediction. If you want to compute probability of 1 prediction, then it is `1 / len(preds)`. You can use the above `inv_quantile` formula as cumulative distribution function. So if you want to compute probability of an interval (a, b), then it is `sum(preds > a & preds < b) / len(preds)`. But I guess what you want is a bit more complicated.

**Comment by Nathan-Furnal** [comment]
@fehiepsi Great ! I'll try some things of my own then, thank you for your help!

**Comment by fehiepsi** [comment]
@Nathan-Furnal Thanks for keeping the discussion so far! Please make a feature request if there is something missing in NumPyro. :) Btw, we have a [forum](https://forum.pyro.ai/) for discussions like this. Posting there would bring attention from community so you might get some better answers for your questions.
