### ISSUE TITLE
fori_collect does not work with non-float arrays

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#252]
The issue is ravel_pytree which calls `vjp` and does not work with int32 or bool arrays. As such, `fori_collect` will fail if the default identity transform is used.

**Comment by fehiepsi** [comment]
@neerajprad  how about we patch [this function](https://github.com/google/jax/blob/master/jax/api.py#L952) to do nothing? it is used to raise errors if inputs of `vjp` are int/bool. Or we can create a `vjp` + `ravel_pytree` version which does not have this check. I prefer using `patch` but would like to hear your opinion too.
