### ISSUE TITLE
Usage of the `scale` effect handler?

### ISSUE THREAD

**Issue by lumip** [pyro-ppl/numpyro#254]
The `scale` effect handler was introduced in commit [495cdbf2](https://github.com/pyro-ppl/numpyro/commit/495cdbf2c696ca9568e5a074e5b45d2e9eb2784c) but varies from other handlers in that it doesn't accept a callable `fn` argument on construction but only the scaling factor. Therefore I'm unsure how to use `scale` with any given model...

I'm suspecting that the `fn` argument should be there but has gone missing. Could it be that the implementation of `scale` has been taken more or less directly from Pyro's `ScaleMessenger` (where `Messenger` classes generally don't take callables in the constructor, however the `scale` convenience function does) and escaped the necessary adoptions for numpyro?

**Comment by neerajprad** [comment]
> Could it be that the implementation of scale has been taken more or less directly from Pyro's ScaleMessenger (where Messenger classes generally don't take callables in the constructor, however the scale convenience function does) and escaped the necessary adoptions for numpyro?

I think that's right, thanks for bringing this up. I think this was intended to be used as a context manager, but there is no reason why this shouldn't be a regular effect handler. I'll fix this shortly.
