### ISSUE TITLE
Slow compilation of while loop when using AutoIAFNormal

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#259]
In `test_autoguide.py::test_logistic_regression[AutoIAFNormal]`, almost 25 seconds out of 32 odd seconds are taken to just compile the while loop. We also cannot use `fori_collect` because of #252.

**Comment by fehiepsi** [comment]
I can confirm this behaviour. The `body_fn` is fast to run and compile but `fori_loop` takes a lot of time. This is likely JAX bug but we need to isolate the reason.

**Comment by neerajprad** [comment]
Thanks for taking a look, @fehiepsi. It is probably some combination of stax NNs and our effect handling stack. I'll try to isolate this soon.

**Comment by neerajprad** [comment]
This issue seems to be much worse with the current JAX master actually. Even `AutoDiagonalNormal` which current compiles in a second seems to take a really long time on JAX master.

**Comment by fehiepsi** [comment]
> Even AutoDiagonalNormal which current compiles in a second seems to take a really long time on JAX master.

I guess this might be related to the change of JAX fori_loop in JAX master (but I haven't test it yet). We need to either jit fori_loop for jit body_fn and use native loop. According to a benchmark which I did [here](https://github.com/google/jax/issues/852#issuecomment-508899753), jit fori_loop is fastest. We might jit fori_loop by default in `numpyro.util.fori_loop`, WDYT?

**Comment by neerajprad** [comment]
> We might jit fori_loop by default in numpyro.util.fori_loop, WDYT?

I see that the issue is still open. I think jitting the for loop seems a good fix on our end!

**Comment by neerajprad** [comment]
Hmm..I'm not sure if the JAX issue that you linked to would handle this, because in this case it looks like the compilation time without JIT is itself higher for some reason. We can check once the upstream issue is fixed.

**Comment by fehiepsi** [comment]
Yes, there are some other scenarios which trigger compiling time. E.g. [in here](https://github.com/google/jax/issues/772), by random change in computation of that function, the compiling time goes from 2s to 1m. I think something relevant is happening here and it is hard to detect. :(

**Comment by fehiepsi** [comment]
@neerajprad Do we still need to follow up with this issue? We have solved it with `jit(fori_loop)`. In case we need to follow up, can you update the title to better reflect the issue?

**Comment by neerajprad** [comment]
I am fine with closing this but we should check this and file an issue upstream in JAX if this isn't resolved with https://github.com/google/jax/issues/852.
