### ISSUE TITLE
Refactor SVI api

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#274]
I think we can simplify the common procedure of svi by
- [x]  group `(opt_init, opt_update, get_params)` into one input

```
opt_init, opt_update, get_params = optimizers.adam(0.05)
svi_init, svi_update, svi_eval = svi(model, guide, elbo, opt_init, opt_update,
                                           get_params)
```
by
```
optim = optimizers.adam(0.05)
svi_init, svi_update, svi_eval, get_params = svi(model, guide, elbo, optim)
```
The reason is we usually don't work with opt_init, opt_update.
- [ ]  Merge the input `i, rng, opt_state` into `svi_state`, so that
    - svi_init(...) returns init state
    - svi_update(state, model_data, guide_data) returns new state
This way, users usually don't need to write a custom `body_fn` to train SVI. In addition, using `fori_collect` will be easier (similar to `sample_kernel` in hmc).
- [x]  ~Allow `fori_collect` to return `collection` and last `val`. The reason is we don't want to collect of svi_states during the way (for memory reason). Only last state and losses are enough.~ **Solution:** use `lax.scan` instead.
- [x]  Use `get_params(svi_state)` in place of `constrain_fn(get_param(opt_state))`. We might have some args such as `get_params(svi_state, model_data, guide_data, )`. So users don't need to know what constrain_fn is when using `svi`.
- [x] We don't need to have `get_params` arg in `autoguide.__init__(...)`. We only need to feed in the params got from `get_params(svi_state)`.
- [x] Maybe we can move `rng` of autoguide to `setup`
- [x] It would be nice to have something similar to `pyro.module(...)`. Currently, the logic to handle nn parameters is a bit complicated - (@neerajprad)
```
def guide(batch, **kwargs):
    encode = kwargs['encode']
    encoder_params = param('encoder', None)
    ...
    z_loc, z_std = encode(encoder_params, batch)

encoder_init, encode = encoder(args.hidden_dim, args.z_dim)
decoder_init, decode = decoder(args.hidden_dim, 28 * 28)
_, encoder_params = encoder_init(rng_enc, (args.batch_size, 28 * 28))
_, decoder_params = decoder_init(rng_dec, (args.batch_size, args.z_dim))
params = {'encoder': encoder_params, 'decoder': decoder_params}

opt_state, constrain_fn = svi_init(rng_init, (sample_batch,), (sample_batch,), params)
```
I think we can replace it by
```
def guide(batch, **kwargs):
    encode = module('encoder', encoder(hidden_dim, z_dim))
    z_loc, z_std = encode(batch)

sample_batch = binarize(rng_binarize, train_fetch(0, train_idx)[0])
opt_state, constrain_fn = svi_init(rng_init, (sample_batch,), (sample_batch,), params)
```

Above are my thoughts during some experiences with the current svi api. With those, I think svi api will be pretty clean. What do you think @neerajprad ?

**Comment by neerajprad** [comment]
> I think we can simplify the common procedure of svi by
> 
> * group `(opt_init, opt_update, get_params)` into one input
> 
> ```
> opt_init, opt_update, get_params = optimizers.adam(0.05)
> svi_init, svi_update, svi_eval = svi(model, guide, elbo, opt_init, opt_update,
>                                            get_params)
> ```
> 
> by
> 
> ```
> optim = optimizers.adam(0.05)
> svi_init, svi_update, svi_eval, get_params = svi(model, guide, elbo, optim)
> ```
> 
> The reason is we usually don't work with opt_init, opt_update.
> 
> * Merge the input `i, rng, opt_state` into `svi_state`, so that
>   
>   * svi_init(...) returns init state
>   * svi_update(state, model_data, guide_data) returns new state
>     This way, users usually don't need to write a custom `body_fn` to train SVI. In addition, using `fori_collect` will be easier (similar to `sample_kernel` in hmc).


I think grouping the relevant variables into a state namedtuple can clean up the code. 

> * Allow `fori_collect` to return `collection` and last `val`. The reason is we don't want to collect of svi_states during the way (for memory reason). Only last state and losses are enough.

Why not just use lax.scan for this? If we need to reimplement this (e.g. for progress bar updates), I would suggest calling it `fori_scan` or something instead which will be cleaner than adding another optional arg to `fori_collect` (we can abstract out the common part into a separate function).

> * Use `get_params(svi_state)` in place of `constrain_fn(get_param(opt_state))`. We might have some args such as `get_params(svi_state, model_data, guide_data, )`. So users don't need to know what constrain_fn is when using `svi`.
> * We don't need to have `get_params` arg in `autoguide.__init__(...)`. We only need to feed in the params got from `get_params(svi_state)`.

This seems like a good idea too, and worth a separate refactor.

> * It would be nice to have something similar to `pyro.module(...)`. Currently, the logic to handle nn parameters is a bit complicated
> 
> ```
> def guide(batch, **kwargs):
>     encode = kwargs['encode']
>     encoder_params = param('encoder', None)
>     ...
>     z_loc, z_std = encode(encoder_params, batch)
> 
> encoder_init, encode = encoder(args.hidden_dim, args.z_dim)
> decoder_init, decode = decoder(args.hidden_dim, 28 * 28)
> _, encoder_params = encoder_init(rng_enc, (args.batch_size, 28 * 28))
> _, decoder_params = decoder_init(rng_dec, (args.batch_size, args.z_dim))
> params = {'encoder': encoder_params, 'decoder': decoder_params}
> 
> opt_state, constrain_fn = svi_init(rng_init, (sample_batch,), (sample_batch,), params)
> ```
> 
> I think we can replace it by
> 
> ```
> def guide(batch, **kwargs):
>     encode = module('encoder', encoder(hidden_dim, z_dim))
>     z_loc, z_std = encode(batch)
> 
> sample_batch = binarize(rng_binarize, train_fetch(0, train_idx)[0])
> opt_state, constrain_fn = svi_init(rng_init, (sample_batch,), (sample_batch,), params)
> ```

Again, this can be a nice refactor! 

@fehiepsi - All of these are great recommendations! My only suggestion would be for us to attempt these as separate refactors wherever possible, so that we can incrementally make the code better! I'll be happy to help with any part of this.

**Comment by fehiepsi** [comment]
> Why not just use lax.scan for this?

That's exactly what we need. Thanks for pointing that out! I wonder if `lax.scan` creates extra overhead for the purpose of differentiation, but even in that case, we can create `fori_scan` as you suggested.

> My only suggestion would be for us to attempt these as separate refactors wherever possible, so that we can incrementally make the code better! I'll be happy to help with any part of this.

Yup! I just edit the topic as separate tasks. Feel free to pick any point which you want to work on. It would be great if you can come up with a nice implementation of `module` handler. Right now, I just have a vague idea that it might return a partial function (e.g. `partial(encoder_apply, params)`) and we need to feed in an input_shape arg `encode = module('encoder', encoder(hidden_dim, z_dim), input_shape)` so that if there is no `params` field at `encoder` site (e.g. `guide` is not yet wrapped by `substitute` handler), `encoder_init(random_state, input_shape)` will create that `params` field. I imagine that the situation is more complicated than that but we can leverage these works to handlers. :)
