### ISSUE TITLE
mcmc is so slow with the new version of JAX

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#288]
The new [refactor of JAX](https://github.com/google/jax/issues/587#issue-430578895) makes our MCMC extremely slow. Tests in `test_mcmc` are really slow too. This is high priority because otherwise, we can't run tests in Travis.

**Comment by neerajprad** [comment]
@fehiepsi - Is it the same issue as you have linked? If so, we can probably go back to our earlier hack in `fori_collect`.

**Comment by fehiepsi** [comment]
@neerajprad I tried it but it does help. The issue happens in `test_warmup_adapter` so I guess the issue lies at `lax.cond`. Still investigating...

**Comment by fehiepsi** [comment]
Hopefully, the only problem is the one at https://github.com/google/jax/issues/1239.

**Comment by mattjj** [comment]
Sorry for the disruption! I think google/jax#1240 should fix this, but please let me know if it doesn't (by opening an issue on the JAX issue tracker with a new repro, since AIUI the repro in google/jax#1239 has been fixed).

**Comment by fehiepsi** [comment]
Hi @mattjj , thanks for a quick fix! With that PR, our inference algorithms are working now. Indeed, it seems that everything is about 2x faster than before. E.g. our `test_mcmc` tests took 240s with jax=0.1.41 but only took 142s with that PR. Whoa!!!
