### ISSUE TITLE
Separate out primitives from the handlers module

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#292]
We can name this module `primitives.py` or `pyro.py`. This will help point out which statements are pyro primitives vs regular functions. e.g. `pyro.sample`, `pyro.param`, etc.

**Comment by fehiepsi** [comment]
Agreed! Having to use `from numpyro.handlers import sample, param` is inconvenient, especially for users who is familiar with `pyro.sample`, `pyro.param`,... I think we should expose them to `numpyro.__init__` as in pyro.

**Comment by neerajprad** [comment]
> Agreed! Having to use from numpyro.handlers import sample, param is inconvenient, especially for users who is familiar with pyro.sample, pyro.param,...

Yes, I'm just refactoring this. Now they can use `numpyro.sample`. I thought that putting a module called `pyro` might be problematic when working with pyro imported, but this should provide a similar way to access numpyro primitives.

**Comment by fehiepsi** [comment]
Thanks @neerajprad ! The import section is more reasonable now. I still see it a bit overwhelm. Let's see how things change when we refactor SVI/MCMC to classes. :)
