### ISSUE TITLE
Bullets are not rendered in notebooks

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#319]
It seems like bullets are not rendered in our notebook tutorial. e.g. http://pyro.ai/numpyro/bayesian_regression.html

Let us fix it for the next release.

<img width="717" alt="Screen Shot 2019-09-04 at 10 44 52 AM" src="https://user-images.githubusercontent.com/1762463/64278220-140faf80-cf01-11e9-9a64-a4d9eb275440.png">

**Comment by fehiepsi** [comment]
I think this is a duplication of #231. We have fixed this issue but haven't updated the website yet.

**Comment by fehiepsi** [comment]
Basically, we need an empty list before starting Markdown list.
```
Here is a list:  # need an empty line after this line

- item 1
- item 2
```

**Comment by neerajprad** [comment]
Closing this as duplicate. Let us track this in #231, and make sure that the tutorials are correctly updated before release.
