### ISSUE TITLE
Do not use private utility functions from JAX

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#32]
For convenience, we are currently using many JAX functions that haven't been exposed publicly like `_promote_args`. Let us reimplement (and customize these functions as needed) in `util.py`, so that we don't incur dependency on private functions that might be removed or whose API changed without notice.

**Comment by fehiepsi** [comment]
It seems that we are no longer use private utils from JAX except in `contrib` and `util`, so I close this issue.
