### ISSUE TITLE
Thin out distribution wrappers and aggregate in continuous.py

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#36]
We can thin out our distribution wrappers, and let numpy do the dispatching, e.g. `np.log` or `np.exp` will be correctly dispatched by numpy even though they will incur a small dispatch cost. Like `discrete.py` we can move all the lightly wrapped continuous distribution into `continuous.py`.

**Comment by fehiepsi** [comment]
Let's focus on #82 instead.
