### ISSUE TITLE
Run MCMC with multiple chains without modifying any environment flags

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#364]
Users would like to be able to run MCMC without having to set the `--xla_force_host_platform_device_count` flag in advance. In certain cases, it is not possible to do this, e.g. in a repl or notebook environment. 

cc. @null-a who will need this for brmp.

Related JAX issue - https://github.com/google/jax/issues/1408.

**Comment by fehiepsi** [comment]
As a temporary solution, I think we can do this automatically when users import `numpyro` (by setting `os.environ` as in our examples).

**Comment by neerajprad** [comment]
Hmm..I was under the impression that we had to set the environment flag before loading JAX, but seems like this should work even after the fact by setting this through `os.environ`. Is that true? In that case, we can just set/unset it as needed.

**Comment by fehiepsi** [comment]
In addition, I also think that it is good to use `cpu` by default. So my proposal is:
1. set cpu + max device_count by default
2. make some utilities: `numpyro.util.set_backend('gpu')` to change backend, `numpyro.util.set_num_devices(...)` to change the number of required devices.

**Comment by fehiepsi** [comment]
> Is that true? In that case, we can just set/unset it as needed.

yes, it is true

**Comment by fehiepsi** [comment]
I am not sure what intra-op is useful for, because I didn't observe much different in covtype data (in cpu).

**Comment by neerajprad** [comment]
I think it will be safer to retain the XLA defaults since that's what would be most rigorously tested by the XLA and JAX devs. My concern was that this wasn't even possible to do once we imported JAX. But if it is, we can just do this in the MCMC class itself without changing anything else.

**Comment by neerajprad** [comment]
Oh sorry, I missed this "The only requirement is we set it at the top of the script (i.e. no np.ones(3) is called until we set these flags". That we certainly can't guarantee.

**Comment by fehiepsi** [comment]
Even if we don't change the defaults, having those utilities is helpful (rather than having to remember the name of those flags - I find myself always go to examples folder to copy those flags to notebooks :D).

**Comment by neerajprad** [comment]
I agree we should have those utilities. I'm also fine changing the default to CPU and setting num devices (though hopefully the num device argument won't carry over when we change the backend to GPU) to CPU count, but it will be good to confirm with the JAX devs just so that we don't end up with a default config that causes other hard-to-debug issues.
