### ISSUE TITLE
Rename rng -> rng_key 

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#377]
I think this was a case of sloppy naming that we began with, and has percolated throughout the code base. Since we only ever pass the `PRNGKey`, the argument name should reflect that. Thanks to @fritzo for calling this out while reviewing the generic PR in Pyro.

**Comment by fehiepsi** [comment]
Do you mean `seed` is different from `key` (i.e. random state)? If so, I agree!

**Comment by neerajprad** [comment]
I think either `rng_seed` or `rng_key` should be fine, wherever we are currently using the `rng` argument name. Or simply even just `key` if the rng part is obvious from context.

**Comment by fehiepsi** [comment]
I would prefer `rng_key`. In numpy, np.random.seed arg is an `int`, while `np.random.RandomState` is an int array.

**Comment by fritzo** [comment]
While I'm not familiar with JAX rng architecture, I find `rng_state` more understandable than `rng_key`.

**Comment by neerajprad** [comment]
> I find rng_state more understandable than rng_key.

JAX's PRNG does not have a state though, so I think this will probably cause some confusion. It uses a hash function to map this "key" (+ some counter say `1..n` for generating vectorized samples) to a random sample in Int256. The key is explicitly split by users to generate new samples, unlike traditional PRNGs which internally update their state.
