### ISSUE TITLE
Support `parallel` argument to predictive

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#398]
In Pyro MCMC predictive, we have a `parallel` keyword to resolve the plate issue https://github.com/pyro-ppl/pyro/issues/1995. JAX supports batching out of the box. However,
using vmap for a large num_samples and a large model will consume [much more memory](https://github.com/google/jax/issues/1113). I faced memory issue in training bnaf for covtype dataset and using `lax.map` solves the problem.

Probably we should change the keyword to `sequential` to avoid confusion.

**Comment by neerajprad** [comment]
That's a good idea, we should have this.
