### ISSUE TITLE
vectorized elbo does not work with beta bernoulli model

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#414]
As observed in #413, when running SVI in beta bernoulli with num_particles=2, we get the error
>  NotImplementedError: Forward-mode differentiation rule for 'while' not implemented

This seems like a JAX issue but we need to isolate the bug to report upstream.

**Comment by TuanNguyen27** [comment]
@fehiepsi from a quick glance the error traces to here: https://github.com/google/jax/blob/master/jax/interpreters/ad.py#L217

**Comment by fehiepsi** [comment]
Thanks, @TuanNguyen27 ! I believe that this error comes from while_loop of gamma sampler in JAX, but it is a bit hard to make a small repro script. Anyway, this issue should not block your PR, feel free to complete it and mark failing tests as xfail.

**Comment by fehiepsi** [comment]
Just want to put a context: this issue is tracked at https://github.com/google/jax/issues/1789.

**Comment by fehiepsi** [comment]
This is fixed in the latest jax release.
