### ISSUE TITLE
Add tutorial for models with missing data

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#415]
We should able to run MCMC for models with missing data in NumPyro because NumPyro supports improper priors through `param` primitive. This is also a good chance to illustrate that NumPyro supports improper priors.

Related issues in other repos:
+ Pyro: https://github.com/pyro-ppl/pyro/issues/1106, https://github.com/pyro-ppl/pyro/issues/1676
+ brmp: https://github.com/pyro-ppl/brmp/issues/43, https://github.com/pyro-ppl/brmp/issues/44

**Comment by neerajprad** [comment]
I think the issue in Pyro refers to allowing a way to support models with sample statements of the kind `pyro.sample('obs', dist(..), obs=[some partially observed tensor])`, where we condition on the observed data and impute the missing entries. Could you clarify how having `param` statements in MCMC help this use case?

**Comment by fehiepsi** [comment]
I will use the most naive way to impute those missing data. For example,
```
def model(x, y):
    loc = sample('loc', Normal(0, 1))
    scale = sample('scale', LogNormal(0, 1))
    isnan = onp.isnan(x)
    x_impute = param('x_impute', np.zeros(isnan.sum()))
    x = ops.index_update(x, onp.nonzero(isnan), x_impute)  # update x
    sample('x', dist.Normal(loc, scale), obs=x)
    ...
```
I am not sure how to make this possible with `pyro.sample`...

**Comment by neerajprad** [comment]
I see - I think your method will give us the ML estimate for the missing values.

> I am not sure how to make this possible with pyro.sample.

I am not quite sure, but maybe sampling from the `dist.Normal(..)` might work:

```
    x_impute = sample('x_impute', dist.Normal(loc, scale))
    x = ops.index_update(x, onp.nonzero(isnan), x_impute)  # update x
    sample('x', dist.Normal(loc, scale), obs=x)
```

In any case, I think this will make for a good tutorial.

**Comment by fehiepsi** [comment]
> the ML estimate for the missing values

Actually, those imputed values will have priors `dist.Normal(loc, scale)` because the statement
```
sample('x', dist.Normal(loc, scale), obs=x)
```
acts on the "merged" x (x_notnan & x_impute).

The script in your comment will double log_prob of `x_impute`.

**Comment by neerajprad** [comment]
Interesting. No, you are absolutely right about the double counting. What I wrote above is incorrect unless we are doing masked observes. Actually, your original solution is quite clever! This will make for an interesting tutorial, look forward to it.
