### ISSUE TITLE
Suggested changes to diagnostics / summary

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#424]
- [x] As in Pyro, we should have the summary function split into two components - one that returns a dict object `d[site_name] = {'mean': .., 'std', ..}` and a `print_summary` function which formats this into a table. The idea is that other examples can make use of the summary function and add to the diagnostics if needed.
 - [ ] Output other metadata like when the model is compiling and when it is sampling. This is specially useful when we run multiple chains and it is not clear whether all the time is being taken to compile the model or if it is the sampling part that is taking time. Related #309. 
 - [x] Divergence is useful information and we should record it by default and have it be emitted as part of the `summary` information.

**Comment by fehiepsi** [comment]
Probably we should rename `summary` to `print_summary` before the release?

About the second point, until JAX/XLA supports doing it, we can recommend users to set `num_warmup=1, `num_samples=0` if they are curious.

About divergence information, we can easily support it before the release. Are you working on this?

**Comment by neerajprad** [comment]
None of these are release blockers and can make it into the next minor release. Just the documentation / making sure that the interface is reasonable is important for this release.

**Comment by fehiepsi** [comment]
I moved the description for the remaining issue to #309, which is quite related. Let's close this for now.
