### ISSUE TITLE
[FR] supporting `pyro.factor` primitive

### ISSUE THREAD

**Issue by hzyjerry** [pyro-ppl/numpyro#449]
Hi, I'm currently doing research on agent modeling, and I'm wondering if the functionalities of `pyro.factor` is in the roadmap of numpyro?

The pyro repo has some [great examples](https://github.com/pyro-ppl/pyro/blob/dev/examples/rsa/generics.py) covering the use case I have in mind.

**Comment by fehiepsi** [comment]
Hi @hzyjerry, we will support that feature soon.

**Comment by hzyjerry** [comment]
Thanks! The latest PR looks great
