### ISSUE TITLE
Mark documentation for internal utility functions as experimental

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#452]
We should start making a distinction between a thinner more stable public API, and internal subroutines that we are freer to change. For instance, some of our internal utilities like `hmc` and `potential_energy` are exposed in the documentation. We should mark the interfaces for these as experimental, since for such internal functions, we would like to be able to break backward compatibility when needed to support other features. e.g. #451.

**Comment by fehiepsi** [comment]
I think this is addressed in #455.
