### ISSUE TITLE
Misc refactoring in mcmc util

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#453]
While trying to support #441, I noticed a few things that can be refactored in `mcmc.util`:

 - [x] Abstract out getting the potential function / constrain function from `initialize_model`. This part does not need to be vectorized and needs to be done just once.
 - [x] It seems that `prototype_params` will be reused if valid in the vectorized case, and seems like a bug. We can either not use `prototype_params` in the vectorized case or vectorize this too (in that case, the point above isn't valid). Another option is to just remove `prototype_params` to keep the interface simple.
 - [x] Clearly mark in the docstring which functions are vectorizable, i.e. accept vectorized `rng_key` arguments.
 - [x] Mark all interfaces in this class as experimental currently. 
 - [x] Change all `*args, **kwargs` to `model_args=(), model_kwargs=None` to keep the function signatures consistent. I think we should only expose `*args, **kwargs` for user facing interface for functions that have no or very few arguments.
 - [ ] Rename `contrain_fn` --> `transform_to_constrained`, `transform_fn` --> `transform_sites`. Suggestions welcome.
 - [x] ~Add `skip_params` options to `init_to_*` methods (currently only `init_to_uniform` seems to have it.~ Not needed, we only need this internally for `_init_to_uniform` and `_init_to_median`, as @fehiepsi pointed out.

**Comment by fehiepsi** [comment]
> Abstract out getting the potential function / constrain function from initialize_model. This part does not need to be vectorized and needs to be done just once.

Agreed! We have built all low-level functionalities to make things work during development. Now, we have got a simplified interface. I think it is a good idea to revise low-level ones - if they make things clearer or faster.

> It seems that prototype_params will be reused if valid in the vectorized case

I'll review this carefully. I can recall that it is tricky to have proper logic here.

> Add skip_params options to init_to_* methods

This arg is used internally. I don't think we need to expose it.

> Change all *args, **kwargs to model_args=(), model_kwargs=None to keep the function signatures consistent.

Agreed!

> Rename contrain_fn --> transform_to_constrained, transform_fn --> transform_sites.

Most users won't touch these utilities (unless they want to work with functional hmc) so feel free to improve their names. Your suggestions look good to me.

**Comment by neerajprad** [comment]
@fehiepsi - The first one is more to help with the other PR. In general, I'm not too concerned about complexity in the low level APIs, and I don't think we need to spend time simplifying it, unless it is needed to make it easier to refactor and support other features on top.

**Comment by fehiepsi** [comment]
I guess the remaining task: renaming `contrain_fn --> transform_to_constrained, transform_fn --> transform_sites` is not necessary anymore. Feel free to create a new issue for that purpose. :)
