### ISSUE TITLE
numpyro equivalent to pymc3's Deterministic

### ISSUE THREAD

**Issue by jwschroeder3** [pyro-ppl/numpyro#462]
First of all, thank you for this excellent work!

I'm trying to implement the Finnish horseshoe prior (Piironen, J., and Vehtari, A., 2017).
Edit: I should credit Michael Betancourt for his implementation of the Finnish HS [here](https://betanalpha.github.io/assets/case_studies/bayes_sparse_regression.html).
I'm able to calculate the horseshoe as follows:

```python
def finnish_horseshoe(M, m0, N, var, half_slab_df, slab_scale2, tau_tilde, c2_tilde, lambd, beta_tilde):
    
    tau0 = (m0/(M-m0) * (np.sqrt(var)/np.sqrt(1.0*N)))
    tau = tau0 * tau_tilde
    c2 = slab_scale2 * c2_tilde
    lambd_tilde = np.sqrt(c2 * lambd**2 / (c2 + tau**2 * lambd**2))
    beta = tau * lambd_tilde * beta_tilde
    
    return(beta)

def model(y_vals,
          design_mat,
          N, # number of y_vals
          slab_df=1,
          slab_scale=1,
          expected_large_covar_num=10):

    a_prior = dist.Normal(10., 10.)
    a = numpyro.sample("alpha", a_prior)

    # update from pymc3
    half_slab_df = slab_df/2
    variance = y_vals.var()
    slab_scale2 = slab_scale**2
    hs_shape = (design_mat.shape[1],)
    
    beta_tilde = numpyro.sample('beta_tilde', dist.Normal(0., 1.), sample_shape=hs_shape)
    lambd = numpyro.sample('lambd', dist.HalfCauchy(1.), sample_shape=hs_shape)
    tau_tilde = numpyro.sample('tau_tilde', dist.HalfCauchy(1.))
    c2_tilde = numpyro.sample('c2_tilde', dist.InverseGamma(half_slab_df, half_slab_df))
    
    bC = finnish_horseshoe(M = hs_shape[0],
                                    m0 = expected_large_covar_num,
                                    N = N,
                                    var = variance,
                                    half_slab_df = half_slab_df, 
                                    slab_scale2 = slab_scale2,
                                    tau_tilde = tau_tilde,
                                    c2_tilde = c2_tilde,
                                    lambd = lambd, 
                                    beta_tilde = beta_tilde)

    C = np.dot(design_mat, bC)
    mu = a + C

    sig_prior = dist.Exponential(1.)
    sigma = numpyro.sample('sigma', sig_prior)
    return numpyro.sample('obs', dist.Normal(mu, sigma), obs=y_vals)
```

The problem I have is that the sampled values of `bC` are not tracked during sampling. In pymc3 I can track samples of `bC` using `pm.Deterministic`. Is there a numpyro equivalent, or would I have to implement a new distribution class?

Thanks for your help!

**Comment by fehiepsi** [comment]
Hi @jwschroeder3 , currently, you can record `bC` using

```
def model():
    ...
    bC = ...
    numpyro.sample("bC", dist.Delta(bC), obs=bC)
    ...
...
posterior = mcmc.get_samples()
bC = numpyro.infer.Predictive(model, posterior).get_samples(jax.random.PRNGKey(0), *args)
```
IMO `bC` is not a latent site to sample, so it should belong to posterior predictive phase. Is it too verbose? We can also provide a primitive `numpyro.deterministic("bC", bC)` to replace `numpyro.sample("bC", dist.Delta(bC), obs=bC)`, but we would like to hear your opinion first. :)

**Comment by jwschroeder3** [comment]
Cool.
I definitely see what you're saying about bC not being a latent site, and it belonging in posterior predictive. I will plan to record bC this way in the future. 

I am of the opinion that for people to quickly pick up numpyro, a `deterministic` primitive would be very helpful. It has the benefit of being more obvious than using posterior predictive sampling to grab variable like `bC` out of the model.

**Comment by fehiepsi** [comment]
Thanks for your opinion! I'll make a PR for it soon.

About the above proposal, I just meant to have `numpyro.deterministic("bC", bC)` replace `numpyro.sample("bC", dist.Delta(bC), obs=bC)` because it is:
+ not obvious why we have `obs=bC` here (though with extra thoughts, we can see that it tells MCMC: `bC` is not a latent variable and this site's log_prob is zero).
+ shorter than using `dist.Delta` for simple transforms, e.g.
```
logits = ...
# dist.Delta would require two lines of codes
probs = logit_to_prob(logits)
numpyro.sample("probs", dist.Delta(probs), obs=probs)
# deterministic only requires 1 line
numpyro.deterministic("probs", logit_to_prob(logits))
```
+ easier to interpret.

We will think more about should we record those values in MCMC at the end of the sampling phase. The reason is doing this would require us to rerun the model again to get those deterministic values. Though it is pretty fast to do so for models I worked with, I would like to wait for having more feedback on the performance of NumPyro before introducing that overhead. :)

Btw, if you think NumPyro is slow for any of your models, please let us know. That information would be very useful for us!

**Comment by jwschroeder3** [comment]
I agree with everything you've stated above. Thanks for your help. FYI, so far I'm thrilled with numpyro's performance, but I'll be sure to let you know if I have problems in the future.

**Comment by martinjankowiak** [comment]
@fehiepsi before you submit a PR we should perhaps think about this a bit more. if possible, we don't want numpyro primitives to drift from pyro primitives. so if we do it in numpyro we should also do it in pyro.

@neerajprad @fritzo @eb8680 thoughts on adding a primitive to help record deterministic computations in programs?

**Comment by neerajprad** [comment]
This has been something that users have often requested for Pyro. @karalets just brought this up last week. So far, the workaround has been to use `sample('record', dist.Delta(z), obs=z))`, at least in MCMC, but I think this should work for SVI too. I think the easiest way to implement this would be to alias this pattern (as @fehiepsi noted above) using a `deterministic` primitive. Then this will be available in the trace and from `Predictive` (for MCMC). Looking to hear others thoughts on this.

**Comment by eb8680** [comment]
> thoughts on adding a primitive to help record deterministic computations in programs?

If it's only a one-line alias for a `sample` call, that seems fine.  Would we have to make breaking changes to any existing validation logic for edge cases in SVI?

**Comment by fehiepsi** [comment]
@eb8680 I think that we don't have breaking changes because this only introduces additional observation sites to the trace. Do you have an example in mind?

**Comment by eb8680** [comment]
> Do you have an example in mind?

I was thinking there might be assertions somewhere in our SVI validation logic about guide sites not being observed that would be triggered if there was a `deterministic` call in a guide for some reason, but I didn't actually find any.

**Comment by FlorianWilhelm** [comment]
I would also love to see `deterministic` primitive in numpyro as it exists in Pyro now. The last comment of @neerajprad seems to be wrong as version 0.2.3 is already released but does not contain `deterministic`. I think it should rather read 0.2.4.
