### ISSUE TITLE
Regression in fori_collect when progress bar disabled

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#475]
I am finding that with progress bar disabled, `fori_collect` is not returning the same results for the sparse regression example:
 - [x] It fetches the wrong `init_state` and runs adaptation twice.
 - [ ] Results returned when progress bar is enabled/disabled are different.
 - [x] When progress bar is disabled, the time taken is almost twice. This seems to be a regression from earlier when disabling the progress bar was much faster.

**Comment by fehiepsi** [comment]
The difference of results when progbar disabled/enabled is explained in https://github.com/pyro-ppl/numpyro/pull/470#issuecomment-560989836. So I close this for now.
