### ISSUE TITLE
Disable jit with custom kernel

### ISSUE THREAD

**Issue by hzyjerry** [pyro-ppl/numpyro#485]
Hi numpyro team,

For my use case, I would like to have the kernel perform some inner optimization (e.g. `scipy.optimize`). Something similar to

```python
def kernel(prior, data):
   opt = optimize(prior)
   log_p = -distance(opt, data)
   numpyro.factor(log_p)
mcmc = MCMC(NUTS(kernel))
```
However, I couldn't get it working because `numpyro` passes in `Traced<ConcreteArray(3.7071364)>with<JVPTrace(level=1/0)>` or `Traced<ShapedArray(float32[])>with<JVPTrace(level=2/0)>,` as arguments to kernel, which conflicts with the external optimizer (in this case `scipy.optimize`).

I assume that `numpyro` is trying to `jit` the kernel for speed improvements. In this case, would it be possible to avoid using `jit`? Would it end up compiling the entire `scipy` library?

**Comment by neerajprad** [comment]
@hzyjerry - It is not just that `jit` wouldn't work, if we used some scipy function implemented in C, the execution will not be visible to the jax tracer, and we won't be able to compute gradients either, which HMC/NUTS will need. Depending on what the optimizer is doing, do you think it is possible to implement it using JAX primitives (for instance, you can take a look at some of the optimizers in `numpyro.optim`)? I don't know about the problem that you are working on, but even if you re-implement the optimizer, I'm not sure what HMC would give you in your example - what is the target distribution that you are looking to sample from?

**Comment by hzyjerry** [comment]
Hi, @neerajprad thanks a lot for the swift response!

I'm currently using `scipy.optimize.fmin_l_bfgs_b` to optimize, which may be (unfortunately) a hard requirement because other optimizers seem to work a lot worse. Yet, I do know analytical method to compute gradient (`d opt / d prior`) post-hoc. Would it be possible to still let external optimizers do the job, and then substitute in the gradient for JAX?

The use case would be to model human agents as some noisily rational actors. We're currently assuming that the distribution could be arbitrary.

**Comment by hzyjerry** [comment]
Is there any assumption numpyro makes that prefers the target distribution to be known? Would love to learn more about the mechanisms behind.

**Comment by neerajprad** [comment]
@hzyjerry - The implementation in numpyro doesn't make any assumptions, other than those implicit in HMC. That is to say, that you should be able to define a function which when given a state, returns the potential energy for that state, which is the unnormalized negative log density of your target distribution (we can just use the negative log joint density in a typical bayesian inference setting). The other relevant assumptions are that we should be able to compute the gradient of this function w.r.t. the state variables, and you shouldn't have discrete state variables.  If these are satisfied, we can use it to generate samples from the target distribution. 

> Is there any assumption numpyro makes that prefers the target distribution to be known?

The target distribution doesn't need to be known (that's probably the reason why we are running MCMC!), but we do need that we should be able to evaluate the unnormalized density w.r.t. this target distribution and able to compute gradients for HMC. 

> Yet, I do know analytical method to compute gradient (d opt / d prior) post-hoc. 

I think you can define a custom jax primitive that computes this derivative. But the higher level question is - what are you looking to get from MCMC in your model? Is this a probabilistic model?

**Comment by hzyjerry** [comment]
Thanks for the guide!

> what are you looking to get from MCMC in your model? Is this a probabilistic model?

Yes, I think agent modeling (https://agentmodels.org/) is a fun and active research field. The common problem setup is we assume a probabilistic human decision model (e.g. human runs some form of approximal optimization) with unknown parameters. We estimate these parameters from behavioral data.

For anyone that's interested, here's [one relevant paper](https://arxiv.org/abs/1711.02827) that I really like.

From what I can see, the tricky part of integrating these formulations with PPL is they don't have easy-to-compute gradients. E.g. the original implementation for the paper I linked uses general Metropolis-Hasting algorithm (instead of HMC, NUTS provided by numpyro).

**Comment by fehiepsi** [comment]
@hzyjerry I think you might be interested in [this issue in JAX](https://github.com/google/jax/issues/1400). Until LBFGS is implemented there, you can try other JAX optimizers as @neerajprad suggested to see if things work as your expectations. If you don't want to use AD in JAX, you can also write a [custom transform with jvp rule](https://jax.readthedocs.io/en/latest/jax.html#jax.custom_transforms). Then I think NUTS will work (if not, please let us know). FYI, I have used NUTS successfully with ode integrators. You can get an idea about how to define custom transform and gradient at [ode source code](https://github.com/google/jax/blob/master/jax/experimental/ode.py#L377).

**Comment by hzyjerry** [comment]
@neerajprad may be one more reason to support Metropolis-Hasting ([old issue](https://github.com/pyro-ppl/pyro/issues/179)) :)

**Comment by hzyjerry** [comment]
@fehiepsi very cool! Thanks for the pointer

**Comment by neerajprad** [comment]
Thanks for the links, @hzyjerry. We haven't had too many requests for metropolis hastings, mostly because it fares badly in high dimensions, and a vanilla task specific version should be really easy to implement. If you would like to implement it, I think you'll find all the distributions and other utilities already in place for your in numpyro. Once you have that, we'll be happy to work with you to see if there is a way to have a more general version that we can incorporate in numpyro.

**Comment by fehiepsi** [comment]
I think it deserves a "contributed welcome"/"good first issue" feature request. This would be a nice reference for users who want to construct an MCMCKernel. @hzyjerry would you mind making a new issue for your feature request?

**Comment by hzyjerry** [comment]
@fehiepsi makes sense. I'm lacking some starter tasks that are less domain-specific than the one I'm working on. I can see two directions:

1. Metropolis-Hasting Kernel that does not require gradient
2. MCMCKernel that allows user-specified gradient via `custom_transform`

I think I can make an issue once I find some good starting tasks.

**Comment by fehiepsi** [comment]
@hzyjerry I think the first one is a really nice direction! I am not sure if the second direction is necessary. You can define your model/potential_fn with `custom_transform` operators, then you can use HMC/NUTS for that model/potential_fn freely, e.g.
```
@jax.custom_transform
def f(x):
    return x ** 2

jax.defvjp(f, lambda g, ans, x: g * np.sin(x))

def potential_fn(x):
    return f(x)
```
Then you can use `potential_fn` with HMC/NUTS. Here `potential(3) == 9`, and `grad(potential)(3) == sin(3)`.

I guess you have another idea in mind?

**Comment by hzyjerry** [comment]
Hi @fehiepsi I'd like to follow up on this and seek your advice :) 

My solution has converged to implementing a custom JAX primitive. I have tried using `numpyro.optim` but the compilation is still stalling (could be because the optimization is too complicated with its own JAX computation graphs).

I'm currently stuck at adding XLA translation rules. I believe it's similar to your previous issue at https://github.com/google/jax/issues/451. I'm wondering if you were able to resolve it by adding XLA translation rules?

The outline of my primitive looks like 
```python
untracable_primitive_p = jax.core.Primitive('untracable_primitive')

def untracable_primitive(x):
    return untracable_primitive_p.bind(x)

def untracable_primitive_impl(x):
    # main body of optimization that take in onp.array
    # we don't want jax to trace this function, which takes very very long time to compile
    return onp.array(x)

untracable_primitive_p.def_impl(untracable_primitive_impl)


untracable_primitive_p.def_abstract_eval(lambda x: x)


jax.interpreters.ad.defvjp(untracable_primitive_p, lambda g, x: 1 * g)
```

**Comment by hzyjerry** [comment]
another solution would be to run numpyro without `@jit` the kernel, since the gradient can be computed by hand. 

The speed slowdown would be very tolerable for me. But it seems that `numpyro.kernel` is tightly integrated with `jit` and `lax` and it would be difficult to disable jit compile?

**Comment by fehiepsi** [comment]
@hzyjerry I think you can define a custom primitive following [gamma sampler](https://github.com/google/jax/blob/master/jax/random.py#L925) pattern. Note that `_gamma_impl` returns a tuple there so that `xla.lower_fun` works.

**Comment by hzyjerry** [comment]
@fehiepsi Thanks for the pointer! That PR looks amazing.

I'm still trying to get my example to work. I wonder if the `_gamma_batching_rule` is a crucial step in getting it working?

My cryptic error message looks like `RuntimeError: Invalid argument: Expected array argument for input tensor operand of gather op, but got (f32[10,10]).`

**Comment by hzyjerry** [comment]
Actually was able to get it working by following your PR line by line. Thanks for the help.
