### ISSUE TITLE
Numerical issues in distributions.util.poisson

### ISSUE THREAD

**Issue by nkaimcaudle** [pyro-ppl/numpyro#491]
Hi, seems the function distributions.util.poisson encounters numerical issues when rate parameter is too high, in the code I see exp(-rate) which will go to zero as rate parameter increases.

Here is my code showing the issue

```
import jax.numpy as np
import jax.random as random
import numpy as onp
import numpyro
from numpyro.distributions.util import poisson

mu = rate = 1000
N = 2**12

A = onp.random.poisson(lam=mu, size=N)
print( A.mean() )  ###prints around 1000.

key = random.PRNGKey(64)
B = poisson(key, rate=rate, shape=(N,))
print( B.mean() ) #prints arounds 87.
```

**Comment by fehiepsi** [comment]
Thanks for the report!

You are right, the algorithm in numpyro is only good for a small rate. For a large rate, I think we need to implement another algorithm e.g. [the one in wikipedia](https://en.wikipedia.org/wiki/Poisson_distribution#Generating_Poisson-distributed_random_variables) or [the transformed rejection method in numpy](https://github.com/numpy/numpy/blob/master/numpy/random/src/distributions/distributions.c#L537).

We'll address this issue for the next release. :)
