### ISSUE TITLE
Import MCMC into Arviz

### ISSUE THREAD

**Issue by nkaimcaudle** [pyro-ppl/numpyro#492]
Hi, not sure if this belongs in NumPyro or Arviz but in my relatively simple model when I import the data into Arviz InferenceData it takes a long time to calculate.

I am running a ZeroInflatedPoisson model and trying to estimate the gate parameter on pre-defined groups. In this toy example I have 16k observations and 4 groups. On my Ryzen 3900X the MCMC stage takes just 8secs whereas bringing the data into ArviZ takes over 100secs. 4 chains with num_warmup=1000 and num_samples=1000.

I can see all my cpus/threads are in use whilst az.from_numpyro() is run, all 24 running ~30%

I updated from the master branch recently for both NumPyro and ArviZ.

```
import numpy as onp

import jax
import jax.numpy as np
import jax.random as random
from jax.scipy.special import logsumexp, expit

import numpyro
import numpyro.distributions as dist
from numpyro.infer import MCMC, NUTS, Predictive, log_likelihood
numpyro.set_host_device_count(4)
numpyro.set_platform('cpu')
import arviz as az
import time
import pandas as pd


print( 'jax', jax.__version__ )
print( 'numpyro', numpyro.__version__ )
print( 'arviz', az.__version__ )


N = 2**14
idx_group = random.randint(random.PRNGKey(1), shape=(N,), minval=0, maxval=4)
A = random.normal(random.PRNGKey(1), shape=(N,))*12
A = np.abs(A).astype('int32')
group_probs = np.array([0.2, 0.9, 0.5, 0.65])
p = random.bernoulli(random.PRNGKey(2), shape=(N,4), p=group_probs)
p = p[np.arange(N),idx_group]
y = A*p



def model(y=None):
    gate = numpyro.sample('gate', dist.Normal(0, 5))
    with numpyro.plate('groups', 4):
        gate_group = numpyro.sample('gate_group', dist.Normal(0, 5))
    rate = numpyro.sample('rate', dist.HalfNormal(10))
    gate_ = expit(gate+gate_group[idx_group])
    obs = numpyro.sample('obs', dist.ZeroInflatedPoisson(gate_, rate), obs=y)
    
t0 = time.perf_counter()
rng_key, rng_key_prior, rng_key_pred = random.split(random.PRNGKey(32), num=3)
mcmc = MCMC(NUTS(model, target_accept_prob=0.9), 1000, 1000, num_chains=4, progress_bar=False)
mcmc.run(rng_key, y=y, extra_fields=('z', 'energy', 'diverging'))
print( 'mcmc', time.perf_counter() - t0)

t0 = time.perf_counter()
idata = az.from_numpyro(mcmc)
print( 'idata', time.perf_counter() - t0)
print( az.summary(idata) )
```

output
```
jax 0.1.53
numpyro 0.2.3
arviz 0.5.1
mcmc 8.581132674999026
idata 104.77336627499972
                mean     sd  hpd_3%  hpd_97%  ...  ess_sd  ess_bulk  ess_tail  r_hat
gate          -0.192  2.131  -4.124    3.897  ...   266.0     264.0     404.0   1.01
gate_group[0]  1.676  2.131  -2.447    5.581  ...   266.0     264.0     405.0   1.01
gate_group[1] -1.445  2.132  -5.510    2.521  ...   256.0     265.0     413.0   1.01
gate_group[2]  0.313  2.131  -3.792    4.235  ...   266.0     264.0     396.0   1.01
gate_group[3] -0.243  2.131  -4.363    3.674  ...   267.0     265.0     406.0   1.01
rate           9.702  0.032   9.639    9.763  ...   935.0     939.0     940.0   1.01

[6 rows x 11 columns]
```

**Comment by fehiepsi** [comment]
Hi @nkaimcaudle , I think that 100s is a more reasonable value here. Due to https://jax.readthedocs.io/en/latest/async_dispatch.html the python code can run when the actual compiled code has not finished its job yet. Could you call mcmc.print_summary() before recording the time in numpyro? If it still shows that arviz is slow, then there is indeed a problem somewhere.

Is 100s slow in your opinion? Btw, if you see any related question, you can post it here. :)

**Comment by nkaimcaudle** [comment]
Ok, so essentially the sampling takes 100s but Jax was returning control to python whilst it was still running, but az.from_numpyro() had to wait for the sampling to actually complete. 

Indeed if I add in a print_summary() statement after run and before the time counter then it shows 100s or so. And the arviz function is then very quick.

Noted

**Comment by fehiepsi** [comment]
Yup. :)

**Comment by fehiepsi** [comment]
@nkaimcaudle Let me close this for now. If this confusion happens again in the future, we'll add a note to either docs or readme to clarify. :)

**Comment by vanAmsterdam** [comment]
I'd like to +1 for adding this to some docs / readme
I didn't know about this behavior from jax; I was running into the same issue and have spent quite some time trying to profile the code

**Comment by fehiepsi** [comment]
Sure, we'll add a note into `run` method. Do you want to contribute? :)

**Comment by vanAmsterdam** [comment]
something like this #611 ?

**Comment by fehiepsi** [comment]
Thank @vanAmsterdam for addressing this issue!
