### ISSUE TITLE
[FR] sample adaptive MCMC

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#497]
Requested by @martinjankowiak ! This is a nice sampler to have. For me, this is a good chance to validate our MCMCKernel interface.

Reference: https://papers.nips.cc/paper/9107-sample-adaptive-mcmc.pdf

If the performance is good, we need to push this to Pyro too.

**Comment by fehiepsi** [comment]
@martinjankowiak If you want to implement this, please go ahead! Otherwise, I can work on this this weekend.

**Comment by martinjankowiak** [comment]
i don't have time to do this right now but happy to look at a PR!
