### ISSUE TITLE
link the NeurIPS 2019 workshop paper in readme?

### ISSUE THREAD

**Issue by mattjj** [pyro-ppl/numpyro#512]
After a quick skim I didn't notice an obvious link to [the NeurIPS 2019 workshop paper](https://openreview.net/forum?id=H1g1niFhIB) in the README. It'd be great to include, especially because it has benchmarks!

WDYT?

cc @jekbradbury

**Comment by neerajprad** [comment]
Good idea, thanks for the reminder. We'll add a link to the README shortly.

**Comment by fehiepsi** [comment]
Yeah, we will add it soon. Actually a better reference would be https://arxiv.org/abs/1912.11554 where benchmark results are updated and have a link to `benchmarks` branch to replicate results. cc @neerajprad
