### ISSUE TITLE
Reuse mcmc.run() without recompilation on a pickled mcmc

### ISSUE THREAD

**Issue by VincentBt** [pyro-ppl/numpyro#514]
I'm trying to get additional samples fastly from an  `MCMC` object which I saved and then recovered later. I didn't manage to do it fast i.e. without the compilation phase (which is really long for my model). Is it something numpyro can currently do?

I also tried on the eight_schools example, with the same arguments (y and sigma) to mcmc.run both before saving and after loading, and I tried with or without `jit_model_args=True`. There is always a compilation phase, which is not here if I don't pickle.

I can give a code example if needed.

**Comment by neerajprad** [comment]
The compilation for NUTS inference will always be triggered for a new session even if it is the exactly same model. In your case, even within the same session, I think just saving and loading the model will change its `id`, and Python will consider it a different object and recompile everything. Unfortunately, I do not think there is a way to save compiled JAX assets to be reusable across different sessions. If JAX provided something like `torch.jit.save/load`, we could support it. What is your use case, if I may ask?

**Comment by VincentBt** [comment]
My model is really slow (especially the compilation, which takes ~80% of the total time) and I simply want to be able to get additional samples fast, in case I don't have enough effective samples.
I don't know if it answers your question.

**Comment by VincentBt** [comment]
and more importantly, I have to run mcmc.run() many times (the fitting is done for many subjects and I also use different models) so I need to save the objects somewhere.

**Comment by neerajprad** [comment]
> My model is really slow (especially the compilation, which takes ~80% of the total time) 

If you could share your code, we can try to see why compilation is so slow. 

> and I simply want to be able to get additional samples fast, in case I don't have enough effective samples.

This is currently only possible if you would like to draw multiple samples within the same session, but I see that you are looking to do this on your reloaded model which won't work for the reasons I mentioned earlier. Let us try to see why compilation is slow first, because that might be more easily addressable.

**Comment by fehiepsi** [comment]
> we can try to see why compilation is so slow

Agreed! This is a more realistic approach for now.

**Comment by vanAmsterdam** [comment]
I have a different use case for the same problem of reusing a model for different data without recompilation. It's a measurement error / latent variable model with global and local parameters. To get N samples from the posterior predictive over new data, we will need to run separate MCMC runs with the same model, but with global parameters substituted from N different posterior samples from the initial run.

If each of these runs requires recompilation, this will slow things down a lot. E.g. stan does not have this issue. Or are there tricks / other things to do this? I've experimented with running multiple mcmc chains in the posterior mode and using different initialization values for the global parameters, and then masking the global parameters out to the MCMC sampler, but that didn't work. Also I can make a big model that basically copies this model N times, but that takes very long to compile.

Minimal example:

```
import jax
import numpyro
from jax import numpy as np, random
import numpy as onp
from numpyro.distributions import Normal, BernoulliLogits, HalfNormal
from numpyro.infer.mcmc import MCMC, NUTS

def model(x,y=None):
    b_z_x = numpyro.sample('b_z_x', HalfNormal(2.5)) # for model identification
    b_z_y = numpyro.sample('b_z_y', Normal(0, 5))
    mu_y  = numpyro.sample('mu_y',  Normal(0, 5))
    with numpyro.plate('obs', x.shape[0]):
        zhat = numpyro.sample('zhat', Normal(0,1))
        # sample proxy
        numpyro.sample('obs_x', BernoulliLogits(b_z_x*z), obs=x)
        # sample y
        numpyro.sample('obs_y', Normal(b_z_y*z+mu_y, 0.1), obs=y)

rng_key = random.PRNGKey(seed=1)
rng_key, rng_key_z     = random.split(rng_key)
rng_key, rng_key_x     = random.split(rng_key)
rng_key, rng_key_y     = random.split(rng_key)
rng_key, rng_key_mcmc1 = random.split(rng_key)

# data
n     = 1000
z     = Normal().sample(rng_key_z, sample_shape=(n,))
x     = BernoulliLogits(1*z).sample(rng_key_x)
y     = Normal(z, .1).sample(rng_key_y)

# model
def model(x,y=None):
    b_z_x = numpyro.sample('b_z_x', HalfNormal(2.5)) # for model identification
    b_z_y = numpyro.sample('b_z_y', Normal(0, 5))
    mu_y  = numpyro.sample('mu_y',  Normal(0, 5))
    with numpyro.plate('obs', x.shape[0]):
        zhat = numpyro.sample('zhat', Normal(0,1))
        # sample proxy
        numpyro.sample('obs_x', BernoulliLogits(b_z_x*z), obs=x)
        # sample y
        numpyro.sample('obs_y', Normal(b_z_y*z+mu_y, 0.1), obs=y)

kernel = NUTS(model)
mcmc   = MCMC(kernel, num_warmup=100, num_samples=100)
mcmc.run(rng_key_mcmc1, x,y)
samples_1 = mcmc.get_samples()
```

**Comment by fehiepsi** [comment]
@vanAmsterdam Does your global parameters have different shapes in each run? If your data/parameters have the same shape, then you can avoid [recompiling](https://github.com/pyro-ppl/numpyro/blob/master/test/test_mcmc.py#L535) by setting `MCMC(..., jit_model_args=True)`.

**Comment by vanAmsterdam** [comment]
Tried it and it makes a huge difference, thanks!

**Comment by vedal** [comment]
@fehiepsi Thanks for the tip to set `jit_model_args=True`. However, I tried it on the [Time Series Forecasting](http://pyro.ai/numpyro/time_series_forecasting.html) example, and it gives shape errors. Do you have any idea what the reason for this could be?
Error:
```ValueError: Axis size 4 does not match leading dimension of shape (80,)```

**Comment by fehiepsi** [comment]
Hi @vedal, I think it is a bug, thanks for catching it!

> mcmc.run() only seems to utilize one CPU, while mcmc.get_samples() utilize all in parallel

I guess `mcmc.run` runs in parallel in background due to [async dispatch](https://jax.readthedocs.io/en/latest/async_dispatch.html). `get_samples` is pretty cheap and does not involve numeric operators.

**Comment by fehiepsi** [comment]
Going back to this issue, I don't think there will be further actions we can take here. Currently, we added supports for pickling mcmc objects, avoid recompiling for multiple runs, and greatly improve the compiling time. Hope that they partly resolve the topic issue. Pickling a compiled object is not yet supported in jax, so please reopen the issue if anyone thinks we can take some actions here.
