### ISSUE TITLE
Create support for MaskedDistribution

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#520]
Refer to the discussion in https://forum.pyro.ai/t/hmm-like-model-with-sequences-of-different-lengths/1507.

**Comment by TuanNguyen27** [comment]
I'm interested in helping out with this !

**Comment by neerajprad** [comment]
@TuanNguyen27 - That's great. You could take a look at Pyro's [MaskedDistribution](https://github.com/pyro-ppl/pyro/blob/dev/pyro/distributions/torch_distribution.py#L227) and [distribution.mask](https://github.com/pyro-ppl/pyro/blob/dev/pyro/distributions/torch_distribution.py#L147) method. Let us know if you need any help.

**Comment by fehiepsi** [comment]
@TuanNguyen27 Did you have a chance to work on this feature? If you want, I can make a PR for this. I need to use this distribution to test out some codes.

**Comment by TuanNguyen27** [comment]
ah, please go head, i have't had time to work on this :)
