### ISSUE TITLE
Sequential Sampling Strategy

### ISSUE THREAD

**Issue by ross-h1** [pyro-ppl/numpyro#534]
Hi all,

I have a sequential problem where I need to build an initial model and then update this as new data arrives (eg. every month for monthly data) I know that sequential MCMC is a whole separate field but for a few reasons (mostly its generality) I want to find an efficient way of using NUTS in this context. Instead of the brute force method of re running the whole sampling from scratch on an expanding window of data (too slow), I’m considering:

1. Re using parameter estimates and mass matrix from initial sampler run to start the sampler on the expanded window of data and running fewer sampler iterations. 

What’s the best way to get the (dense) mass matrix and initialisation values from run t in to the sampler for run t+1?

Or:

2. Use posterior estimates from first run of the sampler as priors in the second run, and only the new data. Pymc3 has an ‘Interpolated’ Distribution type which samples from an fitted empirical histogram of data to do this. (Example here https://docs.pymc.io/notebooks/updating_priors.html) I guess this could be implemented in numpyro? Alternatively I guess I can use my prior distributions re parameterised based on samples from previous fit...

Again I want to use mass matrix and parameter estimates from previous fits, so need to set up the sampler with these somehow?

**Comment by fehiepsi** [comment]
Hi @ross-h1, your requests are interesting! For parameter estimates, I believe you can simply calculate it from posterior samples. For the mass matrix, you can do the same (by calculating (co)variance of your samples) or extract from the hidden attribute (`_last_state`).
```
mcmc._last_state.adapt_state.inverse_mass_matrix
```

To specify initial values, you can use [init_to_values](http://num.pyro.ai/en/stable/utilities.html#init-to-value) initialization strategy. We currently do not expose initial mass matrix to NUTS/HMC class (though it is exposed in the functional [hmc](http://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.hmc.init_kernel) api). The reason is we want to wait for a user request before doing so. :)

> re running the whole sampling from scratch

Tip: If your model does not have [local latent variables](http://pyro.ai/examples/svi_part_ii.html#Subsampling-when-there-are-only-local-random-variables), you can turn `jit_model_args` in [MCMC](http://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.MCMC) to True to avoid recompiling your model.

> Interpolated Distribution

In case you want to have this distribution, could you help us create a new feature request? It would be a very good first issue for NumPyro contributors. :)

**Comment by ross-h1** [comment]
Sounds like I have two requests then!

Had looked at hmc class, but i think the health warning in the docs is well founded!

So:

1. Expose Initial Mass Matrix in NUTS class

2. ’Interpolated’ distribution, although perhaps ‘Empirical’ may be a better name?

Very happy to help create a formal request!

**Comment by ross-h1** [comment]
Also, I think the mass matrix is calculated on unconstrained HMC parameters, not on the constrained versions returned in samples?

So need to get at these somehow…🤔

The mass matrix does seem to have a significant effect on sampling speed where there are correlations in the posterior, so worthwhile being able to tweak I think, especially for sequential sampling where the posterior changes very little from epoch to epoch. I start my model with 120 observations, and increase by 1 every month, so it’s less than 1% change every iteration… seems very wasteful to estimate the mass matrix every run of the sampler...

**Comment by fehiepsi** [comment]
> the mass matrix is calculated on unconstrained HMC parameters

It is a very good point! Yeah, the better option would be to extract from `mcmc._last_state`.

**Comment by ross-h1** [comment]
Yep, ok. Would be great to be able to build a new mass matrix though, so could perhaps update this after each set of samples, perhaps using some sort of exponential weighting… then plug back in for the next set of samples. This would provide maximum flexibility, and hopefully make NUTS more viable for sequential problems.

The mass matrix is only updated during warmup I think? This way could get the benefit of more samples contributing to the covariance matrix.

Also, how is warmup run using the hmc interface? Although its specified as a parameter in init_kernel,  I don’t see how to actually run the warmup iterations and therefore update the mass matrix…

**Comment by fehiepsi** [comment]
@ross-h1 You can run warmup using `fori_collect` in [this example](https://github.com/pyro-ppl/numpyro/blob/master/examples/stochastic_volatility.py#L91). To get the last warmup state, you can use `fori_collect(num_warmup, num_warmup, ..., return_last_val=True)` (sounds complicated... :D).

> The mass matrix is only updated during warmup I think?

Yes.

**Comment by neerajprad** [comment]
I think we would like to support (2) for active learning. @karaletsos has also brought up this issue before. I'm not the best informed on this topic, but the `Interpolated` distribution in pymc3 sounds promising. I'm not sure how well that works in high dimensions.

**Comment by theofanis** [comment]
I hate it to disrupt any discussion here, but I think I was mentioned in a comment here by mistake, which is totally fine, but @neerajprad probably wanted to notify someone else, so it's only fair to drop by and mention it and help you guys reach a resolution faster 😄.

Feel free to delete my comment - or I will gladly do it - after you see this and mention the person you initially intended to.

**Comment by vanAmsterdam** [comment]
> Tip: If your model does not have [local latent variables](http://pyro.ai/examples/svi_part_ii.html#Subsampling-when-there-are-only-local-random-variables), you can turn `jit_model_args` in [MCMC](http://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.MCMC) to True to avoid recompiling your model.

this has been here for some time, but can you explain why local latent variables mess with the jitting speed-up?

**Comment by fehiepsi** [comment]
> why local latent variables mess with the jitting speed-up?

Good point. I can't recall why I said so. The requirement should be: model args are jittable (e.g. they are `numpy.ndarray` or a tuple/dict of them).

**Comment by atlasd** [comment]
@ross-h1 did you figure out how to do this? I want to do the same thing, looking for an example.

**Comment by fehiepsi** [comment]
@atlasd This is supported in the last release. Please see an example [here](http://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.MCMC.post_warmup_state) and let us know what you think.

**Comment by MrinankSharma** [comment]
@fehiepsi hey, i'm also requesting that the initial mass matrix could be exposed! By the way, do you know how I can get the correspondence between elements of the mass matrix and the actual variables in my model?

**Comment by MrinankSharma** [comment]
> > how I can get the correspondence between elements of the mass matrix and the actual variables in my model
> 
> Good question! The correspondence is a bit ambiguous (depending on how jax converts a dictionary to a flatten array). That's why we haven't exposed `inverse_mass_matrix` to the api. To specify the initial inverse mass matrix, you can use [MCMC.init](http://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.MCMCKernel.init) to get the initial state, then you can replace the fields `adapt_state.inverse_mass_matrix`, `adapt_state.mass_matrix_sqrt` by your specified mass matrix. Then before running MCMC, setting [post_warmup_state](http://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.MCMC.post_warmup_state) to that modified initial state.
> 
> To get the ordering, you can use `z_flat, unravel_fn = jax.flatten_util.ravel_pytree(a_dict_of_latent_variables)`, then call `unravel_fn(inverse_mass_matrix)`.

Thanks for the quick response :) 

I'm not sure where to get the dictionary of latent variables from either to be honest. For example, I know that numpyro will convert my variables into unconstrained versions, so I'd guess I can't pass some of the posterior samples.

**Comment by fehiepsi** [comment]
I see. It will be stored in the `z` field of the initial state (obtained from kernel's init method, e.g. `NUTS.init(...)`).

**Comment by MrinankSharma** [comment]
> I see. It will be stored in the `z` field of the initial state (obtained from kernel's init method, e.g. `NUTS.init(...)`).

Thanks! managed to get it to work

**Comment by MrinankSharma** [comment]
> > how I can get the correspondence between elements of the mass matrix and the actual variables in my model
> 
> Good question! The correspondence is a bit ambiguous (depending on how jax converts a dictionary to a flatten array). That's why we haven't exposed `inverse_mass_matrix` to the api. To specify the initial inverse mass matrix, you can use [MCMC.init](http://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.MCMCKernel.init) to get the initial state, then you can replace the fields `adapt_state.inverse_mass_matrix`, `adapt_state.mass_matrix_sqrt` by your specified mass matrix. Then before running MCMC, setting [post_warmup_state](http://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.MCMC.post_warmup_state) to that modified initial state.
> 
> To get the ordering, you can use `z_flat, unravel_fn = jax.flatten_util.ravel_pytree(a_dict_of_latent_variables)`, then call `unravel_fn(inverse_mass_matrix)`.

another question -- actually it seems that `HMCAdaptState` doesn't allow for item assignment, so I can't directly set the matrix.

**Comment by fehiepsi** [comment]
You can use [_replace](https://docs.python.org/3/library/collections.html#collections.somenamedtuple._replace) method to change field values of a namedtuple. In this case, you can do `state = state._replace(adapt_state=state.adapt_state._replace(inverse_mass_matrix=...))`

**Comment by srivaschennu** [comment]
> @atlasd This is supported in the last release. Please see an example [here](http://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.MCMC.post_warmup_state) and let us know what you think.

Hi @fehiepsi ! I'm trying to get sequential MCMC working in numpyro using the example you linked.

Specifically, I would like to be able to save my MCMC object and update it with new data at a later point. I tried this using the `post_warm_up_state` approach, but I haven't been able to get it working. Here is my sample code:

```
import jax.numpy as jnp
import numpyro
from numpyro.infer import MCMC, NUTS
import numpyro.distributions as dist
import jax


def simple_model():
    p = numpyro.sample('p', dist.Beta(1, 1))
    numpyro.sample("successes", dist.Binomial(jnp.array([100]), p), obs=jnp.array([10]))


if __name__ == "__main__":
    for i in range(5):
        if i == 0:
            mcmc = MCMC(NUTS(simple_model), num_chains=4, num_warmup=2000, num_samples=2000)
            rng_key = jax.random.PRNGKey(0)
        else:
            mcmc.post_warmup_state = mcmc.last_state
            rng_key = mcmc.post_warmup_state.rng_key

        mcmc.run(rng_key)
        print(mcmc.get_samples()['p'].var(axis=0))

```

In the above, I'm trying to sequentially update the posterior 5 times in a loop, and would expect to see the posterior of the variable `p` to go down with consecutive updates. But this doesn't seem to happen, as can be seen in the output:

```
Posterior variance after first iteration: 0.00096065475
Posterior variance after second iteration: 0.00093164056
Posterior variance after third iteration: 0.000935624
Posterior variance after fourth iteration: 0.00090657204
Posterior variance after fourth iteration:0.0009206332
```

Could you please point me towards updating my model specification and code to achieve this? I'm on numpyro 0.8.0.

Thanks again for this amazing tool!

**Comment by fehiepsi** [comment]
Hi @srivaschennu I think the result is expected. Post warmup sample is just the last sample from the previous run. It does not help you update the posterior.

**Comment by srivaschennu** [comment]
> Hi @srivaschennu I think the result is expected. Post warmup sample is just the last sample from the previous run. It does not help you update the posterior.

Thanks for confirming @fehiepsi . Is it possible to update the posterior with new data currently with numpyro? Reading the the discussion in this issue didn't give me a clear idea. If not, this would be a really useful feature! :) Even if this is not currently supported out of the box, if you have suggestions on how to implement this, that would be very much appreciated! Thanks in advance!!

**Comment by fehiepsi** [comment]
I'm not sure what's the principle way to do. I guess one way is
```
def simple_model(c0=1, c1=1):
    p = numpyro.sample('p', dist.Beta(c0, c1))
    numpyro.sample("successes", dist.Binomial(jnp.array([100]), p), obs=jnp.array([10]))

mcmc = MCMC(NUTS(model), num_warmup=100, num_samples=100)
mcmc.run(PRNGKey(0))
old_samples = mcmc.get_samples()["p"]
c0, c1 = estimate_c0_c1_from_beta_samples(old_samples)
mcmc.run(PRNGKey(1), c0=c0_new, c1=c1_new)
new_samples = mcmc.get_samples()
```

**Comment by srivaschennu** [comment]
Ah great, thanks for the tip @fehiepsi !

**Comment by ColdTeapot273K** [comment]
@fehiepsi i'm trying to make online learning work with numpyro via `post_warmup_state` trick mentioned here and in the [doc](https://github.com/pyro-ppl/numpyro/blob/6b2353427c21792b5b4bfcb01192bb408ee9944f/numpyro/infer/mcmc.py#L504-L509)

But i encounter erroneous behaviour when the new data is from a shifted distribution. Namely, `std` turns to 0.0, `n_eff`, and perhaps `r_hat` give bogus values.

Example to reproduce, based on 8 schools:

```python
import numpy as np

J = 8

y = np.array([28.0, 8.0, -3.0, 7.0, -1.0, 1.0, 18.0, 12.0])

sigma = np.array([15.0, 10.0, 16.0, 11.0, 9.0, 11.0, 10.0, 18.0])
# %%
import numpyro
import numpyro.distributions as dist

# Eight Schools example


def eight_schools(J, sigma, y=None):
    mu = numpyro.sample("mu", dist.Normal(0, 5))

    tau = numpyro.sample("tau", dist.HalfCauchy(5))

    with numpyro.plate("J", J):
        theta = numpyro.sample("theta", dist.Normal(mu, tau))

        numpyro.sample("obs", dist.Normal(theta, sigma), obs=y)


from jax import random
from numpyro.infer import MCMC, NUTS

nuts_kernel = NUTS(eight_schools)

mcmc = MCMC(nuts_kernel, num_warmup=500, num_samples=1000)

rng_key = random.PRNGKey(0)

mcmc.run(rng_key, J, sigma, y=y)
mcmc.print_summary()
#                 mean       std    median      5.0%     95.0%     n_eff     r_hat
#         mu      4.43      3.18      4.22     -0.10      9.96    225.27      1.00
#        tau      4.22      3.02      3.39      0.89      7.94    116.48      1.01
#   theta[0]      6.41      5.70      5.51     -2.43     15.23    278.77      1.01
#   theta[1]      4.84      4.80      4.78     -3.66     12.00    454.28      1.00
#   theta[2]      3.68      5.23      3.87     -3.62     12.69    365.55      1.00
#   theta[3]      5.00      4.86      4.78     -2.45     12.87    384.35      1.00
#   theta[4]      3.46      4.70      3.84     -3.76     11.12    351.25      1.00
#   theta[5]      3.83      5.09      3.81     -4.24     11.49    432.41      1.00
#   theta[6]      6.78      5.33      6.13     -1.04     16.05    270.36      1.00
#   theta[7]      5.24      5.61      4.76     -2.30     14.99    442.56      1.00

# Number of divergences: 16

# %%
mcmc.post_warmup_state = mcmc.last_state
mcmc.run(mcmc.post_warmup_state.rng_key, J, sigma * 20, y=y * 20)
mcmc.print_summary()
#                 mean       std    median      5.0%     95.0%     n_eff     r_hat
#         mu      6.82      0.00      6.82      6.82      6.82      0.50       nan
#        tau      6.33      0.00      6.33      6.33      6.33      0.50       nan
#   theta[0]      9.73      0.00      9.73      9.73      9.73      0.50      1.00
#   theta[1]      0.76      0.00      0.76      0.76      0.76      0.50      1.00
#   theta[2]      2.65      0.00      2.65      2.65      2.65      0.50      1.00
#   theta[3]     12.03      0.00     12.03     12.03     12.03      0.50      1.00
#   theta[4]      4.80      0.00      4.80      4.80      4.80      0.50      1.00
#   theta[5]      5.27      0.00      5.27      5.27      5.27      0.50      1.00
#   theta[6]     19.74      0.00     19.74     19.74     19.74      0.50      1.00
#   theta[7]     11.27      0.00     11.27     11.27     11.27      0.50       nan

# Number of divergences: 0
```

Empirically i've discovered 
- the data shift size past certain threshold causes the behaviour, namely 
`mcmc.run(mcmc.post_warmup_state.rng_key, J, sigma * 2, y=y * 2)` doesn't produce the behaviour
- `num_samples` also affects the behavior

---

Where might be a problem and what could be a workaround?

**Comment by fehiepsi** [comment]
I'm not sure. I think you need to run adaptation again for new potential energy. You can use `init_to_value` to start with the last value from the previous inference result.

**Comment by martinjankowiak** [comment]
when the data changes a small amount the curvature of the posterior changes a small amount and the previous mass matrix will tend to perform well.

when the data changes a large amount the curvature of the posterior changes a large amount and the previous mass matrix will tend to perform poorly. the only way to get around this more-or-less robustly is to do more adaptation, either starting from scratch or using the previously learned mass matrix as a starting point.

**Comment by ColdTeapot273K** [comment]
> when the data changes a small amount the curvature of the posterior changes a small amount and the previous mass matrix will tend to perform well.
> 
> when the data changes a large amount the curvature of the posterior changes a large amount and the previous mass matrix will tend to perform poorly. the only way to get around this more-or-less robustly is to do more adaptation, either starting from scratch or using the previously learned mass matrix as a starting point.

I think i've figured one way to do it. Seems to be working. I've simplified the example a bit:

```python
# %%
import numpy as np

J = 8

y = np.array([28.0, 8.0, -3.0, 7.0, -1.0, 1.0, 18.0, 12.0])

sigma = np.array([15.0, 10.0, 16.0, 11.0, 9.0, 11.0, 10.0, 18.0])
# %%
import numpyro
import numpyro.distributions as dist

# Eight Schools example


def eight_schools(J, sigma, y=None):
    mu = numpyro.sample("mu", dist.Normal(0, 5))

    tau = numpyro.sample("tau", dist.HalfCauchy(5))

    with numpyro.plate("J", J):
        theta = numpyro.sample("theta", dist.Normal(mu, tau))

        numpyro.sample("obs", dist.Normal(theta, sigma), obs=y)


from jax import random
from numpyro.infer import MCMC, NUTS

nuts_kernel = NUTS(eight_schools)

mcmc = MCMC(nuts_kernel, num_warmup=500, num_samples=1000)

mcmc.last_state
# %%

rng_key = random.PRNGKey(0)

mcmc.run(rng_key, J, sigma, y=y)
mcmc.print_summary()


#                 mean       std    median      5.0%     95.0%     n_eff     r_hat
#         mu      4.43      3.18      4.22     -0.10      9.96    225.27      1.00
#        tau      4.22      3.02      3.39      0.89      7.94    116.48      1.01
#   theta[0]      6.41      5.70      5.51     -2.43     15.23    278.77      1.01
#   theta[1]      4.84      4.80      4.78     -3.66     12.00    454.28      1.00
#   theta[2]      3.68      5.23      3.87     -3.62     12.69    365.55      1.00
#   theta[3]      5.00      4.86      4.78     -2.45     12.87    384.35      1.00
#   theta[4]      3.46      4.70      3.84     -3.76     11.12    351.25      1.00
#   theta[5]      3.83      5.09      3.81     -4.24     11.49    432.41      1.00
#   theta[6]      6.78      5.33      6.13     -1.04     16.05    270.36      1.00
#   theta[7]      5.24      5.61      4.76     -2.30     14.99    442.56      1.00

# Number of divergences: 16
# %%

# extra adaptation
for i in range(3):
    mcmc.warmup(
        rng_key=mcmc.last_state.rng_key,
        init_params=mcmc.last_state.z,
        J=J,
        sigma=sigma,
        y=y * 10,
    )
# / extra adaptation

mcmc.post_warmup_state = mcmc.last_state
mcmc.run(mcmc.post_warmup_state.rng_key, J, sigma, y=y * 10)
mcmc.print_summary()


#                 mean       std    median      5.0%     95.0%     n_eff     r_hat
#         mu      1.21      5.20      1.20     -5.99     10.85   1704.14      1.00
#        tau    134.47     38.27    127.63     74.57    183.72   1026.01      1.00
#   theta[0]    276.13     15.31    276.09    251.63    301.93   2174.78      1.00
#   theta[1]     79.40      9.94     79.43     61.29     93.64   1964.28      1.00
#   theta[2]    -28.36     15.41    -28.81    -57.87     -4.92   1664.06      1.00
#   theta[3]     69.47     10.79     69.23     51.81     86.19   1785.82      1.00
#   theta[4]    -10.21      8.79    -10.33    -23.57      5.18   1915.42      1.00
#   theta[5]      9.50     10.66      9.70     -7.01     27.20   1576.17      1.00
#   theta[6]    178.90      9.47    178.97    163.47    194.60   1347.44      1.00
#   theta[7]    117.88     16.92    117.93     91.28    145.85   2004.19      1.00

# Number of divergences: 0
```

Am I correct here? This should reuse both the parameter/variable estimates and the mass matrix state from previous run.
