### ISSUE TITLE
Confusing error on grad of Categorical.log_prob

### ISSUE THREAD

**Issue by joaogui1** [pyro-ppl/numpyro#541]
I was trying to implement OpenAI's [simple policy gradient](https://github.com/openai/spinningup/blob/master/spinup/examples/pytorch/pg_math/1_simple_pg.py)
using JAX and used numpyro for the categorical distribution, but when computing the gradient I get the following error: `ValueError: start_indices must have an integer type`
Does anyone know what could it be?
Here's a link to the [colab](https://colab.research.google.com/drive/1tfB-qZ8_-zNS9vv0ZbFV-YHGiwRD1fUH)
I'm sorry that it's not a minimal example, but I will try to give any extra info requested

**Comment by fehiepsi** [comment]
I think you should provide int input to log_prob, probably by changing the following `float32` to `int32`?
```
jnp.asarray(batch_acts, dtype=jnp.float32)
```

**Comment by joaogui1** [comment]
It worked, thanks!
