### ISSUE TITLE
missing expand_by() feature

### ISSUE THREAD

**Issue by LysSanzMoreta** [pyro-ppl/numpyro#547]
Hi!

I am writing to kindly request the expand_by() for sampling from distributions feature (present in pyro) to appear also in numpyro. We had to implement a not so pretty work-around by expanding the dimensions of the parameters (means, sd,...) in order to achieve something similar. 

Thank you very much in advance!! :)

**Comment by fehiepsi** [comment]
@LysSanzMoreta could you elaborate your usage case? It seems to me that you can use [sample_shape](http://num.pyro.ai/en/stable/primitives.html#numpyro.primitives.sample) instead.

**Comment by LysSanzMoreta** [comment]
Hi! 

Oh! I see, this:
M = pyro.sample("M", dist.StudentT(1,0,3).expand_by([data1.shape[0],data1.shape[1]).to_event(2))

Is the same as:
M = numpyro.sample("M", dist.StudentT(1, 0, 3), sample_shape=(data1.shape[0], data1.shape[1]))

I think we missed the sample_shape argument back then or we were very focused on finding expand_by(). We did extra work for nothing heheh, but it's ok, works either way.  Weird, nevermind then, thanks!

**Comment by fehiepsi** [comment]
It seems that `sample_shape` works, so I close this issue. :)
