### ISSUE TITLE
Sampling with invalid observations (e.g. Poisson(1|-1))?

### ISSUE THREAD

**Issue by vanAmsterdam** [pyro-ppl/numpyro#549]
Is this a bug or is this by design? If so, maybe it deserves a notion in the documentation of sample / distributions.

```
import numpyro
from numpyro.distributions import Poisson

with numpyro.handlers.seed(rng_seed=1):
    numpyro.sample('foo', Poisson(1), obs=-1)
    numpyro.sample('bar', Poisson(1, validate_args=True), obs=-1)

```

doesn't throw an error

**Comment by fehiepsi** [comment]
This is expected. We don't validate obs value at `sample` statement, but will validate it at log_prob computation.
```python
from numpyro.distributions import Poisson
Poisson(1, validate_args=True).log_prob(-1)
```
will raise a warning for you and mark out-of-support log probability by -inf.

**Comment by fehiepsi** [comment]
@vanAmsterdam You can follow up on the question in [the forum](https://forum.pyro.ai/). Currently, the only method which requires validating samples is `log_prob`, so the current design is fine IMO. If you have other suggestions, please let us know.
