### ISSUE TITLE
"Cannot find valid initial parameters" after data size exceeds some threshold

### ISSUE THREAD

**Issue by jhmenke** [pyro-ppl/numpyro#552]
I am not sure if it's a bug or a problem with my model. In that case please close this issue :)

I am using the Bayesian Neural Network example as my base here, D_H (hidden layer neurons) being set to 30. D_X is 36 while D_Y is variable. I have found that as long as D_Y is below certain number (7 in my case), everything works great and i get expected results. However, as soon as i use another input, i get:

>RuntimeError: Cannot find valid initial parameters. Please check your model again.

Now, if i keep the higher dimension of D_Y but delete for example the second layer so that the number of parameters is lowered again, it starts running flawlessly again. 

It seems that _there is an inherent limitation on how many parameters the sampler can take until it cannot find initial parameters_. 

I thought the issue may lie with the Normal(0, 1) initialization of all weights and tried using the Kaiming initialization from pytorch (w1_init ...), but that does not change anything. It seems that the number of parameters is the limiting factor.

Is that a bug or can numpyro simply not handle problem of the size? Thanks!

Relevant model as per the example:
```
def model(X, Y, D_H, w1_init, w2_init, w3_init):
    D_X, D_Y = X.shape[1], Y.shape[1] if Y is not None and len(Y.shape) > 1 else 1

    # sample first layer (we put unit normal priors on all weights)
    w1 = numpyro.sample("w1", dist.Normal(w1_init, np.ones((D_X, D_H))))  # D_X D_H
    b1 = numpyro.sample("b1", dist.Normal(np.zeros(D_H), np.ones(D_H)))[np.newaxis, :]
    z1 = nonlin(np.matmul(X, w1) + b1)   # N D_H  <= first layer of activations

    # sample second layer
    w2 = numpyro.sample("w2", dist.Normal(w2_init, np.ones((D_H, D_H))))  # D_H D_H
    b2 = numpyro.sample("b2", dist.Normal(np.zeros(D_H), np.ones(D_H)))[np.newaxis, :]
    z2 = nonlin(np.matmul(z1, w2) + b2)  # N D_H  <= second layer of activations

    # sample final layer of weights and neural network output
    w3 = numpyro.sample("w3", dist.Normal(w3_init, np.ones((D_H, D_Y))))  # D_H D_Y
    z3 = np.matmul(z2, w3)   # N D_Y  <= output of the neural network

    sigma_obs = numpyro.sample("prec_obs", dist.Normal(np.zeros(D_Y), 0.1 * np.ones(D_Y)))
    numpyro.sample("Y", dist.Normal(z3, sigma_obs), obs=Y)
```

**Comment by fehiepsi** [comment]
@jhmenke You can try some init_strategy such as [init_to_prior](http://num.pyro.ai/en/stable/utilities.html#init-to-prior) or [init_to_value](http://num.pyro.ai/en/stable/utilities.html#init-to-value).

**Comment by jhmenke** [comment]
Thanks. Of the available options, only *init_to_median* works up to  a bigger size but also stops working (even with, e.g., 100 samples) at some point.

Do you think it would make sense to train a discrete ANN first and then transfer the trained weights as the means of the Normals in the BNN?

**Comment by fehiepsi** [comment]
In your model, `sigma_obs` has real support, which will cause NaN if it takes a negative value; so using HalfNormal or Exponential prior to `sigma_obs` would be more reasonable. But I don't know why `init_to_value` does not work. I think that as long as you can find a good init params, `NaN` shouldn't happen (this points out that there should be some bugs in `find_initial_params` logic).

**Comment by jhmenke** [comment]
Although i have no idea of the math behind it, replacing the Normal with a HalfNormal solves the error for any init_to_* or even None at all.
You can probably decide better if it should have worked regardless when i chose _init_to_value_ (so there's a bug) or if it's just a poor model.

**Comment by fehiepsi** [comment]
Great to hear that it solves your problem. I guess you didn't specify an initial valid value for `prec_obs` site using `init_to_value`, e.g. (`init_to_value({"prec_obs": 1.})`)?

**Comment by jhmenke** [comment]
Of course i forgot. I only set w1-w3 and b1-b3. Setting prec_obs to a value > 0 (i tried 0.1) seems to work even if i use Normal instead of HalfNormal.

Thank you so much for your insightful comments!

**Comment by EvanZ** [comment]
Hmm I realize this is closed but I'm having the same issue using Pyro. If I use more than a few hundred data samples I get this error.

**Comment by fehiepsi** [comment]
@EvanZ If you are using Pyro, you can follow the discussion here: https://forum.pyro.ai/t/valueerror-when-data-size-surpasses-some-amount/2536 to see if the issue can be debugged.

**Comment by paapu88** [comment]
for me, replacing 
`kernel = NUTS(model)`
by
```
from numpyro.infer import init_to_feasible
kernel = NUTS(model, init_strategy=init_to_feasible())
```
solved the problem
version:
```
>>> numpyro.__version__
'0.8.0'
```
