### ISSUE TITLE
'Normal' object has no attribute 'expand'

### ISSUE THREAD

**Issue by liseeocean** [pyro-ppl/numpyro#554]
Hi,
I find distributions in numpyro don't have .expand but pyro have. How can I get this one?
It works in pyro:
import pyro.distributions as dist
N=10

wi=dist.Normal(0., 1.).expand([N, N]).to_event(2)

Not work in numpyro:

import numpyro.distributions as dist
N=10

wi=dist.Normal(0., 1.).expand([N, N]).to_event(2)

**Comment by fehiepsi** [comment]
@liseeocean This seems like a duplicated issue of https://github.com/pyro-ppl/numpyro/issues/547#issuecomment-591486854. Could you check if it solves your problem?

**Comment by liseeocean** [comment]
Thank you very much for your quick reply! Do you know how to use "from pyro.nn import PyroSample" in numpyro? 
In Pyro:
self.linear = PyroModule[nn.Linear](hidden_size, output_size)
self.fc1.weight = PyroSample(dist.Normal(loc=0., scale=1.))

**Comment by fehiepsi** [comment]
The `.expand()` method is available now. Thanks for making this feature request!
