### ISSUE TITLE
Support numpyro.subsample

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#556]
As [requested](https://github.com/pyro-ppl/numpyro/issues/546#issuecomment-592002328) by @justindomke, it would be nice to have native support for subsampling, without requiring users to write subsample code.

This also comes from the internal discussion we have today.

**Comment by fritzo** [comment]
Note there is a new [pyro.subsample()](http://docs.pyro.ai/en/stable/primitives.html#pyro.primitives.subsample) primitive that might be a good place to start.
