### ISSUE TITLE
Convenient way to turn off distributions arg checks

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#56]
With https://github.com/pyro-ppl/numpyro/pull/53, we can turn off distributions args checking with a contextmanager called `validation_disabled()`. Disabling is required because the args checking doesn't work with JIT (which isn't itself an issue since we anyways shouldn't need to JIT these extra debugging related features). 

The current context manager is a hack because it is a global flag, and we might call the distributions' `logpdf` method after the distribution is initialized which may result in the flag being applied incorrectly. Given scipy's inheritance pattern and use of `frozen` vs `non-frozen` instances, I couldn't see an easy way of storing this flag in the constructor (like we do in PyTorch), but it is worth addressing this as we clean up the interface.

**Comment by fehiepsi** [comment]
After working on #79, I think that I have a better understanding to discuss about this issue now.

About arg_check, we didn't do checking in continuous distribution, so I make a new issue #80. Given that we use frozen distribution is Pyro, it is worth to support it only for `frozen` distribution. We might mimic #79 to add a flag to frozen instance.

In addition, I prefer to let `arg_check=False` by default when our library is matured enough. : )

**Comment by neerajprad** [comment]
This should already be addressed. I now think that most time is spent in model debugging, so it would be better to have the default as validation enabled, provided that the checks are largely jittable. Right now, we have args checking turned off by default, but we can discuss and change this behavior in the future.
