### ISSUE TITLE
MCMC run with unobserved Poisson output fails

### ISSUE THREAD

**Issue by lumip** [pyro-ppl/numpyro#560]
## Brief summary
I have just been running an MCMC involving a Poisson distribution without the observations to get some prior draws and encountered an `NotImplementedError` doing so.

## Example Code
A simple replicating example is the following:
```python
import jax.numpy as np
import jax

import numpyro.distributions as dist
from numpyro.primitives import sample
from numpyro.infer import NUTS, MCMC
import numpyro
numpyro.set_host_device_count(4)

def model(counts=None):
    N = 1 if counts is None else counts.shape[0]
    rate = sample("rate", dist.LogNormal(), sample_shape=(N,))
    counts = sample("counts", dist.Poisson(rate), obs=counts)
    
sampler = NUTS(model)
mcmc = MCMC(sampler, 200, 200, num_chains=4, progress_bar=False)
key = jax.random.PRNGKey(0)
mcmc.run(key)
```
The same code runs fine when fixing observations for the model (passing in a `counts` array). 

## Details of Encountered Error
The resulting exception is thrown during `mcmc.init()` in the `__call__` function of the `biject_to` instance of `ConstraintRegistry` (in `numpyro/distributions/transforms.py`) which is called for an  `_IntegerGreaterThan` constraint which is not in the registry. (That constraint is the support constraint of the `PoissonDistribution`)
Somehow that constraint seems to just be missing in the registry for some reason. Other constraints are present, most notably the non-integer `_GreaterThan`, so I believe this is an oversight. Indeed, the same error does not occur if I would be sampling from, say, a Normal distribution instead of the Poisson.

Can you confirm this is a bug and I'm not doing something wrong, and if so, how to fix it?

**Comment by neerajprad** [comment]
I think the error is misleading (we should fix that). In your case, the issue is that we can really use HMC to sample from discrete variables. However, if you just want to sample from the prior, you can use the `Predictive` utility:

```python
from numpyro.infer import Predictive

Predictive(model, num_samples=100)(random.PRNGKey(0))
```

You can use the same class to also draw values from the posterior predictive, by passing in the `posterior_samples` argument (returned values from `mcmc.get_samples()`. 

```python
Predictive(model, posterior_samples=...)(random.PRNGKey(1))
```

**Comment by lumip** [comment]
Ah, I see. Thanks!
