### ISSUE TITLE
MCM sampling with custom jax function

### ISSUE THREAD

**Issue by jeammimi** [pyro-ppl/numpyro#570]
Hello, I have a function that I have writen using jax in another module and which is called Tpm,
and that use as input an array which is fixed called ran and an input N,4 array that I want to sample.
Here I am trying to use this function in a numpyro model:

```
def model(MRT=None):
    eff = numpyro.sample('eff', dist.Normal(0.5, 0.1))
    pos = numpyro.sample('pos', dist.Normal(10,0.1))
    sig= numpyro.sample('sig', dist.Normal(1, 0.2))
    mean_time = numpyro.sample('mt', dist.Normal(10., 4))
    
    
    sigma = numpyro.sample('sigma', dist.Exponential(1.))
    
    print(mean_time)
    array = np.array([[pos,eff,sig,mean_time]])
    print(array,array.dtype)
    ran = np.arange(0,100)
    mrt = Tpm(ran,array)
    numpyro.sample('obs', dist.Normal(mrt, sigma), obs=MRT)
```
Here I am making it run with a 1,4 array.

If I run it like that it does not work, because the input arrray created is of type dtype and 
does not work with my function

If I change one line by 
```
array = np.array([[pos,eff,sigma,mean_time]],dtype=np.float)
```
When I run it with mcm sample, it run a couple of time then output an error:

```
0.15651608
[[1.07742548 0.8264904  1.26886559 0.15651608]] float64
Traced<ConcreteArray(0.15651608)>with<JVPTrace(level=8/0)>
[[1.07742548 0.8264904  1.26886559 0.15651608]] float64
6.8987417
[[9.90196228 0.61384559 1.13733149 6.89874172]] float64
Traced<ConcreteArray(0.15651608)>with<JVPTrace(level=8/0)>
[[1.07742548 0.8264904  1.26886559 0.15651608]] float64

  0%|          | 0/3000 [00:00<?, ?it/s]

6.8987417
[[9.90196228 0.61384559 1.13733149 6.89874172]] float64
6.8987417
[[9.90196228 0.61384559 1.13733149 6.89874172]] float64
Traced<ShapedArray(float32[])>with<JVPTrace(level=9/1)>


I truncate the error 

     15     print(mean_time)
---> 16     array = np.array([[pos,eff,sigma,mean_time]],dtype=np.float)
     17     print(array,array.dtype)
     18     mrt = Tpm(ran,array)

ValueError: setting an array element with a sequence.

```
Do you know how I can make it work?

Here is a function that look like the one in my module and that reproduce this behaviour:

```
def Mi(chsi):
    return np.prod(chsi)

Mim = vmap(Mi,(0),0)

def Tpm0(ran,chs):
    return np.prod(Mim(chs)) * ran
 ```

**Comment by fehiepsi** [comment]
@jeammimi I think you will need to use
```python
array = np.stack([pos,eff,sig,mean_time], axis=-1)
```

**Comment by jeammimi** [comment]
Thank you, it worked.

I have a question regarding the speed of the mcm sampler.

right now for about 400 parameters, the speed of the mcm sampler is about 17s /it .
Is it normal ?
My function take about 6 ms / evaluation.

Best

**Comment by fehiepsi** [comment]
If your function takes about 6ms/evaluation then `17s/it` might be not normal. Generally, I think you can either:
+ optimize your code
+ reparameterize your model (so it took fewer steps to construct a binary tree in NUTS)
+ or use GPU

**Comment by jeammimi** [comment]
I dont understand in detail the NUTS algorithm, but at some point it must compute the derivative
of the function with respect to the parameter.
I know that if I just do the gradient of the least square difference between my data and my model,
If I dont jit the gradient, it is slow.
Do your implementation compile the gradient, or does one must give it compiled to increase the speed.
Best

**Comment by fehiepsi** [comment]
Hi @jeammimi , we use JAX, while compiles both forward and backward (computing grad) pass. You don't have to worry about it I think.

**Comment by fehiepsi** [comment]
@jeammimi I think we can close this because the topic issue is resolved with `np.stack`. Please open another issue if you observe some performance issue with NumPyro.

**Comment by jeammimi** [comment]
Yes you are right.
Thank you!
