### ISSUE TITLE
Inference by enumeration

### ISSUE THREAD

**Issue by stuhlmueller** [pyro-ppl/numpyro#571]
Related: [Unobserved discrete latent variables](https://github.com/pyro-ppl/numpyro/issues/542)

**Comment by neerajprad** [comment]
Thanks for filing this, @stuhlmueller. 

My understanding is that most of this work is already happening in Funsor and Pyro, and we may need to port some of @eb8680's refactoring code from https://github.com/pyro-ppl/pyro/pull/2307. @fehiepsi - Please feel free to add any blocking / in-progress issues.

**Comment by fehiepsi** [comment]
@stuhlmueller We added [some tests](https://github.com/pyro-ppl/numpyro/pull/572/files#diff-fed0396c70de3697c3e0eb518df45b00) for enumeration (gaussian mixture model, Bernoulli latent) in #572. Could you take a look at those tests and let us know if they already cover your usage cases? We love more feedbacks/examples before getting through that PR. Thanks!!

**Comment by fehiepsi** [comment]
After #572, MCMC works for models with discrete latent variables. We'll follow up on the compiling time issue for `markov` models in #678.
