### ISSUE TITLE
Adding Difference-of-Proportions Example

### ISSUE THREAD

**Issue by freddyaboulton** [pyro-ppl/numpyro#578]
Hi,

This is in reference to issue #189 . I have created an example script showing how to test whether two proportions are equal via logistic regression. Can I get permission to push my branch and create a PR?

Thank you!

**Comment by fehiepsi** [comment]
Hi @freddyaboulton , thanks for the contribution! I believe you can push your branch to your fork and make a PR without problems. Let me know if you get any issues.

**Comment by freddyaboulton** [comment]
Thanks @fehiepsi ! I created #581 .
