### ISSUE TITLE
Iterative NUTS consumes more memory than recursive in big models

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#58]
#54 implements both recursive and iterative NUTS. It has been shown that iterative method outperforms recursive method in term of reducing overhead. However, currently iterative NUTS consumes a bit more memory than recursive NUTS as demonstrated in this [gist](https://gist.github.com/fehiepsi/cd8409d0a3feb3e3f287b12b9960d13c).

### Current benchmark (for tree depth = 10)

+ latent dim = 10
  - iterative: 791 µs, 233.23 MiB
  - recursive: 3.71 s, 232.61 MiB

+ latent dim = 100
  - iterative: 1.34 ms, 297.91 MiB
  - recursive: 3.76 s, 283.20 MiB

+ latent dim = 1000
  - iterative: 8.46 ms, **503.02 MiB**!
  - recursive: 3.79 s, 380.55 MiB

**Comment by fehiepsi** [comment]
@neerajprad I just update the [gist](https://gist.github.com/fehiepsi/cd8409d0a3feb3e3f287b12b9960d13c) with new profiling. Iterative nuts consumes just the same memory as recursive nuts for full tree. But it will ask more while compiling as shown in the last benchmark (that makes sense because it has to evaluate 2 branches of lax.cond e.g.). So I have no worry about memory any more.

 Are you fine if I just remove recursive nuts to make it easier for optimizing iterative nuts?

**Comment by neerajprad** [comment]
> Are you fine if I just remove recursive nuts to make it easier for optimizing iterative nuts?

I think the only reason to have it for some time would be for debugging purposes, but if you think we don't need that, go for it!

**Comment by neerajprad** [comment]
> Iterative nuts consumes just the same memory as recursive nuts for full tree.

That's awesome!

**Comment by fehiepsi** [comment]
Hehe, so I close this issue.
