### ISSUE TITLE
substitute_fn argument in the substitute effect handler.

### ISSUE THREAD

**Issue by ethanluoyc** [pyro-ppl/numpyro#587]
Is the way to use substitute_fn expected? 

I was expecting that values returned by substitute_fn will be unchanged. However, from the code it appears that these values will be base_value and will be transformed. This is not mentioned in the documentation.

https://github.com/pyro-ppl/numpyro/blob/25d055ad4b5a5e85a02159af87e8db1451243217/numpyro/handlers.py#L432

**Comment by fehiepsi** [comment]
@ethanluoyc You are right that it will substitute base values of transformed distributions. We should document it better. Btw, I believe that we will remove this arg when #511 is incorporated.

**Comment by ethanluoyc** [comment]
Actually I would like to know if substitute with the original value can be supported? I am writing an LMH sampler and this comes handy..

**Comment by fehiepsi** [comment]
Oops, sorry, somehow I missed your comment. Could `param_map` argument resolve your issue? We are going to remove those `base_param_map`, `substitute_fn` arguments because they are not necessary. Could you share your usage case so we can have better decisions?

**Comment by ethanluoyc** [comment]
I think this would work! Thanks!
