### ISSUE TITLE
Problem with setting initial value

### ISSUE THREAD

**Issue by organic-chemistry** [pyro-ppl/numpyro#597]
(I am using numpyro   0.2.4)

Hello,
when I run my model I have the following error:

`Cannot find valid initial parameters. Please check your model again`
When I print the value for the first samples of the model, I don't understand how the values are sampled, because I choose a small scale for the normal distribution but the values sampled are far from the initial values:

in the model Here is a part of my code in the mode definition:

```
mti = chs[::, 3]
print("init",mti)
mt= numpyro.sample('mt', 
                   dist.Normal(loc=mti,scale=np.array([0.1] * len(mti))))
print("Sampled",mt)
```
And the first output when I run 

```
kernel = NUTS(model)
mcmc = MCMC(kernel, num_warmup, num_samples, num_chains=1)
mcmc.run(rng_key_,obs=all_data)
```
is 

```
init [55.066776 49.781464 54.160652 56.67783  39.967762 26.07386  31.048147
 25.361017 35.727913 24.021101 27.176115 24.100166 21.28712  25.72563
 20.654652 31.847694 29.916624 33.566547 32.181293 50.280743 36.36    ]
Sampled [ 1.9994469  -0.08439302  0.88904     1.0050912  -1.3353357   1.5967388
 -1.8687382   1.8645926  -0.57492685  0.68502283 -0.30930138 -0.695817
 -0.6461806  -1.7297425   1.7614388  -1.5908298  -1.4360228  -0.7251029
 -1.7875538   0.05770493 -0.8764796 ]

```

So the sampled value is very far from the initial value.
What Am I doing wrong?
Thank you

**Comment by fehiepsi** [comment]
@organic-chemistry Could you try [init_to_prior](http://num.pyro.ai/en/stable/utilities.html#init-to-prior) strategy? (you can just set `init_strategy=init_to_prior()` in [NUTS](http://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.mcmc.NUTS) definition)

**Comment by organic-chemistry** [comment]
Thank you it worked.
It may be useful to mention using other init_strategy when the error 
`Cannot find valid initial parameters. Please check your model again`
is raised. I struggle for quite some time before asking here.
Thanks again
