### ISSUE TITLE
Support MaskedDistribution, ExpandedDistribution for TransformReparam

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#610]
cc @neerajprad

**Comment by fehiepsi** [comment]
@neerajprad Looking like your issue requires to handle the composition of those distributions? Or we just need to support some simple composition?
```
dist.TransformedDistribution(...).mask(...).expand(...)
```

**Comment by neerajprad** [comment]
@fehiepsi - it will be nice if we could support arbitrary compositions, but let me think about it a bit to see if there's a natural way to do this.

**Comment by fehiepsi** [comment]
Closed because ExpandedDistribution has been supported. For MaskedDistribution, we can use `ImproperUniform` instead (as illustrated in the docs of `ImproperUniform`).
