### ISSUE TITLE
Support for bijective transforms for use in HMC

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#62]
This will be important for inference on models that contain distributions with constrained support. I think PyTorch's transforms module is pretty nice, and we can follow the same pattern here.

cc. @fehiepsi

**Comment by fehiepsi** [comment]
I'll try to make an initial api for this after adding dirichlet distribution.

**Comment by neerajprad** [comment]
@fehiepsi - have you already started working on this? I think this is a blocker for working on more interesting models.

**Comment by fehiepsi** [comment]
@neerajprad I have not yet worked on this. Feel free to work on this if you want. I am doing on the hmc pr which we discussed yesterday and will work on lax.scan instead. :)

**Comment by fritzo** [comment]
See also "constraint support in minipyro" https://github.com/pyro-ppl/pyro/issues/1819
I think you should be able to:
1. fork torch.distributions.constraints
2. fork torch.distributions.transforms
3. use torch.distributions.constraint_registry's `biject_to` directly (or fork to avoid torch dependency)

**Comment by fehiepsi** [comment]
@fritzo , we already did this for most constraints. ^^
