### ISSUE TITLE
Support `do` handler

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#620]
While answering a [question](https://forum.pyro.ai/t/beginners-toy-examples-tutorials-for-exact-inference-on-discrete-variables/1911) in the forum, I found that `do` handler will be useful if users want to intervene with a value for a site to compute conditional distribution, rather than joint distribution.

Here is how [poutine.do](https://github.com/pyro-ppl/pyro/blob/dev/pyro/poutine/do_messenger.py) messenger implemented in Pyro. Basically, the idea is to [condition](http://num.pyro.ai/en/stable/handlers.html#condition) and add a field `stop=True` (equivalent to using [block](http://num.pyro.ai/en/stable/handlers.html#block) handler) to the message.

**Comment by TuanNguyen27** [comment]
I'd like to work on this over the weekend if no one claims it by then !

**Comment by fehiepsi** [comment]
Thank @TuanNguyen27 for addressing this issue!
