### ISSUE TITLE
Why 'seed' the model in posterior predictive density in bayesian regression tutorial?

### ISSUE THREAD

**Issue by vanAmsterdam** [pyro-ppl/numpyro#624]
This may be a minor thing, but going through the Bayesian Regression notebook tutorial again, I noticed this piece of code:

```python
def log_likelihood(rng_key, params, model, *args, **kwargs):
    model = handlers.condition(handlers.seed(model, rng_key), params)
    model_trace = handlers.trace(model).get_trace(*args, **kwargs)
    obs_node = model_trace['obs']
    return obs_node['fn'].log_prob(obs_node['value'])
```

If I'm not mistaken, this `handlers.seed(...)` bit doesn't do anything and could be left out. It might be a bit confusing to someone reading about the posterior predictive density.

**Comment by fehiepsi** [comment]
Thanks, @vanAmsterdam! We have fixed the tutorial.
