### ISSUE TITLE
Indepedent distribution does not have `enumerate_support` implemented

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#650]
This bug is observed in #646.

**Comment by fritzo** [comment]
Note we specifically avoided implementing `IndependentDistribution.enumerate_support()` in torch.distributions because the size of the cartesian product space grows exponentially in `event_shape.numel()`, so most uses would be impractical or lead to OOM errors.

**Comment by fehiepsi** [comment]
I see. Thanks for explaining! I am going to ask this question in slack but you are so fast. :))
