### ISSUE TITLE
Behavior of `condition` handler is different from `pyro.condition`

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#665]
In Pyro, we allow `condition` on observed sites, but this is not allowed in NumPyro. Should we relax this constraint? cc @neerajprad 

(I think this issue will block #638: we can not compose `do(condition(...))`)

**Comment by fritzo** [comment]
@eb8680 ?

**Comment by eb8680** [comment]
I don't see why this would block #638, can you explain?

**Comment by fehiepsi** [comment]
With `condition(model, {'z': 1})`, `z` will be come an observed site. Then in `do.process_msg(z_site)`, we do `apply_stack(z_site.copy())`, which will do `condition` again on the observed `z_site.copy()`.

**Comment by fehiepsi** [comment]
Actually, this constraint is [relaxed in Pyro](https://github.com/pyro-ppl/pyro/pull/2157/files#diff-8b4f7d602fb71525c816c41901267f78) to support `do` handler. :D
