### ISSUE TITLE
Jacobian of constrain_fn returned by initialize_model

### ISSUE THREAD

**Issue by tomsons22** [pyro-ppl/numpyro#673]
Hi,

I have a question about the automatic transformations applied to models with constrained domains. Once we define a model `model`, we can initialize it using `init_params, potential_fn, constrain_fn = initialize_model(model, ...)`. Here, `constrain_fn` receives an unconstrained sample `u` and returns a sample `c` constrained to the correct domain. I want to compute the log-abs-det of the Jacobian of the transformation `constrain_fn(u)`.

One solution (which apparently does not always work) involves getting the transformations applied when the model is initialized, using the function `T=get_model_transforms(model, ...)`, and then calling `T.log_abs_det_jacobian(u, T(u))`, where `T(u)` is the constrained sample obtained after applying transformation `T` to the unconstrained sample `u`.

However, I came across some examples for which the transformation `T(u)` and `constrain_fn(u)` give different results. Then, the Jacobian of `T(u)` cannot be used in place of the Jacobian of `constrain_fn(u)`. One such case is the following:

```
import numpyro
import numpyro.distributions as pydist
import jax

rng_key = jax.random.PRNGKey(1)

def model():
	tau = numpyro.sample("tau", pydist.InverseGamma(2., 2.))

u, _, constrain_fn = numpyro.infer.util.initialize_model(rng_key, model)

T, replay_model = numpyro.infer.util.get_model_transforms(rng_key, model)

print('a:', constrain_fn(u)['tau'])
print('b:', T['tau'](u['tau']))

```

This outputs

```
a: 1.2376825
b: 0.8079617
```

This basically says that for this example both transformations are not the same. However, if I change the InverseGamma distribution used in the model by a HalfNormal, HalfCauchy, Beta, or Gamma, both output values are indeed equal.

Is there a simple way of computing the log-abs-det of the `constrain_fn(u)` transformation that works for all distributions?

A bit more info: The method shown above works for several distributions except the InverseGamma. I think this has to do with the fact that the InverseGamma is itself defined as a TransformedDistribution, and I think that this transformation is not being included either in the `constrain_fn` or `get_model_transforms`, but I may be wrong.

Thanks!!

**Comment by fehiepsi** [comment]
> this has to do with the fact that the InverseGamma is itself defined as a TransformedDistribution

Hi @tomsons22, you are right about that. In 0.2.4, the transform only transforms unconstrained values to the base values of transformed distributions. We have removed that ambiguity in the master branch. However, we also change the API of those utilities in `infer/util.py` a bit. I think, for now, the corresponding code will be
```python
(u, _, _), _, constrain_fn, _ = numpyro.infer.util.initialize_model(rng_key, model)
T, _, _, _ = numpyro.infer.util._get_model_transforms(numpyro.handlers.seed(model, rng_key), (), {})
print('a:', constrain_fn(u)['tau'])
print('b:', T['tau'](u['tau']))
```

The easiest way to get log det of the transforms for general model is:
```
log_det = numpyro.infer.util.log_density(model, args, kwargs, params) + numpyro.infer.util.potential_energy(model, args, kwargs, unconstrained_params)
```

**Comment by tomsons22** [comment]
Hi @fehiepsi,

Thanks for the helpful response! I have two additional questions regarding your answer:

(1) "We have removed that ambiguity in the master branch." This means that, with the version of Numpyro in the master branch and the piece of code you wrote, ` constrain_fn(u)['tau']` and `T['tau'](u['tau'])` would always return the same thing, right? (In other words, the method I propose in the original question would work?).

(2) The way to compute log_det involving `log_density(...)` and `potential_function(...)`, requires having both `params` and `unconstrained_params`. Given `unconstrained_params ` we can generate `params=constrain_fn(params)`. Given `params`, is there any simple way of generating `unconstrained_params `? That is, is there any simple way of getting the inverse of `constrain_fn(...)`.

**Comment by fehiepsi** [comment]
>  always return the same thing, 

Yes.

> is there any simple way of getting the inverse of constrain_fn(...).

I think you can use the hidden function `numpyro.infer.util._get_model_transforms` to get the transform and use `numpyro.infer.util.transform_fn` to forward/inverse those transforms. To avoid using that hidden function, for most models (including all models without `deterministic` sites), you can also use
```python
(u, _, _), _, postprocess_fn, _ = numpyro.infer.util.initialize_model(rng_key, model)
inv_transforms = postprocess_fn.args[0]
```
