### ISSUE TITLE
Metropolis Hasting MCMC for simulating spin model

### ISSUE THREAD

**Issue by PHYSICSIDEA** [pyro-ppl/numpyro#674]
Dear numpyro team,

So I am dealing with what is so-called spin models in physics, whereby the state space is discrete and of very large dimension. The standard procedure to approximate the true distribution ( which is theoretically a Boltzmann distribution) of such systems consists of generating a Markov chain of states, one after another, by specifying a transition probability from the current to the next state. For the Metropolis-Hasting method, this transition probability is of the form min (1, exp(-dH)), where dH is equal to the change of a function of the state H (Hamiltonian in physics literature) corresponding to this transition. The reason for taking this procedure, instead of defining a prior distribution is that the state space is exceedingly large and one hence prefers to sample only those regions of considerable weights. The mentioned MH procedure allows one to do so. As I am a total newbie,  could you point me out to a tutorial or start reading for implementing MH procedure in numpyro? Thanks.

**Comment by fehiepsi** [comment]
Hi @PHYSICSIDEA, you can create an MH kernel by subclassing [MCMCKernel](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/mcmc.py#L44) and implementing `init` and `sample` method. Could you take a look there and see if that interface is enough for your purpose? I am happy to discuss with you any difficulty that you got.

**Comment by fehiepsi** [comment]
@PHYSICSIDEA We just expose [MCMCKernel in docs](http://num.pyro.ai/en/latest/mcmc.html#numpyro.infer.mcmc.MCMCKernel). I hope that subclassing it and implementing `init`, `sample` would be enough for your MH kernel compatible with `MCMC` class. Please let me know if you need further clarification either here or in [forum](https://forum.pyro.ai/).
