### ISSUE TITLE
Running PyPl release on Colab GPU runtime has suboptimal performance

### ISSUE THREAD

**Issue by wandomPewlin** [pyro-ppl/numpyro#688]
I spent quite some time trying to get numpyro to run on Colab's GPU runtime. Initially, I got it to work by running the following code block.
```
!pip install numpyro
!pip install --upgrade https://storage.googleapis.com/jax-releases/cuda101/jaxlib-0.1.37-cp36-none-linux_x86_64.whl
```
I then ran the [logistic_regression](https://github.com/pyro-ppl/numpyro/blob/master/notebooks/source/logistic_regression.ipynb) benchmark with both CPU and GPU runtime on Colab. The CPU version took `~35ms` per step while the GPU version took `~27ms` (both HMC and NUTS were pretty close), which is not as great of an improvement compared to the values stated in the notebook.
After digging through the issues, I realized there were some critical changes to both jaxlib and numpyro after numpyro's PyPl release, so I then run the following code to install the latest numpyro version from github.
```
!pip install git+https://github.com/pyro-ppl/numpyro.git
!pip install --upgrade https://storage.googleapis.com/jax-releases/cuda101/jaxlib-0.1.51-cp36-none-manylinux2010_x86_64.whl
!pip install --upgrade jax
```
Running the same benchmark on GPU runtime now only takes `~6ms` each step. I am not quite sure if this should be considered as an issue, but I think it might help others trying to run numpyro on colab before the next PyPl release.
_EDIT: Grammar_

**Comment by fehiepsi** [comment]
Thanks @wandomPewlin for helpful information! We just update numpyro to 0.3 so I guess we can close this issue. 

Hope that this suboptimal performance does not happen with the release version. :D
