### ISSUE TITLE
NumPyro master and PyPI versions not in sync

### ISSUE THREAD

**Issue by jawolf314** [pyro-ppl/numpyro#695]
Hi - I was running some examples that use newly released features on the master branch and noticed that the PyPI version seems to be based on the version 0.2.4 from January 2020.  I wonder if this is because the minor versions need to be incremented -- many new features have been added since January 2020, but the minor version has not been incremented.  Not sure how this package is updated on PyPI when there are updates to master.  Just wanted to surface this.

**Comment by jawolf314** [comment]
One reason the versioning may be important is that with the releases since January there are some backwards incompatibility issues if using the master branch (e.g., the SGT example). If someone downloads NumPyro from PyPI and then tries running the latest SGT - the example will fail at the imports.

```
ModuleNotFoundError: No module named 'numpyro.contrib.control_flow'
```

**Comment by fehiepsi** [comment]
@jawolf314 Do you have some solutions for this issue? I understand your point but not sure what is the best way to deal with it.

**Comment by fehiepsi** [comment]
Maybe we can add some pip statements at the first cell (like colab notebooks) which install the specific versions (if it is no longer backward compatibility) and remove it for each release?

**Comment by neerajprad** [comment]
I think when we move to using jax master for development, we could just bump up the version in `version.py` and checks in the examples / tutorials, i.e. our examples/tutorials on the master branch should assert that numpyro's version is at least `0.2.5`, and our `version.py` should be `0.2.5-dev`. That way the examples on the master branch will fail the assertion when run on an earlier version of jax/numpyro. Probably something to keep in mind after our release.

**Comment by jawolf314** [comment]
@fehiepsi I am not sure the best way to deal with this. I was wondering if there is CI/CD to PyPI when the new master branches are released - but based on the pip install numpyro the original 0.2.4 seems to be what is pulled from PyPI. I was wondering if incrementing the minor version when there are changes to master would be required - depending on how the deployment to PyPI is done.  I imagine many people are installing from PyPI instead of directly from the master branch in Github.

**Comment by jawolf314** [comment]
Bumping up the micro version ("major.minor.micro" schema) when a change to master occurs would probably be the simplest solution.  Currently, the 0.2.4 in PyPI is incompatible with the time_series_forecast.ipynb, but the assert in that notebook is for version 0.2.4.  I took at look at PEP440 (https://www.python.org/dev/peps/pep-0440/#id24) - that's how I interpret the PEP.

**Comment by fehiepsi** [comment]
Thanks @jawolf314! Let me ask some folks about the bumping micro version process. I'm not familiar with it.

The short term solution is we will try to fix #671 and release NumPyro 0.3 in a couple of days. But after that, I agree that tutorial requirement and numpyro version should be consistent so we should think about this issue after the release.

**Comment by neerajprad** [comment]
> Bumping up the micro version ("major.minor.micro" schema) when a change to master occurs would probably be the simplest solution.

That was my thought as well. As @fehiepsi mentioned, this will most likely not be an issue in the future until we start tracking jax master again after release, or make a backward incompatible change (which are becoming rarer). If we need to track the jax master again, we will make sure that we bump our version during development so that users are not misled. Thanks for raising this issue.

**Comment by fehiepsi** [comment]
@neerajprad Could you help me with this issue? It is unclear to me what we need to do. :(

**Comment by neerajprad** [comment]
@fehiepsi - From what I understood, the issue is that our version check in the tutorials is not as strict as it should be in the master branch. Anytime we are using something that is only available in the master branch in one of our tutorials, and a user runs the same tutorial with the release version of numpyro, we should raise an error. 

To address this, once we release `0.3.1`, we can bump up the version in `version.py` and prepend `dev` to it and update our checks in the tutorials. This is only relevant after the release (if we require our tutorials to use some feature from the master branch that's not in release) and I can do that once we make the next release. Feel free to remove the milestone, since this should happen after the release.

**Comment by fehiepsi** [comment]
Thanks, @neerajprad! I get it now. That way makes a lot of sense to me.

**Comment by jawolf314** [comment]
@fehiepsi and @neerajprad , the initial reason I brought up the versioning was that in PyPI the latest version was behind the master branch in GitHub. I thought maybe this was due to the way the minor versioning was being handled in the package, because at the time the version in PyPI had the same major.minor.micro version number as the master branch in GitHub. The PyPI version was from January 2020.

**Comment by fehiepsi** [comment]
Sorry, @jawolf314! I missed your comment.

We use `master` branch for developing so it is not possible to pin `master` to PyPI. I know that some other repositories use `dev` for developing code and `master` for the released code but we don't follow that way here. To go to a PyPI version, you can use tag to find the correct code base. For example, code for `0.3.0` release can be found at [this link](https://github.com/pyro-ppl/numpyro/tree/0.3.0) or at [the example page](https://pyro.ai/numpyro/), which we only update it after the release.
