### ISSUE TITLE
Implement some popular distributions

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#703]
This issue tracks some popular distributions that are not available in NumPyro yet.

- [x] [Geometric distribution](https://pytorch.org/docs/master/distributions.html#geometric)
- [x] [ZeroInflatedNegativeBinomial](http://docs.pyro.ai/en/stable/distributions.html#zeroinflatednegativebinomial)
- [x] [Weibull distribution](https://pytorch.org/docs/master/distributions.html#weibull) (supported in `contrib.tfp`)
- [x] [DirichletMultinomial](http://docs.pyro.ai/en/stable/distributions.html#dirichletmultinomial) (supported in `contrib.tfp`)
- [ ] [FoldedDistribution](http://docs.pyro.ai/en/stable/distributions.html#foldeddistribution)

**Comment by TuanNguyen27** [comment]
TFP also has [Geometric ](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Geometric) & [Weibull](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Weibull) distribution support, in case #710 is successful :)

**Comment by fehiepsi** [comment]
Yeah, if those distributions in `numpyro.contrib.tfp.distributions` work well, we will probably move them to the main module. There are some interesting distributions in tfp such as [JointDistributionSequential](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/JointDistributionSequential).

**Comment by nkaimcaudle** [comment]
Is it possible to also add [SinhArcsinh transformation](https://www.tensorflow.org/probability/api_docs/python/tfp/bijectors/SinhArcsinh) ?

**Comment by fehiepsi** [comment]
@nkaimcaudle Sure, I just created a FR for it. :)

**Comment by dirmeier** [comment]
Ciao all, 

I'm working on two models with ZINB and Weibull likelihoods right now, if you are interested to have implementations for both of these, I could open up a PR. 

Maybe it could also make sense to have the alternative parameterization of the NB (https://mc-stan.org/docs/2_26/functions-reference/nbalt.html), since that is the one mainly used for regression models.

Best,
Simon

**Comment by fehiepsi** [comment]
Hi @dirmeier, your proposals sound great to me. Regarding NB, you could name the other parameterization `NegativeBinomial2`. :)
