### ISSUE TITLE
Integrate with Tensorflow Probability distribution

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#704]
TFP has some [subtraces](https://www.tensorflow.org/probability/api_docs/python/tfp/substrates/jax/distributions), including JAX. It is helpful to build a layer so that users can use TFP distributions in NumPyro. This helps avoid duplication of effort and settles some collaborations between two communities in the future.

It is nice to make TFP Normal distribution works in NumPyro first. Probably we can start with `numpyro.contrib.tfp.distributions.Normal`...

**Comment by TuanNguyen27** [comment]
While working on #705 I found [Oryx](https://github.com/tensorflow/probability/tree/master/spinoffs/oryx) ; [documentation](https://www.tensorflow.org/probability/oryx/notebooks/a_tour_of_oryx) which is another good candidate for integration with numpyro :D

**Comment by fehiepsi** [comment]
@TuanNguyen27 Do you have some suggestions on how to integrate it in NumPyro? The ability to transform a sampling function to a log probability function looks pretty cool! It would be great if we can use it to simplify some implementations or enable a new way to do inference.

**Comment by TuanNguyen27** [comment]
I don't know numpyro internals well enough to make suggestion, but if you have an example implementation in numpyro that could be replaced by the submodules implemented in Oryx I can prototype something out :D I am interested in both refactoring numpyro & new inference !

**Comment by fehiepsi** [comment]
@TuanNguyen27 For now, I don't have any idea in mind. :(

**Comment by TuanNguyen27** [comment]
PPS: We have another candidate, https://github.com/google/objax :D
