### ISSUE TITLE
Strange/interesting thing about speed

### ISSUE THREAD

**Issue by hzyjerry** [pyro-ppl/numpyro#706]
Dear numpyro team,

I'm experiencing some strange/interesting thing about inference speed. 

My `sampler.run` and `samples = sampler.get_samples(...)` operations are fairly fast using numpyro. However, it is when I print out `samples` that the code stalls for up to a few minutes. I wonder if this is a widely observed thing with numpyro, or a potential misuse on my end?

Thanks for your insights!

**Comment by hzyjerry** [comment]
Here is what the code roughly looks like

```python
sampler.run(
    rng_key,
    init_params=...,
    extra_fields=["mean_accept_prob"],
) # Fast
sample_ws = sampler.get_samples(group_by_chain=True) # Fast
print(sample_ws) # Slow
```

**Comment by martinjankowiak** [comment]
@hzyjerry [this](https://jax.readthedocs.io/en/latest/async_dispatch.html) might be relevant

also, for the future, please post questions like these in our [forum](https://forum.pyro.ai/)

**Comment by hzyjerry** [comment]
Thanks!
