### ISSUE TITLE
Support jax.scipy minimizers in NumPyro

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#716]
After jax 0.1.74, `bfgs` minimizer is available in JAX. It would be nice to have a BFGS wrapper in `numpyro.optim`.

In jax/scipy, 'BFGS' is provided through `method` keyword in [minimize](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-bfgs.html#optimize-minimize-bfgs). I am not sure if we should make a wrapper `numpyro.optim.Minimize` for `minimize` or we should split those methods into separated classes such as `numpyro.optim.BFGS`. With the former, new minimizers in JAX will be supported in NumPyro without modifications. With the latter, it is more explicit and friendlier to PyTorch users. Either way looks good to me.

cc @Joshuaalbert who implemented BFGS minimizer in JAX

**Comment by Joshuaalbert** [comment]
I like the first way. It'll be familiar for people who have used scipy, where you also specify a method name. And then as you noted, it'll let people use new methods as they become available. JAX is following the scipy interface so you can expect the output of minimize to stay consistent.

**Comment by fehiepsi** [comment]
Yeah, I agree. After some tfp prs, if no one wants to tackle this issue, I'll do it.
