### ISSUE TITLE
Guide for translating code from webppl to numpyro

### ISSUE THREAD

**Issue by prpr2770** [pyro-ppl/numpyro#722]
Hi, I'm working on a project where I can implement the inference in webppl, but I'm having issues in translating the codebase into numpyro, as I'd like to scale-up and parallelize the computations. Is there a guidebook/reference that helps understand how webppl codebase can be translated into numpyro? 

thanks

**Comment by fehiepsi** [comment]
Hi @prpr2770, I haven't used webppl but [this forum post](https://forum.pyro.ai/t/is-there-an-equivalent-pyro-construct-for-webppls-infer-operator/612) might be a good start. We don't have guidebook or reference for this. It seems to me that two libraries target different inference methods.

In case you want to port an inference algorithm to NumPyro, could you post your pseudo-code here? I will try to see if it will be beneficial to use JAX in your algorithm. (basically, if the algorithm has static loops inside, it is a good idea to use JAX)

**Comment by prpr2770** [comment]
Thank you for linking me to the forum-post. I tried to follow up on the way the RSA is implemented, for handling my particular use-case, but I'm facing some errors. 

I have provided my code in this gist [here](https://gist.github.com/prpr2770/94a6171e5e6f694531a7bdeebcd82d92).
I obtain the following error: 
```
Traceback (most recent call last):
  File "PermutationInferencePyroRSA.py", line 164, in <module>
    mymodel = PermutationInference(FullData, RandPerm)
TypeError: unhashable type: 'list'

```

**Comment by fehiepsi** [comment]
Really sorry for the long response, @prpr2770! Somehow I missed your comment. It seems to be very tricky to perform the task in your gist in JAX/NumPyro. I think it is better to stick with the Pyro version instead, in case you already resolved the hash issue (I'm not familiar with how RSA is implemented).
