### ISSUE TITLE
NumPyro disables GPU on import

### ISSUE THREAD

**Issue by C-J-Cundy** [pyro-ppl/numpyro#727]
When numpyro is imported, the platform is set to 'cpu' by default in the init file. 
This was very confusing to me since suddenly jax stopped recognising my GPU--only after a bit of digging did I discover it was due to the numpyro import statement. 

I think it would make sense to either display a warning or reconsider changing the platform, since it's a bit unexpected for a module to change some global state on import.

**Comment by fehiepsi** [comment]
I think one solution is to make it clear in README on NumPyro uses CPU backend by default and how to switch between backends? What do you think? I think adding a warning is unnecessary for most NumPyro users but I agree that changing the default JAX behavior might cause confusion for JAX users.

**Comment by C-J-Cundy** [comment]
Yep, a clear note in the README will certainly help. 

I think I would have still been caught out unless the warning in the README was very obvious, since coming from a jax point of view the behaviour of numpyro seems very strange. The jax ethos tends to be that by default a gpu/tpu will always be used if available, as it tends to be very reliably faster than the cpu. (Typically compilation can also be quite a bit faster for gpu too, I guess because the XLA focus is more on gpu than cpu). The numpyro behaviour is very un-jax-like

**Comment by fehiepsi** [comment]
I still don't find a good reason to enable GPU by default for most NumPyro users so adding a clear note is a good option to me here. If there are more people want GPU to be default, we can open a vote in forum to see which default option is better. ;)

Currently, with most examples that we have, CPU is much faster than GPU, and in CPU, we can run multiple chains, while with GPU, we have to buy new GPUs to be able to do that (or using `chain_method='vectorized'`, which is only valuable for a large number of chains).
