### ISSUE TITLE
Support enumeration in SVI

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#741]
Currently, enumeration is supported in MCMC but is not yet tested in SVI. It would be nice to support this feature for SVI too.

**Comment by fritzo** [comment]
This is good motivation to move enumeration tests into pyro-api https://github.com/pyro-ppl/pyro/issues/2606 I believe @eb8680 has already done much of the work as part of https://github.com/pyro-ppl/pyro/issues/2580

**Comment by eb8680** [comment]
I can take this issue, since I'll need to update `numpyro.contrib.funsor` in the process.

**Comment by thisiscam** [comment]
I wonder if there is any update to this feature? I tried SVI with discrete latent variables and seem to be running into issue similar to 1174

**Comment by fehiepsi** [comment]
@eb8680 @ordabayevy Do you have a prototype or a guideline for how to support this feature? There are many requests for this so I would like to understand better how to implement. Thanks!

**Comment by ordabayevy** [comment]
Hi @fehiepsi . I believe it should be possible to port the implementation of `TraceEnum_EBLO` from `pyro.contrib.funsor` to NumPyro. I would be happy to discuss the details over Zoom.
