### ISSUE TITLE
Log probability calculation with arviz conversion goes wrong with enumeration

### ISSUE THREAD

**Issue by vanAmsterdam** [pyro-ppl/numpyro#744]
Not sure if I should post this here or at the arviz github, but converting an MCMC object to arviz data goes wrong when using enumeration in the model. 
A invalid _random_bits error get's thrown when calculating the log likelihoods
Check e.g. notebooks/source/discrete_imputation.ipynb and try `az.from_numpyro(impmcmc)` on cell 9

**Comment by fehiepsi** [comment]
Thanks for the report, @vanAmsterdam! I have thought about this a bit. We need to tell [log_likelihood](http://num.pyro.ai/en/stable/utilities.html#numpyro.infer.util.log_likelihood) to use `enum` if the model has discrete latent variable. I think we can add a flag to `log_likelihood` to control a behavior and after the next release of numpyro, we can make a PR in arviz to enable the flag when the model has discrete latent variables.

**Comment by fehiepsi** [comment]
@vanAmsterdam Do you need this feature soon? I have thought a lot about this FR but couldn't find a simple solution yet. As I understand, we need to filter out all latent sites but keep those discrete sites that the observation site depends on, and marginalize them. That seems doable to me. When there are multiple observation sites, my only solution is to loop over them and do the above steps for each of them.

A much simpler solution is to skip marginalizing those discrete sites. For that, we only need to seed the model before feeding into the likelihood calculation. For example, you can add to [this line](https://github.com/pyro-ppl/numpyro/blob/cce00d1b0e976909d686fb7866b404ea751c0f44/numpyro/infer/util.py#L581):
```python
substituted_model = seed(substituted_model, rng_seed=0)
```

It will take me a bit of time to implement the first solution (but I will try to do it before the next release). In the mean time, you can use the second solution if you don't do any diagnostics with likelihood in arviz.

**Comment by vanAmsterdam** [comment]
I have no immediate use for this feature, but obviously we will need to sort it out. Once a solution is in place, we could add it to the discrete imputation example

**Comment by fehiepsi** [comment]
I think this is achieved via `infer_discrete`. We'll illustrate its usage in the `annotation` example.
