### ISSUE TITLE
Port autoguide AutoNormal from Pyro

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#746]
I am trying to fit a bnn in #743 with ELBO loss but couldn't optimize it with stochastic KL. It might work if I use AutoNormal with TraceMeanField_ELBO, so I would like to add this feature to try that option.

**Comment by fritzo** [comment]
@eb8680 do you think it would be easy to implement the KL parts of
TraceMeanField_ELBO (not the baseline parts) using Funsor?

**Comment by eb8680** [comment]
> do you think it would be easy to implement the KL parts of TraceMeanField_ELBO (not the baseline parts) using Funsor?

Sorry, missed this earlier. We could certainly write `eager` patterns that called the upstream KL implementations in TFP or PyTorch and a very simple `TraceMeanField_ELBO` reimplementation that used them - this would look very similar to the [`Trace_ELBO` implementation in `pyro.contrib.funsor`](https://github.com/pyro-ppl/pyro/blob/dev/pyro/contrib/funsor/infer/trace_elbo.py), but with slightly reordered terms.

A bigger challenge would be to try and include analytic KL or entropy terms automatically in `TraceEnum_ELBO` where possible.
