### ISSUE TITLE
NumPyro is breaking with JAX 0.2

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#749]
In JAX 0.2 release, many of our tests are failing... I think it is related to the new [omnistaging](https://jax.readthedocs.io/en/latest/CHANGELOG.html#jax-0-2-0-september-23-2020) mechanism.

This issue discusses several strategies that we would follow for our next release:
- Release 0.3.1 and pin jax version to `0.1.77`
- Release 0.3.1, pin jax version to `0.2.0`, disable omnistaging by default
- Try to fix all issues if possible, then release 0.3.1 with 0.2.0.

The first option is the safest because we don't understand much how stable the omnistaging is. Hopefully, it is stable enough, the issue lies at some other JAX commits, and all failing tests can be easily fixed.

**Comment by neerajprad** [comment]
How easy is it to fix the tests/other issues with `0.2.0`. I agree that it is best to pin to `0.1` for the time being.

**Comment by fehiepsi** [comment]
I am trying to fix those issues. Hopefully, they will be easy to fix. :)
