### ISSUE TITLE
Port poutine.collapse to NumPyro

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/numpyro#756]
Pyro introduced a `poutine.collapse()` effect in https://github.com/pyro-ppl/pyro/pull/2620, allowing exact conjugate inference over blocks of code, similar to @neerajprad's [pyro.contrib.conjugate](https://github.com/pyro-ppl/pyro/blob/dev/pyro/contrib/conjugate/infer.py).

@fehiepsi I think this would be an edifying intro to using Funsor for general pattern matching. Once `poutine.collapse()` is implemented in NumPyro, we can add [new conjugacy patterns](https://github.com/pyro-ppl/funsor/issues/367) to Funsor. Currently I believe only Beta-Binomial and Gaussian-Gaussian are implemented. I think some good starter Funsor tasks would be implementing patterns for say Beta-Bernoulli and then patterns for plates, as in Beta-plated(Binomial).

cc @eb8680

**Comment by fehiepsi** [comment]
Thanks, @fritzo! Let me assign this to myself. And will do some conjugate stuffs after this.
