### ISSUE TITLE
PyroModule with Objax

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#758]
I think that [Objax](https://github.com/google/objax) is a JAX-based neural network library that is closest to PyTorch. This seems to be a good candidate to have something like [PyroModule](http://docs.pyro.ai/en/stable/nn.html#module-pyro.nn.module) in NumPyro.

**Comment by TuanNguyen27** [comment]
interested in taking this issue :)

**Comment by fehiepsi** [comment]
I imagine that it will require a big design to be able to have some sort of stateful PyroModule in numpyro. On the other hand, it seems that Flax has been widely adopted among jax nn ecosystems. So I would like to close this issue. We can explore Objax in the future if it becomes a norm. :)
