### ISSUE TITLE
Fix exception chaining all over the codebase

### ISSUE THREAD

**Issue by akihironitta** [pyro-ppl/numpyro#761]
I recently went over [PyTorch](https://github.com/pytorch/pytorch/pull/43836) and [Detectron2](https://github.com/facebookresearch/detectron2/pull/1945), suggesting a fix in the way that Python 3's exception chaining is used.

As described in detail in [the article](https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with), exception chaining ([PEP 3134](https://www.python.org/dev/peps/pep-3134/)) can be used to make exceptions more user-friendly, and in that case, the syntax `raise .. from ..` needs to be used.

When `raise .. from ..` is used, there will be a line saying `The above exception was the direct cause of the following exception` between tracebacks. However, when we implicitly chaining exceptions (meaning when `raise .. from ..` syntax is not used), the message will be `During handling of the above exception, another exception occurred` which can confuse users.

Specifically, the following should be used in order to chain exceptions:
```python
try:
    something_which_raises_OldError()
except OldError as e:
    raise NewError("A more user-friendly exception message.") from e 
```
instead of:
```python
try:
    something_which_raises_OldError()
except OldError:
    raise NewError("A more user-friendly exception message.")
```

Here is one example which needs to be fixed. The below case needs a fix because it means, "while handling `KeyError`, `NotImplementedError` **unexpectedly** occurs."
https://github.com/pyro-ppl/numpyro/blob/298f3c9907fab8eb1dc08b1acf636edc2b6ba4cc/numpyro/distributions/transforms.py#L556-L559

If this suggestion sounds good and reasonable, I'd be happy to submit a PR! Let me know your thoughts on this!

**Comment by fehiepsi** [comment]
Sure, thanks @akihironitta! The fix looks more reasonable to me.

**Comment by akihironitta** [comment]
@fehiepsi Thank you for your quick response! I'll give it a go later this week!

**Comment by akihironitta** [comment]
@fehiepsi Just made #764 ready for review. Can you have a look at the changes?
