### ISSUE TITLE
[FR] add a thompson sampling example

### ISSUE THREAD

**Issue by martinjankowiak** [pyro-ppl/numpyro#768]
add an example script that that uses thompson sampling, either in the context of gaussian process based bayesian optimization (see e.g. [here](http://gpss.cc/gpss15/talks/Nado.pdf)) or gaussian process or logistic regression based contextual binary bandits (see e.g. [here](https://gdmarmerola.github.io/ts-for-contextual-bandits/)).

for a basic GP implementation in numpyro see [here](https://github.com/pyro-ppl/numpyro/blob/master/examples/gp.py).
for a basic logistic regression implementation in numpyro see [here](https://github.com/pyro-ppl/numpyro/blob/master/examples/covtype.py).

**Comment by fehiepsi** [comment]
I think this is resolved in #1014. Thanks, @dominikstrb!
