### ISSUE TITLE
Support float64 array

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#77]
Currently, we only develop and test for float32 array. When the functionalities are ready, we should test for float64 array too.

**Comment by neerajprad** [comment]
> When the functionalities are ready, we should test for float64 array too.

Note that float64 will be significantly slower than float32 for GPU, so I think it is a good practice to write our code assuming that we will run it on float32, i.e. ensure numerical stability whenever possible. e.g. by providing logit support in distributions. I think tests passing with float32 should almost always pass with float64 (the reverse isn't true)?

**Comment by fehiepsi** [comment]
@neerajprad This is to prevent something like `a = np.array([1.])`, `np.arange(...)`, or `random.normal(...)` without `dtype` in the code.
