### ISSUE TITLE
Omnistaging does not work when enabling distributions' validation

### ISSUE THREAD

**Issue by hyperfra** [pyro-ppl/numpyro#771]
Hi again,

I have updated to 0.4 and my probit model (that runs in the previous version) gives the following error:

ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected.

the model I fairly simple, (see below), I thought it might be cdf (jax.scipy.stats.norm.cdf) but could not make sense of it.

Have you experienced such changes by updating ?

MODEL:

def model(nwifeinc,
                  educ,
                  exper,
                  exper2,
                  age,
                  kidslt6,
                  kidsge6,
                  y=None):
    
    alpha = numpyro.sample("alpha", dist.Normal(0, 1))
    b1 = numpyro.sample("b1", dist.Normal(0, 1))
    b2 = numpyro.sample("b2", dist.Normal(0, 1))
    b3 = numpyro.sample("b3", dist.Normal(0, 1))
    b4 = numpyro.sample("b4", dist.Normal(0, 1))
    b5 = numpyro.sample("b5", dist.Normal(0, 1))
    b6 = numpyro.sample("b6", dist.Normal(0, 1))
    b7 = numpyro.sample("b7", dist.Normal(0, 1))
    xb =  alpha + b1*nwifeinc  + b2*educ +b3*exper + b4*exper2 + b5*age  + b6*kidslt6 + b7*kidsge6
    phi =  cdf(xb)  
    numpyro.sample("y", dist.BernoulliProbs(phi), obs=y)

**Comment by fehiepsi** [comment]
Hi @hyperfra, I think this is due to a new behavior of JAX 0.2 called [omnistaging](https://github.com/google/jax/blob/master/design_notes/omnistaging.md). We got a couple of issues like this when we pump JAX to 0.2. Our fixes are to change `jnp` to `np` at various places. Could you post your error trace so we can identify where the issue is?

**Comment by hyperfra** [comment]
hi @fehiepsi thanks.
1. disabling oministaging worked. :-)
2. complete error if I do not disable omnistaging below:

j---------------------------------------------------------------------------
FilteredStackTrace                        Traceback (most recent call last)
<ipython-input-19-059edad865e3> in <module>
     32 with numpyro.validation_enabled():
---> 33     probit.run(random.PRNGKey(1), **dat)

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/mcmc.py in run(self, rng_key, extra_fields, init_params, *args, **kwargs)
    445         if self.num_chains == 1:
--> 446             states_flat, last_state = partial_map_fn(map_args)
    447             states = tree_map(lambda x: x[jnp.newaxis, ...], states_flat)

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/mcmc.py in _single_chain_mcmc(self, init, args, kwargs, collect_fields)
    312             init_state = self.sampler.init(rng_key, self.num_warmup, init_params,
--> 313                                            model_args=args, model_kwargs=kwargs)
    314         if self.postprocess_fn is None:

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/hmc.py in init(self, rng_key, num_warmup, init_params, model_args, model_kwargs)
    449             rng_key, rng_key_init_model = jnp.swapaxes(vmap(random.split)(rng_key), 0, 1)
--> 450         init_params = self._init_state(rng_key_init_model, model_args, model_kwargs, init_params)
    451         if self._potential_fn and init_params is None:

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/hmc.py in _init_state(self, rng_key, model_args, model_kwargs, init_params)
    412                 model_args=model_args,
--> 413                 model_kwargs=model_kwargs)
    414             if self._init_fn is None:

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/util.py in initialize_model(rng_key, model, init_strategy, dynamic_args, model_args, model_kwargs)
    429                                                                   model_kwargs=model_kwargs,
--> 430                                                                   prototype_params=prototype_params)
    431 

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/util.py in find_valid_initial_params(rng_key, model, init_strategy, enum, model_args, model_kwargs, prototype_params)
    256     if rng_key.ndim == 1:
--> 257         (init_params, pe, z_grad), is_valid = _find_valid_params(rng_key, exit_early=True)
    258     else:

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/util.py in _find_valid_params(rng_key, exit_early)
    251         # even if the init_state is a valid result
--> 252         _, _, (init_params, pe, z_grad), is_valid = while_loop(cond_fn, body_fn, init_state)
    253         return (init_params, pe, z_grad), is_valid

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/util.py in while_loop(cond_fun, body_fun, init_val)
    121     else:
--> 122         return lax.while_loop(cond_fun, body_fun, init_val)
    123 

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/lax/lax_control_flow.py in while_loop(cond_fun, body_fun, init_val)
    270   cond_jaxpr, cond_consts, cond_tree = _initial_style_jaxpr(cond_fun, in_tree, init_avals)
--> 271   body_jaxpr, body_consts, body_tree = _initial_style_jaxpr(body_fun, in_tree, init_avals)
    272   if not treedef_is_leaf(cond_tree) or len(cond_jaxpr.out_avals) != 1:

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/lax/lax_control_flow.py in _initial_style_jaxpr(fun, in_tree, in_avals)
     71 def _initial_style_jaxpr(fun: Callable, in_tree, in_avals):
---> 72   jaxpr, out_avals, consts, out_tree = _initial_style_open_jaxpr(fun, in_tree, in_avals)
     73   closed_jaxpr = core.ClosedJaxpr(pe.convert_constvars_jaxpr(jaxpr), ())

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/lax/lax_control_flow.py in _initial_style_open_jaxpr(fun, in_tree, in_avals)
     66   wrapped_fun, out_tree = flatten_fun_nokwargs(lu.wrap_init(fun), in_tree)
---> 67   jaxpr, out_avals, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals)
     68   return jaxpr, out_avals, consts, out_tree()

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/util.py in body_fn(state)
    234         potential_fn = partial(potential_energy, model, model_args, model_kwargs, enum=enum)
--> 235         pe, z_grad = value_and_grad(potential_fn)(params)
    236         z_grad_flat = ravel_pytree(z_grad)[0]

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/util.py in potential_energy(model, model_args, model_kwargs, params, enum)
    156     # no param is needed for log_density computation because we already substitute
--> 157     log_joint, model_trace = log_density_(substituted_model, model_args, model_kwargs, {})
    158     return - log_joint

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/util.py in log_density(model, model_args, model_kwargs, params)
     59             else:
---> 60                 log_prob = site['fn'].log_prob(value)
     61 

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/distributions/util.py in wrapper(self, *args, **kwargs)
    524             value = kwargs['value'] if 'value' in kwargs else args[0]
--> 525             mask = self._validate_sample(value)
    526             log_prob = jnp.where(mask, log_prob, -jnp.inf)

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/distributions/distribution.py in _validate_sample(self, value)
    245         if not_jax_tracer(mask):
--> 246             if not jnp.all(mask):
    247                 warnings.warn('Out-of-support values provided to log prob method. '

FilteredStackTrace: jax.core.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected.

The problem arose with the `bool` function. 

While tracing the function body_fn at /anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/util.py:209, this value became a tracer due to JAX operations on these lines:

  operation rc:bool[] = reduce_and[ axes=(0,) ] rb:bool[753]
    from line /anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/distributions/distribution.py:246 (_validate_sample)

You can use transformation parameters such as `static_argnums` for `jit` to avoid tracing particular arguments of transformed functions.

See https://jax.readthedocs.io/en/latest/faq.html#abstract-tracer-value-encountered-where-concrete-value-is-expected-error for more information.

Encountered tracer value: Traced<ShapedArray(bool[])>with<DynamicJaxprTrace(level=1/0)>

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

ConcretizationTypeError                   Traceback (most recent call last)
<ipython-input-19-059edad865e3> in <module>
     31 probit = MCMC(NUTS(model), 500, 1000, num_chains=1)
     32 with numpyro.validation_enabled():
---> 33     probit.run(random.PRNGKey(1), **dat)

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/mcmc.py in run(self, rng_key, extra_fields, init_params, *args, **kwargs)
    444         map_args = (rng_key, init_state, init_params)
    445         if self.num_chains == 1:
--> 446             states_flat, last_state = partial_map_fn(map_args)
    447             states = tree_map(lambda x: x[jnp.newaxis, ...], states_flat)
    448         else:

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/mcmc.py in _single_chain_mcmc(self, init, args, kwargs, collect_fields)
    311         if init_state is None:
    312             init_state = self.sampler.init(rng_key, self.num_warmup, init_params,
--> 313                                            model_args=args, model_kwargs=kwargs)
    314         if self.postprocess_fn is None:
    315             postprocess_fn = self.sampler.postprocess_fn(args, kwargs)

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/hmc.py in init(self, rng_key, num_warmup, init_params, model_args, model_kwargs)
    448         else:
    449             rng_key, rng_key_init_model = jnp.swapaxes(vmap(random.split)(rng_key), 0, 1)
--> 450         init_params = self._init_state(rng_key_init_model, model_args, model_kwargs, init_params)
    451         if self._potential_fn and init_params is None:
    452             raise ValueError('Valid value of `init_params` must be provided with'

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/hmc.py in _init_state(self, rng_key, model_args, model_kwargs, init_params)
    411                 init_strategy=self._init_strategy,
    412                 model_args=model_args,
--> 413                 model_kwargs=model_kwargs)
    414             if self._init_fn is None:
    415                 self._init_fn, self._sample_fn = hmc(potential_fn_gen=potential_fn,

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/util.py in initialize_model(rng_key, model, init_strategy, dynamic_args, model_args, model_kwargs)
    428                                                                   model_args=model_args,
    429                                                                   model_kwargs=model_kwargs,
--> 430                                                                   prototype_params=prototype_params)
    431 
    432     if not_jax_tracer(is_valid):

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/util.py in find_valid_initial_params(rng_key, model, init_strategy, enum, model_args, model_kwargs, prototype_params)
    255     # Handle possible vectorization
    256     if rng_key.ndim == 1:
--> 257         (init_params, pe, z_grad), is_valid = _find_valid_params(rng_key, exit_early=True)
    258     else:
    259         (init_params, pe, z_grad), is_valid = lax.map(_find_valid_params, rng_key)

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/util.py in _find_valid_params(rng_key, exit_early)
    250         # XXX: this requires compiling the model, so for multi-chain, we trace the model 2-times
    251         # even if the init_state is a valid result
--> 252         _, _, (init_params, pe, z_grad), is_valid = while_loop(cond_fn, body_fn, init_state)
    253         return (init_params, pe, z_grad), is_valid
    254 

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/util.py in while_loop(cond_fun, body_fun, init_val)
    120         return val
    121     else:
--> 122         return lax.while_loop(cond_fun, body_fun, init_val)
    123 
    124 

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/lax/lax_control_flow.py in while_loop(cond_fun, body_fun, init_val)
    269   init_avals = tuple(_map(_abstractify, init_vals))
    270   cond_jaxpr, cond_consts, cond_tree = _initial_style_jaxpr(cond_fun, in_tree, init_avals)
--> 271   body_jaxpr, body_consts, body_tree = _initial_style_jaxpr(body_fun, in_tree, init_avals)
    272   if not treedef_is_leaf(cond_tree) or len(cond_jaxpr.out_avals) != 1:
    273     msg = "cond_fun must return a boolean scalar, but got pytree {}."

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/lax/lax_control_flow.py in _initial_style_jaxpr(fun, in_tree, in_avals)
     70 @cache()
     71 def _initial_style_jaxpr(fun: Callable, in_tree, in_avals):
---> 72   jaxpr, out_avals, consts, out_tree = _initial_style_open_jaxpr(fun, in_tree, in_avals)
     73   closed_jaxpr = core.ClosedJaxpr(pe.convert_constvars_jaxpr(jaxpr), ())
     74   return closed_jaxpr, consts, out_tree

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/lax/lax_control_flow.py in _initial_style_open_jaxpr(fun, in_tree, in_avals)
     65 def _initial_style_open_jaxpr(fun: Callable, in_tree, in_avals):
     66   wrapped_fun, out_tree = flatten_fun_nokwargs(lu.wrap_init(fun), in_tree)
---> 67   jaxpr, out_avals, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals)
     68   return jaxpr, out_avals, consts, out_tree()
     69 

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/interpreters/partial_eval.py in trace_to_jaxpr_dynamic(fun, in_avals)
    992     main.source_info = fun_sourceinfo(fun.f)  # type: ignore
    993     main.jaxpr_stack = ()  # type: ignore
--> 994     jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
    995     del main
    996   return jaxpr, out_avals, consts

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/interpreters/partial_eval.py in trace_to_subjaxpr_dynamic(fun, main, in_avals)
   1002     trace = DynamicJaxprTrace(main, core.cur_sublevel())
   1003     in_tracers = map(trace.new_arg, in_avals)
-> 1004     ans = fun.call_wrapped(*in_tracers)
   1005     out_tracers = map(trace.full_raise, ans)
   1006   jaxpr, out_avals, consts = frame.to_jaxpr(in_tracers, out_tracers)

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    149 
    150     try:
--> 151       ans = self.f(*args, **dict(self.params, **kwargs))
    152     except:
    153       # Some transformations yield from inside context managers, so we have to

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/util.py in body_fn(state)
    233 
    234         potential_fn = partial(potential_energy, model, model_args, model_kwargs, enum=enum)
--> 235         pe, z_grad = value_and_grad(potential_fn)(params)
    236         z_grad_flat = ravel_pytree(z_grad)[0]
    237         is_valid = jnp.isfinite(pe) & jnp.all(jnp.isfinite(z_grad_flat))

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/traceback_util.py in reraise_with_filtered_traceback(*args, **kwargs)
    135   def reraise_with_filtered_traceback(*args, **kwargs):
    136     try:
--> 137       return fun(*args, **kwargs)
    138     except Exception as e:
    139       if not is_under_reraiser(e):

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/api.py in value_and_grad_f(*args, **kwargs)
    802     tree_map(partial(_check_input_dtype_grad, holomorphic), dyn_args)
    803     if not has_aux:
--> 804       ans, vjp_py = _vjp(f_partial, *dyn_args)
    805     else:
    806       ans, vjp_py, aux = _vjp(f_partial, *dyn_args, has_aux=True)

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/api.py in _vjp(fun, has_aux, *primals)
   1846   if not has_aux:
   1847     flat_fun, out_tree = flatten_fun_nokwargs(fun, in_tree)
-> 1848     out_primal, out_vjp = ad.vjp(flat_fun, primals_flat)
   1849     out_tree = out_tree()
   1850   else:

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/interpreters/ad.py in vjp(traceable, primals, has_aux)
    108 def vjp(traceable, primals, has_aux=False):
    109   if not has_aux:
--> 110     out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
    111   else:
    112     out_primals, pvals, jaxpr, consts, aux = linearize(traceable, *primals, has_aux=True)

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/interpreters/ad.py in linearize(traceable, *primals, **kwargs)
     95   _, in_tree = tree_flatten(((primals, primals), {}))
     96   jvpfun_flat, out_tree = flatten_fun(jvpfun, in_tree)
---> 97   jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
     98   out_primals_pvals, out_tangents_pvals = tree_unflatten(out_tree(), out_pvals)
     99   assert all(out_primal_pval.is_known() for out_primal_pval in out_primals_pvals)

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/interpreters/partial_eval.py in trace_to_jaxpr(fun, pvals, instantiate)
    402   with core.new_main(JaxprTrace) as main:
    403     fun = trace_to_subjaxpr(fun, main, instantiate)
--> 404     jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
    405     assert not env
    406     del main

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    149 
    150     try:
--> 151       ans = self.f(*args, **dict(self.params, **kwargs))
    152     except:
    153       # Some transformations yield from inside context managers, so we have to

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/util.py in potential_energy(model, model_args, model_kwargs, params, enum)
    155     substituted_model = substitute(model, substitute_fn=partial(_unconstrain_reparam, params))
    156     # no param is needed for log_density computation because we already substitute
--> 157     log_joint, model_trace = log_density_(substituted_model, model_args, model_kwargs, {})
    158     return - log_joint
    159 

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/util.py in log_density(model, model_args, model_kwargs, params)
     58                 log_prob = site['fn'].log_prob(value, intermediates)
     59             else:
---> 60                 log_prob = site['fn'].log_prob(value)
     61 
     62             if (scale is not None) and (not is_identically_one(scale)):

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/distributions/util.py in wrapper(self, *args, **kwargs)
    523         if self._validate_args:
    524             value = kwargs['value'] if 'value' in kwargs else args[0]
--> 525             mask = self._validate_sample(value)
    526             log_prob = jnp.where(mask, log_prob, -jnp.inf)
    527         return log_prob

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/distributions/distribution.py in _validate_sample(self, value)
    244         mask = self.support(value)
    245         if not_jax_tracer(mask):
--> 246             if not jnp.all(mask):
    247                 warnings.warn('Out-of-support values provided to log prob method. '
    248                               'The value argument should be within the support.')

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/core.py in __bool__(self)
    505   def __getitem__(self, idx): return self.aval._getitem(self, idx)
    506   def __nonzero__(self): return self.aval._nonzero(self)
--> 507   def __bool__(self): return self.aval._bool(self)
    508   def __int__(self): return self.aval._int(self)
    509   def __long__(self): return self.aval._long(self)

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/core.py in error(self, arg)
    862                       f"or `jnp.array(x, {fun.__name__})` instead.")
    863   def error(self, arg):
--> 864     raise_concretization_error(arg, fname_context)
    865   return error
    866 

/anaconda3/envs/numpyro04/lib/python3.7/site-packages/jax/core.py in raise_concretization_error(val, context)
    851          "See https://jax.readthedocs.io/en/latest/faq.html#abstract-tracer-value-encountered-where-concrete-value-is-expected-error for more information.\n\n"
    852           f"Encountered tracer value: {val}")
--> 853   raise ConcretizationTypeError(msg)
    854 
    855 

ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected.

The problem arose with the `bool` function. 

While tracing the function body_fn at /anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/infer/util.py:209, this value became a tracer due to JAX operations on these lines:

  operation rc:bool[] = reduce_and[ axes=(0,) ] rb:bool[753]
    from line /anaconda3/envs/numpyro04/lib/python3.7/site-packages/numpyro/distributions/distribution.py:246 (_validate_sample)

You can use transformation parameters such as `static_argnums` for `jit` to avoid tracing particular arguments of transformed functions.

See https://jax.readthedocs.io/en/latest/faq.html#abstract-tracer-value-encountered-where-concrete-value-is-expected-error for more information.

Encountered tracer value: Traced<ShapedArray(bool[])>with<DynamicJaxprTrace(level=1/0)>

**Comment by fehiepsi** [comment]
Thanks, @hyperfra! It is really helpful. I think we can fix this issue.
