### ISSUE TITLE
Need some help understanding the code behind BNN!

### ISSUE THREAD

**Issue by Nikolin4** [pyro-ppl/numpyro#787]
Hi Numpyro Community,

I am using bayesian neural network  from  http://pyro.ai/numpyro/examples/bnn.html, and I am trying to understand from the documentations the following functions. For some of you, this issue might not be a hard issue, but this is the case for me since I am just learning the MCMC.

```python
def run_inference(model, args, rng_key, X, Y, D_H):
    start = time.time()
    kernel = NUTS(model)
    mcmc = MCMC(kernel, args.num_warmup, args.num_samples, num_chains=args.num_chains,
                progress_bar=False if "NUMPYRO_SPHINXBUILD" in os.environ else True)
    mcmc.run(rng_key, X, Y, D_H)
    mcmc.print_summary()
    print('\nMCMC elapsed time:', time.time() - start)
    return mcmc.get_samples()
```
and 
```python
def predict(model, rng_key, samples, X, D_H):
    model = handlers.substitute(handlers.seed(model, rng_key), samples)
    # note that Y will be sampled in the model because we pass Y=None here
    model_trace = handlers.trace(model).get_trace(X=X, Y=None, D_H=D_H)
    return model_trace['Y']['value']
```
I might not be very clear with my questions, but I kindly ask you to try to explain as good you can.

Questions, part 1.
 The function ```python run_inference(model, args, rng_key, X, Y, D_H)``` takes a model bnn, args, rng_key, input data X, the labels Y, and the number of nodes for each layer in bnn.
We have the kernel NUTS, or the algorithm NUTS as an argument of MCMC, which in my understanding is the Hamiltonian Monte Carlo algorithm. 

This is somewhat unclear to me, what is MCMC in this instance, and what does MCMC do in this particular case alongside with ```python mcmc.run(rng_key, X, Y, D_H) ``` ?
Does ```python mcmc.run ``` adapts steps size and mass matrix ?

Furthermore, what does    ```python  mcmc.get_samples() ``` 
Does ```python  mcmc.get_samples() ``` collects the sampling from the posterior distribution ?

Questions about 
```python def predict(model, rng_key, samples, X, D_H)```

This line 
```python model = handlers.substitute(handlers.seed(model, rng_key), samples) ``` 
puzzles me. What does this line of code do ?

What does this line of code
  ```python model_trace = handlers.trace(model).get_trace(X=X, Y=None, D_H=D_H)```
do too ?

My questions might not be very clear because of my inability to understand the MCMC algorithms, as well as the inability of my programming skill, but please try to explain as much you can. It also be beneficial if you also explain the algortinm behind this code.
I hope to hear from you!
Best regards

**Comment by fehiepsi** [comment]
Hi @Nikolin4, I think the [bayesian regression](http://pyro.ai/numpyro/bayesian_regression.html) tutorial answers all of your questions: what MCMC does, what those handlers do in `Predictive` section,... Please let us know if you need us clarify any point in that tutorial. :)

**Comment by Nikolin4** [comment]
@fehiepsi Thank you for your quick reply!
I will have a look at the tutorial you referred me, and I will be back with any question if not understood, thank you again

**Comment by fehiepsi** [comment]
Hi @Nikolin4, if you have any further questions, you can use Pyro [forum](https://forum.pyro.ai/). It is a great resource to look for solutions and discussions. :)
