### ISSUE TITLE
Warn on missing plate

### ISSUE THREAD

**Issue by akotlar** [pyro-ppl/numpyro#790]
Requested by @fehiepsi: Briefly, for models with discrete latent variables, sampling outside of plate context yields some fairly confusing stack traces during inference. Numpyro could instead warn during model validation. 

https://forum.pyro.ai/t/global-latent-variables-numpyro-crash/2313

**Comment by fehiepsi** [comment]
Thanks, @akotlar!

**Comment by akotlar** [comment]
Thank you Du!
