### ISSUE TITLE
Simplify the patterns with PRNGIdentity

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#798]
Currently, `PRNGIdentity` is a special distribution that returns a random key under `seed` handler. One issue with it is we need to have extra logics to filter this site out at various places. For examples at
+ [elbo](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/elbo.py#L159)
+ [log_density](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/util.py#L53)
+ autoguide [here](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/util.py#L53) and [here](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/util.py#L53)
+ [get model's transform](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/util.py#L271)
and I think we will get some issues if we use `contrib.funsor` with this distribution.

We can add "filter-out" logics to those places (there are only a few of them) but I think it is easy to forget. In addition, if this site appears under `plate` statement, then it becomes an `ExpandedDistribution`, so the logics at above places do not apply anymore.

This issue is created to discuss about ways to simplify the pattern of using PRNGIdentity. Currently, generating a random key is only used in AutoGuide and `numpyro.module`, so I think we are flexible to create a new pattern for it. One possible solution is to make a primitive to generate a PRNGKey, instead of relying on `sample` primitive.

**Comment by fritzo** [comment]
:+1: to creating new primitives rather than overloading `sample()`. I think @eb8680 and I have concluded that `_Subsample` distributions were a bad idea (e.g. requiring `prune_subsample_sites()`), and that it is less error-prone to introduce new primitives like `pyro.subsample()` and `pyro.barrier()`.

**Comment by fehiepsi** [comment]
Thanks, @fritzo. Let me make a draft to see if using a primitive, we can avoid the above overheads.
