### ISSUE TITLE
Magic number in svi.run

### ISSUE THREAD

**Issue by xidulu** [pyro-ppl/numpyro#814]
Progress bar mode in svi.run contains a magic number 20 at 

https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/svi.py#L177

Does that number describes the logging frequency I guess? If so, I think maybe it's better to turn it into a user-defined args.

**Comment by fehiepsi** [comment]
> Does that number describes the logging frequency I guess?

Yes. Currently, `svi.run` is experimental and just a convenient function (especially for ones who are familiar with NumPy but not familiar with JAX) so we don't want to populate its arguments. A high-level inferface (some discussions about it can be found in #792) might be incorporated in the future if needed.

**Comment by xidulu** [comment]
@fehiepsi 

> Did you find 5% makes the report fast or slow?

The report rate is OK for me.

Btw, would the verbose mode slow down the performance, since it uses native for loop instead of jax.scan()?

**Comment by fehiepsi** [comment]
Yes, it will slow things down a bit, less than 1ms per step I guess. Unless your model is small and needs a large number of steps to converge, the difference is small.

**Comment by xidulu** [comment]
@fehiepsi 
Thanks for ur info
My questions are resolved. 😀
