### ISSUE TITLE
Example suggestion - Cycling

### ISSUE THREAD

**Issue by caxelrud** [pyro-ppl/numpyro#825]
Hi, I looking for help to translate to Numpyro an example from "Infer.net" that I coded, some time ago, in F#.
The code is attached.
The example is simple but covers all cases that I am looking for including:
-	Obtains approximate probability distributions.
-	Uses a hierarchical model. 
-	Does online-learning of the model using Bayesian statistics (even with missing values).
-	Predicts the next measurement probability distribution. 
-	Allows the calculation of probabilistic queries about the next measurement as “will it be higher than a certain value?”.
-	Does model comparison.
-	Allows the calculation of probabilistic comparison between things as “who will have the highest measurement?”
-	Allows retraction of any (one or more) variable the system including inputs.
-	Ability to create entities (a cyclist) that can be added as needed.

Thanks!

[Infer_Cycling_0_2_fsx.txt](https://github.com/pyro-ppl/numpyro/files/5589542/Infer_Cycling_0_2_fsx.txt)

**Comment by fehiepsi** [comment]
> The example is simple

Almost 600 lines of code might be not that simple. :D Could you try to see which functionality that you need to support, then open feature requests for them? Please also use our active [forum](https://forum.pyro.ai/) for asking questions and discussions.

**Comment by caxelrud** [comment]
Hi,
I divided the example in part in order to make my questions and discussions objective.
The following code starts with the model [1]. 
Then the code does: 
- add evidences and execute [2], 
- modify the model and execute [3],
- evaluate a logic question within the model [4],
- clear the evidence of an input (retract) and execute to infer this input.

I need help to write these functionalities with numpyro. Thanks!

`//-----------------------------------------------------------------------------------
// CyclingTime 1

// [1] The model
let averageTime =  Variable.GaussianFromMeanAndPrecision(15.0, 0.01).Named("AverageTime")
let trafficNoise = Variable.GammaFromShapeAndScale(2.0, 0.5).Named("trafficNoise") 
let travelTimeMonday = Variable.GaussianFromMeanAndPrecision(averageTime, trafficNoise).Named("TravelTimeMon")
let travelTimeTuesday = Variable.GaussianFromMeanAndPrecision(averageTime, trafficNoise).Named("TravelTimeTue")
let travelTimeWednesday = Variable.GaussianFromMeanAndPrecision(averageTime, trafficNoise).Named("TravelTimeWed")

// [2] Train the model
travelTimeMonday.ObservedValue <- 13.0
travelTimeTuesday.ObservedValue <- 17.0
travelTimeWednesday.ObservedValue <- 16.0

let engine = InferenceEngine()

let averageTimePosterior = engine.Infer<Gaussian>(averageTime);
let trafficNoisePosterior = engine.Infer<Gamma>(trafficNoise);

printfn "averageTimePosterior (mean,variance): %A" averageTimePosterior
printfn "trafficNoisePosterior: %A" trafficNoisePosterior
(*
averageTimePosterior: Gaussian(15.33, 1.32)
trafficNoisePosterior: Gamma(2.242, 0.2445)[mean=0.5482]  
*)

// [3] Add a prediction variable and retrain the model
let tomorrowsTime = Variable.GaussianFromMeanAndPrecision(averageTime,trafficNoise).Named("TomorrowsTime")
let tomorrowsTimeDist = engine.Infer<Gaussian>(tomorrowsTime)
let tomorrowsMean = tomorrowsTimeDist.GetMean()
let tomorrowsStdDev = Math.Sqrt(tomorrowsTimeDist.GetVariance())
printfn "Tomorrows predicted time: %f plus or minus %f" tomorrowsMean tomorrowsStdDev
(*
Tomorrows predicted time: 15.326309 plus or minus 2.147767
*)

// [4] You can also ask other questions of the model 
let probTripTakesLessThan18Minutes = engine.Infer<Bernoulli>(tomorrowsTime << 18.0).GetProbTrue()
printfn "Probability that the trip takes less than 18 min: %f" probTripTakesLessThan18Minutes
(*
Probability that the trip takes less than 18 min: 0.893410
*)

// [5] INPUT RETRACTION
//Add observed value for tomorrowsTime (CA)
tomorrowsTime.ObservedValue <- tomorrowsMean
// Clear TimeWednesday
travelTimeWednesday.ClearObservedValue()
let travelTimeWednesdayDist = engine.Infer<Gaussian>(travelTimeWednesday)
(*
val travelTimeWednesdayDist : Gaussian = Gaussian(15.11, 4.301)
*)
`

**Comment by caxelrud** [comment]
Hi,
To add some context.
My objective, after obtaining the model, is to use it to verify the likelihood for one complete set of input evidences. And, eliminate the evidence of one input at a time (retraction) and do inference of this input and compare with the actual evidence.

**Comment by fehiepsi** [comment]
Hi @caxelrud, those lecture notes about [causal inference](https://bookdown.org/robertness/causalml/docs/) might be also helpful for you. I would suggest raising questions in [the forum](https://forum.pyro.ai/). We mainly use github to track the issues and feature requests.

**Comment by caxelrud** [comment]
Hi,
I realized that Probabilistic Programming Languages (PPL), as Numpyro, are powerful but they are not necessarily Graphs (or Networks). There are some features that are ease in Graphs and not as easy in PPL (by design).
The example that I proposed is a good fit for Infer.Net (based on Factor Graphs) including variable retraction and online learning.
For PPL, it will require rewriting/re-arranging the model code.

**Comment by fehiepsi** [comment]
Thanks for suggesting the example, @caxelrud! It looks like that this example is not easy to model and perform inference in NumPyro (I assume). Please feel free to reopen this issue if you think we can address some features of the topic comment. :)
