### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by ab-10** [pyro-ppl/numpyro#834]
It would be useful to have CONTRIBUTING.md for this project.

The [Pyro CONTRIBUTING.md](https://github.com/pyro-ppl/pyro/blob/dev/CONTRIBUTING.md) can serve as a nice template here.

If the maintainers of the project are happy with the idea, I can draft a version in a form of a PR.

**Comment by fehiepsi** [comment]
Thanks for volunteering @ab-10! Please go ahead. This is definitely needed.
