### ISSUE TITLE
Broken install under Python 3.9

### ISSUE THREAD

**Issue by lumip** [pyro-ppl/numpyro#838]
When I try to install numpyro in a Python 3.9 environment, I get a messed up installation of incompatible packages. The following have been my steps:
```
conda create --name numpyro-py39 python=3.9
conda activate numpyro-py39
pip install numpyro --no-cache
```
The outcome of this are the following installed packages
```
jax==0.1.35
jaxlib==0.1.57
numpyro==0.1.0
```
Now, this version of jaxlib is incompatible with that version of jax and, of course, I would like to have the most recent version of numpyro to work with.

It seems the following is what happens: The jax authors have not provided versions of jaxlib previous to 0.1.57 for Python 3.9 on the package index. The latest version of numpyro (0.4.1) requires jaxlib 0.1.56, which is thus not available. Pip goes through the available versions, not finding possible configuration until it reaches numpyro version 0.1.0, which does not fix a specific version of jaxlib (but is fine with `jaxlib>=0.1.14`, and requires `jax==0.1.35`, which itself does not constrain the jaxlib version).

As a quick fix, would you consider bundling up a 0.4.2 version with updated jax and jaxlib dependencies that installs on Python 3.9?

**Comment by fehiepsi** [comment]
Hi @lumip, I would like to hold this until the next jaxlib release. The last jaxlib version has a regression issue regarding compiling time. If you want to use numpyro now, I think you can install the master version with `pip install git+https://github.com/pyro-ppl/numpyro.git`.

- [ ] we should also pump up [those numbers](https://github.com/pyro-ppl/numpyro/blob/master/setup.py#L71) too.

**Comment by lumip** [comment]
I can see where you're coming from, but now it boils down to having no version of numpyro for Python 3.9 rather than one that compiles slowly (at least not from official installation channels)?

Installing from git is something I'd like to avoid as I'm looking for something I can put in my own setup.py that doesn't change from under my feet as numpyro evolves.

**Comment by fehiepsi** [comment]
> having no version of numpyro for Python 3.9

Agree, I guess we should say something like supporting 3.9 is in development, probably after the supported jaxlib version is more stable. In setup.py, you might add `python <= 3.8` for now.
