### ISSUE TITLE
MVN doesn't support batched scale_tril

### ISSUE THREAD

**Issue by quattro** [pyro-ppl/numpyro#862]
Hi,

I'm trying to performed batched sampling using the Cholesky decomposition formulation and running into issues. The following code works fine,

```python
    # build MVN params for batched sample
    def build_mvn_params(name, shape):
        covs = []
        mus = numpyro.param(f"mu_{name}", jnp.zeros(shape))
        for idx in range(shape[0]):
            covs.append(numpyro.param(f"cov_{name}_{idx}", jnp.eye(shape[1]), constraint=constraints.positive_definite))

        return mus, covs

    # sample posteriors for W; we can batch across dimensions under a single sample by concatenating means and covs
    mus_w, covs_w = build_mvn_params("w", (j, k))
    numpyro.sample("W", dist.MultivariateNormal(mus_w, covs_w))
```

But swapping out for

```python
            covs.append(numpyro.param(f"cov_lchol_{name}_{idx}", jnp.eye(shape[1]), constraint=constraints.lower_cholesky))
``` 
and
```python
    numpyro.sample("W", dist.MultivariateNormal(mus_w, scale_tril=covs_w))
```

Results in the following error: ```TypeError: matmul requires ndarray or scalar arguments, got <class 'list'> at position 0.```

**Comment by fehiepsi** [comment]
@quattro Could you make a replicable code? There might be a bug somewhere with `scale_tril` but it is hard to tell...

**Comment by quattro** [comment]
A bit of debugging found the issue. 

Right now a user can pass in a list of covariance matrices (one for each batch dim) and MVN's private Cholesky decomposition enforces that the result is a proper batched DeviceArray (at continuous.py:715). If a user directly passes in a list of lower triangular matrices, there is no conversion to a single batched DeviceArray (at continuous.py:720), which breaks downstream sampling.

I can just make sure my code passes in a DeviceArray for now, but might be worth adding a check/validation on arguments.

**Comment by fehiepsi** [comment]
It is interesting that we can pass a list of covariance matrices. I didn't expect that to work. In NumPyro, all parameters are ndarray.

> adding a check/validation on arguments.

If you enable validation `numpyro.enable_validation()`, you might trigger a warning or an error for an invalid `covariance_matrix`. :) Anyway, glad that you found the issue. :+1:
