### ISSUE TITLE
Clarify meaning of "experimental" for chain_method='vectorized'

### ISSUE THREAD

**Issue by martiningram** [pyro-ppl/numpyro#863]
Hi numpyro team,

First off, thanks a lot for your work -- so far, the NUTS sampler you have written has been great to use!

I wanted to ask about some clarification about why `chain_method='vectorized'` for the `mcmc` function (https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/mcmc.py#L198) is labelled experimental in the docstring. In particular, is there a reason to believe that its estimates are in any way compromised compared to `parallel` or `sequential`? As someone who tends to have access to one GPU only, I've found it much faster than running the chains in sequence, but I'm a little concerned about it perhaps being less reliable somehow. Should I be testing the results against the `parallel` implementation, or should `vectorized` be fine to use?

Thanks!

**Comment by fehiepsi** [comment]
Hi @martiningram, I think it would be safe to use, though I didn't play much with that option. In GPU, it might be fast in small models but usually in CPU, it will be slower than other options.

**Comment by martiningram** [comment]
@fehiepsi that's very helpful, thanks! It certainly seems to be much faster for me than running things in sequence on a single GPU. Good to hear the experimental label applies only to performance. That answers my question -- please feel free to close the issue if you like!
