### ISSUE TITLE
Expose Tree Depth as additional MCMC diagnostics

### ISSUE THREAD

**Issue by mdenhollander** [pyro-ppl/numpyro#864]
Currently, the diagnostics that are available for the MCMC sampler do not include any information about the tree_depth per iteration. 

This information would be highly useful, since the tree depth values can give important insights on the state of the sampler, next to information like the divergences, effective sample size and acceptance probability.

The tree depth is already calculated in the hmc.py script. Hence, it should mostly be a matter of adapting the MCMC class, such that the "get_diagnostics()" or "get_extra_fields()" also return the values of the tree depths for every iteration.

Many thanks in advance!

**Comment by fehiepsi** [comment]
Hi @mdenhollander, you can collect `num_steps` and compute
```python
tree_depth = np.log2(num_steps).astype(int) + 1
```
I think we should add a better doc to [HMCState](http://num.pyro.ai/en/latest/mcmc.html#numpyro.infer.hmc.HMCState) to reflect this fact. What do you think?

**Comment by mdenhollander** [comment]
Hi @fehiepsi, thank you for your quick response.

You are indeed right that the tree_depth can be easily computed based on the number of trajectory steps, but this is something that could potentially be overlooked. I believe adding some information about this to the documentation would therefore be extremely helpful.

Thanks!
