### ISSUE TITLE
Looking for example of mini-batch training with SVI

### ISSUE THREAD

**Issue by vitkl** [pyro-ppl/numpyro#869]
Hi numpyro team!

I am interested in doing mini-batch training with both local and global variables. Ideally using Pytorch style with DataLoader to avoid copying all data to GPU and `lax.scan` for speed. Any related examples would be appreciated!

I have this in mind but not sure if it could work:
```
# from jax tutorials
def numpy_collate(batch):
    if isinstance(batch[0], jnp.ndarray):
        return jnp.stack(batch)
    elif isinstance(batch[0], (tuple, list)):
        transposed = zip(*batch)
        return [numpy_collate(samples) for samples in transposed]
    else:
        return jnp.array(batch)
        
class NumpyLoader(DataLoader):
    def __init__(self, dataset, batch_size=1,
                 shuffle=False, sampler=None,
                 batch_sampler=None, num_workers=0,
                 pin_memory=False, drop_last=False,
                 timeout=0, worker_init_fn=None):
        super(self.__class__, self).__init__(dataset,
                                             batch_size=batch_size,
                                             shuffle=shuffle,
                                             sampler=sampler,
                                             batch_sampler=batch_sampler,
                                             num_workers=num_workers,
                                             collate_fn=numpy_collate,
                                             pin_memory=pin_memory,
                                             drop_last=drop_last,
                                             timeout=timeout,
                                             worker_init_fn=worker_init_fn)

loader = DataLoader(dataset, batch_size=256)
state, losses = lax.scan(lambda state_1, batch: self.svi[name].update(state_1, batch),
                                         init_state, loader)
```

The example here looks rather convoluted because it is not clear what are the requirements for `train_fetch` https://github.com/pyro-ppl/numpyro/blob/master/examples/vae.py#L89.

**Comment by fehiepsi** [comment]
> to avoid copying all data to GPU and lax.scan for speed

I don't know how to use `lax.scan` and avoid copying all data to GPU. I think you can raise this question upstream to JAX. I just guess that it is not possible.

About examples, you can jump around flax/haiku repository to find a pattern that is most suited for your problem.

**Comment by vitkl** [comment]
I see. Thanks for explaining! 

With regard to speedup, `lax.scan` https://github.com/vitkl/cell2location_numpyro/blob/main/cell2location_numpyro/models/pyro_model.py#L234-L245 for my problem takes roughly 15 minutes on GPU whereas wrapping `svi.update` in `jit` (https://github.com/vitkl/cell2location_numpyro/blob/main/cell2location_numpyro/models/pyro_model.py#L247-L255, https://github.com/vitkl/cell2location_numpyro/blob/main/cell2location_numpyro/models/pyro_model.py#L301-L309) takes hours on GPU. Maybe I am doing something else incorrectly.
I will try `svi.update` in `jit` with minibatch data.

**Comment by fehiepsi** [comment]
I was seeing you redefined `body_fn` in [each step](https://github.com/vitkl/cell2location_numpyro/blob/main/cell2location_numpyro/models/pyro_model.py#L305), so `jit` will not hit the cache. You can do something like
```python
jit_step_update = jit(self.step_update, static_argnums=(0, 3))
for e in epochs_iterator:
    self.state[name], loss = jit_step_update(self.svi[name],
                                             self.state[name],
                                             self.x_data,
                                             self.extra_data)
```

**Comment by fehiepsi** [comment]
Interesting! I have an impression for a long time that using `jit(update)` alone only adds dispatching cost, which moves the loss from GPU to CPU, is very small comparing to time to perform an actual svi.update. Assume that you did SVI with 100000 steps, then the additional cost takes 10ms per svi step, which is quite large in my opinion. I am not sure what is the reasoning behind that cost. Just curious, what happens when you removed those tqdm stuffs?

**Comment by vitkl** [comment]
That's right, I am doing 30k iterations (full data 6486 obs * 6303 var, not minibatch). Removing tqdm does not change anything.

I omitted one important detail previously, I am adding the following flags:
```
os.environ["JAX_PLATFORM_NAME"] = "gpu"
os.environ["XLA_PYTHON_CLIENT_ALLOCATOR"]="platform" 
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"]="false" # without this all GPU memory is reserved (e.g. 32 GB)
```

It looks like `os.environ["XLA_PYTHON_CLIENT_ALLOCATOR"]="platform" ` has most substantial effects:
1. Removing this flag equalised the speed difference between `svi.update in jit` and `lax.scan` - to 8 min for both.
2. Removing it also increased the GPU memory utilisation for `svi.update in jit` from 4.4 to 9.2 GB. I also see that the memory utilisation fluctuates between 2.4 and 4.4 GB when this flag is set - potentially indicating that some data is moved in and out of memory (which could explain lower speed).
3. Removing it also increased the GPU memory utilisation for `lax.scan` from 4.4 to 9.2 GB

**Comment by fehiepsi** [comment]
Interesting! Thanks for your info. I just learn that there are those settings in JAX. Looking like in [jax docs](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html#gpu-memory-allocation), they said `platform` is very slow and is not recommended for general use. :D

Looking like this issue is clearer now. To avoid copying all data to GPU, you need to `jit` body function instead of using `scan`. With `platform` (28 min), it is 2x slower than `pymc3`, which takes `14 min`, while without `platform` (9 min), it is 1.5x faster than `pymc3`. I guess you can set `XLA_PYTHON_CLIENT_MEM_FRACTION=.XX` as in [its docs](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html#gpu-memory-allocation) to decide how much memory to use in your problem.

**Comment by vitkl** [comment]
I will try to summarise the note for SVI.run next week.

We will implement the minibatch training in our repo within the next 2-3 weeks and then it can be added as example somewhere. So far I did tests on all data rather than minibatch. Our package aims to provide general training code for many similar models so it won't be a minimal example of minibatch training - but we can try to distil the relevant code and add somewhere as an example. Would that be useful?

**Comment by fehiepsi** [comment]
Please just stick with what is convenient for you. It would be also nice if you share some of the best practices in the READMEof your repository (or any other form). Then we can add link in numpyro README pointing to your repository, to illustrate numpyro usage on GPU in real application. I believe either way would be useful for many users. When someone asks, we can point to those best practices. :)

**Comment by fehiepsi** [comment]
I guess the questions have been clarified. Please feel free to reopen the issue or use forum if there are follow-up questions.
