### ISSUE TITLE
Update distribution api with new upstream changes

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#874]
This tracks some enhancemences in PyTorch/Pyro distributions. Some are required by `funsor`. Some are changed for consistency.
- [x] `.infer_shapes()` https://github.com/pyro-ppl/pyro/pull/2739
- [x] `Transform.inv`  #164
- [x] Move `is_discrete` to constraints (deprecate `Distribution.is_discrete`?)
- [x] Add `event_dim` to constraint (remove transforms' input_event_dim/output_event_dim?)

**Comment by fritzo** [comment]
@fehiepsi I'll try to submit a `Transforms` PR to PyTorch tomorrow, where we can discuss the Transforms api. I like your idea of getting rid of `.input_event_dim` and `.output_event_dim`, and I think we can even deprecate `.event_dim`.

**Comment by fehiepsi** [comment]
Thanks, @fritzo, for resolving this issue!
