### ISSUE TITLE
UnexpectedTracerError with DiscreteHMCGibbs, a latent discrete variable with more than 1 dim, and num_chains>1

### ISSUE THREAD

**Issue by rexdouglass** [pyro-ppl/numpyro#907]
The combination of 
1) A latent discrete variable with event_shape > 1x
2) num_chains>1

Throws the following error
#UnexpectedTracerError: Encountered an unexpected tracer. Perhaps this tracer escaped through global state from a previously traced function.
#The functions being transformed should not save traced values to global state. Detail: tracer created on line /home/skynet3/numpyro/numpyro/infer/hmc_gibbs.py:356 (<dictcomp>).

Minimally reproducible example
```
import os
import numpyro
import jax
from jax import random
import jax.numpy as jnp
import numpyro.distributions as dist
from numpyro.infer import DiscreteHMCGibbs, MCMC, NUTS
numpyro.set_platform("gpu") 
numpyro.set_host_device_count(2) 
print(jax.__version__) #0.2.8
print(numpyro.__version__) #0.5.0
print(jax.config.FLAGS.jax_backend_target) #local
print(jax.lib.xla_bridge.get_backend().platform) #gpu

#Fails
#UnexpectedTracerError: Encountered an unexpected tracer. Perhaps this tracer escaped through global state from a previously traced function.
#The functions being transformed should not save traced values to global state. Detail: tracer created on line /home/skynet3/numpyro/numpyro/infer/hmc_gibbs.py:356 (<dictcomp>).
def model():
  C = numpyro.sample("C", dist.Bernoulli(probs=0.5 * jnp.ones(5 )  ))
kernel = DiscreteHMCGibbs(NUTS(model), modified=True)
mcmc   = MCMC(kernel, num_warmup=100, num_samples=100, num_chains=2)
mcmc.warmup(random.PRNGKey(0))
mcmc.run(random.PRNGKey(1))
```

The error does not appear if the discrete variable is size 1 or if the number of chains=1. Only the combination of both throws the error

```
#Works
def model():
  C = numpyro.sample("C", dist.Bernoulli(probs=0.5  ))
kernel = DiscreteHMCGibbs(NUTS(model), modified=True)
mcmc   = MCMC(kernel, num_warmup=100, num_samples=100, num_chains=2)
mcmc.warmup(random.PRNGKey(0))
mcmc.run(random.PRNGKey(1))

#Works
def model():
  C = numpyro.sample("C", dist.Bernoulli(probs=0.5 * jnp.ones(5 )  ))
kernel = DiscreteHMCGibbs(NUTS(model), modified=True)
mcmc   = MCMC(kernel, num_warmup=100, num_samples=100, num_chains=1)
mcmc.warmup(random.PRNGKey(0))
mcmc.run(random.PRNGKey(1))
```

**Comment by fehiepsi** [comment]
Thanks, @rexdouglass, for the detailed explanation! I think we should change [jnp.broadcast_to](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/hmc_gibbs.py#L356) to `(import numpy as np) np.broadcast_to` because `jnp.foo` will create a tracer, rather than concrete arrays when running multiple chains. Do you want to submit a fix together with a regression test? :)

**Comment by rexdouglass** [comment]
I can confirm that changing that single line and adding the import for numpy as np resolves the error on both by small test example above as well as that larger covid nowcast I'm working on.

```
name: np.broadcast_to(site["fn"].enumerate_support(False).shape[0], jnp.shape(site["value"])) #changed jnp to np per discussion here https://github.com/pyro-ppl/numpyro/issues/907
```

I did not change the jnp.shape to np, I don't think it matters unless some later jax bug is introduced about mixing and matching.
