### ISSUE TITLE
[FR] Two-sided TruncatedNormal distribution

### ISSUE THREAD

**Issue by njjiang** [pyro-ppl/numpyro#914]
Currently the TruncatedNormal distribution only supports setting the low bound, and adding the high bound is in [a TODO comment](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/distributions/continuous.py#L1155). Is there a plan to add this soon?

**Comment by fehiepsi** [comment]
Hi @njjiang, please follow-up with #895. Looking like it is a useful feature so I'll set a higher priority for that issue.
