### ISSUE TITLE
‘BernoulliLogits’ object has no attribute ‘mask’

### ISSUE THREAD

**Issue by pookiecoding** [pyro-ppl/numpyro#930]
Hello! We are trying this tutorial: https://github.com/pyro-ppl/numpyro/blob/master/notebooks/source/discrete_imputation.ipynb

and we go this error message:
AttributeError: ‘BernoulliLogits’ object has no attribute ‘mask’
in the function impmodel().

Would you have suggestions on how to fix this?
Note: we use numpyro.infer import MCMC, NUTS.
Thank you.

**Comment by fehiepsi** [comment]
Hi @pookiecoding, could you try to update `funsor`? I guess the error happens because of using the old `funsor` version.

**Comment by pookiecoding** [comment]
Yes! that works. We updated our Ubuntu, and funsor. Thank you very much @fehiepsi for quick answer.
