### ISSUE TITLE
DiscreteHMCGibbs Draws Samples of Incorrect Shape

### ISSUE THREAD

**Issue by RylanSchaeffer** [pyro-ppl/numpyro#931]
Opening an issue at the request of Du Phan, based on [our conversation on the forum](https://forum.pyro.ai/t/problem-in-mcmc-sampling-of-categorical-variable/1192/10). The [DiscreteHMCGibbs](http://num.pyro.ai/en/latest/mcmc.html#numpyro.infer.hmc_gibbs.DiscreteHMCGibbs) sampler appears to draw samples of the incorrect shape for the discrete variables. For instance, the demo in the documentation shows returns samples with shape `(number of samples,)` instead of `(number of samples, number of observations)` for the model:

```
def model(probs, locs):
     c = numpyro.sample("c", dist.Categorical(probs))
     numpyro.sample("x", dist.Normal(locs[c], 0.5))
```

I think there should be one sampled Categorical per observation.

**Comment by fehiepsi** [comment]
Thank you, @RylanSchaeffer! Sorry for the late response. I'll address this soon.

**Comment by RylanSchaeffer** [comment]
Thank you!

**Comment by RylanSchaeffer** [comment]
The source of the apparent incorrect shape was that I was unintentionally incorrectly using pyro plates with numpyro plates. Switching to correctly using only numpyro plates solved the apparent bug.
