### ISSUE TITLE
[Feature Request] Observed Deterministic

### ISSUE THREAD

**Issue by peterroelants** [pyro-ppl/numpyro#932]
I have a model where my observed variable is the output of a deterministic function. However it is unclear to me how I can condition the model on my observed samples. Ideally I would like to use something like:
```
y = numpyro.deterministic('y', x, obs=y_obs)
```
Similar to using the `obs` parameter in [`numpyro.sample`](http://num.pyro.ai/en/stable/primitives.html#sample).

Is this something that would be possible to implement?

**Comment by fritzo** [comment]
Hi @peterroelants, this may be possible in some cases via [handlers.collapse](https://num.pyro.ai/en/stable/handlers.html#collapse), but that will only work in special cases of conjugate distributions and a narrow class of deterministic transformations. Can you paste an example with a little more detail, showing (1) the distributions from which `x`'s inputs are drawn; (2) the entire transformation from those inputs to your deterministic `x`; and (3) the distribution in your conditioning `numpyro.sample` statement?

See also
- https://github.com/pyro-ppl/pyro/issues/568
- https://github.com/pyro-ppl/pyro/issues/773
- https://forum.pyro.ai/t/how-should-one-do-inference-when-conditioning-on-a-delta/723

**Comment by peterroelants** [comment]
Hi @fritzo , thank you for providing some more context.
I also have been trying to see if PyMC (which I assume works fairly similar) tackles this problem. I came across [this PyMC forum post](https://discourse.pymc.io/t/observed-deterministic/483) and related [Stack Exchange question](https://stats.stackexchange.com/questions/416725/observed-deterministic-variables-in-mcmc). If I understand correctly the main problem is coming up with a likelihood function for any deterministic function.

My specific use case was shifting a HalfNormal distribution by adding a constant. However, it occurred to my I can avoid this problem by subtracting the same constant from my observations.

**Comment by fehiepsi** [comment]
@peterroelants You can use `TransformedDistribution` as in the last link of @fritzo's comment.
```python
sample("obs", TransformedDistribution(HalfNormal(scale), AffineTransform(loc, 1)), obs=data)
```
Or you can use TruncatedDistribution
```python
sample("obs", TruncatedDistribution(Normal(loc, scale), low=loc), obs=data)
```

**Comment by fehiepsi** [comment]
@peterroelants I think this issue has been resolved. In general, if you have a bijective deterministic transform, you can always use `TransformedDistribution` API to do the job. Please feel free to reopen this again if needed.

**Comment by peterroelants** [comment]
Yes, I have solved my use case.

Thank you for your help!

**Comment by gcskoenig** [comment]
Hi!

Are there any plans to allow observation of deterministic nodes in the future? In general, for Structural Causal Models (Pearl/Spirtes/Peters/...), the most widely adapted graphical causal model, all observable variables are deterministic functions of not observable latent variables, which we would want to infer to compute counterfactuals. For instance, for models with invertible structural equations pyro can be used, however otherwise workarounds (such as introducing pseudo stochastic sample sites with very small variance) have to be used.

**Comment by eb8680** [comment]
@gcskoenig there is no natural way to support a non-approximate version of what you are describing outside of trivial scenarios, e.g. where every random variable is discrete or full-rank linear-Gaussian or every mechanism is invertible. Even [the meaning of conditioning is not always obvious in general](https://dl.acm.org/doi/abs/10.1145/3374208), especially when the event in question has measure 0.

As you observed, you can use `numpyro.sample` or `numpyro.factor` for adding arbitrary soft constraints to any part of your model. [This paper](http://proceedings.mlr.press/v97/tavares19a.html) suggests some standard approximations to hard constraints and an annealing strategy to tighten them as inference progresses. NumPyro's effect handler and reparameterizer APIs would make it easy to package such approximations in a model-agnostic way, though we have no plans to do this ourselves.
