### ISSUE TITLE
[FR] SGLD and SG-MCMC inference in numpyro?

### ISSUE THREAD

**Issue by alshedivat** [pyro-ppl/numpyro#950]
Hi there,

Thanks for creating numpyro!

I'm wondering, is there any interest in supporting SG-MCMC methods (such as SGLD, [IASG](https://www.jmlr.org/papers/volume18/17-214/17-214), etc.) in numpyro?

I searched around a bit, and it seems like the pyro community doesn't find SGLD-style methods as useful (pyro-ppl/pyro#1921). I'd be happy to contribute though if there's any interest at all. Personally, I'd like to use numpyro for [one of my projects](https://blog.ml.cmu.edu/2021/02/19/an-inferential-perspective-on-federated-learning/), which requires SG-MCMC. I have [a custom implementation of IASG](https://github.com/alshedivat/fedpa/blob/master/federated/inference/sampling.py#L95-L174) in JAX, but it would be so much nicer to have it as yet another `infer.mcmc.MCMCKernel`. What do y'all think?

**Comment by fehiepsi** [comment]
Welcome, @alshedivat! When SG-MCMC methods are available, I would like to see how it performs against HMCECS (contributed by @OlaRonning and his team in the last NumPyro release). :D

**Comment by fehiepsi** [comment]
Update: checkout @jeremiecoullon's [SGMCMCJax](https://github.com/jeremiecoullon/SGMCMCJax) for SGLD and SGMCMC! :rocket:

It would be nice to have a tutorial on how to convert a NumPyro model to SGMCMCJax format (logprior / loglikelihood). Currently, we only have [initialize_model](http://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.util.initialize_model) utility to give us a potential function of a model together with initial values. I guess for `logprior`, we can just mask out the likelihood using `numpyro.handlers.mask`.

**Comment by jeremiecoullon** [comment]
Glad that my [SGMCMCJax](https://github.com/jeremiecoullon/SGMCMCJax) library might be helpful here!
A tutorial to convert a NumPyro model to a logprior and a loglikelihood format would be great I agree. This is something that I will try to look into when I find the time (though anyone else: feel free to try this out!).

And I'm also curious to see how the different sgmcmc samplers perform compared to HMCECS

**Comment by fehiepsi** [comment]
NumPyro can be used with other libraries. Please check out https://num.pyro.ai/en/latest/tutorials/other_samplers.html
