### ISSUE TITLE
Unhelpful Error Dirichlet Process Mixture Model

### ISSUE THREAD

**Issue by RylanSchaeffer** [pyro-ppl/numpyro#953]
Following my post here, https://forum.pyro.ai/t/dirichlet-process-gaussian-mixture-model-typeerror-for-small-concentration-parameter/2685, when one tries creating a Dirichlet Process Mixture Model with 0 mixture components, the error message returned is 

`TypeError: iota shape must have every element be nonnegative, got (-1,).`

This isn't helpful in identifying the source of the error. Could a better message be returned?

**Comment by fehiepsi** [comment]
Thank you, @RylanSchaeffer. I think all we need is to add an assertation `size > 0` in the [constructor](https://github.com/pyro-ppl/numpyro/blob/e2e82189e96f45a1d2715c15217b85ed55e9f16e/numpyro/primitives.py#L347) of `plate`.
