### ISSUE TITLE
Allow to set an additional max tree depth during warmup phase

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#960]
This could be useful (needs some experiments though) in cases NUTS trajectories are long and it is slow to collect samples to estimate mass matrix during warmup phase. The side effect can be warmup samples are more correlated, so the estimated mass matrix might be not good.

**Comment by martinjankowiak** [comment]
would this be simple to implement? maybe `max_tree_depth` could be an `int` (default behavior) or a `tuple` of `int`s specifying `(max_tree_depth_warmup, max_tree_depth_post_warmup)`

**Comment by fehiepsi** [comment]
> simple to implement?

You bet. It is [simple](https://github.com/pyro-ppl/numpyro/compare/max-tree-depth?expand=1) :)
