### ISSUE TITLE
Test for collapse beta bernoulli is failing

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#964]
Currently, the test `test/test_handlers.py::test_collapse_beta_binomial` is failing after a change in funsor: https://github.com/pyro-ppl/funsor/pull/491

Investigating...

**Comment by fritzo** [comment]
Possible leads include:
- a [disabled test](https://github.com/pyro-ppl/funsor/pull/491/files#diff-4347c85e3f7c7b6325a851b81efa03efb7bfc4c500dbcfac315fd6b8ac007c91L660) in that funsor PR.
- refactoring of `stack` from a `Function` to a `Funitary(ops.stack)`
