### ISSUE TITLE
[FR] Integrate with new Flax linen

### ISSUE THREAD

**Issue by gustavehug** [pyro-ppl/numpyro#979]
It seems that the Flax [integration](http://num.pyro.ai/en/stable/primitives.html?highlight=flax#random-flax-module) leverages the now [deprecated](https://flax.readthedocs.io/en/latest/flax.nn.html) `flax.nn` module.

This is a feature request to integrate with the new [`flax.linen`](https://github.com/google/flax/tree/master/flax/linen#linen-a-comfortable-evolution-of-flax) module.

**Comment by fehiepsi** [comment]
Hi @gustavehug, do you want to take a stab at this? I'll be busy for the next few weeks and also would like to use `linen` for an LDA model after that. At my first impression, its API looks closer to PyTorch `nn.Module` than `flax.nn`.

**Comment by gustavehug** [comment]
Hi @fehiepsi , yes I can take a look in the coming weeks !

**Comment by fehiepsi** [comment]
This is integrated into the master branch. Thanks, @gustavehug !
