### ISSUE TITLE
What happens when numpyro.factor takes an array

### ISSUE THREAD

**Issue by hzyjerry** [pyro-ppl/numpyro#980]
Hi, it looks like `numpyro.factor` can take either a value or an array. When would we want to pass in an array?

In this meaningless example (we should pass in a value), what would be the behavior when we pass in an array?
```python
def model():
    with numpyro.plate("item", 20):
        prob = numpyro.sample('prob', dist.Normal(0, 1)) # shape is (20,)
    numpyro.factor('prob', prob)
```

**Comment by fritzo** [comment]
An array could add a different factor for each element of a batch, but then your factor statement should be inside the `plate`:
```py
def model():
    with numpyro.plate("item", 20):
        prob = numpyro.sample('prob', dist.Normal(0, 1)) # shape is (20,)
        numpyro.factor('prob', prob)
```
Alternatively outside of the plate, you should be reducing:
```py
```py
def model():
    with numpyro.plate("item", 20):
        prob = numpyro.sample('prob', dist.Normal(0, 1)) # shape is (20,)
    numpyro.factor('prob', prob.sum(-1))
```
```

**Comment by hzyjerry** [comment]
Thanks! Does running MCMC on your first example return 20 chains that are sampled in parallel?

For algorithms like Metropolis Hasting, could it happen that during sampling the 20 chains, some are finished and some haven't?

**Comment by fehiepsi** [comment]
@hzyjerry To get 20 chains, you can set `MCMC(kernel, num_chains=20)`. But I guess it is not relevant to your question.

> could it happen that during sampling the 20 chains, some are finished and some haven't?

Yes, this is true with the default behavior (`chain_method="parallel"`). To perform one sampling step across all chains, you can set `MCMC(..., chain_method="vectorized")`. I think `vectorized` method is good for random walk MH or non-adaptive HMC algorithm.

**Comment by hzyjerry** [comment]
Thanks!
