### ISSUE TITLE
dist.Categorical outputs different shapes during sampling

### ISSUE THREAD

**Issue by hzyjerry** [pyro-ppl/numpyro#981]
Hi, I'm looking at the annotation example, and looks like (strangely) the `dist.Categorical` outputs different shapes during sampling process.

In the code below I marked a line where I inspected. In the first pass after the sampling starts, `c` has shape (45,1), which is reasonable undering `num_items=45`. However at the second time, `c` has shape (4, 1, 1), which is strange because:

1. Why is there an extra dimension? Is this caused by batching? Why doesn't it happen for continuous distributions?
2. Why is `plate` no longer adding 45 to its shape?
 

```python
def multinomial(annotations):
    """
    This model corresponds to the plate diagram in Figure 1 of reference [1].
    """
    num_classes = int(np.max(annotations)) + 1
    num_items, num_positions = annotations.shape

    with numpyro.plate("class", num_classes):
        zeta = numpyro.sample("zeta", dist.Dirichlet(jnp.ones(num_classes)))

    pi = numpyro.sample("pi", dist.Dirichlet(jnp.ones(num_classes)))

    with numpyro.plate("item", num_items, dim=-2):
        c = numpyro.sample("c", dist.Categorical(pi))
        # import pdb; pdb.set_trace() <---------------------

        with numpyro.plate("position", num_positions):
            y = numpyro.sample("y", dist.Categorical(zeta[c]), obs=annotations)
```

**Comment by fritzo** [comment]
This is due to enumeration; see the [tensor shapes tutorial](https://pyro.ai/examples/tensor_shapes.html)

**Comment by hzyjerry** [comment]
Thanks for the pointer. On a somewhat related note, I took the example from `test_infer_discrete.py` to play around (included).

```python
  @config_enumerate
  def model(z=None):
      p = numpyro.param("p", np.array([0.75, 0.25]))
      iz = numpyro.sample("z", dist.Categorical(p), obs=z)
      print("iz.shape = {}".format(iz.shape))
      z = jnp.array([0., 1.])[iz]
      logger.info("z.shape = {}".format(z.shape))
      print("z.shape = {}".format(z.shape))
      with numpyro.plate("data", 3):
          x = numpyro.sample("x", dist.Normal(z, 1.), obs=data)
```

The thing I'm having trouble understanding is why/how the input `z=None` is tied with `iz = numpyro.sample("z", dist.Categorical(p), obs=z)`. If I remove the `obs=z`, the program no longer works, and gives `assert is_prng_key(key)` error.

```python
  @config_enumerate
  def model(z=None):
      p = numpyro.param("p", np.array([0.75, 0.25]))
      iz = numpyro.sample("z", dist.Categorical(p))   <--- changed
      print("iz.shape = {}".format(iz.shape))
      z = jnp.array([0., 1.])[iz]
      logger.info("z.shape = {}".format(z.shape))
      print("z.shape = {}".format(z.shape))
      with numpyro.plate("data", 3):
          x = numpyro.sample("x", dist.Normal(z, 1.), obs=data)
```

**Comment by hzyjerry** [comment]
Thanks! It all makes sense after reading [this section](http://pyro.ai/examples/tensor_shapes.html#Broadcasting-to-allow-parallel-enumeration).

**Comment by laygr** [comment]
I had the same issue and solved it by moving one dimension from the batch_shape to the event_shape as follows:
d = dist.Categorical(torch.ones(K, **options) / K).expand([A]).to_event(1)
