### ISSUE TITLE
How to find MAP/maximum likelihood estimation using the minimizer (i.e., BFGS)

### ISSUE THREAD

**Issue by fmc202** [pyro-ppl/numpyro#982]
I want to find the MAP(maximum a posteriori) or Maximum likelihood estimate of my model parameters. I have read the stastical rethinking code using Numpyro by Phan,  where he used SVI with Adam(stepsize =1) optimizer and a guide function returning None. But I found this does not work well for complex models since we have to tune the stepsize manually. Other PPL such as Pymc3 or Stan uses L-BFGS or BFGS to find the maximum of posterior or likelihood without needing to tune the stepsize. I wonder how to use the numpyro.optim.minimize (i.e. the JAX BFGS) to achieve the same goal? Which guide function should be used in SVI? 

Thank you so much.

**Comment by fehiepsi** [comment]
@fmc202 Yes, [Minimize](http://num.pyro.ai/en/stable/optimizers.html#numpyro.optim.Minimize) does it for you (after [L-BFGS available on jax](https://github.com/google/jax/pull/6053), we will use it by default - currently, only `BFGS` is available). You can mimic the example at `Minimize`, with `AutoLaplaceApproximation` is replaced by `AutoDelta`.

FYI, we have a [forum](https://forum.pyro.ai/) to ask for questions. Posting questions there will be helpful for many other people in the community. :)

**Comment by fehiepsi** [comment]
This should be resolved using `Minimize` optimizer. Please feel free to reopen this issue if needed.
